### ISSUE TITLE
Missing content to add bootstrap.css in the help document, resulting in incorrect style

### ISSUE THREAD

**Issue by TimChen44** [radzenhq/radzen-blazor#1002]
**Describe the bug**
Missing content to add bootstrap.css in the help document, resulting in incorrect style
https://blazor.radzen.com/docs/guides/getting-started/installation.html

**Expected behavior**
Add necessary explanations in the document

**Comment by enchev** [comment]
xxx-base.css themes do not need bootstrap.css

**Comment by enchev** [comment]
https://blazor.radzen.com/docs/guides/getting-started/installation.html#include-the-css-and-js
