### ISSUE TITLE
Data grid paging doesn't work when set  @bind-Settings

### ISSUE THREAD

**Issue by DmitryVasilyuk95** [radzenhq/radzen-blazor#1011]
1. Create Data grid component and apply @bind-Settings there 
E.g. 
`<RadzenDataGrid IsLoading=@isLoading Data="@agencies" TItem="AgencyModel" AllowSorting="true" FilterMode="FilterMode.Advanced" class="rz-table-style-1"
                                    AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" AllowPaging="true"
                                    @bind-Settings="@settings" AllowColumnPicking="true" 
                                    ShowPagingSummary="true" PageSize="25" PageSizeOptions="new int[] { 10, 25, 50, 100 }" PagerHorizontalAlign="HorizontalAlign.Left">
`
2. Try to change page size on the UI. 
Expected result:  page size was changed
Actual:  page freezes

**Comment by enchev** [comment]
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/d15ba081-bafa-443f-ad8e-9f62feb514b4)
![settings-pagesize-options](https://github.com/radzenhq/radzen-blazor/assets/5804953/d92bd255-c0a6-4d20-b0c5-b05305ec0081)
