### ISSUE TITLE
DialogService - When set to draggable it locks the height and width, so no longer dynamically changes with content

### ISSUE THREAD

**Issue by Dreagen** [radzenhq/radzen-blazor#1012]
**Describe the bug**
If you have a draggable dialog, once moved it retains a fixed height and width. If the dialog contains content that changes height, i.e an expandable DataGrid, the dialog no longer expands with its content (which it does correctly until you drag the dialog)

**To Reproduce**
1. Create a draggable dialog with some expandable content inside
2. Open the dialog and before dragging it expand the content, the dialog will expand with the content.
3. Close the expandable content, drag the dialog.
4. Open the expanable content and note the dialog no longer expands with the content, you get a scroll bar instead.

**Expected behavior**
Diaglog expands with it's content like it would do prior to dragging.

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/5364054/1e3385b0-9f4f-4940-aca5-b4e263e8d466)

**Desktop (please complete the following information):**
 - Browser [Chrome, Firefox]
 - Version [4.13.0]

**Additional context**
I have a fix I can push up as a PR if you wish, would be happy to discuss and adjust accordingly

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/a020e06c3db83f2b92db7e640ee8f1d79a5afb9f
