### ISSUE TITLE
[Updated steps to reproduce] Data grid paging doesn't work when set @bind-Settings

### ISSUE THREAD

**Issue by DmitryVasilyuk95** [radzenhq/radzen-blazor#1014]
Go to https://blazor.radzen.com/datagrid-save-settings

Edit code and add e.g. PageSizeOptions="new[] { 2, 4, 8, 12 }"

After that try to click a few times. Sometimes it's needed to click a few times
![ezgif com-optimize (1)](https://github.com/radzenhq/radzen-blazor/assets/134110561/7cf4e6ec-23f2-4e8e-8094-3fad54ecbd88)

**Comment by enchev** [comment]
When using PageSizeOption you should also set PageSize to a variable:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/af57a9ae-7308-41ce-95a2-375548b3ea90)
otherwise every change state will reset the PageSize to what is declared in the razor
