### ISSUE TITLE
Add FilterData/SecondFilterData (IEnumerable<>) properties for the RadzenDataGridColumn

### ISSUE THREAD

**Issue by enchev** [radzenhq/radzen-blazor#1015]
Add FilterData/SecondFilterData (IEnumerable<>) properties for the RadzenDataGridColumn along with FilterValueProperty/SecondFilterValueProperty and FilterTextProperty/SecondFilterTextProperty that can be used to render DropDown component in advanced filter similar to enum filtering.

**Comment by bikotoru** [comment]
Could you show an example of how to implement this?

thanks :)
