### ISSUE TITLE
RadzenDataGrid: OnPageSizeChanged and ReloadOnFirstRender redundantly reload

### ISSUE THREAD

**Issue by evandixon** [radzenhq/radzen-blazor#1019]
**Describe the bug**
On the first render of a data grid with both a LoadData delegate and a manually specified PageSize, the LoadData delegate is called twice, once by `PagedDataBoundComponent<>.OnPageSizeChanged` and once by `PagedDataBoundComponent<>.ReloadOnFirstRender`.

**To Reproduce**
1. Create a RadzenDataGrid
2. Define both the LoadData and the PageSize parameters in any order
3. Observe the LoadData implementation being called twice on the first page load.

**Expected behavior**
The initial set of PageSize doesn't trigger a reload when ReloadOnFirstRender is going to trigger a reload

**Comment by enchev** [comment]
Both PageSize and LoadData are used in this demo however LoadData will be called only once:
https://blazor.radzen.com/datagrid-loaddata

**Comment by evandixon** [comment]
On that demo, I added `Console.WriteLine("Reload called. Stack trace: " + Environment.StackTrace.Replace("\n", "\\n"));` to line 102 at the very top of LoadData, and looking in the console shows that LoadData is indeed being called twice, once from ReloadOnFirstRender and once from PageSizeChanged. It's easier to see when LoadData makes a network call since you can see two distinct network requests.

**Comment by enchev** [comment]
Hey @evandixon,

I've used the debugger to check the same:
![loaddata-pagesize](https://github.com/radzenhq/radzen-blazor/assets/5804953/f2087b91-38b3-4ad6-b71c-84a7d83f611a)

**Comment by evandixon** [comment]
@enchev Turns out there's a race condition with the reload caused by OnPageSizeChanged. If the reload works quickly there, ReloadOnFirstRender will see that there's data and not reload. Adding a `await Task.Delay(1000);` to the start of LoadData results in  ReloadOnFirstRender loading before OnPageSizeChanged completes.
