### ISSUE TITLE
Requesting feature to add click event to RadzenProfileMenuItem 

### ISSUE THREAD

**Issue by Matthewsre** [radzenhq/radzen-blazor#102]
I tried adding onclick, but that is not working:

```
            <RadzenProfileMenuItem Text="Profile" Value="Profile" Icon="account_circle" @onclick="ShowProfilePanel">
            </RadzenProfileMenuItem>
```
 I see in the source propagation is stopped:

 https://github.com/radzenhq/radzen-blazor/blob/235ce4873f8597506c64d653af78428b5defafee/Radzen.Blazor/RadzenPanelMenuItem.razor#L5
 
 Could a Click event be added and handled in the OnClick?
 
 https://github.com/radzenhq/radzen-blazor/blob/235ce4873f8597506c64d653af78428b5defafee/Radzen.Blazor/RadzenPanelMenuItem.razor#L198

**Comment by enchev** [comment]
Click event of the RadzenPanelMenu reports the clicked item:
![image](https://user-images.githubusercontent.com/5804953/115673044-da4d2000-a354-11eb-9b4f-fc168641ab29.png)
