### ISSUE TITLE
The RadzenDropDownDataGrid, Search box for filtering does not work when put in a Modal(I only tries)

### ISSUE THREAD

**Issue by kuchbestylin** [radzenhq/radzen-blazor#1029]
**Description**
The search box that appears for filtering in the RadzenDropDownDataGrid, does not work when displayed in a BlazorBootstrap Modal. Only the search box does not function.

**To Reproduce**
1. Declare a blazorbootstrap modal and set onclick events.
2. Inside the modal body, declare a RadzenDropDownDataGrid
3. Try to search, the control does not focus

**Expected behavior**
The Search box should focus when clicked and allow me to search

![Screenshot (19)](https://github.com/radzenhq/radzen-blazor/assets/68732346/a0bc667d-1d05-4d9c-b4d6-094bb88dce60)

DESKTOP
 - OS: Windows
 - Browser Edge
 - Version 114.0.1823.43

**Comment by akorchev** [comment]
Hi @kuchbestylin,

This is a known issue caused by the Bootstrap modal implementation. We can't fix it unfortunately. You can use RadzenDialog instead which doesn't do that.

**Comment by kuchbestylin** [comment]
Okay sure thanks.
