### ISSUE TITLE
Radzen DataGrid self-Reference hierarchy: Touch screen becomes unresponsive after clicking between pages.

### ISSUE THREAD

**Issue by Perks-of-Being-a-Cauliflower** [radzenhq/radzen-blazor#1036]
**Describe the bug**
I have created a MAUI Blazor Windows application which is designed to work on a Windows 10 Surface Pro 2. I am using a self-Reference hierarchy DataGrid as described in the official documentation [https://blazor.radzen.com/datagrid-selfref-hierarchy](url). I have noticed that when there are multiple pages to click between on the data grid the controls will freeze if the user clicks between them too quickly. This bug only appears on a touch screen device as a mouse will still be able to interact with the UI however no touch input appears to be registering once the bug is encountered.

**To Reproduce**
- Create a self-Reference hierarchy DataGrid and populate it with enough data to allow for multiple pages.
- On a touch screen device tap between the pages quickly.
- Eventually you will be unable to interact with any part of the UI in or outside of the data grid using the touch screen however you will still be able to do so using a mouse or keyboard.

Here is a sample app that should mimic the issue. The API I was using to retrieve the data has been replaced by fake data. NOTE: Please ignore the button that says "Press me to navigate to XAML Page". That is for a different bug that causes a memory leak when navigating between pages.
[https://github.com/Perks-of-Being-a-Cauliflower/BaseMauiApp](url)

**Expected behavior**
When I navigate between data grid pages the UI should continue to allow me to interact using touch controls.

**Screenshots**
Below screenshot is just to show which UI controls I am interacting with to cause the bug.
![image](https://github.com/radzenhq/radzen-blazor/assets/61937254/1dad10c3-9f8e-4ed8-a9a5-26d5420043c7)

**Desktop
 - OS: Windows 10
 - Browser: N/A (Local MAUI Application)

**Additional Notes**
Sometimes it appears that I don't need to click between the grid pages very fast to cause the bug. I think clicking fast forces the issue but it appears to happen every so often even with slower interactions.

**Comment by enchev** [comment]
Hey @Perks-of-Being-a-Cauliflower,

The DataGrid component will not handle clicks in any way - the issue is most probably related on how MAUI will handle fast clicks on touch devices and I'm afraid that we cannot do much.
