### ISSUE TITLE
[RadzenSteps] Programatically move forward

### ISSUE THREAD

**Issue by MPapst** [radzenhq/radzen-blazor#104]
**Is your feature request related to a problem? Please describe.**
I want to offer a Wizard like Component using RadzenSteps. On the first step is a input to enter a identifier which must exactly match.
When found, the step can move forward automatically (for the user conveneince).

**Describe the solution you'd like**
Can the [NextStep](https://github.com/radzenhq/radzen-blazor/blob/3c415591db01d090b80650494d1fa49c997b2582/Radzen.Blazor/RadzenSteps.razor#L83) method be used for this?
Do you see any impact when setting this one to public that I did not put into account?

**Describe alternatives you've considered**
Setting the `SelectedIndex` Property from the outside results in a warning from Blazor:
![image](https://user-images.githubusercontent.com/16494676/115693221-04f0a600-a360-11eb-9984-2476abb9b2f0.png)

**Comment by enchev** [comment]
Hey @MPapst ,

You can use our forum for questions:
https://forum.radzen.com/

**Comment by MPapst** [comment]
Hi @enchev,

sorry but I think there is a misunderstanding. I just wanted to ask if there are any impact before providing a pull request.
I'll ask in the forum and come back to the issue when a pr is required :)
