### ISSUE TITLE
DataGrid: expand/collapse issues

### ISSUE THREAD

**Issue by Scnck** [radzenhq/radzen-blazor#1043]
Initial click issues:

first click after a freshly loaded page on the expand arrow of a collapsed group is ignored. The second click works just fine. 

https://github.com/radzenhq/radzen-blazor/issues/430

**Comment by enchev** [comment]
I'm afraid that I cannot reproduce such problem on our demo:
 https://blazor.radzen.com/datagrid-grouping-api

**Comment by Scnck** [comment]
I was setting args.Expanded to true vs null this should be better documented.
