### ISSUE TITLE
DataGrid with multiple Column Filters applied does not filter correctly

### ISSUE THREAD

**Issue by uflowie** [radzenhq/radzen-blazor#1049]
**Describe the bug**
Datagrid rows can be filtered by setting a filter on one of their columns. When applying a filter on multiple columns the UI indicates that multiple columns are being filtered by. However not all of the filters are actually applied to the rows.

**To Reproduce**
1. Go to https://blazor.radzen.com/datagrid-performance
2. Click on the Filter Symbol on the column "First Name"
3. A popup opens that lets you apply filters to this column
4. Click on the first input Field
5. Type "Nancy"
6. Click Apply
7. The Datagrid displays a loading symbol for a short time
8. Once the loading symbol disappears, 5 entries of an employee with the First Name Nancy and Last Name Davolio appear
9. Click on the Filter Symbol on the column "Last Name"
10. Click on the first input field
11. Type "asd"
12. Click Apply

**Expected behavior**
The employee with First Name Nancy and Last Name Davolio no longer appears in the Data Grid, as her last name does not contain "asd".

**Observed behavior**
The employee with First Name Nancy and Last Name Davolio still appears in the results of the DataGrid. Both the filter icon on the First Name and on the Last Name column indicate that a filter has been set. Upon clicking on the icons, we can still see the filters that we have set.

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/119594712/1bdb02a4-21a9-4e5d-9978-d660c98394f5)
![image](https://github.com/radzenhq/radzen-blazor/assets/119594712/c66209df-77bc-42a5-9b18-3ce3e388e683)
![image](https://github.com/radzenhq/radzen-blazor/assets/119594712/5d8e1ad2-f52f-49ea-bfe6-eccc3b611cb0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Comment by enchev** [comment]
Hey @uflowie,

The filter operator between column filters in this demo is set to OR:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/eca027d9-95ca-4827-85f4-20b8e8f24d7d)
