### ISSUE TITLE
Set RadzenPanelMenuItem background color

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1055]
Please add variable
--radzen-panel-menu-item-background-color
that can set background color of parent (whare i set background color) and all childs = RadzenPanelMenuItems

How now i can set all childs background-color?

Thanks.

**Comment by yordanov** [comment]
Hey @Andrey-2021,
Can you elaborate on that or show screenshots? It is not that clear what are you trying to achieve.

**Comment by Andrey-2021** [comment]
![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/36fb3148-6631-487f-854f-7025d3dc997e)

**Comment by Andrey-2021** [comment]
![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/4341a66e-0688-43cf-96c4-86ffe56cb7eb)

**Comment by yordanov** [comment]
You can use the `--rz-panel-menu-item-background-color` CSS variable via style:

```C#
<RadzenPanelMenuItem Text="General" Icon="home" style="background-color: lightgreen;">
    <RadzenPanelMenuItem Text="Buttons" Icon="account_circle" style="--rz-panel-menu-item-background-color: lightgreen;"></RadzenPanelMenuItem>
</RadzenPanelMenuItem>
```
or css class:
```C#
<RadzenPanelMenuItem Text="General" Icon="home" style="background-color: lightgreen;">
    <RadzenPanelMenuItem Text="Buttons" Icon="account_circle" Class="light-green-item"></RadzenPanelMenuItem>
</RadzenPanelMenuItem>

<style>
    .light-green-item {
        --rz-panel-menu-item-background-color: lightgreen;
    }
</style>
```

<img width="328" alt="image" src="https://github.com/radzenhq/radzen-blazor/assets/1118895/906264eb-ba88-44e1-9b63-761f371f6834">

Here is the list of all PanelMenu CSS variables:

https://github.com/radzenhq/radzen-blazor/blob/fcbbd53dd89d1e11915fb03689f350117a7cd445/Radzen.Blazor/themes/components/blazor/_panel-menu.scss#L54-L102
