### ISSUE TITLE
Animate Accordion

### ISSUE THREAD

**Issue by 3hxx** [radzenhq/radzen-blazor#1056]
**Describe the solution you'd like**
Ideally there would be a toggleable animation on all panel which stretches the viewport  so it creates a smooth transition instead of just appearing

**Describe alternatives you've considered**
N/A

**Additional context**
When you open an Accordion the content just appears, whereas my solution would be to animate that event.

**Comment by yordanov** [comment]
Duplicate of https://github.com/radzenhq/radzen-blazor/issues/269
