### ISSUE TITLE
DataGrid word wrap in the table header

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1059]
Please add  Header Word Wrap Flag in DataGridProperties
which will show that it is necessary to wrap long words in the table header -> Title-property in RadzenDataGridColumn.

Thanks.

**Comment by enchev** [comment]
Hey @Andrey-2021,

You can control this using CSS:
https://forum.radzen.com/t/datagrid-column-header/9648/2
