### ISSUE TITLE
LibSassBuilder support

### ISSUE THREAD

**Issue by IceReaper** [radzenhq/radzen-blazor#106]
Would love to see LibSassBuilder support, so instead of including the shipped css file, we can include the base styles and override the theme variables.

**Comment by akorchev** [comment]
What's is currently preventing you from doing that?

**Comment by IceReaper** [comment]
The need to copy/paste the whole .scss directory to be able to include those files.

**Comment by akorchev** [comment]
As far as I see LibSassBuilder needs the .scss files to be a part of the project. So you do need to copy them.
