### ISSUE TITLE
No selected filter value datagrid-enum-filter

### ISSUE THREAD

**Issue by TiuDerca** [radzenhq/radzen-blazor#1063]
Selected value of the selected element in dropdown is not set in a simple filter

**To Reproduce**
Open https://blazor.radzen.com/datagrid-enum-filter
Change FilterMode="FilterMode.Advanced" to FilterMode="FilterMode.Simple"

https://github.com/radzenhq/radzen-blazor/assets/88079618/7f579222-ece5-4e5d-9f41-a55e56418dec

Possible solution:
If remove:
[possible solution](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/DropDownBase.cs#L848)

![devenv_2023-07-14_11-42-37](https://github.com/radzenhq/radzen-blazor/assets/88079618/fe24570d-3b89-4143-98a4-ae4cfce6be49)

it work:

https://github.com/radzenhq/radzen-blazor/assets/88079618/d323f7a7-e23b-414b-8696-2b9138362e78

But I'm not sure if deleting the code is the right solution.

**Comment by enchev** [comment]
Hey @TiuDerca,

No, such change will brake the entire value binding.

**Comment by enchev** [comment]
Already possible in the latest version:
![image](https://github.com/user-attachments/assets/9bbb8f1d-4ec8-4af3-864e-1fe785f7405a)
