### ISSUE TITLE
RadzenDropDownDataGrid Using RadzenDataGrid Filtering

### ISSUE THREAD

**Issue by TWC-Rik** [radzenhq/radzen-blazor#1067]
**Is your feature request related to a problem? Please describe.**
The RadzenDataGrid has great, extensive filter support. The RadzenDropDownDataGrid uses the RadzenDataGrid but has its own filter layered on top which does not have the same functionalities as the RadzenDataGrid filters; it is limited to string search as far as I can tell.

**Describe the solution you'd like**
Allow developers to set FilterMode on the RadzenDropDownDataGrid to specify they want to use the RadzenDataGrid filters and how they want to use them, and pass these settings along to the RadzenDataGrid.

**Describe alternatives you've considered**
In a hacky attempt I inherited RadzenDropDownDataGrid, got the RadzenDataGrid grid field in it through reflection, and overwrote the filter parameters, but when searching it would not update the data in the RadzenDataGrid.

**Additional context**
I cloned Radzen locally and passed the parameters along to the RadzenDataGrid components in RadzenDropDownDataGrid, but when searching it would not refresh the data in the RadzenDataGrid. (Same behavior as above).

**Comment by enchev** [comment]
Thanks for your proposal however we do not plan to support such feature. Two of the DataGrid filter modes are using popups and if we allow such filters for DropDownDataGrid the UI will be popup over popup which is definitely not the best UX practice.
