### ISSUE TITLE
DartSass issues with  @extend.

### ISSUE THREAD

**Issue by DaveBagler** [radzenhq/radzen-blazor#1077]
I noticed the release was patched to revert the switch from LibSass to DartSass because of issues with `@extend`. If you let me know what the issues were, I volunteer to start working on them.

**Comment by enchev** [comment]
Reverted because of this: https://sass-lang.com/documentation/breaking-changes/extend-compound/. We need to change the themes before switching to DartSass

**Comment by akorchev** [comment]
We saw that migrating to DartSass was adding up to 200KB to the compiled CSS files. After some research it turned it was caused by our usage of `@extend` which DartSass doesn't support and generated a ton of wrong CSS selectors which added up to 200KB in size.
