### ISSUE TITLE
Support more flexibility in customising RadzenDropDown multiple items text

### ISSUE THREAD

**Issue by matthetherington** [radzenhq/radzen-blazor#1078]
**Is your feature request related to a problem? Please describe.**

I would like to be able to customize the RadzenDropDown so that it displays eg "2 items selected" when multiple options are selected, and the option value when only a single item is selected. At the moment, the selected values are always displayed as a comma-separated list. It is only possible to customize the Separator as discussed in https://github.com/radzenhq/radzen-blazor/issues/494.  

**Describe the solution you'd like**

I think the suggestion in https://github.com/radzenhq/radzen-blazor/issues/494 of a MultipleItemsTemplate would work fine for my use case.

**Describe alternatives you've considered**

A `RenderMultipleItemsLabelText` parameter of type `Func<IEnumerable<TValue>, RenderFragment>` or similar might be even more flexible.

I'd be more than happy to submit a PR if an approach can be agreed upon. Thanks!

**Comment by enchev** [comment]
Hi @matthetherington,

You can use ValueTemplate to display whatever content you need.
