### ISSUE TITLE
Some notifications are not disappearing when multiple are opened

### ISSUE THREAD

**Issue by technight** [radzenhq/radzen-blazor#1084]
**Describe the bug**
If multiple notifications are triggered within a short amount of time, then some of them will not disappear.
If 3 is opened then 1 will not disappear, 5 open -> 2 will not disappear, 7 open -> 3 and so on.

**To Reproduce**
1. Go to https://blazor.radzen.com/notification
2. Click more than 3 times on one of the show notification buttons
4. See that some of the notifications will not disappear

**Expected behavior**
Notifications disappears after given time

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 115.0.2

**Additional context**
I think this issue may have started after the "Do not hide 2 notifications when clicking close." from release 4.13.6

**Comment by bc3** [comment]
@technight I tested in in y local repo's, before update in PR #1084 , the same behaivour existed :-(

**Comment by technight** [comment]
I belive #1092 should close this issue. The problem was that the loop in RadzenNotification.razor would update the Message parameter of an already existing component when a notification was closed. PR adds the key directive so that the parameters are fixed to the "correct" component instance.
