### ISSUE TITLE
Full height Sidebar dont't work correctly in Full height Sidebar 

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1088]
Hi!
When I use 'Full height Sidebar' It don't work correctly 

1) Sidebar, Header and Footer. Correct example
![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/7d1bc85d-cfeb-4c3b-aba3-462f3fd488b3)

we see
![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/41c6cb81-de3a-48c7-a673-4e937bf985e7)

2)Uncorrect example
Itake it from [https://blazor.radzen.com/layout#full-height-sidebar](Full height Sidebar )
https://blazor.radzen.com/layout#full-height-sidebar

![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/a0807df4-169e-4bcb-9632-8deb4cd2df12)

we see
![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/9c10a4e4-bd01-42d9-b144-80a232c5c888)

Thanks.

**Comment by Cosmatevs** [comment]
That's because you haven't included the footer part in your style code. It should be:
`grid-template-ares: 'rz-sidebar rz-header' 'rz-sidebar rz-body' 'rz-sidebar rz-footer'`

**Comment by Andrey-2021** [comment]
Thanks!
Please add comment/remark about 'rz-sidebar rz-footer' in 'Full height Sidebar' example 
in page
https://blazor.radzen.com/layout#full-height-sidebar

**Comment by Andrey-2021** [comment]
or since it's not obvious (config grid-template-ares:), 
it's better to make a separate flag (Full height Sidebar) in RadzenLayout
