### ISSUE TITLE
Color picker inside dialog doesn't show selected color 

### ISSUE THREAD

**Issue by xirami** [radzenhq/radzen-blazor#1100]
**Describe the bug**
Color picker inside dialog doesn't show selected color

**To Reproduce**
1. Go to repository https://github.com/xirami/radzen-playground/tree/main/colorPicker, download repro sample
2. Run the sample, click on OPEN PICKER DIALOG
3. Change color to whatever in picker
4. Close the picker 
5. Color is not changed

See screenshots.

**Expected behavior**
Color box reflects user selection of color.

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/107033882/d191aacb-90c3-4584-abe6-872e30b421f5)
![image](https://github.com/radzenhq/radzen-blazor/assets/107033882/d74286f3-d153-4681-b8fe-0c798c6bf6d7)
![image](https://github.com/radzenhq/radzen-blazor/assets/107033882/86237899-bd3d-4000-a8ae-2edf74d9a9da)
![image](https://github.com/radzenhq/radzen-blazor/assets/107033882/90c90118-0817-47d0-87d2-32c796551464)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Chrome, Edge, latest

**Comment by Cosmatevs** [comment]
It's not a bug. You have to click [OK] to accept your change. You need to set the `ShowButton` parameter to `false` and then the color change will be immediate.

**Comment by xirami** [comment]
When I press OK no change propagates.
Still looks as a Bug.

Dne st 2. 8. 2023 15:37 uživatel Cosmatevs ***@***.***>
napsal:

**Comment by Cosmatevs** [comment]
Then it's a bug. I've checked it out and it looks like even without the button the color swatch isn't updated. However, after you close the dialog containing the picker and then open it again, then the swatch is changed. Quite an odd behavior.

**Comment by xirami** [comment]
Correct, data binding works, but UI is not updated in Dialog.

**Comment by akorchev** [comment]
Unfortunately I don't think this could ever work. The bound field lives in a different component (the parent) and as a result it cannot be updated from the inline child (or at least I don't know how). A workaround is to define the dialog content in a separate component (its own .razor file) and work from there.

**Comment by xirami** [comment]
Ok will check, makes sense.
