### ISSUE TITLE
Dropdown doesn't show selected item when LoadData-Method uses a different FilterOperator or FilterCaseSensitivity

### ISSUE THREAD

**Issue by bPrantner** [radzenhq/radzen-blazor#1112]
**Describe the bug**
When the method used in loadData doesn't match the FilterCaseSensitivity- and FilterOperator-settings, the selecteditem won't be shown.

**To Reproduce**
1. Go to [Dropdown-Filtering](https://blazor.radzen.com/dropdown-filtering)
2. Alter the source of 'Custom filtering with LoadData event'
` <RadzenDropDown AllowClear="true" @bind-Value=value
                    LoadData=@LoadData AllowFiltering="true"
                    FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" FilterOperator="StringFilterOperator.StartsWith"
                    Data=@customers TextProperty="CompanyName" ValueProperty="CustomerID" Style="width: 100%; max-width: 400px;" />`
4. Search by 'ho' and select 'Around the Horn'
5. Clear-Button is shown (some item is selected), but no text for the selected item

**Expected behavior**
FilterCaseSensitivity and/or FilterOperator are ignored, since loadData is used

**Comment by enchev** [comment]
Hey @bPrantner,

When you use LoadData event filtering should be performed in the event itself by the developer. Check our demos for reference.

**Comment by bPrantner** [comment]
Hey @enchev ,

thanks for the quick answer, I'm still a bit confused though.
![Radzen Dropdown](https://github.com/radzenhq/radzen-blazor/assets/142181890/87ef92f7-1aef-4c95-b4c8-4734dfefebe6)

As you can see, the loadData-event itself isn't the problem, the data is there. However, when you select an item it won't be shown in the dropdown because of the mismatching FilterCaseSensitivity and/or FilterOperator, which is a bit counter-intuitive for me.
