### ISSUE TITLE
Incorrect name and role are defined for the Search criteria section expendable button.

### ISSUE THREAD

**Issue by msftedad** [radzenhq/radzen-blazor#1114]
**Describe the bug**
Assistive technology users will be impacted here as they will not know the purpose and functionality of that control is descriptive name and correct role & state are not defined for the controls.

**To Reproduce**

1. Open the above code pen URL-codepen - [panel (codepen.io)](https://codepen.io/seambr02/pen/LYXroKJ)
2. Open DOM structure and inspect the code
3. Observe the issue.

Alternatively link your repo with a sample project that can be run.
codepen - [panel (codepen.io)](https://codepen.io/seambr02/pen/LYXroKJ)

**Expected behavior**
Correct name as 'Search Criteria' and Role as 'button' should be defined for the Search criteria section expendable button. 

Also, Aria-expended attribute should be defined for the button. So, Narrator should announce proper information like as 'Search Criteria button expended/collapsed'.

**Desktop (please complete the following information):**
OS Build: Windows 11 Enterprise 22H2 (25267.1250)
Edge Dev Browser: Version 111.0.1652.0 (Official build) dev (64-bit)

**Attachments:**
<img width="960" alt="Note_Resources section (1)" src="https://github.com/radzenhq/radzen-blazor/assets/93735775/0c1e6297-f180-44d9-8f5f-175b21da848e">

<img width="960" alt="Code Snip_Incorrect name and role are defined for the expendable button (1)" src="https://github.com/radzenhq/radzen-blazor/assets/93735775/eb62aae2-58d7-450c-92f6-a91303752846">

**Comment by akorchev** [comment]
Hi @msftedad we would accept a PR which addresses this issue.

**Comment by msftedad** [comment]
Hi @akorchev , Any update on this issue?

**Comment by msftedad** [comment]
Hi @akorchev, Verified this issue is still reproduced on the latest environment:

![image](https://github.com/radzenhq/radzen-blazor/assets/93735775/62e39c21-eebc-4dbb-8db5-7af8ca37b2e8)


Issue is still repro on 3P UI:
[Blazor Panel Component | Free UI Components by Radzen](https://blazor.radzen.com/panel)
![image](https://github.com/radzenhq/radzen-blazor/assets/93735775/29bab13f-9725-4951-8e7c-a38a44d26724)

**Comment by akorchev** [comment]
The second screenshot shows that the `role` attribute is correctly set to `button`. Your application is probably using an older version of the Radzen.Blazor library. 

As for the `title` attribute - you can set it to the desired value via the ExpandTitle and CollapseTitle properties of RadzenPanel:

```
<RadzenPanel 
    Text="Search Criteria"
    ExpandTitle="Expanded Search Criteria" 
    CollapseTitle="Collapsed Search Criteria"
/>
```


Here is the actual implementation: https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenPanel.razor#L24
