### ISSUE TITLE
The DataGrid Enum Filter not working for OData

### ISSUE THREAD

**Issue by sabatex** [radzenhq/radzen-blazor#1118]
A Blazor WASM project using an OData provider does not work correctly with Enum data, namely setting the OData filter as enumValue='1'. After changing the selector type from int to string, the OData filter changed to enumValue='Red' and everything worked perfectly. No testing was done for ServerSide.

Changed files:

1. Extensions.cs

```
public static IEnumerable<object> EnumAsKeyValuePair(Type enumType)
{
    return Enum.GetValues(enumType).Cast<Enum>().Distinct().Select(val => new { Value = **val.ToString()**, Text = val.GetDisplayDescription() });
}
```

2. QueryableExtensions.cs

```
                else if (PropertyAccess.IsEnum(column.FilterPropertyType) || PropertyAccess.IsNullableEnum(column.FilterPropertyType))
                    {
                        if (v != null)
                        {
                            value = **v.ToString()**;
                        }
                        if (sv != null)
                        {
                            secondValue = **sv.ToString()**;
                        }
                    }
```
[Fork](https://github.com/sabatex/radzen-blazor)

**Comment by enchev** [comment]
Hey @sabatex,

You might need to check this thread: https://github.com/OData/AspNetCoreOData/issues/422 - in short you will need StringAsEnumResolver.

**Comment by sabatex** [comment]
I fixed the enum issue for OData query and tested for a real project. These changes do not change the default logic. After these changes, work fine with OData EDM by default after installing EnumKeyAsSymbols = true. Small changes to files (Extensions, QueryableExtension) are required.  My last Commit is in fork.
