### ISSUE TITLE
RadzenProgressBar ShowValue doesn't show the value.

### ISSUE THREAD

**Issue by ricardocza** [radzenhq/radzen-blazor#1119]
Describe the bug**
When using RadzenProgress, the ShowValue property it's not working properly.
Altough it renders the div containing the value correctly, there is an display: none !important that it prevents of showing at all.
It is simple to change actually, but I thought it was worth mentioning.

**To Reproduce**
1. I'm using the standard Material theme (in the import <link rel="stylesheet" href="_content/Radzen.Blzor/css/mterial-base.css">
2. When creating an element <RadzenProgressBar Value="10" ShowValue="true" /> it renders the element in the DOM, but the class .rz-progressbar-label comes with display: none !important.

**Expected behavior**
By default I expected it to show the value, which seems to be the stndr value for ShowValue.
Also, it would be a nice feature to have options to choose the position of the value like LabelPosition="LabelPosition.Left / Top / Right / Bottom".

**Screenshots**
https://drive.google.com/file/d/1o7h6THI3Gc9ORtBNBW1bhtu5f9x1GdWT/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 115.0.5790.173

**Additional context**
Sorry if there is some typo or misspelling, my keyboard is killing me right now 😅

**Comment by enchev** [comment]
Hey @ricardocza,

As far as I know this is by definition from Material guidelines, @yordanov can provide more info.

**Comment by yordanov** [comment]
Indeed, that's how Material looks like https://m2.material.io/components/progress-indicators and there is not enough height to fit in the label inside the ProgressBar. We could however try to display the label outside the ProgressBar - not a straightforward solution and might introduce breaking changes to the component's rendering.
