### ISSUE TITLE
HTML Editor binding doesn't work - 4.15.6

### ISSUE THREAD

**Issue by sheltonash** [radzenhq/radzen-blazor#1128]
**Describe the bug**
At version 4.15.6 if you include a html editor with the following attributes, it errors.

`<RadzenHtmlEditor Value="@emailModel.Header" />`

**To Reproduce**
Its as simple as the above.

**Expected behavior**
html editor binding to work

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by enchev** [comment]
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/a406e034-ab6b-4d1f-840f-98f7c9e016bb)
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/420c3c95-eb5d-4624-b3e5-182c88590db8)
