### ISSUE TITLE
RadzenDataGrid - wrong filter format when OData source is null

### ISSUE THREAD

**Issue by giusepanzuto** [radzenhq/radzen-blazor#1131]
Hi all, 

I followed the filter API tutorial on https://blazor.radzen.com/datagrid-filter-api with a grid that uses an odata API to load data.
Unfortunately, when the grid calls LoadData the first time the source is null, and the filter received in the arguments isn't in odata format.

I expected a filter in this format:

`'tolower(WorkOrderCode) eq tolower('AAA') and contains(tolower(SerialNumber), tolower('BBB'))'`

But instead, I received this format:

`(WorkOrderCode == null ? "" : WorkOrderCode).ToLower() == "AA3333".ToLower()`

The issue is caused by the method IsOData which return false if Data is null
```
internal bool IsOData()
{
    if(isOData == null && Data != null)
    {
        isOData = typeof(ODataEnumerable<TItem>).IsAssignableFrom(Data.GetType());
    }
    return isOData != null ? isOData.Value : false;
}
```
Honestly, I cannot say whether this is a real problem, but it is certainly a situation that can waste a lot of time.
The solution (workaround?) is to initialise Data with a new, empty instance of ODataEnumerable. For example:

`ODataEnumerable<WorkOrder> _workOrders = new(Enumerable.Empty<WorkOrder>());
`
Thanks
G.

**Comment by enchev** [comment]
The empty instance of ODataEnumerable is the only way to handle this and unfortunately we don’t have any other solutions.
