### ISSUE TITLE
Reordering of selected RadzenListBox elements with saving checkboxes state

### ISSUE THREAD

**Issue by diovch** [radzenhq/radzen-blazor#1135]
Hello!
I'm not sure that my situation is a bug, but it's unexpected behavior for me

I'm using RadzenListBox to reorder columns in RadzenDataGrid:

`<RadzenListBox @ref="@_selectedListBox" Data="@_selectedColumns" @bind-Value="_selectedColumnsClicked"
AllowSelectAll="false" Multiple="true" 
FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" FilterOperator="StringFilterOperator.Contains" AllowFiltering="true"/>`

`private LinkedList<string>? _selectedColumns = new();`
`private List<string>? _selectedColumnsClicked = new ();`

![image](https://github.com/radzenhq/radzen-blazor/assets/45145225/2a444bc8-42d4-435c-a18e-cf361c73100a)

Practically, I want to select some elements, move them up or down, watch "moving" animation and do the same if I want to without reselecting elements.

For example, I select "Side" element, click upward button, "Side" element takes the second position and saves its active checkbox. Then I can move "Side" up or down by button again if necessary.

Code for reordering elements is following:
```
private async Task ReorderColumns(ReorderType reorderType)
    {
        // changing order of elements in _selectedColumns

        var savedItems = _selectedColumnsClicked?.ToArray();
        _selectedColumnsClicked?.Clear();
        _selectedListBox.Reset();

        foreach (var item in savedItems ?? Array.Empty<string>())
            await _selectedListBox.SelectItem(item);
        
        await InvokeAsync(StateHasChanged);
    }
```

with ` _selectedListBox.Reset()` I see new order of elements, but lose the selection in checkboxes. 

` _selectedListBox.SelectItem(item)` is assigned to activate corresponding checkboxes, but `selectedItems` collection [here](https://github.com/radzenhq/radzen-blazor/blob/2cc575d74b00770164a99b3ff57482f74fffdad4/Radzen.Blazor/DropDownBase.cs#L1187) still has selected elements. So I add clearing ` _selectedColumnsClicked?.Clear()` but it doesn`t help.

How can I reset listbox deeply enough so `selectedItems` becomes empty? And shouldn't the `Reset()` function clear it due to its [code here](https://github.com/radzenhq/radzen-blazor/blob/a04cbeba785b27f1932961402e9ce8b335b0465a/Radzen.Blazor/DropDownBase.cs#L365C13-L365C26)?

**Desktop**
 - OS: Windows
 - Chrome

Thanks!

**Comment by enchev** [comment]
You can set _selectedColumnsClicked to null.

**Comment by diovch** [comment]
But I have already done that.
`selectedItems` in `DropDownBase` level is not empty
