### ISSUE TITLE
[Feature request] Enable different title in column picker than Title (property)

### ISSUE THREAD

**Issue by marekm294** [radzenhq/radzen-blazor#1136]
**Is your feature request related to a problem? Please describe.**
When I have composite columns in RadzenDataGrid which have same columns inside (Title) I cannot differentiate them in ColumnPicker. Therefore as a user I don't know which column do I hide.

**Describe the solution you'd like**
It would be nice to have property ColumnPickerTitle which would be used to set text in ColumnPicker. Title would be used as default value if ColumnPickerTitle wasn't set.

```
/// <summary>
/// Gets or sets the title in column picker.
/// Value of Title is used when ColumnPickerTitle is not set
/// </summary>
/// <value>The title.</value>
[Parameter]
public string ColumnPickerTitle 
{
    get => _columnPickerTitle == null ? Title : _columnPickerTitle;
    set => _columnPickerTitle = value;
}

string _columnPickerTitle;
```

```
<div class="rz-column-picker">
    <RadzenDropDown SelectAllText="@AllColumnsText" AllowSelectAll="@AllowPickAllColumns"
        MaxSelectedLabels="@ColumnsPickerMaxSelectedLabels"
        SelectedItemsText="@ColumnsShowingText" Change=@ToggleColumns
        @bind-Value="@selectedColumns" FilterCaseSensitivity=FilterCaseSensitivity.CaseInsensitive
        Multiple="true" AllowFiltering="@ColumnsPickerAllowFiltering"
        Placeholder="@ColumnsText"
        Data="allPickableColumns"
        TextProperty="ColumnPickerTitle" />
</div>
```

**Describe alternatives you've considered**

**Additional context**

I can push this code and make PR if you approve it as good idea.

**Comment by Cosmatevs** [comment]
I think you can simply make a pull request and it will be merged to the master faster than you'll get an answer here 😉

**Comment by marekm294** [comment]
@Cosmatevs I would really like to make new pull request but I'm not able to create new branch

**Comment by MPapst** [comment]
You need to fork the repository into your account and create a pr from there.
