### ISSUE TITLE
UniqueID and Attributes is null on Map marker click

### ISSUE THREAD

**Issue by markus-renezeder** [radzenhq/radzen-blazor#1137]
UniqueID and Attributes is null on Map marker click

**Comment by enchev** [comment]
Works normally on our demo
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/75ab7763-9f12-46fc-afdd-960e701199d9)

**Comment by markus-renezeder** [comment]
UniqueID and Attributes of the **Marker** is null - not of the map.
