### ISSUE TITLE
RazenGrid in-line edit do not launch RowUpdate Event after call .UpdateRow()

### ISSUE THREAD

**Issue by Acruval** [radzenhq/radzen-blazor#114]
**Describe the bug**
RazenGrid in-line edit do not launch RowUpdate event after call .UpdateRow()

**To Reproduce**
**I can not reproduce in your demo page**
In am following your RazenGrid in-line demo structure. With different data
1. I have colums and I click on edit Icon
2. Yes I can Edit
3. I press Save Icon
3.1 that calls  _grid.UpdateRow(el);
3.2 yes there is a validation
3.3 If all is Ok   OnUpdateRow must be called but it doesn't happen
3.4 The row is still in edit mode

![image](https://user-images.githubusercontent.com/4776748/118280326-02e3b800-b4c4-11eb-92e7-b65d1679b1a2.png)

Net core 3.1

![image](https://user-images.githubusercontent.com/4776748/118280860-800f2d00-b4c4-11eb-9994-2ccac3fcd214.png)

**Comment by akorchev** [comment]
> I can not reproduce in your demo page

We can't do much without reproducing the problem. You can try removing all validators to see if the problem remains. Also you can try debugging the source code.

**Comment by luizs81** [comment]
@Acruval 
Can you share your code, so people can review it and eventually try to reproduce the problem?

**Comment by Acruval** [comment]
It is just a vanilla Grid with a button when I press the button. I have
sent the source code at that moment
  I finally created a form just for edit and use one of my read-only grids
but I can resent you the case.
  any clue you wrote meant 4 am in the morning and because I didn't reply
in 8 hours you close the case..

Cheers

**Comment by saustudio** [comment]
i have same problem, for in-line edit cell.
if i start edit mode , change value,  and click any other row , then edit mode auto closing and don't fired OnRowUpdate
