### ISSUE TITLE
RadzenDataGrid crashes if DataGridSettings.CurrentPage exceeds PageNumbersCount

### ISSUE THREAD

**Issue by tpc-dsc** [radzenhq/radzen-blazor#1140]
**Describe the bug**
The RadzenDataGrid crashes when loading DataGridSettings if the CurrentPage (index from 0) is greater than PageNumbersCount - 2 (which is page count + 1 for some reason). This only happens when loading dynamic data (e.g. date and time updated or state).

**To Reproduce**
1. Using the [blazor.radzen DataGrid save/load settings example](https://blazor.radzen.com/datagrid-save-settings-loaddata), store the DataGridSettings in local browser storage.
2. Select the last page of the DataGrid and check the CurrentPage value is set in in local browser storage.
3. Either delete some rows from the test data, or set a filter that means there will be less data on refresh (e.g. duration < 00:00:10).
4. Refresh the page and you'll see the whole UI freeze.

**Expected behavior**
An exception should be thrown without locking up the UI.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome and Firefox
 - "Radzen.Blazor" Version="4.15.7"

**Additional context**
The workaround is to clear the DataGridSettings current page index in LoadStateAsync to avoid trying to load a non-existent page.
```cs
if (_settings.CurrentPage > _dataGrid.PageNumbersCount - 2)
    _settings.CurrentPage = null;
```

**Comment by enchev** [comment]
I navigated to the last page, filtered EmpoyeeID = 1 which will result in single page and refreshed the page - no UI freeze, no errors:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/e2e03602-61b9-4252-89d5-86243827e75c)

**Comment by enchev** [comment]
> This assumes you either have a stopwatch column or you dynamically calculate the difference between a given start time and the current time.

I'm afraid that I'm unable to reproduce the problem nor to understand what you are saying.
