### ISSUE TITLE
Can the source code be classified and placed in different folders according to the functionality of the components. Sort like the menu on the Demo site.

### ISSUE THREAD

**Issue by TimChen44** [radzenhq/radzen-blazor#1146]
Can the source code be classified and placed in different folders according to the functionality of the components. Sort like the menu on the Demo site.

![image](https://github.com/radzenhq/radzen-blazor/assets/7581981/90fb14d1-ba6b-4f0f-9bdd-3311a12b0f1f)

**Comment by enchev** [comment]
Hey @TimChen44,

We don’t plan such changes.
