### ISSUE TITLE
Select row error when change page DataGrid

### ISSUE THREAD

**Issue by Tham25** [radzenhq/radzen-blazor#1154]
I created a table using Data Grid as shown below.
On the first page, when I select a row, it changes the font color of that line. However, when I move to the 2th, 3th... page, I see that the row in the same position on page 1 also changes color even though I do not click it.
Help me!! Thank team

![image](https://github.com/radzenhq/radzen-blazor/assets/75118940/2c740ac8-21ac-44bd-863d-df7a9e2791ed)
![image](https://github.com/radzenhq/radzen-blazor/assets/75118940/1e9604fc-26c1-402c-b8f9-7e1904b0b8aa)
![image](https://github.com/radzenhq/radzen-blazor/assets/75118940/0b1aebe1-799b-47ab-89f1-4a636afb2530)

**Comment by enchev** [comment]
I'm afraid that this is not acceptable as issue. You can use our forum to post your questions.
