### ISSUE TITLE
Stacked Column chart with a base other than zero 

### ISSUE THREAD

**Issue by MG1376** [radzenhq/radzen-blazor#1164]
I have an application that I need its chart to be like this link from AccuWeather:

[AccuWeather](https://www.accuweather.com/en/us/new-york/10021/january-weather/349727?year=2022)

I tried alot to designate a base for the chart using:

`<RadzenValueAxis Min="@(weathers.Min(w => w.LowTemp))">`

But the chart does not appear correctly. Is there a way in Radzen Blazor to do this?

**Comment by akorchev** [comment]
This seems as a question that is better fitted for our [forum](https://forum.radzen.com).
