### ISSUE TITLE
[Feature Request] `RadzenDataGrid` - allow `EditTemplate` 

### ISSUE THREAD

**Issue by viceroypenguin** [radzenhq/radzen-blazor#1167]
I would like to update `RadzenDataGrid` such that it is possible to flow `EditContext` to an `EditTemplate` for a given row that is currently being edited, similar to the `Template` property.

Purpose: I currently have a row that has too much data to show in a single table row, so I put additional columns into the `<Template/>` property to be displayed when using the expand button. I would like to be able to edit these fields under the row's `EditContext` (using validation, etc.). To me, it would make sense to update RadzenDataGridRow.razor#L138 as follows:
```
@if (Grid.IsRowInEditMode(Item) && Grid.EditTemplate != null)
{
 <CascadingValue Value=@EditContext>
  @Grid.EditTemplate(Item)
 </CascadingValue>
}
else
{
  @Grid.Template(Item)
}
```

I can provide a PR for this if it would help.

**Comment by enchev** [comment]
Hey @viceroypenguin,

I think you can add RadzenTemplateForm in the DataGrid Template to achieve desired effect (editing with validation, etc.)

**Comment by viceroypenguin** [comment]
@enchev Thank you for your response. However, `RadzenTemplateForm` does not do what I am requesting here. Specifically, it does not attach the elements in the `Template` to the `EditContext` of the row; it creates a new `EditContext` for the dropdown area independent of the row. This means that actions take on the row do not affect items inside the template area.

Here, I have followed your instructions and added a `RadzenTemplateForm`, as well as a `RadzenRequiredValidator`. 
![image](https://github.com/radzenhq/radzen-blazor/assets/1992555/74cecdd0-cfdc-4c48-9001-9916ace17b55)

If I add a new order and click save without filling anything in, notice that the `Ship Name` box gets a validation, but the `Country` box does not - the Country box is not affected by the save trigger from the row's `EditContext`.
![image](https://github.com/radzenhq/radzen-blazor/assets/1992555/64e1cf50-6085-464d-8cbe-4160c41a04aa)

**Comment by enchev** [comment]
Using validators in the way you've implemented this template is not supported either:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/67fadb48-5745-4567-835a-3677c33eeb6d)
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/bcec9a5a-b49c-4dcc-afe2-31b41f526ced)

I'm afraid that we cannot accept such pull request

**Comment by viceroypenguin** [comment]
Apologies, thanks for the catch. I mixed up some of the code when saving the final version for PR purposes. If you check out the updated branch (https://github.com/viceroypenguin/radzen-blazor/tree/edittemplate), this works as expected with the validator inside the `EditTemplate`.

**Comment by enchev** [comment]
I've verified the demo and it work as should - you can remove the code from the demo and submit new pull request with just the relevant component changes

**Comment by viceroypenguin** [comment]
Done, thanks!
