### ISSUE TITLE
Verify issue

### ISSUE THREAD

**Issue by LeinerViloria** [radzenhq/radzen-blazor#1172]
https://github.com/radzenhq/radzen-blazor/issues/1166

@enchev, Hi, I was testing the way using the DateRender event, and it's not a natural solution for just to know when a year or a month has changed, my use case doesn't need to look over all days in the calendar view, my use case just need to know when a month or year has changed

**Comment by enchev** [comment]
Hey @LeinerViloria,

You can use the event as I already suggested you and check the date year and month properties. Please use our forum to post questions in the future.
