### ISSUE TITLE
Performance Issues with Validation, when validating complex Graphs

### ISSUE THREAD

**Issue by uflowie** [radzenhq/radzen-blazor#1174]
**Describe the bug**
When using an EditContext for validating a graph, we have run into the following issue: Some Components, most noticably Dropdowns and Datepickers produce some performance issues when a property in a child of the graph is bound. For example, given a graph like:

```csharp
public class Company
{
  public Employee { get; set; }
}

public class Employee
{
  public DateTime BirthDate { get; set; }
}
```

when binding to the BirthDate of an Employee within an EditContext that has the Company as a Model, calling NotifyValidationStateChanged on the EditContext repeatedly will progressively make the site slower. This is because of the following code in the RadzenDatePicker (line 956-961):

```csharp
if (EditContext != null && ValueExpression != null && FieldIdentifier.Model != EditContext.Model)
{
    FieldIdentifier = FieldIdentifier.Create(ValueExpression);
    EditContext.OnValidationStateChanged += ValidationStateChanged;
}
```
In this constellation the line causes the component to hook into EditContext.OnValidationStateChanged every single time the component has its parameters set without unregistering the previous callback, because the condition `FieldIdentifier.Model != EditContext.Model` is always met. As a consequence, the component will rerender +1 times every single time it has its parameters set whenever EditContext.NotifyValidationStateChanged is fired. I suggest storing the model of the FieldIdentifier locally instead of comparing it with the Model of the EditContext.

**Expected behavior**
Whether i bind to the model of the EditContext or some property of a child of that model (or any other model for that matter) should have no bearing on the performance of these components.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (latest)
 - Version: latest

**Comment by akorchev** [comment]
Hi @uflowie,

We will need a reproduction of this issue in order to think of a fix.

**Comment by uflowie** [comment]
Hey @akorchev , sorry for the wait, I have had a couple of busy weeks, I am sure you can relate :). I have created a reproduction of this issue in https://github.com/uflowie/radzen_issue_1174. The steps to reproduce the issue are shown on the site. If you have any questions please don't hesitate to reach out.

**Comment by akorchev** [comment]
Hi @uflowie,

I checked the sample project but I am not sure how it reproduces the problem. Your code always subscribes to the event and the notification message would be called many times as nothing unsubscribes from it.

```
    public override async Task SetParametersAsync(ParameterView parameters)
    {
        await base.SetParametersAsync(parameters);
        if (EditContext != null && ValueExpression != null && FieldIdentifier.Model != EditContext.Model)
        {
            EditContext.OnValidationStateChanged += (_, _) => LogStateHasChangedCall();
        }
    }
 ```
 
 What happens if you use the built-in InputDate?  I tested this and got similar logging behavior:
 
 ```
 public class RadzenDatePickerDiagnostics<TValue> : InputDate<TValue>
{
    [Parameter] public string DiagnosticsName { get; set; } = string.Empty;

    public override async Task SetParametersAsync(ParameterView parameters)
    {
        await base.SetParametersAsync(parameters);
        if (EditContext != null && ValueExpression != null && FieldIdentifier.Model != EditContext.Model)
        {
            EditContext.OnValidationStateChanged += (_, _) => LogStateHasChangedCall();
        }
    }

    private void LogStateHasChangedCall()
    {
        Console.WriteLine($"{DiagnosticsName} wants to call StateHasChanged()");
    }
}
```

**Comment by uflowie** [comment]
InputDate does not unsubscribe, but it also only subscribes once - in InputDate the given snippet is in an if block that is only executed once upon initialization: `if (!_hasInitializedParameters)` in line 228.

**Comment by akorchev** [comment]
In that case I would ask for another reproduction. I just can't test any fix when the reproduction itself does not unsubscribe and constantly logs the message.

**Comment by uflowie** [comment]
Hey, thanks once again for your patience. I have forked the radzen repo and directly modified the datepicker code to simply log calls to ValidationStateChanged. You can reproduce the issue similarly to the previous repository by navigating into the IssueDemo folder and running dotnet run. I haven't been able to get the css working, but the issue is independent of it. Here is the link:
https://github.com/uflowie/radzen-blazor-1174/tree/master/Radzen.Blazor

**Comment by akorchev** [comment]
I've updated the code like this and it seems to make logging be called only once:

```cs
            if (EditContext != null && ValueExpression != null && FieldIdentifier.Model != EditContext.Model)
            {
                FieldIdentifier = FieldIdentifier.Create(ValueExpression);
                EditContext.OnValidationStateChanged -= ValidationStateChanged; //<- new code
                EditContext.OnValidationStateChanged += ValidationStateChanged;
            }
```

Please verify if this fixes your real issue.

**Comment by uflowie** [comment]
Yes, this fixes the issue, thank you. I have found the same issue in DataBoundFormComponent in line 336: https://github.com/radzenhq/radzen-blazor/blob/94c0a52824a9080529d67a46ee90771c12fa7b4e/Radzen.Blazor/DataBoundFormComponent.cs#L25

**Comment by akorchev** [comment]
This commit should address all similar issues: https://github.com/radzenhq/radzen-blazor/commit/15972a92036dcfe3f79ff1546e06f35242cc4915

**Comment by uflowie** [comment]
Thanks for your help!
