### ISSUE TITLE
RadzenPanelMenu - we need a flag that shows where the click was -> on the Text or submenu arrow 

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1180]
Hi!
Please add on 
MenuItemEventArgs args
flags:
1) args.IsTextClicked - shows that there was a click on Text
2) args.IsSubmenuArrowClicked  - shows that there was a click on tex on submenu arrow 

<RadzenPanelMenu Click="OnParentClicked" Style="width:300px" Multiple="@multiple">

void OnParentClicked(MenuItemEventArgs args)
{
if( args.IsTextClicked) ....
if(args.IsSubmenuArrowClicked ....
console.Log($"{args.Text} clicked from parent");
}

Thanks.

![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/76fc67f2-c489-493f-8001-35bcc3ae8277)

**Comment by enchev** [comment]
Clicking expand/collapse icon will update Expanded property which can be bound - if you do not want to use binding you can simply use ExpandedChanged event of the item.
