### ISSUE TITLE
Radzon Components not working in Latest Preview Blazor

### ISSUE THREAD

**Issue by Alik2015** [radzenhq/radzen-blazor#1183]
Created a project and added Radzen Components as per tutorial.  All worked when the project was net core 7 Server Side Blazor.  After upgrading to the new Preview of Blazor in .NET 8 the component stopped working.

Randomly added a Datepicker to the top right of the page under search.  This was working fine until upgrade.  No other libs/css has been updated apart from the nuget packages required for the latest preview.

To see result and reproduce you can find my test repo at [here](https://github.com/Alik2015/RadzenTest).

You can see that selecting date from Datepicker does nothing.

Putting this as a bug as not found any resolution.

**Comment by akorchev** [comment]
You can check this forum thread which explains why this happens: https://forum.radzen.com/t/sidebar-not-working-in-net-8-rc1-experiment/15198

In short this is by design in .NET 8 Blazor - layouts are not interactive by default which means components don't fire events.

**Comment by Alik2015** [comment]
Appreciate the details this was not easy to track down in the forum.  For those who have same issue. read the linke provided above it explains what is happening.
