### ISSUE TITLE
Wrong icon shown for "barcode" in context menu

### ISSUE THREAD

**Issue by scarabdesign** [radzenhq/radzen-blazor#1194]
**Describe the bug**
Google material design icon displayed in context menu for "barcode" is not correct. I noticed this in the context of the context menu, but I presume anywhere else where a string is used to specify an icon.

**To Reproduce**
1. Create a new context menu
```
ContextMenuService.Open(mouseargs, new List<ContextMenuItem> {
   new ContextMenuItem(){ Text = "Undo", Value = 6, Icon = "undo" },
   new ContextMenuItem(){ Text = "Filter", Value = 2, Icon = "search" },
   new ContextMenuItem(){ Text = "Mark All", Value = 1, Icon = "task_alt" },
   new ContextMenuItem(){ Text = "Unmark All", Value = 0, Icon = "radio_button_unchecked" },
   new ContextMenuItem(){ Text = "Reorder Locations", Value = 3, Icon = "import_export" },
   new ContextMenuItem(){ Text = "Scan Barcode", Value = 7, Icon = "barcode" },
   new ContextMenuItem(){ Text = "Save List as Template", Value = 4 },
}, result => {});
```
2. Run app and open context menu, look at the icon that appears:
![1](https://github.com/radzenhq/radzen-blazor/assets/13665840/e8ce1530-b557-4dbf-ad34-fb0565563e4e)

**Expected behavior**
The icon should be the Google material design icon of a barcode:
![2](https://github.com/radzenhq/radzen-blazor/assets/13665840/c36c23b0-a742-4701-8509-577cfae2911c)

**Desktop (please complete the following information):**
 - Radzen.Blazor 4.17.1
 - OS: Window, Android
 - MAUI Blazor WebView
 - .NET8 Preview

**Additional context**
Interestingly, when I searched the Google material design site for the barcode icon it didn't show up in the results at first. I had to clear the cached data for that site before the icon showed up. This hints that perhaps there was an issue with one of the released packages when it was bundled with the Radzen binaries. Just an idea...
https://fonts.google.com/icons?icon.query=barcode

**Comment by enchev** [comment]
We are using Material Icons where there is no such icon:
https://fonts.google.com/icons?icon.query=barcode&icon.set=Material+Icons

**Comment by scarabdesign** [comment]
Ok, thanks for the info. Any way I can use a symbol instead? Is it possible to derive a class or override the context menu?
