### ISSUE TITLE
HtmlEditor - Image size adjustment after upload

### ISSUE THREAD

**Issue by emcga** [radzenhq/radzen-blazor#1209]
**Is your feature request related to a problem? Please describe.**
After adding an image in HtmlEditor, the only way I can see to manipulate an image is to edit the HTML directly. This is an issue
when my clients are using the editor and adding images. Most of the time the size they choose on upload is not correct, and therefore they keep uploading the same image to correct the size. This is not only inconvenient, it consumes space on my server with duplicate data.  

**Describe the solution you'd like**
Have a user friendly way to manipulate the image size after upload. 

**Describe alternatives you've considered**
1. Modifying the component to incorporate a user friendly interface to manipulate image size. 
2. Use the exiting editor API to get the HTML of the selected/clicked image, parse the HTML and extract the image size, display a dialog to allow the user to modify the image parameters, patch the modified HTML back into the editor. I could not find a reliable way to get the HTML of the clicked image using the existing API.

**Comment by emcga** [comment]
I will create a pull request for this in the next few weeks.

**Comment by huxinshuo** [comment]
We also need Image size adjustment after upload.

**Comment by emcga** [comment]
@huxinshuo I'm going to start working on a solution for this again.

**Comment by akorchev** [comment]
There is currently the ability to change the width and height after selecting the image with the mouse (via dragging). The the image dialog should show the width and height and allow the user to adjust them. I think making selection easier is a viable solution (by clicking the image). I will implement that next week.
