### ISSUE TITLE
Radzen Inputs allow adding css 

### ISSUE THREAD

**Issue by douglassimaodev** [radzenhq/radzen-blazor#1212]
```
<RadzenNumeric TValue="decimal" ShowUpDown="false" 
               Format="#,###.00"
@bind-Value=SupplierQuote.Price class="form-control" />
```

this class will be applied to span and not to the input

```
<span class="rz-spinner valid rz-text-align-left form-control" id="-TUSQSD-H0" _bl_5=""><!--!-->
        <input type="text" inputmode="decimal" class="rz-spinner-input valid rz-inputtext" tabindex="0" autocomplete="off" onkeypress="Radzen.numericKeyPress(event, false)" onblur="" onpaste="" _bl_6=""><!--!-->
    </span>
```
    
    would be nice to see a class to apply the input like InputClass etc..

**Comment by ggomarighetti** [comment]
You can access through CSS selectors to the input to apply the styles you need.

If a property like this is implemented, it should be implemented for all inputs, in the various scenarios, as a formfield, as well as separately.

If you want, you could identify all the inputs that have this problem of lack of css class in the "input" tag and reply to this commit, and I will elaborate a PR.

Regards.

**Comment by akorchev** [comment]
Probably some API similar to the existing Attributes - InputAttributes maybe. Won't be as convenient but would allow people to set various attributes .
