### ISSUE TITLE
Website Loading and Crashing

### ISSUE THREAD

**Issue by MPPARMAR9597** [radzenhq/radzen-blazor#1223]
**Describe the bug**
When I open the Radzen website, select the Material free theme, and click on any component, such as the button component, and then click on 'Edit source,' the website takes an extended amount of time to load, and eventually, it crashes, displaying the following error message: 'An error has occurred. This application may no longer respond until reloaded. Reload.

**To Reproduce**
1. Go to the Radzen website.
2. Select the Material-free theme.
3. Click on any component (e.g., button).
4. Click on 'Edit source.'
5. Observe the prolonged loading and eventual crash.

**Expected behavior**
I expected that clicking on a component and then 'Edit source' would load the editor quickly and allow me to edit the source code without any issues.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Google Chrome]
 - Version [118.0.5993.118 (Official Build) (64-bit)]

![image](https://github.com/radzenhq/radzen-blazor/assets/40754653/c4947452-86fc-402c-9a33-1662e5eb8c81)

**Comment by akorchev** [comment]
Hi @MPPARMAR9597,

Most probably you don't have access to the demo source code. We've updated the demos to handle this case and display any errors that may have occurred.

**Comment by MPPARMAR9597** [comment]
Hello @akorchev,

I'm facing an issue with the Blazor Radzen demo on the official website. It seems that the source code isn't visible, which is essential for learning. I'm currently trying to learn Blazor Radzen, and having access to the source code is crucial for the learning process.

You can check out the specific link where I encountered this issue: [https://blazor.radzen.com/typography](https://blazor.radzen.com/typography).

Is there a way to address this problem and make the source code accessible for learners like me? Thank you!

![image](https://github.com/radzenhq/radzen-blazor/assets/40754653/b9592ce0-a72a-4189-b06c-577bb726cbc4)

**Comment by akorchev** [comment]
The source code is available in this repository. You can also check why your browser can't access that URL.
