### ISSUE TITLE
The example for HtmlEditor custom tool does not work correctly.

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#124]
The second example 'Custom tool with template' at https://blazor.radzen.com/html-editor-custom-tools does not work correctly.

The problem is, it does not insert the text at the cursor position but always at very beginning of the document.

The incorrect behavior happens if the custom tool opens a window like dropdown, context menu or the date-time picker.
Then when the user makes the selection, the text is always inserted at the very beginning of the edited document.

(If the custom tool does not open such window, but inserts the text directly everything works fine - like e.g. the first example on that page.)

Please, would it be possible to fix it?

**Comment by akorchev** [comment]
You need to use the SaveSelection method to persist the current cursor position. This needs to happen before the editor loses focus.

**Comment by OndrejUzovic** [comment]
> You need to use the SaveSelection method to persist the current cursor position. This needs to happen before the editor loses focus.

Yes, but sometimes it is not possible to save it before the focus is lost.
E.g. if I provide a custom command button into HtmlEditor via Template of RadzenHtmlEditorCustomTool, then when the callback OnButtonClick is called the focus is already lost and so SaveSelection will not work.

If somebody is interested I found the following solution:

To set the focus back into the HtmlEditor you can use the call:
await myHtmlEditor.ExecuteCommandAsync("insertText", "");

So to preserve the cursor position in HtmlEditor you can call:

```
// Set focus to HtmlEditor
await myHtmlEditor.ExecuteCommandAsync("insertText", "");

// Store the cursor position
await myHtmlEditor.SaveSelectionAsync();
```

And then to insert a text on the cursor position:

```
// Restore the curosor position
await myHtmlEditor.RestoreSelectionAsync();

// Insert a plain text
await myHtmlEditor.ExecuteCommandAsync("insertText", "your text");

```
