### ISSUE TITLE
.net 5 blazor server app no notification

### ISSUE THREAD

**Issue by dynamiclynk** [radzenhq/radzen-blazor#125]
StartUp

![image](https://user-images.githubusercontent.com/621804/120038321-af479300-bfc8-11eb-9c1a-7188882cb93d.png)

inject
![image](https://user-images.githubusercontent.com/621804/120038348-bec6dc00-bfc8-11eb-9278-ad9adc69047c.png)

method
![image](https://user-images.githubusercontent.com/621804/120038371-c7b7ad80-bfc8-11eb-9f81-9b1c79389486.png)

call
![image](https://user-images.githubusercontent.com/621804/120038409-d736f680-bfc8-11eb-9baa-f945b2134c48.png)

No errors also no notification any ideas? I set the the Imports and _Host.cshtml per the project documentation.

**Comment by MPapst** [comment]
Have you added the Notification component in your MainLayout?
