### ISSUE TITLE
RadzenDataGrid CellRender in Net8 does not pass correct Column Property

### ISSUE THREAD

**Issue by Edgecrusher77** [radzenhq/radzen-blazor#1252]
After update to net8 version, conditional styling via CellRender does not work anymore. The args.Column.Property is always the same for every column, while it should change based on the Cell it is rendering.

I've got a code based on this: https://blazor.radzen.com/datagrid-conditional-template
Plus my grid has composite columns.
In Net7 it worked fine and I was able to change args.Attributes by args.Column.Property.
In net8 the args.Column.Property is always the same and it has the name of the top composite column.

**Comment by enchev** [comment]
Our demos are .NET 8 and as far as I can see everything works normally in this example:
https://blazor.radzen.com/datagrid-conditional-template
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/9faea968-8090-4153-b2d3-dbaadc022164)
The composite columns demo works normally as well:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/5d36f737-485c-4615-8cef-0a502a7cb811)
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/056ab35b-ba0b-419b-a80a-ca267545e660)
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/e6720c03-c1f2-4a91-a458-50da1be7f10b)

**Comment by Edgecrusher77** [comment]
Hi Vladimir, thank you for your answer.

I've just attached the code to reproduce the issue. It's just the code of the Blazor Server component that is hosted in a RazorPage. No need to be connected to a database or anything else.

Thank you for your help.

[RadzenIssue.zip](https://github.com/radzenhq/radzen-blazor/files/13375354/RadzenIssue.zip)
