### ISSUE TITLE
Incorrect display of DataGrid (css)

### ISSUE THREAD

**Issue by masterworgen** [radzenhq/radzen-blazor#1253]
When using the DataGrid option AllowAlternatingRows="false", there is a bug associated with displaying data when the Default Theme is enabled (I haven’t tested it on others). I using last version Radzen
https://blazor.radzen.com/datagrid-frozen-columns?theme=default - you can add AllowAlternatingRows="false" in DataGrid, set Default Theme and see the problem I described

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/19784438/a0863982-d923-4857-b205-923d5d3c3f5b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, Opera

**Comment by masterworgen** [comment]
Okey, in mode AllowAlternatingRows="true" have problem too, when focus on row, get this situation
![image](https://github.com/radzenhq/radzen-blazor/assets/19784438/35e067a0-d236-4367-aecf-28391c876090)

**Comment by enchev** [comment]
Here is what I see on this demo:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/5399f6bf-ebab-472b-80bc-d37a7939655c)
Try to clear your browse cache.

**Comment by masterworgen** [comment]
> Here is what I see on this demo: ![image](https://user-images.githubusercontent.com/5804953/283462146-5399f6bf-ebab-472b-80bc-d37a7939655c.png) Try to clear your browser cache.

You are not add `AllowAlternatingRows="false` in DataGrid

**Comment by masterworgen** [comment]
https://youtu.be/0mCKUYSjiiM - i show this
