### ISSUE TITLE
Blazor DataGrid InLine Editing Glitch

### ISSUE THREAD

**Issue by luizs81** [radzenhq/radzen-blazor#126]
**Describe the bug**
When the DataGrid is on "insert row" mode and a user clicks on the "edit" button of another row, an empty row is left in the grid.

**To Reproduce**
1. Go to https://blazor.radzen.com/datagrid-inline-edit
2. Click on "+ Add" button
3. Click on the "edit" button of any other row
4. The row which the "edit" was clicked on will be in "edit mode", but an empty row will be left in the grid.

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
The grid should "cancel" the empty row before changing the new row for update. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser (any)

**Additional context**
- none -

**Comment by luizs81** [comment]
Hi @enchev
Could you please give a feedback before closing the ticket? I feel I was left in the void.

**Comment by bradbamford** [comment]
similar issue when in edit mode and the user clicks the edit button of any other row
