### ISSUE TITLE
Add the ability to show week number in the date picker

### ISSUE THREAD

**Issue by nielsNocore** [radzenhq/radzen-blazor#1276]
For our users it is very important to see week number in the datepicker popup. [https://blazor.radzen.com/datepicker?theme=material](https://blazor.radzen.com/datepicker?theme=material). 
So i would like to suggest a feature to add the ability to show these week numbers. Also it would be a good addition to set the week rule. there are multiple ways to select the first week of a year. 
1. week with 1 January is the first week.
2. first full week in January is the first week. 
3. first week with minimal 4 days of January is the first week. 

our suggestion is to add 2 new parameters to the datepicker:
```c#
[Parameter]
public bool ShowWeekNumber {get; set; } = false;

[Parameter]
public CalendarWeekRule WeekRule {get; set;} = CalenderWeekRule.FirstDay;
``` 

Using the .net methods to get the week numers: [https://learn.microsoft.com/en-us/dotnet/api/system.globalization.calendar.getweekofyear?view=net-8.0](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.calendar.getweekofyear?view=net-8.0)
and using **Culture.DateTimeFormat.FirstDayOfWeek** to get the first day of the week. 

Visualy: 
show the week numer in the first (to be added) column in the calander 
Example from syncfusion blazor: 
<img width="223" alt="image" src="https://github.com/radzenhq/radzen-blazor/assets/122032239/0d03bd8d-e12c-456a-bf0d-8eac83767ca7">

In the same styling as the day names above the dates (current standard theme from Radzen blazor)
<img width="335" alt="image" src="https://github.com/radzenhq/radzen-blazor/assets/122032239/962b528b-ec1e-44c4-910f-3efd1f288550">

We would like to implement this feature our self in to the Radzen blazor components
but creating this feature request to get a discussion going as instructed in the CONTRIBUTING.md

Would like to hear other thoughs about this feature request. 

Niels

**Comment by quicksln** [comment]
Sounds very useful, especially for planning long date in applications.

**Comment by enchev** [comment]
https://github.com/radzenhq/radzen-blazor/commit/64705b393adcdeb1239bbd51561e8595b0f3d6f0
