### ISSUE TITLE
InvalidOperationException Using ColorPicker in Blazor Server fails during prerendering on dispose 

### ISSUE THREAD

**Issue by TFTomSun** [radzenhq/radzen-blazor#128]
**Describe the bug**
System.InvalidOperationException
  HResult=0x80131509
  Message=JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
  Source=Microsoft.AspNetCore.Components.Server
  StackTrace:
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)

**To Reproduce**
1. Add the colorpicker to a serverside prerendered  app
2. enable all exceptions and start it
3. the dispose of the popup fails, because it tries to access the JSRuntime during the serverside prerendering

![image](https://user-images.githubusercontent.com/5387192/120781129-0e595a80-c529-11eb-88a5-8dd2d6c9ed29.png)

**The decompiled source code of radzen popup.cs**
![image](https://user-images.githubusercontent.com/5387192/120781210-203afd80-c529-11eb-856b-081d1c11c798.png)

**The call stack of the issue**
![image](https://user-images.githubusercontent.com/5387192/120781334-46f93400-c529-11eb-9e58-4b440eda0b54.png)

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
no crash

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/6eb05ce9b441a2bdb15c0165f402158f547fa8c1
