### ISSUE TITLE
Support for RTL (Right to Left)

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [radzenhq/radzen-blazor#1281]
Hi,
Have you any plans to support RTL in Radzen?
Do you accept pull requests about RTL if someone does it for you?

Regards.

**Comment by akorchev** [comment]
Hi @Ali-YousefiTelori,

Yes, we plan to add support for RTL at some point in 2024. We will do so ourselves as the change requires substantial changes to all components.

**Comment by bakhtvar** [comment]
We are eagerly waiting for the RTL, to switch from Mud to RadZen as the Rad by far is better

**Comment by enchev** [comment]
Added in https://github.com/radzenhq/radzen-blazor/commit/92e4249eecaf6a59e235dd9202cbaebc3bb37d96
