### ISSUE TITLE
In RadzenRating Value must be double, not int

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1284]
Hi!

The Value in RadzenRating must be double,
to show that the average score is not an integer

**Is your feature request related to a problem? Please describe.**
I can't show statistics - average score

**Describe the solution you'd like**
Value must be double, not int

![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/21080114-e5ce-41ac-ac4d-0ab7abdee434)

Thanks!!!!!!

**Comment by akorchev** [comment]
This would be a breaking change I am afraid.
