### ISSUE TITLE
On this webpage, the operation is slow

### ISSUE THREAD

**Issue by sdhzth** [radzenhq/radzen-blazor#1289]
https://blazor.radzen.com/datagrid-inline-edit,    the operation is slow

**Comment by enchev** [comment]
Works pretty fast for me
![datagrid-inline](https://github.com/radzenhq/radzen-blazor/assets/5804953/412123ff-0c5b-4d5f-a606-523b9ba06965)

**Comment by sdhzth** [comment]
When you edit, such as the "Freight" field, there is a slow feeling when delete character or Editing
