### ISSUE TITLE
Radzen Multi-select dropdown values show the backside of modal popup

### ISSUE THREAD

**Issue by SuriyaArul** [radzenhq/radzen-blazor#129]
Hi All, 

I'm using the Radzen Multi-Select dropdown in the modal popup in my blazor application. But I'm getting results (values are in behind the modal popup), like this below image. How to adjust the dropdown values and OnChange function in Radzen Multi-Select. 

Thanks, Suriya
![ModalPopup](https://user-images.githubusercontent.com/68591063/120792414-22b24d00-c553-11eb-977c-1d33a6b993a6.jpg)

**Comment by SuriyaArul** [comment]
Hi @akorchev,
can you give some information about this issue?

**Comment by akorchev** [comment]
[I replied to your forum post.](https://forum.radzen.com/t/blazor-dropdown-multi/5976/7?u=korchev). Please do not create duplicates.
