### ISSUE TITLE
Grid LoadData documentation

### ISSUE THREAD

**Issue by dtitovgis** [radzenhq/radzen-blazor#131]
https://blazor.radzen.com/datagrid-loaddata

In code tab need use:
        // Important!!! Make sure the Count property of RadzenDataGrid is set.
        count = employees.Count;
Instead of:
        // Important!!! Make sure the Count property of RadzenDataGrid is set.
        count = dbContext.Employees.Count();

**Comment by enchev** [comment]
Hey @dtitovgis,

employees.Count is not total records count while dbContext.Employees.Count() is.

**Comment by dtitovgis** [comment]
employees.Count is total for filtered records. look your demo: 
if filter is set pages not take effect.
