### ISSUE TITLE
Switching tabs by using the keyboard is not possible

### ISSUE THREAD

**Issue by johanpolak** [radzenhq/radzen-blazor#1316]
**Describe the bug**
I can't navigate from one tab (within RadzenTabs) to another. When I press the tab-key, the focus-state appears on the next tab, but nothing happens when I press the enter-key. My expectation is that the focused tab will be opened when I press the enter-key.

**Expected behavior**
My expectation is that the focused tab will be opened when I press the enter-key.

**Comment by enchev** [comment]
Hey @johanpolak,

There is a branch for keyboard navigation where this is already implemented.

**Comment by johanpolak** [comment]
That's great! Any idea when this will be merged to the master branch?

**Comment by johanpolak** [comment]
Allright, then I'll wait patiently. Thank you for adding keyboard support, that's a great addition to the components.

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/347942668d9003788403ec4e315ae2bfcec68263
