### ISSUE TITLE
Boolean Filter on DataGrid is wrong.

### ISSUE THREAD

**Issue by declan-m** [radzenhq/radzen-blazor#132]
**Describe the bug**
Filtering by Boolean values in datagrid is unclear.

**To Reproduce**
Create any data table with a Boolean field. and try and filter by it. The boxes for no filter and false seem to be swapped and false filter is clear and clear filter is false

**Expected behavior**
Blank Square = no filter
X in square = filter to false
tick in square = filter to true

**Screenshots**
![Clear box is filtering to FALSE only](https://user-images.githubusercontent.com/47781356/121033693-50da9b80-c7a4-11eb-8c14-6b39521d85d9.png)
![X in box is filtering to all](https://user-images.githubusercontent.com/47781356/121033767-5fc14e00-c7a4-11eb-978d-91605fb10488.png)

**Desktop:**
 - OS: Windows
 - Browser Edge
 - Version 91

**Comment by enchev** [comment]
Hey @declan-m ,

Blank Square is false
X in square = is no filter
tick in square = filter to true

**Comment by declan-m** [comment]
@enchev Yes I know but that is extremely unclear. X is usually used to indicate incorrect/false not 'no filter'. It would make much more sense for X to be false and a blank square to be no filter.
