### ISSUE TITLE
RadzenDataGrid not loading on first render when another component use AllowVirtualization and async LoadData

### ISSUE THREAD

**Issue by Egans146** [radzenhq/radzen-blazor#1332]
**Describe the bug**
I encountered this issue when using a RadzenDropDown with AllowVirtualization=true and async LoadData, and at the same time a DataGrid with AllowVirtualization=true and async LoadData.
The component below reproduces this issue; the datagrid is not populated on first load, but if you comment out the dropdown or manually call RefreshDataAsync with the Refresh button, LoadData is called and the datagrid is populated:

```razor
<RadzenDropDown TValue=Item
                AllowVirtualization=true
                LoadData="OnDropDownLoadData"
                Data="dropDownItems"
                Count="dropDownItemCount" />

<RadzenDataGrid @ref=grid AllowVirtualization=true
                LoadData="OnGridLoadData"
                Data="gridItems"
                Count=gridItemCount
                Style="height: 30rem;">
    <Columns>
        <RadzenDataGridColumn TItem="Item" Property="@nameof(Item.Value)" Title="Value" />
    </Columns>
</RadzenDataGrid>

<RadzenButton Click="() => grid.RefreshDataAsync()">Refresh</RadzenButton>

@code {
    class Item(int value) { public int Value { get; } = value; };

    RadzenDataGrid<Item> grid;

    int dropDownItemCount;
    IEnumerable<Item> dropDownItems;

    async Task OnDropDownLoadData(LoadDataArgs args)
    {
        await Task.Delay(1);
        dropDownItemCount = 100;
        dropDownItems = Enumerable.Range(args.Skip ?? 0, args.Top ?? 10).Select(e => new Item(e)).ToArray();
        StateHasChanged();
    }

    int gridItemCount;
    IEnumerable<Item> gridItems;

    async Task OnGridLoadData(LoadDataArgs args)
    {
        await Task.Delay(100);
        gridItemCount = 100;
        gridItems = Enumerable.Range(args.Skip ?? 0, args.Top ?? 10).Select(e => new Item(e)).ToArray();
        StateHasChanged();
    }
}
```

Trying out different versions of Radzen, I found it was working in version 4.15.12. By reverting 5995eb8, it seems to correct the issue, but I'm not sure it would be adequate.

**Expected behavior**
RadzenDataGrid should load data and render properly when rendered with other components using AllowVirtualization and async LoadData.

**Desktop:**
 - OS: Windows
 - Browser: chrome
 - Version 4.24.0

**Comment by Egans146** [comment]
Thank you for the fix.
Unfortunately, it still happens occasionally, specifically after a browser refresh.

**Comment by enchev** [comment]
Unfortunately I don't have any other ideas on how to force the Virtualize component to request items without calling explicitly RefreshDataAsync() which will lead again to double LoadData on initial load. Possible solution can be to define some non null Data by default: `IEnumerable<Item> gridItems = new[] { default(Item) };`
