### ISSUE TITLE
DropDownDataGrid - Keyboardnavigation (arrows) trigger OnChange event. 

### ISSUE THREAD

**Issue by Stefanu83** [radzenhq/radzen-blazor#1333]
**Is your feature request related to a problem? Please describe.**
The feature is related to the DropDownDataGrid (https://blazor.radzen.com/dropdown-datagrid) 

Imagine using the arrow keys (key arrowup, key arrowdown) to go through the items. 

Every time an item is selected (ie key arrowup or key arrowdown) the Change event is triggered.  But since I use the dropdown in a cascading like scenario that means that if a user moves through a list for every item the Change event is triggered, and additional data is loaded for the cascading dropdown(s). 

**Describe the solution you'd like**
I'd like an option that only triggers the Change event when an item is positively selected from the dropdown list and the dropdown list is closed (ie enter / mouse click on an item). 

**Describe alternatives you've considered**
None, it's an enhancement

**Comment by pianomanjh** [comment]
Does `SelectedItemChanged` get you what you're looking for?

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/347942668d9003788403ec4e315ae2bfcec68263
