### ISSUE TITLE
Support class property to customize style

### ISSUE THREAD

**Issue by jiaming0708** [radzenhq/radzen-blazor#135]
**Is your feature request related to a problem? Please describe.**
Would like to use class property to customize style.

**Describe the solution you'd like**
Currently, the component is able to customize style via style property, style is a good way to override and make sure the priority be the highest, sometime want to use the existing class, the style will be duplicated.

**Comment by enchev** [comment]
Hey @jiaming0708,

Arbitrary attributes including class attribute are supported in all components

**Comment by jiaming0708** [comment]
oh~~thanks!! I don't notice that
