### ISSUE TITLE
Pagination component defines colors that it does not use 

### ISSUE THREAD

**Issue by djatkinsrealis** [radzenhq/radzen-blazor#1351]
While styling a custom theme, I noticed that changing the hover colors, for the back and next buttons of the paginator, did not cause any visible change.

Looking at the themes\components\blazor\_paginator.scss, these variables are defined but not used:

- $paginator-back-button-hover-color
- $paginator-next-button-hover-color
- $paginator-back-button-hover-background-color
- $paginator-next-button-hover-background-color

Instead, the back and next buttons use the standard pagination hover colors only.

I am happy to post a fix, but have 2 questions:
- Do you intend to allow separate hover colors for the next and previous buttons (if not, should we just remove those unused variables).
- Would you want to extend this to the first and last buttons as well (either share the above colors, or add new variables for those).

**Comment by yordanov** [comment]
Indeed, these were added in advance to make sure we cover differences between various design languages (e.g. Material buttons vs. Fluent vs. Radzen's defaults), but at the end of the day never utilised.

Do you need to define separate hover states for the non-numeric buttons in your theme? If there is no reasonable need to do so, we will consider removing them altogether with a next major version (v5). Just skip these in your theme for the time being. 

Appreciate reporting such discrepancies. Thank you @djatkinsrealis 🙏
