### ISSUE TITLE
RadzenDropDown doesn't display values inside the dropdown when cleared when using AllowVirtualization

### ISSUE THREAD

**Issue by egans146** [radzenhq/radzen-blazor#1352]
**Describe the bug**
When a RadzenDropDown with AllowVirtualization is provided a value before the user selection and the value is cleared, the dropdown doesn't display any values when opened.

```razor
<RadzenDropDown @bind-Value=Value
                Data="items"
                Count="itemCount"
                LoadData="OnLoadData"
                AllowFiltering=true
                AllowClear=true
                TextProperty="@nameof(Item.Value)"
                AllowVirtualization=true />

@code {
    class Item(string value) { public string Value { get; } = value; };

    RadzenDataGrid<Item> grid;

    int itemCount = 1000;

    IReadOnlyList<Item> itemSource;
    Item Value;

    protected override void OnInitialized()
    {
        var charset = "abcdef ".ToCharArray();
        var items = Enumerable.Range(0, itemCount)
            .Select(e =>
            {
                Random.Shared.Shuffle(charset);
                return new Item(new string(charset));
            })
            .ToArray();
        itemSource = items;
        Value = items.First();
    }

    IEnumerable<Item> items;

    void OnLoadData(LoadDataArgs args)
    {
        IEnumerable<Item> query = itemSource;

        if (args.Filter != null)
            query = query.Where(e => e.Value.Contains(args.Filter));

        itemCount = query.Count();
        items = query.Skip(args.Skip ?? 0).Take(args.Top ?? 10).ToArray();
        StateHasChanged();
    }
}
```

In the example, if the dropdown is opened prior to clearing the value, the dropdown shows the values as intended.

![Animation](https://github.com/radzenhq/radzen-blazor/assets/6442594/d3ef5044-3c7c-4308-ba46-262e6e493a90)

**Desktop:**
 - OS: Windows
 - Browser: Brave
 - Version 4.24.4

**Comment by enchev** [comment]
Unfortunately I was not able to reproduce this using our demos
![dd-async](https://github.com/radzenhq/radzen-blazor/assets/5804953/5f111fb1-68fa-45ae-a675-dc305e088145)

Maybe I'm doing something wrong?

**Comment by egans146** [comment]
Thank you for taking the time to investigate the issue.
Here are the steps to reproduce with the example provided:
1: Load the page containing the component.
2: Clear the drop-down value.
3: Open the drop-down.
