### ISSUE TITLE
General tab items list should be accessible with up/down arrow keys.

### ISSUE THREAD

**Issue by msftedad** [radzenhq/radzen-blazor#1356]
**Describe the bug**
The tab item list is not accessible from the arrow keys. It is only accessible using the Tab key.
If the tab items will not be accessible with up down arrow keys it may create confusion for the screen reader dependent users, and they may have trouble in accessing the UI properly.

**To Reproduce**
1.Open [URL](https://blazor.radzen.com/tabs) in edge dev browser.
2.Navigate to the tab item in 'Tabs position' section using tab key.
3.Try to navigate tab list using arrow key and observe the behavior.

Alternatively link your repo with a sample project that can be run.
[URL](https://blazor.radzen.com/tabs)

**Expected behavior**
The tab items must be accessible with arrow keys and after pressing enter focus should move the tab pane controls.

**Screenshots**
![MAS2 4 3_General tab items should be accessible with up down arrow keys](https://github.com/radzenhq/radzen-blazor/assets/93735775/a6dd8d9c-f94f-4735-a1e2-22387d3f1982)

**Desktop (please complete the following information):**
OS Build: Windows 11 Enterprise 22H2 (25267.1250)
Edge Dev Browser: Version 111.0.1652.0 (Official build) dev (64-bit)

**Attachment**

https://github.com/radzenhq/radzen-blazor/assets/93735775/b38ec6e1-94a7-4506-a00d-63fbcbb75c17

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/347942668d9003788403ec4e315ae2bfcec68263
