### ISSUE TITLE
Incorrect focus order is observed for navigation list that appears after activating Hamburger menu icon.

### ISSUE THREAD

**Issue by msftedad** [radzenhq/radzen-blazor#1358]
**Describe the bug**
After the hamburger menu icon using tab key, the focus does not land on the Search list item inside the navigation list. Instead, it moves to header region the page.
Keyboard users will be impacted here as they will not be able to navigate properly if the focus order defined for the navigation list is incorrect.

**To Reproduce**
1.Open [URL](https://blazor.radzen.com/panelmenu) in edge dev browser.
2.Navigate the Hamburger menu icon button and activate it.
3.Hamburger menu button will be expended.
4.Navigate to the page in forward navigation using tab key.
5.Observe the issue.

Alternatively link your repo with a sample project that can be run.
[URL](https://blazor.radzen.com/panelmenu)

**Expected behavior**
Once the user activates the hamburger menu icon and navigates further, focus should first move inside the navigation list and then move to the header region.

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/93735775/5d43dadd-cb1a-48d8-94b0-d4f59d7b19b2)

**Desktop (please complete the following information):**
OS Build: Windows 11 Enterprise 22H2 (25267.1250)
Edge Dev Browser: Version 111.0.1652.0 (Official build) dev (64-bit)

**Attachment**
https://github.com/radzenhq/radzen-blazor/assets/93735775/37288e82-a916-484d-ae43-645019378434

**Comment by enchev** [comment]
> Once the user activates the hamburger menu icon and navigates further, focus should first move inside the navigation list and then move to the header region.
No. The navigation order is according to the order of the declaration/render of the focusable HTML elements. There is no special order made for the navigation menu in our demos.

**Comment by msftedad** [comment]
Hi @enchev, After activating the Hamburger menu button, a pane opens on the left side. However, when pressing the Tab key, the focus moves to the next control in the header section instead of shifting to the controls within the Hamburger menu list in the left pane.
Can you please reopen the issue?
