### ISSUE TITLE
Progressbar background color

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#136]
I think it would be a nice feature if it is possible to set the background color for the progress bar.

It would be useful in scenarios where the progress bar is used to indicate some state (e.g. memory consumption) where the background color can indicate a warning if it is too high.
(E.g. if the memory consumption is less then 50% the background color would be green, if less then 80% orange and between 80%-100% it could be red.)

**Comment by vazan** [comment]
Yep, i'm looking for that kind of customization. I building a monitoring apps and that should be really awesome if we can customise that color. :)

**Comment by yordanov** [comment]
See ProgressBarStyle in this demo -> https://blazor.radzen.com/progressbar
