### ISSUE TITLE
DataGrid column resize issues

### ISSUE THREAD

**Issue by Nox21419** [radzenhq/radzen-blazor#137]
**Describe the bug**
Resizing columns on the DataGrid can sometimes throw errors and prevent 
expanding rows after.

**To Reproduce**
Create a DataGrid with data loaded from a list of objects
- ColumnWidth="350px"
- AllowColumnResize="true"

Resize the columns around until the error appears

**Screenshots**
error shown in firefox console: 
![image](https://user-images.githubusercontent.com/37754532/121536894-74365e00-c9d1-11eb-99fb-a451dee1e855.png)

**Additional context**
Error seems to happen on any browser

**Comment by enchev** [comment]
Hey @Nox21419 ,

I was not able to reproduce this exception using our demo:
https://blazor.radzen.com/datagrid

Do you have any additional settings for the DataGrid/page?

**Comment by Nox21419** [comment]
Hey @enchev,
I did some additional testing, it seems to be an issue with resizing columns when there is more than one frozen column.

Here is a simple setup that gave me the error when resizing the columns
![image](https://user-images.githubusercontent.com/37754532/121907922-84647b00-ccfa-11eb-8325-1fa4fb504ab4.png)
