### ISSUE TITLE
RadzenDataGrid Filter and Sort don't work with ComplexType

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1370]
Blazor project: https://github.com/Andrey-2021/RadzenDataGrid

**Describe the bug**
In RadzenDataGrid dont't work sort and filter with `[ComplexType]`

first class:
`public class PriceListService
{
	[Key]
	public int Id { get; set; }

	[Required]
	public PriceListServiceBase ServiceBase { get; set; } = new();
}
`
second class: 
`
[ComplexType]
public class PriceListServiceBase
{
	public int Index { get; set; }
	public string? Code { get; set; }
	public string? ServiceName { get; set; }
}
`

**RadzenDataGrid **
![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/a8e79dba-77fe-4fb9-87d9-72944b165f07)

![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/911b121d-a13d-4817-879d-318caac8aba4)

We have 
Exception: Comparing complex types to null is not supported.

![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/e975858f-4281-4b76-8a43-fb36ade6f954)

**To Reproduce**
1. Load project https://github.com/Andrey-2021/RadzenDataGrid
1. Config db connection string 'DefaultConnection' in appsettings.json
2. Run project
3. Click button 'First step -> Add Data to Db'
4. try sort column Index or Code or Name in RadzenDataGrid
we get an error: Exception: Comparing complex types to null is not supported.

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/668bc33d-3993-48c4-88f8-d94a3ababb29)

**Comment by enchev** [comment]
Since you are using LoadData the sorting is at your premises in the event handler:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/25d6d440-68ad-4ec6-8ea9-3da145bc164e)
If the EF cannot translate such sort expression to SQL you can use ToList() for your data to sort in-memory.

**Comment by Andrey-2021** [comment]
`System.Linq.Dynamic.Core` today don't work with `[ComplexType]` 
We must use `[Owned]`

Additional information: https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/778
