### ISSUE TITLE
Feature Request - RadzenPanel TitleBar Toggle

### ISSUE THREAD

**Issue by blazorber** [radzenhq/radzen-blazor#1374]
Hello,

is it possible to get the whole titlebar as a toogle to expand/collapse the panel? 

![image](https://github.com/radzenhq/radzen-blazor/assets/128692095/27daf286-170e-4166-b92c-26501191b79c)

Easier usability on mobile devices. They dont have to search for the smaller icon which is the only toggle.

Would be great. 

Best regards

**Comment by enchev** [comment]
Yes, you can do that with the following HeaderTemplate:
```
    <HeaderTemplate>
        <div onclick="this.parentNode.querySelector('.rz-panel-titlebar-toggler').click()" style="width:100%;">
            Your text
        </div>
    </HeaderTemplate>
```
Use our forum in the future for such questions.
