### ISSUE TITLE
DataGrid LoadOnDemand blink on scroll (only with Firefox)

### ISSUE THREAD

**Issue by yanis-abc** [radzenhq/radzen-blazor#1376]
**Describe the bug**
**I got a graphic problem with Firefox, the grid blink when i scroll and that doesnt appear with other browsers.**
I use .NET 7.0 and my application is in Blazor Server.

**To Reproduce**
I am currently working with Radzen DataGrid and I try to load my data on the scroll (with the LoadData event).
I have a style of "cache" that store the data i have already fetch which is used when i scroll back.

My algorithm is :

1. When the LoadData is fired
2. If my page calculated with args.Skip.Value and args.Top.Value is not available in cache
2.1. Then fetch the API and store the data in the cache
3. Else
3.1. Pick the data in cache

You can see under two GIF of the behavior, the first one with Microsoft Edge and the second with Firefox.

**>1 Microsoft Edge**
![RadzenEdge](https://github.com/radzenhq/radzen-blazor/assets/150428543/f9fe5034-81ba-4290-8480-c5212cbd2204)

**>2 Mozilla Firefox**
![RadzenMozilla](https://github.com/radzenhq/radzen-blazor/assets/150428543/ad6c1792-27fa-443f-b771-fbc2a1deeb2a)

**Do you have any idea of what i did wrong ?**
Thanks.

Best regards,
Yanis.

**Comment by enchev** [comment]
Let's continue the conversation in our forum: https://forum.radzen.com/t/datagrid-loadondemand-blink-on-scroll-only-with-firefox/16441/2
