### ISSUE TITLE
Sorting a DataGrid results in an empty DataGrid on https://blazor.radzen.com

### ISSUE THREAD

**Issue by gauss-lvs-dev** [radzenhq/radzen-blazor#1381]
**Describe the bug**
Sorting a DataGrid with virtualization results in an empty DataGrid on https://blazor.radzen.com/. The content of the grid appears once I start scrolling in the grid.

**To Reproduce**
1. Go to https://blazor.radzen.com/datagrid-virtualization-loaddata 
2. Click on the column header OrderID in order to sort the grid
3. The grid is empty afterwards

**Expected behavior**
A grid with content sorted by the selected column.

**Screenshots**
![datagrid_empty](https://github.com/radzenhq/radzen-blazor/assets/51820531/c9b6545d-e037-4881-8b9b-7553b9425d13)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge, Mozilla Firefox

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/cda2ca43dd80d0d2078549fda0eae37be8454ae4
