### ISSUE TITLE
When having @ref and SettingsChanged on a DataGird Compoment together the is SettingsChanged Method is called infinity often

### ISSUE THREAD

**Issue by Alex-Dall** [radzenhq/radzen-blazor#1382]
Hello,
as described in the headline the following Code is calling Writing "Hello" to the console for an infinity amount after i change a setting for the first time (change page, apply a filter, ...). The application is haning up because of this infinity loop.

```
 <RadzenDataGrid @ref="@_serverLog" TItem="ServerLog" FilterMode="FilterMode.SimpleWithMenu" AllowFiltering="true" AllowSorting="true" AllowGrouping="true" AllowPaging="true" PageSize="25" Style="height: calc(100vh - 160px)" RowRender="@RowRender" SettingsChanged="@(() => { Console.WriteLine("Hallo"); })">
[...]
```

Do I make somthing wrong or is this a bug?

King regards,
Alex

**Comment by enchev** [comment]
The code is not complete - please use our forum to post such questions.
