### ISSUE TITLE
Click on any element in the form triggers click on RadzenButton below

### ISSUE THREAD

**Issue by nine-2-five** [radzenhq/radzen-blazor#1384]
**Describe the bug**
NET 8 Maui Blazor, with RadzenTemplateForm or EditForm, with textbox with no click handler and a button with click handler.
When any of the elements on the form are tapped, the click event on RadzenButton fires, and fires indefinetly.

**To Reproduce**
1. Create a form with RadzenTextBox and RadzenButton
2. Click on a textbox
3. Click handler for RadzenButton fires (and it won't stop firing)

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
The click handler should only fire when the RadzenButton is clicked.

**Screenshots**

**Desktop (please complete the following information):**
 - Android 14
 - BlazorWebView
 - NET 8

**Additional context**

**Comment by enchev** [comment]
By definition HTML form will be submitted on ENTER:
https://www.w3.org/TR/2018/SPSD-html5-20180327/forms.html#implicit-submission
You can set the button type to Button instead Submit to avoid this.
