### ISSUE TITLE
DataGrid text column filtering broken as of v4.25.0

### ISSUE THREAD

**Issue by mcluley** [radzenhq/radzen-blazor#1386]
Problem only since v4.25.0
When filtering is applied to a datagrid, the automatic filtering texboxes on just text columns, no longer allows the cursor to be put into the textbox and subsequently anything typed into it. Behaviour is as if the filter textbox is readonly.

 - OS: Windows 10
 - Browser:  Microsoft Edge (Version 121.0.2277.128 (Official build) (64-bit))
 - Radzen.Blazor Version: 4.25.0 onwards

Described problem was not present on previous version of v4.24.7

**Comment by enchev** [comment]
Works normally on our demos:
https://blazor.radzen.com/datagrid-simple-filter
