### ISSUE TITLE
Expand Collapse in TreeView

### ISSUE THREAD

**Issue by GioeEng** [radzenhq/radzen-blazor#1389]
In the TreeView control in Data-Binding, when you collapse and expand an element a few times, a **blocking error occurs**.
The operation is also **easily replicated on the site demo**.

The problem occurs on line 259 of RadzenTreeItem.razor.cs trying to do an Insert of an element beyond the Count of the collection.

The error is caused by the new part related to the new 'KeyPress' functions defined in the latest versions.

Going back to commit 1a3643d6 the problem does not occur.

**Comment by Nardo86** [comment]
I can confirm, this also happens in https://blazor.radzen.com/tree-data-binding when collapsing and expanding a message appears at the bottom "An error has occurred. This app may no longer respond until reloaded. [Reload]"
