### ISSUE TITLE
RadzenDataGrid 

### ISSUE THREAD

**Issue by djatkinsrealis** [radzenhq/radzen-blazor#1392]
**Describe the bug**

**To Reproduce**

Alternatively link your repo with a sample project that can be run.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by enchev** [comment]
Hi @djatkinsrealis,

Unfortunately I'm not sure what you are reporting, can you provide additional details?

**Comment by djatkinsrealis** [comment]
I did not complete that submission. No idea why it posted itself. I will delete this post.
