### ISSUE TITLE
DataFilter Auto not working for DateTime

### ISSUE THREAD

**Issue by ollie-dot-earth** [radzenhq/radzen-blazor#1396]
**Describe the bug**
The Auto apply feature of the DataFilter doesnt work for DateTime

**To Reproduce**
1. Go to https://blazor.radzen.com/datafilter
2. Enter a filter that uses DateTime
4. See that it doesnt auto apply the way it does for other filters

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
After entering the filter it should apply

**Desktop:**
 - OS: Windows 11
 - Browser: Chromium, Vivaldi
 - Version: 120

**Comment by nnuuvv** [comment]
??
Any context?

**Comment by enchev** [comment]
Hey @nnuuvv,

Are you using git for the first time? Do you see referenced commit closing the issue?
