### ISSUE TITLE
Tooltip Showing Multiple LineSeries Values

### ISSUE THREAD

**Issue by SwiftyZA** [radzenhq/radzen-blazor#1403]
The tooltip on the datamarkers of a linechart only contains the value of the current series. Is it possible to override this content and provide my own? My goal here is to replicate the behavior of the Blazor.Boatstrap chart datamarker tooltip where the tooltip contains the corresponding value of all other series'.
![image](https://github.com/radzenhq/radzen-blazor/assets/8044300/8deb09ed-e385-4ce5-ba73-d83532215a1a)

**Comment by yordanov** [comment]
Shared chart tooltip added with #1651
