### ISSUE TITLE
Please remove out of support framework

### ISSUE THREAD

**Issue by scharada** [radzenhq/radzen-blazor#1404]
net core 5.0 has been out of support for sometime now but is still supported by razden.
please consider removing it..

**Comment by enchev** [comment]
It’s already removed in our 5.0 branch:
https://forum.radzen.com/t/upcoming-changes-in-radzen-blazor-5-0-0/16516

**Comment by enchev** [comment]
Fixed https://github.com/radzenhq/radzen-blazor/commit/92e4249eecaf6a59e235dd9202cbaebc3bb37d96
