### ISSUE TITLE
PageSize can't be changed with PageSize Dropdown when DataGrid has set PageSize and Settings is used.

### ISSUE THREAD

**Issue by marekm294** [radzenhq/radzen-blazor#1407]
**Describe the bug**
Page size can't be changed (title of the bug)

**To Reproduce**
If you have RadzenDataGrid with these setting
```
PageSizeOptions="[10, 20, 40, 60]"
@bind-Settings="@DataGridSettings"
```
PageSize is correctly set when you change it in the dropdown.

But when you add PageSize value
```
PageSize="20"
PageSizeOptions="[10, 20, 40, 60]"
@bind-Settings="@DataGridSettings"
```
it's no more possible to change the value with the dropdown.
PageSIzeChanged is first called with correct value and then it's called again but with original value (there are two field in the code for one Property in this is probably causing the problem)

If load datasettings with page size different than PageSize set as "default" value
```
PageSize="20"
PageSizeOptions="[10, 20, 40, 60]"
@bind-Settings="@DataGridSettings"
```
the first page will use page size loaded from Settings.
But if you change Page, PageSize is automatically change to PageSize set as "default" (20 in this case).

Expected behavior**
PageSize can be set to and Settings can be used at the same time,

**Comment by enchev** [comment]
PageSize should be bound to a variable and changed accordingly as well.

**Comment by marekm294** [comment]
@enchev I'd like to suggest to update demo where you show developers how should it work

**Comment by enchev** [comment]
Hey @marekm294,

You can check this demo:
https://blazor.radzen.com/datagrid-save-settings-loaddata
