### ISSUE TITLE
Material theme buttons font issue

### ISSUE THREAD

**Issue by eldadweiss** [radzenhq/radzen-blazor#1413]
Hi,

When using a fresh .Net8 Blazor WebApp project with Radzen components (using the default Material theme) the buttons font is different than the buttons in your site. after investigating I found that it even happens in your "How to use the free Radzen Blazor UI Components in .NET 8" Youtube tutorial video.

How it should look : https://blazor.radzen.com/button?theme=material
How it looks : https://www.youtube.com/watch?v=q6PDQ-mXtf8 (go to 6:08).

**Comment by yordanov** [comment]
Looks like Bootstrap styles are interfering with Radzen. We are working on detaching any Bootstrap dependencies in [Radzen.Blazor 5.0.0](https://forum.radzen.com/t/upcoming-changes-in-radzen-blazor-5-0-0/16516) that should resolve this issue.

**Comment by enchev** [comment]
Fixed https://github.com/radzenhq/radzen-blazor/commit/92e4249eecaf6a59e235dd9202cbaebc3bb37d96
