### ISSUE TITLE
Data grid settings are not working after last update

### ISSUE THREAD

**Issue by dominikcip** [radzenhq/radzen-blazor#1414]
We are binding DataGridSettings (as mentioned in demo) and load data in OnInitializedAsync(). DataGridSettings are still succesfully saved in local storage but Settings are not applied to grid after loading.

**Comment by enchev** [comment]
Any example how to reproduce this? Works normally on our demos:
https://blazor.radzen.com/datagrid-save-settings
https://blazor.radzen.com/datagrid-save-settings-loaddata

**Comment by dominikcip** [comment]
FIrst one works everywhere but the second one (https://blazor.radzen.com/datagrid-save-settings-loaddata) does work only in Edge,Safari and Mozilla but not in Chrome browser.

**Comment by dominikcip** [comment]
Yep that helped, thanks!
