### ISSUE TITLE
Infinite reload loop in RadzenDataGrid with empty data when AllowVirtualization is true and Settings are applied.

### ISSUE THREAD

**Issue by difg76** [radzenhq/radzen-blazor#1416]
**Describe the bug**
In a RadzenDataGrid that has empty Data and AllowVirtualization="true" (and AllowPaging="false"), when settings are applied, it goes into an infinite Reload loop that freezes the application. This seems to happen due to the change in  https://github.com/radzenhq/radzen-blazor/pull/1175, which relies on Query.Top being to set to a non-null value, but that only happens when AllowPaging="true".

The issues seems to be mainly with the call to StateHasChanged() after LoadStateAsync() (in the datagrid-save-settings). Without that call, it doesn't happen, but the settings are then not updated properly after they are loaded until some point later that causes a re-render.

Not sure what the best fix is, but limiting that if condition in pull request 1175 to only apply to non-virtualized grids seems to work.

**To Reproduce**
In the datagrid-save-settings demo:
1. In RadzenBlazorDemos/Pages/DataGridSaveSettings.razor, for the RadzenDataGrid component, change AllowPaging to false, and add AllowVirtualization="true".
2. In that same file, in OnInitializedAsync, change the line "employees = dbContext.Employees;" to "employees = new List<Employee>();" so that the employees list is empty.
3. In Radzen.Blazor/RadzenDataGrid.razor.cs, in the LoadSettingsInternal method, add a log inside the "if (View.Any() == false && Query.Top == null)" block, such as Console.WriteLine("LoadSettingsInternal shouldUpdateState 14.");
4. Run the demo in hosted mode (RadzenBlazorDemos.Host).
5. Navigate to the datagrid-save-settings page.
6. The page should load, and a grid should show with no rows.
7. Open the developer console to see the logs.
8. Make a change that causes settings to be saved (like changing the sort order in one of the columns).
9. You'll see the log added in step 3 being logged over and over (infinite loop), and the grid never updates.
10. If you try opening the page again (may need to close it and then open a new one and navigate back to the page), you'll notice it do the same logging and never finish rendering the page.

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
The grid works as expected, showing no rows and with the expected settings applied (sort order as set in step 8).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome
 - Version: 122

**Additional context**
I experience this in my own application when the grid has been created and settings are loaded but there's no data (the data is still being loaded, though this issue causes the data loading call to be starved and never get executed.

**Comment by enchev** [comment]
Thanks for the report @difg76! Please submit pull request with the fix!
