### ISSUE TITLE
Tooltip in cell of virtualized RadzenDataGrid Disappears

### ISSUE THREAD

**Issue by KaleyBM-FSB** [radzenhq/radzen-blazor#1417]
**Describe the bug**
When hovering over an icon within a RadzenDataGridColumn in a virtualized RadzenDataGrid, the tooltip doesn't always show.
But when it does show, it's only for a split second before it disappears.

**To Reproduce**

```
 <RadzenDataGrid AllowColumnResize="true" AllowAlternatingRows="true" AllowSorting="true" GridLines="@DataGridGridLines.Both" AllowVirtualization="true"
                 @bind-Value="@selectedItems" Data="@Items" TItem="Customer" IsLoading=@DataLoading Sort="@ShowLoading" RowRender="RowRender">
     <Columns>
         <RadzenDataGridColumn TItem="Customer" Title="Third Party Solutions" Property="ThirdParty" TextAlign="TextAlign.Center">
             <Template>
                 <RadzenLabel Visible="@context.ThirdParty" MouseEnter="@(args => ShowTooltip(args, context))" Style="width:100%;"><RadzenIcon Icon="check_circle" IconColor="@Colors.Base900" /></RadzenLabel>
             </Template>
         </RadzenDataGridColumn>
     </Columns>
 </RadzenDataGrid>

@code {

...

 @*Without this rows would not be same height*@
 void RowRender(RowRenderEventArgs<Customer> args)
 {
     args.Attributes.Add("style", $"height:38px;");
 }

 void ShowTooltip(ElementReference elementReference, Customer customer, TooltipOptions options = null) => tooltipService.Open(elementReference, ds =>
 @<div>
     <ul style="list-style:none;margin:0px;padding:0px;">
         @if (customer.Dash)
     {
         <li>Dash</li>
     }
         @if (customer.Merchant)
     {
         <li>Merchant</li>
     }
         @if (customer.Wealth)
     {
         <li>Trust & Wealth</li>
     }
     </ul>
 </div>
     , options);
}
```

1. Test virtualized RadzenDataGrid similar to above code.
2. Add duration to TooltipOptions to test difference (tooltip still does not always show on hover but at least it does stay on screen for the duration).
3. Remove AllowVirtualization="true" and test difference (tooltip works perfectly fine now)

**Expected behavior**
I would expect the tooltip to show just like it does on a paged RadzenDataGrid.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 122.0.6261.112 

**Additional context**
Not sure if the tooltip _can_ be used in a cell of a virtualized RadzenDataGrid, I know virtualization can be pretty finicky. Please let me know if there is any work around for this.

**Comment by enchev** [comment]
I'm unable to reproduce such problem
![tooltip-virt](https://github.com/radzenhq/radzen-blazor/assets/5804953/82be2128-0616-4bfd-9844-0f0ee3704770)
