### ISSUE TITLE
[WASM] [Net 6 Preview 4] RadzenDataGrid Filter Exception Error

### ISSUE THREAD

**Issue by rblanca** [radzenhq/radzen-blazor#143]
**Describe the bug**
Using Any Filter option in RadzenDataGrid its results in an "System.Exception: Specific method not found: FirstOrDefault". My apologies if the error it's not related to Radzen Team due the fact that I'm using a preview version of the runtime.

**To Reproduce**
1. Create a simple RadzenDataGrid  
2. Use the Filter option in the DataGrid
3. See the error

**Expected behavior**
It should not have crash

**Screenshots**
![image](https://user-images.githubusercontent.com/37780410/122096437-f1543f80-cde4-11eb-9a8d-e5bc994915d6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 
 - Version 91

**Additional context**

Here is the simple code I've used

```<RadzenCard class="mt-4">
	<RadzenDataGrid @ref="gridUserDTO" Data="@users" TItem="UserDTO" AllowFiltering="true" AllowColumnResize="true" AllowSorting="true" PageSize="10" EmptyText="No hay datos a mostrar." LogicalFilterOperator="LogicalFilterOperator.Or"  Style="height:400px; width:100%;">
	<Columns>
		<RadzenDataGridColumn TItem="UserDTO" Property="Id" Title="Id"  Width="30%"/>
		<RadzenDataGridColumn Context="_context" TItem="UserDTO" Property="Name" Title="Nombre" Width="30%">
			<Template Context="user">
				@user.Name
			</Template>
			<EditTemplate Context="user">
				<RadzenTextBox @bind-Value="@user.Name"  />
			</EditTemplate>
		</RadzenDataGridColumn>
	</Columns>
	</RadzenDataGrid>
</RadzenCard>

@code {

	string selectedUserId { get; set; }
	IEnumerable<UserDTO> users { get; set; } = new List<UserDTO>();

	RadzenDataGrid<UserDTO> gridUserDTO;
```

**Comment by enchev** [comment]
Hi @rblanca,

The issue is related to https://github.com/zzzprojects/System.Linq.Dynamic.Core/. Maybe it's already fixed however we plan to upgrade to .NET 6 when we have at least CTP.
