### ISSUE TITLE
Draggable dialog title bar collapses when draggable is set to true on default theme when there is no title

### ISSUE THREAD

**Issue by DanRogers99** [radzenhq/radzen-blazor#1432]
https://blazor.radzen.com/dialog?theme=default&wcag=false

```
    public async Task OpenOrder()
    {
        await DialogService.OpenAsync<DialogCardPage>(string.Empty,
               new Dictionary<string, object>() { { "OrderID", orderID } },
               new DialogOptions() { Width = "700px", Height = "512px", Resizable = true, Draggable = true });
    }
```

![image](https://github.com/radzenhq/radzen-blazor/assets/33861884/85cd17b4-470a-409b-9b01-7014f5c8ed55)

### Behaviour of empty title with draggable set to false
```
    public async Task OpenOrder()
    {
        await DialogService.OpenAsync<DialogCardPage>(string.Empty,
               new Dictionary<string, object>() { { "OrderID", orderID } },
               new DialogOptions() { Width = "700px", Height = "512px", Resizable = true, Draggable = false });
    }
```
![image](https://github.com/radzenhq/radzen-blazor/assets/33861884/632a65a0-e064-4b4d-804d-d290c15e37e5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 122
 - Version 4.28.4

**Comment by enchev** [comment]
I don't see any difference using the latest version:
![image](https://github.com/user-attachments/assets/fa32287d-8d37-45a4-a7e5-91f205ea8510)
![image](https://github.com/user-attachments/assets/d81d2acb-9051-40af-9623-1de1a4c69928)
