### ISSUE TITLE
When you have multiple alerts created and you close the first one, all of them are closed

### ISSUE THREAD

**Issue by javierlatorrep** [radzenhq/radzen-blazor#1443]
**Describe the bug**
When having multiple alerts and closing first, the second is closed too.

![2024-03-27-17-46-48-min (1)](https://github.com/radzenhq/radzen-blazor/assets/23117048/13d89d99-5656-4cb2-9bb8-43d6c7f8513c)

**To Reproduce**
1. Go to https://blazor.radzen.com/alert?theme=material&wcag=false
2. Click on Edit Source
3. Paste the following code
```
<RadzenStack Gap=0>
    @foreach (var lastExample in lastExamples)
    {
        if (!storedExamples.Contains(lastExample.Title)) {
            <RadzenAlert class="rz-mt-0" Close=@(() => { OnClose(lastExample); })>
                <RadzenText TextStyle=TextStyle.H6 class="color-inherit">
                    @((MarkupString)lastExample.Title)
                </RadzenText>
                @((MarkupString)lastExample.Body)
            </RadzenAlert>
        }
    }
</RadzenStack>

@code {
    public class Example {
        public string Title {get; set;}
        public string Body {get; set;}
    }

    public List<string> storedExamples = new();
    public List<Example> lastExamples = new();

    protected override void OnInitialized()
    {
        lastExamples = new List<Example> {
            new Example { Title = "Test1", Body = "Body1" },
            new Example { Title = "Test2", Body = "Body2" },
        };
    }

    public void OnClose(Example example)
    {
        storedExamples.Add(example.Title);
    }
}
```
4. Click on Run the code.
5. Close the alert with Test1 title.

**Expected behavior**
The first Alert should be closed, but the second should still be visible.

**Screenshots**
Gif on the top

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge 
 - Version 123.0.2420.53 (Official build) (64-bit)

**Additional context**
Radzen Blazor: 4.28.8

**Comment by enchev** [comment]
Hey @javierlatorrep,

You need to set @key when you create Blazor components in a loop:
```
<RadzenAlert @key=lastExample ...
```

**Comment by javierlatorrep** [comment]
Great! Thanks @enchev! 👏🏼
