### ISSUE TITLE
Dialog drag broken when a text selection from body is expanded to title.

### ISSUE THREAD

**Issue by milanc** [radzenhq/radzen-blazor#1444]
**Describe the bug**
After text is selected inside the dialog and the selection is also including the title, dialog gets locked in the drag mode.
The only way to stop dragging is by right clicking on the dialog and clicking on the X.
After this, the following exception is thrown on every mouse move.
`Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '10'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId') .....`

This behavior is 

**To Reproduce**
1. Go to [Dialog Example](https://blazor.radzen.com/dialog#open-page-as-dialog)
2. Open the dialog
3. Drag mouse to select the text in the body and extend selection to the title text.
![image](https://github.com/radzenhq/radzen-blazor/assets/8333458/d33e7619-39f0-4c77-8349-89460da3c1e2)
4. Release the mouse and start dragging
5. Notice that after releasing the mouse, dialog is still following the mouse movements.
6. Right click on the dialog and click **X** button
7. Notice exception being thrown in the console.

**Expected behavior**
Dialog should not stuck in the drag mode.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123.0.6312.59

**Additional context**
Initially I thought is it intermittent and based on some quick drag and click actions but while reproducing it for this defect I realized that the issue is manifested only when title text is included in the selection.

Without looking into the code, I assume the easiest solution would be to disable title text selection.
.rz-dialog-title {
   ...
    user-select: none;
}

**Comment by enchev** [comment]
Fixed https://github.com/radzenhq/radzen-blazor/commit/81d14cbecc2826bc113acaa05d0548a4f772c735
