### ISSUE TITLE
DataGrid autosize/autofit columns

### ISSUE THREAD

**Issue by enchev** [radzenhq/radzen-blazor#145]
Details: https://forum.radzen.com/t/feature-request-datagrid-autosize-autofit/8235

**Comment by Tilation** [comment]
This would be very nice to have, instead of hardcoding width values for each column

**Comment by enchev** [comment]
You can use the following style to force the DataGrid to auto-size columns:
```
 <style>
    .rz-grid-table {
        width: unset;
    }
</style>
```
Check this demo for reference:
https://blazor.radzen.com/datagrid-inline-edit
