### ISSUE TITLE
Column picker can't read visibility if DataGrid column has a variable for Title

### ISSUE THREAD

**Issue by larow616** [radzenhq/radzen-blazor#1451]
**Describe the bug**
If a RadzenDataGridColumn has a Title set to a string variable vs hard-coded, the correct value of the variable is shown in the picker but it appears as unselected, even though the column is visible. Workaround is to explicitly set the Visibility of the column to true.

**To Reproduce**
1. Create a datgrid and set AllowColumnPicking=true
2. Create variable _myTitle and set it during Initialization of the razor component.
3. Set column as follows: <RadzenDataGridColumn Title="@_myTitle" Property="SomeProperty"></RadzenDataGridColumn>
4. View column picker - value of _myTitle will show, but it is unchecked.

**Comment by enchev** [comment]
Works well in our demo: https://blazor.radzen.com/datagrid-column-picker
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/00103406-ffcc-4618-b789-b18caa6a3ef6)
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/06fd368e-4a37-4d77-8e3e-1c80f7a1e484)

![column-picker-title](https://github.com/radzenhq/radzen-blazor/assets/5804953/eecc78a1-b30d-4f6d-95c1-e076eed4f343)

**Comment by larow616** [comment]
Ok - I didn't realize it is by design to explicitly set Visible when Title is a variable. Thanks for clarifying!
