### ISSUE TITLE
RenderTreeBuilder to create Radzen components with validator(s) causes InvalidOperationException: Cannot find component with Name [name]

### ISSUE THREAD

**Issue by larow616** [radzenhq/radzen-blazor#1452]
[RadzenDynamicControlSample.zip](https://github.com/radzenhq/radzen-blazor/files/14855056/RadzenDynamicControlSample.zip)
**Describe the bug**
I am attaching a sample project with nuget package 4.29.1 which reproduces the error. Sample project works as expected with version 4.20.1. This error is preventing me from upgrading to the latest version.

I am using automation based on model properties to create components with a RenderTreeBuilder. On the Left side of the screen, the attached sample generates 3 textboxes with validators. The right side of the screen is a static textbox bound to a model property with a required validator. Clicking Save will generate the error.

**To Reproduce**
1. Run the sample and click Save. Look at developer tools in the browser to see error description.

**Comment by akorchev** [comment]
Hi @larow616,

Change your code from `builder2.AddAttribute(10, "autocomplete", false);` to `builder2.AddAttribute(10, "AutoComplete", false);` and it should work as expected.

**Comment by larow616** [comment]
That worked. Thank you for your help!
