### ISSUE TITLE
Misleading filter indication

### ISSUE THREAD

**Issue by RTSTALER** [radzenhq/radzen-blazor#1455]
I found two bugs. Here are the reproduction steps:

Bug 1
1. Open advanced filter window
2. Write something in any of two meanings
3. Press Tab
4. The filter icon changes to active
5. Press Escape

Result: The filter icon remains active, although the data has not been loaded, which is misleading

Because when you enter any value, the filter value changes and I cannot bypass this. As one of the options, I suggest clearing the column filter by pressing a button Escape

Bug 2

1. Open advanced filter window
2. Select any filter operator except IsNull/IsNotNull/IsEmpty/IsNotEmpty
3. Write something in any of two meanings
4. Erase everything you wrote and click Apply.

Result: The filter was applied when it shouldn't be
After all, to filter by “empty string” there are the above listed filters

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome/Edge/Firefox
 - Version RadzenDemos

**I sent you a merge request, but was rejected without any response. I hope to hear it**

**Comment by enchev** [comment]
Hey @RTSTALER,

Are you using GitHub for the first time? Your pull request was no rejected but closed by a commit with more general implementation/fixes.
