### ISSUE TITLE
RadzenDataGridColumn frozen function sometime not work

### ISSUE THREAD

**Issue by yukking** [radzenhq/radzen-blazor#146]
When RadzenDataGridColumn width uint is rem or use RadzenDataGrid CellRender callback set cell attributes, frozen function are not work. Thanks.
![image](https://user-images.githubusercontent.com/8501077/122362358-a542ff80-cf8a-11eb-8a69-fcd59db5f679.png)
![image](https://user-images.githubusercontent.com/8501077/122362576-d1f71700-cf8a-11eb-8c87-7c7149772e10.png)

**Comment by enchev** [comment]
We cannot reproduce a bug from a screenshot. I already answered your other issue that we cannot reproduce the problem:
https://github.com/radzenhq/radzen-blazor/issues/144
If you continue to open duplicate issues with little to no info I'll have no other option but ban you from this repo.
