### ISSUE TITLE
@bind-Settings="@Settings" don't work

### ISSUE THREAD

**Issue by MatteoProbe** [radzenhq/radzen-blazor#1460]
**Describe the bug**
I copied the code to save the datagrid settings to localStorage but it doesn’t work. In localStorage the data is saved correctly and then retrieved properly deserialized. I do not understand why the settings are not applied on the datagrid. I am in webAssembly. (I attach the code screenshots) 

![datagrid2](https://github.com/radzenhq/radzen-blazor/assets/165903254/3e605662-b52d-49f0-ad3f-5c0d836e4496)

![datagrid1](https://github.com/radzenhq/radzen-blazor/assets/165903254/fbaccb06-2182-4cf0-82cd-9d97f15e2d1b)

**Comment by enchev** [comment]
You can check our demo to see what’s different with yours. Our demos are also WebAssembly.
