### ISSUE TITLE
Issue with RadzenTabsItem Template in Material-base Theme

### ISSUE THREAD

**Issue by Lemaus123** [radzenhq/radzen-blazor#1461]
**Description**
The bug is related to modifying the template in the RadzenTabsItem component. By clicking on the rows of my table, it opens tabs dynamically to see more information about the selected item.

I modified the template to add an icon represented by an 'x' at the end of the tab to be able to close it.

**In the dark-base and standard-base themes, it works, but not in the **material-base** theme.**

I saw that there are some issues created regarding the material-base theme, but I took the time to open a new issue.

**Reproduction**
Create a RadzenTabs component and add a template to the RadzenTabsItem similar to this.
 
```c#
<RadzenTabsItem>
     <Template>
         <span @onclick="() => function(sim.Id)">
	            @sim?.Name
         </span>

         <span style="display: flex; gap: 6px; margin-left: 5px; cursor:pointer">
	            <RadzenIcon IconColor="@Colors.Danger" Icon="close" Size="ButtonSize.ExtraSmall" @onclick="() => function2(sim)"/>
         </span>
     </Template>
<RadzenTabsItem>
``` 

**Screenshots**
On this dark theme, the 'x' button works properly. It calls my function, and everything works well.
![image](https://github.com/radzenhq/radzen-blazor/assets/115738837/9af7a9dc-c84f-479d-ac26-1d6753d84559)

This is the non-working material-base theme.
![image](https://github.com/radzenhq/radzen-blazor/assets/115738837/91263bcf-45c9-4ece-8669-513cfe7a6808)

**Desktop (please complete the following information):**
I'm using Brave, but I doubt the browser is the problem since other themes work well.

**Comment by yordanov** [comment]
Hi @Lemaus123,

Maybe you can try with a RadzenButton instead of RadzenIcon?

Here is the button configuration that makes it look like a blank icon only button:

```html
<RadzenButton Icon="close" ButtonStyle="ButtonStyle.Danger" Size="ButtonSize.ExtraSmall" Variant="Variant.Text" />
```

Also you don't need the `<span style="display: flex; gap: 6px; margin-left: 5px; cursor:pointer">` the way it is.
