### ISSUE TITLE
RadzenNumeric isn't updating value when format property is used

### ISSUE THREAD

**Issue by chrgraefe** [radzenhq/radzen-blazor#147]
**Describe the bug**
RadzenNumeric isn't updating value when format property is used

**To Reproduce**
Repo: https://github.com/chrgraefe/RadzenNumeric

1. Start project
2. Navigate to "/radzennumericexample"
3. Click into numeric field
4. delete just the value (50) after the decimal point
5. type 25 as new value after the decimal point. So the new value is 1200.25 €
6. leave the form field
7. value is now 0.00 €

**Expected behavior**
Value is in the field as editted

**Comment by MPapst** [comment]
happened because of the currency symbol, which was not removed before trying to parse the given string into a decimal.
