### ISSUE TITLE
Date is not selected when using RazdenDatePicker in OnDemand PopupRenderMode.

### ISSUE THREAD

**Issue by uittorio** [radzenhq/radzen-blazor#1473]
**Describe the bug**

Dates are not selected when using RazdenDatePicker in OnDemand PopupRenderMode.

**To Reproduce**
1. Go to (https://blazor.radzen.com/datepicker)
2. Scroll down to first example
4. Click on Edit Source
5. Add PopupRenderMode="PopupRenderMode.OnDemand" to the RadzenDatePicker
6. Run the new code
8. Open the popup to select date
9. Select a date
10. Observe that the date is not selected

**Expected behavior**
Date is selected and displayed

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/17477623/c9405bb4-f61f-4bb5-a481-3c0804f42b0b)
![image](https://github.com/radzenhq/radzen-blazor/assets/17477623/7537d03f-e0b1-4418-9e1d-f0f73f9a90b6)

**Desktop (please complete the following information):**
 - OS: [Linux-PopOS]
 - Browser [chrome]
 - Version [122.0.6261.111 (Official Build) (64-bit)]
- Radzen.Blazor [4.29.8]. This is the one used by the blazor.radzen.com. View screenshot

By changing the PopupRenderMode to PopupRenderMode.Initial it works. 

I've noticed that if I use the keyboard to select the day instead of the mouse it works regardless of the render mode.

I've tried to remove extra event listeners by selecting the element in the browser! I've found out that by removing a mouseup event listener the component was working as expected but I couldnt determine what code was attached to the event. 

Hopefully this helps!

**Comment by enchev** [comment]
Here is what I see:
![dp-ondemand](https://github.com/radzenhq/radzen-blazor/assets/5804953/85465364-41b9-4e69-b720-5c0bcf51e8b6)

**Comment by uittorio** [comment]
I can still reproduce it on the browser version I've mentioned above. Which browser/OS are you using? I will ask around to try it with different browsers and let you know

**Comment by enchev** [comment]
Thanks @colinbate! I was able to reproduce it and will remove mouseup code.
