### ISSUE TITLE
RadzenListBox create access to FilterString

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1476]
For RadzenListBox
need create access to the FilterString from code.
I want to set the initial value in FilterString

![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/054dbdf6-a28e-4f06-b79e-7b7f42fccf36)

**Comment by enchev** [comment]
You can use @bind-SearchText. Use our forum in the future for such questions.

**Comment by Andrey-2021** [comment]
Excuse me.
Please add info/example about @bind-SearchText
to pages:

https://www.radzen.com/documentation/blazor/listbox/
https://blazor.radzen.com/listbox
https://blazor.radzen.com/docs/guides/components/listbox.html
https://blazor.radzen.com/docs/api/Radzen.Blazor.RadzenListBox-1.html
