### ISSUE TITLE
RadzenTabs component out of sync occurs between the SelectedIndex and the displayed tab

### ISSUE THREAD

**Issue by aplib** [radzenhq/radzen-blazor#1482]
https://github.com/radzenhq/radzen-blazor/issues/1463#issuecomment-2067545805

    <RadzenTabs @bind-SelectedIndex=@selectedIndex>
        <Tabs>
            <RadzenTabsItem Text="Customers">
                Customers
            </RadzenTabsItem>
            @if (!remove_section)
            {
                <RadzenTabsItem Text="Orders">
                    Orders
                </RadzenTabsItem>    
            }
            <RadzenTabsItem Text="Order Details">
                Order Details
            </RadzenTabsItem>
        </Tabs>
    </RadzenTabs>
    
    <p>
        @selectedIndex
    </p>
    
    <RadzenCheckBox @bind-Value=@remove_section Name="CheckBox1" />
    <RadzenLabel Text="CheckBox" Component="CheckBox1" Style="margin-left: 8px; vertical-align: middle;" Change="@(()=>StateHasChanged())" />
    
    @code {
        bool remove_section;
        int selectedIndex = 0;
    }

Check cases for the second and last tab separately

**Comment by enchev** [comment]
Adding items in such way in Blazor will always add the conditional item at the end and the index of the item will no longer be the initial one. You can manually set the index in such cases.
