### ISSUE TITLE
Splitbutton tabindex

### ISSUE THREAD

**Issue by MitchKuijpers** [radzenhq/radzen-blazor#1488]
The splitbutton has a tabindex around the entire button. However this will limit the user when using tabs, you will not be able to choose another options.

So my understanding would be that the the main button and the chevron should be two individual buttons and after opening the splitbutton the first element op the options should get the focus state.

**Comment by enchev** [comment]
SplitButton is a single tab stop component. More info about how to navigate between items can be found on our demos
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/7286171a-c353-4ce1-93c0-89a7f748f7ae)
