### ISSUE TITLE
DataFilter CompositeFilterDescriptor.LogicalFilterOperator is not reflecting the value from rendering

### ISSUE THREAD

**Issue by Kyles-Code** [radzenhq/radzen-blazor#1500]
In order to build a query manually, I need to parse the Filters object and translate to different query language for specific data source. (Ex: Ealsticsearch index).
However, the Filters object is NOT reflecting the value I chose in the browser like the screenshots below.

Value I chose in the browser at runtime:
![image](https://github.com/radzenhq/radzen-blazor/assets/66630609/5301904c-d1f6-49c8-810b-3dca6d6c38a7)

When I inspect the LogicalFilterOperator value on debugging:
![image](https://github.com/radzenhq/radzen-blazor/assets/66630609/83a71a58-c8db-433b-abb5-5074a33c305d)

Happy coding and regards,
Kyle

**Comment by Kyles-Code** [comment]
Adding more info, 
1. Client side WebAssembly (WASM)
2. Microsoft Edge browser : Version 123.0.2420.81 (Official build) (64-bit) on Windows 10

**Comment by enchev** [comment]
Works normally on our demos, make sure you are using the latest version:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/662e65d0-4958-4273-b3a6-8bf2f9dccd37)

**Comment by Kyles-Code** [comment]
Thank you for the response.
Yes it works on demo and DataFilter is bound with dataset. However, if I just want to get and parse CompositeFilterDescriptor, it doesn't reflect the value I chose. I am using ver 4.31.1.

**Comment by Kyles-Code** [comment]
> Works normally on our demos, make sure you are using the latest version: ![image](https://private-user-images.githubusercontent.com/5804953/328085078-662e65d0-4958-4273-b3a6-8bf2f9dccd37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTcxMTMsIm5iZiI6MTcxNTAxNjgxMywicGF0aCI6Ii81ODA0OTUzLzMyODA4NTA3OC02NjJlNjVkMC00OTU4LTQyNzMtYjNhNi04YmYyZjlkY2NkMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTczMzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc2N2RjMGEzMjAxNjYzOTZmZjUzZDc3M2YxOGYzYTZjNmVhMDA4OGFiZjFhZjkwMmM4YTU3MjIxMWYzNTE1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vMoXAGbPGozeE8jnTqBbSMfVnxoEad_XkluzNgFCAQE)

Thank you for the response.
Yes it works on demo and DataFilter is bound with dataset. However, if I just want to get and parse CompositeFilterDescriptor, it doesn't reflect the value I chose. I am using ver 4.31.1.
