### ISSUE TITLE
[bug] Dropdown 'Clear' button always visible

### ISSUE THREAD

**Issue by sendf** [radzenhq/radzen-blazor#1510]
When enabling 'AllowClear' for a DropDown, the 'X' icon never disappears, even when there is no value to clear anymore.

Here is an example (correct):
![image](https://github.com/radzenhq/radzen-blazor-studio/assets/168279078/3242beff-7f83-4785-8b52-d0a45b32f0f3)

After clicking the 'X', the icon should also be cleared along with the value, since there is nothing else to clear anymore:
![image](https://github.com/radzenhq/radzen-blazor-studio/assets/168279078/cae1f115-f746-430d-bd1d-a1bd7f14e4aa)

**Comment by enchev** [comment]
Here is what I see
![dp-clear](https://github.com/radzenhq/radzen-blazor/assets/5804953/a7f65f20-4a56-4e77-b862-f420eefd9bef)
