### ISSUE TITLE
RadzenDatePicker focus out issue on field edit

### ISSUE THREAD

**Issue by irtazaali** [radzenhq/radzen-blazor#1514]
RadzenDatePicker bind value not updated when date is edited in the text field and at the same time HTML button type submit clicked

1. Select date from picker
2. Edit date in the date field by changing value manually for year
3. Without clicking on any control on the form click submit button (HTML button type=submit)
4. The last edit of date picker field does not apply to the bind value

Alternatively before clicking submit button, click anywhere on the form or other fields, the change applies to the bind value

Browser: Chrome, Bing

**Comment by enchev** [comment]
I believe that this will be the case with any input. You can use @oninput event to update the value while typing.
