### ISSUE TITLE
Offer a DateRange Picker

### ISSUE THREAD

**Issue by taylorchasewhite** [radzenhq/radzen-blazor#1517]
**Is your feature request related to a problem? Please describe.**
I'd like to make it easy for a user to click and drag to select a range of dates. Currently I need to render two `DatePicker` components side by side or use a second component library that offers such a component but doesn't match with Radzen's nice look.

**Describe the solution you'd like**
I'd like to see a new component, `DateRangePicker` that allows binding to a `StartDate` and `EndDate` and has many of all the same parameters offered by the `DatePicker` like `Footer`.

Ultimately, I'm looking for something similar to this obsolete React Date Range component that's no longer maintained:

[https://hypeserver.github.io/react-date-range/](https://hypeserver.github.io/react-date-range/)

<img width="479" alt="image" src="https://github.com/radzenhq/radzen-blazor/assets/3686217/079876f9-e7f4-449e-8ae2-58c25d24df72">

Quick options on the left side are a nice touch but not necessary.

**Describe alternatives you've considered**
See initial prompt--I've considered using separate libraries, or two side-by-side `DatePicker` components.

**Comment by taylorchasewhite** [comment]
I suppose this is related to #157

**Comment by enchev** [comment]
Duplicate to https://github.com/radzenhq/radzen-blazor/issues/157
