### ISSUE TITLE
When the DatePicker component is placed in a modal popup (like bootstrap), the zindex gets messed up because the markup is injected outside of the modal element.  This prevents typing in the textboxes and interating with the components as intended.

### ISSUE THREAD

**Issue by nashtag** [radzenhq/radzen-blazor#1520]
**Describe the bug**

**To Reproduce**

Alternatively link your repo with a sample project that can be run.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by akorchev** [comment]
[There isn't anything we can do](https://forum.radzen.com/t/radzen-dropdown-dont-allow-me-to-type-anything-in-the-search/9776/20?u=korchev) to fix this problem in the Bootstrap dialog. You can use [RadzenDialog](https://blazor.radzen.com/dialog) instead.
