### ISSUE TITLE
Radzen DataGrid won’t apply saved settings after v4.29.2

### ISSUE THREAD

**Issue by QA-MaxMaassen** [radzenhq/radzen-blazor#1522]
Dear all,

I’m currently working on a project that relies heavily on the Radzen DataGrid. Therefore, I’ve created a Razor component called GenericGrid that inherits from the RadzenDataGrid.

In this setting I want to save any changes applied to the settings of the grid by registering internally (inside GenericGrid) to the SettingsChanged event of the Radzen DataGrid. Vice versa, I want to apply the saved settings again, when the page gets loaded and the GenericGrid renders initially.

My implementation stops working though, when I use a Radzen version higher than v4.29.2. More detailed, the GenericGrid still saves changed settings correctly, also loads them correctly but the loaded settings won’t be reflected in the GUI. This still works in v.4.29.2.
It’s worth noting that I can’t use the bind-Settings attribute of the Radzen DataGrid, as this is not available in this inherited scenario. Also, I don’t want to use the approach shown in the demo, as this would require me to handle the SettingsChanged event on every single page where I’m using the GenericGrid. The handling should rather be done centrally inside the GenericGrid component – handling the settings on every page (~100 pages inside my application) is not a good solution for my scenario.

During the implementation I noticed that handling the SettingsChanged event inside the derived component and applying the saved settings works until including version 4.29.2, as long as the GenericGrid gets assigned an empty variable to the Settings attribute (needed for some internal check != null inside the Radzen DataGrid before applying the settings). When using v4.29.3 or higher also the rendering behavior of the DataGrid changes: While a SettingsChanged event was fired before during rendering containing a settings object with RowCount = 0, the SettingsChanged event now doesn’t get fired anymore.

I’ve provided the relevant code for the derived GenericGrid component as well as the usage inside an exemplary page. Any advice or possible changes to this behavior are gladly apricated, as this currently stops me from implementing a frequently asked customer requirement.

Best regards and thanks in advance.
 
GenericGrid.razor
```
@using Newtonsoft.Json
@using System.Text

@inherits Radzen.Blazor.RadzenDataGrid<TItem>;
@typeparam TItem where TItem : class;

@{
    base.BuildRenderTree(__builder);
}

@code {
    /// <summary>
    /// Stores the local state of the DataGridSetting.
    /// Required, as the SettingsChanged method of the Radzen DataGrid can not be hidden or overwritten.
    /// </summary>
    private DataGridSettings? dataGridSettings;

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();

        //register internal event handler of the SettingsChanged event of the Radzen DataGrid
        SettingsChanged = new EventCallbackFactory().Create<DataGridSettings>(this, HandleSettingsChanged);

        //trys to load saved settings for the current user and DataGrid component
        await InvokeAsync(LoadGridStateAsync);        
    }

    /// <summary>
    /// Handles the SettingsChanged event of the Radzen DataGrid to enable storing of custom DataGridSettings.
    /// </summary>
    private void HandleSettingsChanged()
    {
        if (Settings != null && Settings.Columns.Count() == 0) //during first render the settings have Column.Count() == 0
        {
            Settings = dataGridSettings; //revert unwanted overwriting of default Radzen settings, when Grid renders initially
        }

        //only write changed settings to the database
        if (dataGridSettings != Settings 
            && (Settings != null && Settings.Columns.Count() > 0)) //avoid unwanted storing of default Radzen settings, when Grid renders initially
        {
            dataGridSettings = Settings;
            InvokeAsync(SaveGridStateAsync);
        }        
    }

/// <summary>
/// Allows async handling of changed Radzen DataGridSettings
/// </summary>
/// <returns></returns>
private async Task SaveGridStateAsync()
{
    try
    {
        //create a model object
        var setting = new DatagridSetting
        {
            DatagridId = "SampleValue",            
            Settings = JsonConvert.SerializeObject(dataGridSettings)
        };

        //try to find the associated record in the database
        var records = (await dataGridSettingService.getEntriesAsync()).Where(x => x.DatagridId == "SampleValue");

        if (records != null && records.Count() > 0)
        {
            var record = records.First();
            record.Settings = setting.Settings;
            //update an existing record in the database
            await dataGridSettingService.updateEntryAsync(record);
        }
        else
        {
            //add a new record to the database
            await dataGridSettingService.addEntryAsync(setting);
        }
    }
    catch (Exception e)
    {
        Log.Error(e, e.Message);
        throw;
    }
}

    /// <summary>
    /// Allows async loading of customized Radzen DataGridSettings
    /// </summary>
    /// <returns></returns>
    private async Task LoadGridStateAsync()
    {
        try
        {
            //try to find the associated record in the database
            var records = (await dataGridSettingService.getEntriesAsync()).Where(x => x.DatagridId == "SampleValue");

            if (records != null && records.Count() > 0)
            {
                var record = records.First();
                var setting = JsonConvert.DeserializeObject<Radzen.DataGridSettings>(record.Settings);
                if (setting != null)
                {
                    dataGridSettings = setting;
                    //assign the loaded settings to the Radzen DataGrid
                    Settings = setting;
                }
            }
        }
        catch (Exception e)
        {
            Log.Error(e, e.Message);
            throw;
        }        
    }
```

SamplePage.razor
```
@page "/SamplePage"
<GenericGrid Settings="settings" TItem="SomeModel" Data="@entries"
    <Columns>
                <RadzenDataGridColumn Filterable="true" TItem="SomeModel" Property="SomeProperty" TextAlign="TextAlign.Start" Title="Some Title"                                      
                </RadzenDataGridColumn>
    </Columns>
</GenericGrid>

@code {
    /// <summary>
    /// Bound collection of entries for the grid.
    /// </summary>
    ObservableCollection<SomeModel> entries;

    // Settings for datagrid; Radzen DataGrid must have a settings param to apply settings!
    private DataGridSettings settings;
}
```

**Comment by QA-MaxMaassen** [comment]
Issue got closed without response - I'm still looking forward to any advice on this.
We might need to switch to another frontend library if we can't resolve this....

**Comment by enchev** [comment]
Feel free to refer to my answer in the forum thread you've posted. Without runnable code replicating the problem we will unable to help.
