### ISSUE TITLE
RadzenPanelMenu StaticRendering

### ISSUE THREAD

**Issue by HolyOne** [radzenhq/radzen-blazor#1526]
I understand that webassembly is not present in static rendering mode.
but the components which are likely to be on the MainLayout such as RadzenPanelMenu,RadzenSwitch should support interaction with javascript so they can be available until webassembly loads.

My scenario here is I have to use microsofts account pages because i need external authentication. And they can only be loaded with static rendering. And I now have to redesign the layout without Radzen components because they wont work on login pages because they have to be static

**Comment by akorchev** [comment]
We don't plan to implement them components with JavaScript as well. We think it defeats the purpose of using Blazor. You should use a pure JS library if you need that.

**Comment by HolyOne** [comment]
I accept that but components like RadzenPanelMenu ,RadzenSidebarToggle  should be the exception. otherwise it beats the purpose of those components in a blazor webasembly application resulting in a worse user experience on a webassembly auto rendered page because it ends up being rendered staticly
