### ISSUE TITLE
Add Sorting(OrderBy) method for RadzenDataList

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1532]
Please add methods for sorting datas in RadzenDataList:
1) Sort( nameof(PropertyName), enum/bool asc/desc );
2) ClearSort();

Thanks.

**Comment by enchev** [comment]
There is no need to add such functionality since there is no UI in this component for sorting. You can use LINQ method OrderBy() and Dynamic LINQ if you need dynamic expressions.
