### ISSUE TITLE
Dropdown does not looks like in the demo

### ISSUE THREAD

**Issue by FLAMESpl** [radzenhq/radzen-blazor#1533]
**Describe the bug**
Radzen dropdown does not appear as in demo. Text and scrollbars are wrong. In devtools I have found that white text color comes from something called `_reboot.scss`, obviously I do not include this style by myself, neither I am using other styles libraries than radzen except for bootstap.min.css as stated in "get started" instruction.

**To Reproduce**
- Include radzen.blazor v4.32.1
- Use dark-base theme
- Add RadzenDropdown component

**Expected behavior**
- Dropdown is the same as in demo

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/17801634/9753608d-ea08-4346-8a46-815f3458dfd3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chome 125.0.6422.77

**Comment by enchev** [comment]
Maybe you should use our forum for such questions.
