### ISSUE TITLE
Feature Request: Auto focus on DialogSide

### ISSUE THREAD

**Issue by francisco-zr** [radzenhq/radzen-blazor#1534]
**Is your feature request related to a problem? Please describe.**
If i open a side dialog with OpenSideAsync can't use AutoFocus feature of normal dialogs because doen't exist in SideDialogOptions, so i need to use @ref attribute and AferRenderAsync to focus first form input

**Describe the solution you'd like**
Having a bool parameter in SideDialogOptions class or DialogOptionsBase to have a way to auto focus in first input like normal Dialog.

**Comment by enchev** [comment]
Implemented in https://github.com/radzenhq/radzen-blazor/commit/f99fc6f15fbbcdf6950537825f6de38e5c388980
