### ISSUE TITLE
InvalidOperationException: Cannot provide a value for property 'DialogService' on type 'Radzen.Blazor.RadzenHtmlEditorSource'. There is no registered service of type 'Radzen.DialogService'.

### ISSUE THREAD

**Issue by huxinshuo** [radzenhq/radzen-blazor#1552]
InvalidOperationException: Cannot provide a value for property 'DialogService' on type 'Radzen.Blazor.RadzenHtmlEditorSource'. There is no registered service of type 'Radzen.DialogService'.
InvalidOperationException: Cannot provide a value for property 'DialogService' on type 'Radzen.Blazor.RadzenHtmlEditorLink'. There is no registered service of type 'Radzen.DialogService'.

HtmlEditorLink and HtmlEditorSource is wrong in wpf-blazor

**Comment by enchev** [comment]
https://forum.radzen.com/t/radzendialog-cannot-provide-a-value-for-property-service/2462/2
