### ISSUE TITLE
RadzenDropdownDataGrid: Selected values get cleared if component is dynamically generated

### ISSUE THREAD

**Issue by bancroftway** [radzenhq/radzen-blazor#1562]
When Radzendropdowndatagrid component is dynamically generated, it loses it's state when clicking outside the component. I have recorded a video showing the issue: https://youtu.be/YxjRH9oJ0uA

I also attempted to reproduce this issue in a minimal app, but so far, I have been unsuccessful. I am hoping you can provide some suggestions/ideas to get past the issue. 

 - OS: Windows 11
 - Browser: IE Edge (Chromium based)
 - Browser Version: 126.0.2592.53
 - Radzen.Blazor Version: 4.32.7

**Comment by enchev** [comment]
I'm afraid without code replicating the issue we cannot assist. Use our forum if you are looking for general assistance from our community.
