### ISSUE TITLE
datagrid save settings example not-up-to-date

### ISSUE THREAD

**Issue by GregorySeifert** [radzenhq/radzen-blazor#1563]
This page code sample seems to be obsolete:
https://blazor.radzen.com/datagrid-save-settings

the JRuntime library seems to have modified its API:

var result = await JSRuntime.InvokeAsync<string>("window.localStorage.getItem", "Settings");
=> Argument2: needs to be object[]

await JSRuntime.InvokeVoidAsync("window.localStorage.setItem", "Settings", JsonSerializer.Serialize<DataGridSettings>(Settings));
=> function unknown

**Comment by enchev** [comment]
The example is definitely up to that since it's running using exactly the same code.
