### ISSUE TITLE
In RadzenScheduler add public Event OnChangeView when click on Views buttons

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1565]
Please in RadzenScheduler
add  EventCallback OnChangeView
when clicked on Views buttons=when we choose View

![image](https://github.com/radzenhq/radzen-blazor/assets/92442252/7b406c2b-4c19-4a81-ae18-c984aa91ead6)

**Comment by enchev** [comment]
You can use LoadData event which is invoked when the current view is changed:
https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenScheduler.razor.cs#L431
