### ISSUE TITLE
Add CharacterPattern  to a textBox

### ISSUE THREAD

**Issue by nielsNocore** [radzenhq/radzen-blazor#1573]
**Is your feature request related to a problem? Please describe.**
We would like to limit some text inputs in the which characters can be used. like [a-z] of [a-zA-z0-1] ect ect.
But it is not a masked value. 

**Describe the solution you'd like**
A CharacterPattern to be used in the text box to enforce the used characters. 

**Describe alternatives you've considered**
Using the mask box, but not always there is a mask of a limiting amount of input. only the allowed character sets  is limited.

**Comment by akorchev** [comment]
Hi @nielsNocore,

You can use the [pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) attribute today. RadzenTextBox supports custom attributes which will propagate to the `<input>` element that it renders.

**Comment by nielsNocore** [comment]
Hi @akorchev 

yes ofcource, did not think about it.
thank you for your fast awnser!  

mabey an nice addition for the examples/docs

**Comment by akorchev** [comment]
Not sure what stops you from using RadzenMask right now. You can set `Mask` to `***********` to allow for longer strings.

**Comment by nielsNocore** [comment]
i think you are right, we will use the radzenmask!
thanks
