### ISSUE TITLE
Use PackageLicenseExpression instead of PackageLicenseFile

### ISSUE THREAD

**Issue by vincentscode** [radzenhq/radzen-blazor#1577]
**Is your feature request related to a problem? Please describe.**
The Radzen.Blazor package uses an embedded license file instead of a license expression. This makes it hard to filter automatically; therefore, we have to approve each version manually to ensure no license change occurred.

**Describe the solution you'd like**
Since Radzen.Blazor uses the MIT license, the package could use a `PackageLicenseExpression` instead of a `PackageLicenseFile` to convey its licensing. This is recommended when using one of the supported licenses (https://learn.microsoft.com/en-us/nuget/reference/nuspec#license) and would make automatically approving this package's license possible. The License would also be directly visible on nuget instead of an opaque link to a license file.

**Comment by akorchev** [comment]
We would accept a PR with the proposed change.
