### ISSUE TITLE
How to submit contribution (DataAnnotionValidator)

### ISSUE THREAD

**Issue by ace90210** [radzenhq/radzen-blazor#1589]
Hi,
While developing i wanted to reuse existing code which used data annotations for validation messages. I could not see a suitable Validator to created one following your patterns. i fully implemented it in the demo site as well and believe it should be good to go.

I forked Radzen and created a PR here
[Data Annotation validator Pull Request](https://github.com/radzenhq/radzen-blazor/pull/1588)

In it i updated the demo site with the following changes:

- add link on home page under validators list
- Added example page under validators
- Added link in components list with an icon

**Comment by akorchev** [comment]
Hi @ace90210,

It seems you have found the way to submit a pull request. I am closing this issue.
