### ISSUE TITLE
Datagrid OnChange (oninput) search for integers 

### ISSUE THREAD

**Issue by onemoreuserinthisworld** [radzenhq/radzen-blazor#159]
**Is your feature request related to a problem? Please describe.**
When using the "search" feature (filters) in a Datagrid, the text (varchar, nchar, etc...) property displays the results as the user inputs the value. However, the same does not occur when using an integer as you have to hit "enter" to get only that one exact parameter.

**Describe the solution you'd like**
Is it possible to apply the same concept to integers as well?

**Describe alternatives you've considered**
I've tried to modify the field to a text using a template. However, it did not yield the expected result.
```
 <RadzenGridColumn TItem="User" Property="UserId" Title="User Id" Sortable="true" Filterable="true">
                <Template Context="data">
                    @data.OwnerId.ToString()
                </Template>
  </RadzenGridColumn>

```
**Additional context**

**Comment by enchev** [comment]
Hey @onemoreuserinthisworld ,

The grid filter will use Contains for strings, this is not possible for numeric types.
