### ISSUE TITLE
Dropdown filtering korean characters issue

### ISSUE THREAD

**Issue by Leekibum** [radzenhq/radzen-blazor#1592]
https://forum.radzen.com/t/dropdown-filtering-korean-characters-issue/16823/1

There was an issue with Dropdown filtering Korean characters. I saw a similar issue on the Radzen forum, but it has not been resolved.

I entered "하나둘셋", but the result is "하나나두둘세셋".
There is a bug in the SearchText @oninput of DropDown. Currently, the input tag is using both value and @oninput. Since .NET 7.0, there have been changes in the way two-way data binding works.
![DropDownFilterError](https://github.com/radzenhq/radzen-blazor/assets/30650478/c79d8d57-7ef9-464b-8868-88c49a0b730c)

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0#use-bindgetbindset-modifiers-and-avoid-event-handlers-for-two-way-data-binding

**Comment by enchev** [comment]
Let’s continue the conversation in the forum.
