### ISSUE TITLE
Incorrect cursor display when changing column width in RadzenDataGrid

### ISSUE THREAD

**Issue by AlexForeach** [radzenhq/radzen-blazor#1597]
**Describe the bug**
If there are few columns in the table, then when changing the column width, the cursor and the element for changing the column width appear in different places. This is most noticeable when there are 3 or fewer columns in the table.

**To Reproduce**
1. Go to '[DataGrid Column Resizing](https://blazor.radzen.com/datagrid-column-resizing)'
2. Leave 3 columns in the table
3. Change the size of the column and follow the cursor

**Expected behavior**
The end of the column should move along with the cursors without sudden jerks

**Desktop**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 126.0.2592.102

**Comment by enchev** [comment]
You need to remove `ColumnWidth="300px"` if you want to avoid this.
