### ISSUE TITLE
Double component parameter names should be allow with additional properties

### ISSUE THREAD

**Issue by kensleebos** [radzenhq/radzen-blazor#1601]
**Describe the bug**
When using event parameters like dragover in Radzen, adding attributes such as @dragover:preventDefault="true" or @dragover:stopPropagation="true" should be possible. However, this results in an RZ10010 error.

**To Reproduce**
Create a new Radzen Blazor project.
Add a radzen component that handles the dragover event.
Attempt to use @dragover:preventDefault="true" or @dragover:stopPropagation="true" in the component.
Observe the RZ10010 error.

**Expected behavior**
The component should allow the use of @dragover:preventDefault="true" and @dragover:stopPropagation="true" without throwing an RZ10010 error. The parameters should be passed down.

**Additional context**
<RadzenDataGrid @ondragover="OnDragOver" @ondragover:preventDefault="true" @ondragover:stopPropagation="true">
    Drag over me
</RadzenDataGrid>

@code {
    private void OnDragOver(DragEventArgs e) {
        // Handle dragover event
    }
}

**Comment by enchev** [comment]
I've just tested this on our demos and it compiles normally:
![dg-drag](https://github.com/user-attachments/assets/e179abe7-94a8-4088-9186-e39df03e4acf)

**Comment by kensleebos** [comment]
The error occurs within visual studio:

![image](https://github.com/user-attachments/assets/289ea32c-8065-4b85-8b17-2ed66b2ca9f6)

when i run the application without the preventdefault it compiles fine, i can even add it while running and hot reload it. That also works but during original compile it gives that error. The error doesn't occur when adding the same attributes to a normal div.

i'm using radzen version: 4.34.1

**Comment by enchev** [comment]
Looks like this is something related to any Blazor component not specific to Radzen.Blazor:
```
<NavLink @ondragover="OnDragOver" @ondragover:preventDefault="true" @ondragover:stopPropagation="true">
</NavLink>

@code {
    private void OnDragOver(DragEventArgs e)
    {
        // Handle dragover event
    }
}
```
![image](https://github.com/user-attachments/assets/22aebd0f-1de3-44e0-8f23-738ea17f6667)

https://github.com/dotnet/aspnetcore/issues/18460

I'm afraid that we cannot do anything about this.
