### ISSUE TITLE
Support for Material Icons and Bootstrap.

### ISSUE THREAD

**Issue by DaveBagler** [radzenhq/radzen-blazor#1602]
Google has deprecated Material Icons and is pushing people to Material Symbols. Do you plan to migrate to Material Symbols or another icon library or stay on Material Icons?

Similarly, Bootstrap 4 is no longer supported. Do you plan to migrate themes to Bootstrap 5 or change to another front-end library or stay on 4?

**Comment by akorchev** [comment]
Our upcoming 5.0 release will use Material Symbols. We have also removed all Bootstrap references so this release will address your other concern as well.
