### ISSUE TITLE
DataGrid Inline insert error

### ISSUE THREAD

**Issue by AliAjami2020** [radzenhq/radzen-blazor#1610]
Hi, 
I upgraded the Radzen component from version 4.34.3 to 5, and when I clicked on 'Add New Row' to the DataGrid inline, it did not work. It affected all pages that have inline DataGrid inserts, and they are not working.
![errorgrid](https://github.com/user-attachments/assets/a89b8b11-2b69-4177-a27c-2df9f86cae5a)

**Comment by CyLuGh** [comment]
I just create #1611 about this, it seems to occur only when the source collection is empty. Is it like that for you too?

**Comment by AliAjami2020** [comment]
Thank you, I have not tested DataGrid with data source that has data yet, but it happened when I bounded the DataGrid to an empty data list initially. I am trying to first add multiple rows then save them to the database.

**Comment by enchev** [comment]
There are no changes related to this functionality in Radzen.Blazor 5.0:
![image](https://github.com/user-attachments/assets/6092cfdb-5467-4c98-9d7c-a293aa902f17)

**Comment by AliAjami2020** [comment]
> There are no changes related to this functionality in Radzen.Blazor 5.0: ![image](https://private-user-images.githubusercontent.com/5804953/351014082-6092cfdb-5467-4c98-9d7c-a293aa902f17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjE0OTgsIm5iZiI6MTcyMTY2MTE5OCwicGF0aCI6Ii81ODA0OTUzLzM1MTAxNDA4Mi02MDkyY2ZkYi01NDY3LTRjOTgtOWQ3Yy1hMjkzYWE5MDJmMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTUxMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2I0MzE0ZDlkZmQ2ODcyMDZmMWJiNmNhZDVhNTg3NWViY2QzYWJiMzYwN2VkNjUwNjc4ZTFlOTg3ZWM1NGQ3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OGu9UqaEVJSkZ0HYkh0W6POSjfrNOHDAkdMaF-ZzjNk)

Thank you for checking. There are some changes in styles and themes in version 5. Could they effect it? when a user adds new record to the DataGrid, it is supposed to refresh the DataGrid and show the added row.

**Comment by guuskuiper** [comment]
What also helps is setting the ShowEmptyMessage parameter on the RadzenDataGrid to false.
Otherwise the EmptyTextis shown when the grid is empty when you add add a new row.
