### ISSUE TITLE
Can't insert row in empty datagrid since 5.0.0

### ISSUE THREAD

**Issue by CyLuGh** [radzenhq/radzen-blazor#1611]
**Describe the bug**
Since 5.0.0, RadzenDataGrid won't show newly created row if the bound collection was empty. It will work fine if there was at least one element in the collection. Everything is working fine on 4.34.4.

**To Reproduce**
1. Create a RadzenDataGrid with an empty list as its Data.
2. Have a button that will create an item and it to the grid with `await dataGrid.InsertRow(myObject);`
3. Nothing happens in the UI

**Expected behavior**
Data grid should add a new row in edit mode

**Screenshots**
Expected behavior:
![image](https://github.com/user-attachments/assets/b448605e-caaf-44d8-8719-df2e8e99feaf)

In 5.0.0, stuck on
![image](https://github.com/user-attachments/assets/c86994a8-53d5-4fdc-bc26-cb3ba0bff434)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version 127.0.2651.61

**Comment by enchev** [comment]
Let's keep the conversation in the other issue:
https://github.com/radzenhq/radzen-blazor/issues/1610
