### ISSUE TITLE
Upgrading to 5.0.1 from 4.34.4 has caused UI issues.

### ISSUE THREAD

**Issue by freyfrey01** [radzenhq/radzen-blazor#1615]
**Describe the bug**
Updating from Radzen.Blazor 4.34.4 to 5.0.1 has broken many of our date pickers. The calendar view no longer displays when selecting the calendar button on the date picker. Calendar button is very far off the intended input box.

**To Reproduce**
1. Create a page with Radzen.Blazor 4.34.4 and add the DatePicker component, modify however you please.
2. Update Radzen.Blazor to 5.0.1, notice DatePicker no longer works.

**Expected behavior**
Expect updates between Radzen.Blazor to have no major effects on the functionality of razor pages. Keep the general layout and component visuals the same but improve backend performance or functionality. Do not expect several aspects to be broken due to production updates.

**Screenshots**
Radzen.Blazor 4.34.4 date picker component on razor page:
![image](https://github.com/user-attachments/assets/d90b30aa-c0e3-4ae7-ab4e-080cb2a5499e)

Radzen.Blazor 5.0.1:
![image](https://github.com/user-attachments/assets/cc085194-773d-4d4f-ab90-1a2cbd43be70)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Chrome v126.0.6478.128 

**Additional context**
Noticed this only occurs sometimes. With enough refreshes, the issue typically goes away but it has not been consistent with the date picker properly loading.

**Comment by akorchev** [comment]
Try clearing your browser cache.

**Comment by freyfrey01** [comment]
> Try clearing your browser cache.

@akorchev this resolved the issue but my site is open and regularly used by 500+ employees. Is there a way to force cache refresh or for the team to possibly add version control to CSS to prevent using cached CSS files

**Comment by akorchev** [comment]
[RadzenTheme](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenTheme.razor.cs#L30) does it out of the box. You can either [use it](https://blazor.radzen.com/get-started/net8?theme=material3#theme) or implement a similar versioning approach.
