### ISSUE TITLE
CheckBox list (Excel like) Filter Values repeat values when scroll down

### ISSUE THREAD

**Issue by aines-ldr** [radzenhq/radzen-blazor#1616]
Hi, the component it's cool but i detected a issue in the datagrid when I use filters like excel.

You website sample have the same issue, look,

https://blazor.radzen.com/datagrid-checkboxlist-filter?theme=material3

![image](https://github.com/user-attachments/assets/ab020689-3ad0-49a7-a766-6ddc523e8c8b)
![image](https://github.com/user-attachments/assets/bc42c8ba-0b7c-4756-8bda-257ca952c53e)
![image](https://github.com/user-attachments/assets/e508b876-2ef0-4c9e-aa35-812bd6ec264a)

If you scroll down the list values, when the list refresh when you go down the values show again an repeat, never show last values because always shows the same scrolling down.

**Comment by aines-ldr** [comment]
Thanks!!, how I uptdate my project with this change?, in the next update?.

**Comment by enchev** [comment]
If you add it similar to our demos you will always get latest release version:
https://github.com/radzenhq/radzen-blazor/blob/master/RadzenBlazorDemos/RadzenBlazorDemos.csproj#L9
We will do our best to release this fix before the end of the week.

**Comment by aines-ldr** [comment]
Hi, the release is ready?
