### ISSUE TITLE
Should DataBoundFormComponent<T>.ValueChanged be EventCallback<T?>

### ISSUE THREAD

**Issue by Mertsch** [radzenhq/radzen-blazor#1623]
**Describe the bug**
https://github.com/radzenhq/radzen-blazor/blob/ec4f370f298bad10762c0798282792fffc158203/Radzen.Blazor/DataBoundFormComponent.cs#L135
states that `ValueChanged` is `EventCallback<T>` but shouldn't it be `EventCallback<T?>`?

**Comment by enchev** [comment]
Hey @Mertsch,

Not sure what you are reporting. If you are looking for general advice you might start new thread in our forum.
