### ISSUE TITLE
where can i find the(Startup.ConfigureServices)

### ISSUE THREAD

**Issue by huxinshuo** [radzenhq/radzen-blazor#1625]
Please add DialogService and NotificationService in Startup.ConfigureServices:

public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddScoped<DialogService>();
    services.AddScoped<NotificationService>();
    ...
}
But my app is blazor-wpf not the server mode , I  can not find the(Startup.ConfigureServices)  path.

**Comment by akorchev** [comment]
Check the [getting started](https://blazor.radzen.com/get-started) instructions.
