### ISSUE TITLE
InvalidOperationException: Object of type 'Radzen.Blazor.RadzenDialog' does not have a property matching the name '@rendermode'.

### ISSUE THREAD

**Issue by huxinshuo** [radzenhq/radzen-blazor#1628]
I add <RadzenComponents @rendermode="InteractiveAuto" /> to mainlayout ,builder.Services.AddRadzenComponents() to Program.cs

But it shows ->InvalidOperationException: Object of type 'Radzen.Blazor.RadzenDialog' does not have a property matching the name '@rendermode'.

I delete <RadzenComponents @rendermode="InteractiveAuto" />  it runs ok but htmeditor's image can not work.

**Comment by akorchev** [comment]
Check the getting started instructions for your .NET version.
