### ISSUE TITLE
How  to make the login like a dialog?

### ISSUE THREAD

**Issue by huxinshuo** [radzenhq/radzen-blazor#1629]
The Login contains Card， but Dialog  is waked up by DialogService system。

normally  Login  needs as a Dialog  with mask，not only  as a page，so how can i  get a Login  with dialog  style？
![QQ截图20240727213611](https://github.com/user-attachments/assets/4a64de3a-4a3e-4784-9e63-4a89ea3a4d46)

or how to  hide  the dialog's title bar (which has title and close button)

**Comment by enchev** [comment]
Hey @huxinshuo,

Use our forum for such post.
