### ISSUE TITLE
Scheduler - Highlight/Style current day (or selected day(s))

### ISSUE THREAD

**Issue by Matthewsre** [radzenhq/radzen-blazor#163]
Requesting to enable functionality of the scheduler component to highlight the current day from the Calendar View.

A few people have requested this in the forums:
https://forum.radzen.com/t/how-to-highlight-today-in-scheduler-component/4884

I haven't seen a feature request on the repo that I can follow so creating this :)

Being able to highlight a specified Date (Today or other Date) from the Month view. On the other views maybe highlighting a range since it has the time broken out.

This could also just be styling/templates that gets applied manually and could also work for modifying the background for weekends or holidays.

**Comment by akorchev** [comment]
This is will be possible by handling the newly implemented SlotRender event (still not officially released in nuget). Here is an example: https://github.com/radzenhq/radzen-blazor/blob/master/RadzenBlazorDemos/Pages/SchedulerPage.razor#L37-L50

**Comment by robertosalemi** [comment]
Ottimo il suggerimento per selezionare la data corrente (today).

E' possibile evidenziare il giorno selezionato dall'utente?
Ad esempio tramite l'evento OnSlotSelect?

Grazie.
