### ISSUE TITLE
where can i put my code to somewhere  if  DialogService.Confirm' OkButton is pressed? 

### ISSUE THREAD

**Issue by huxinshuo** [radzenhq/radzen-blazor#1634]
<RadzenButton Text="Confirm dialog" ButtonStyle="ButtonStyle.Secondary" 
        Click=@(args => DialogService.Confirm("Are you sure?", "MyTitle", new ConfirmOptions() { OkButtonText = "Yes", CancelButtonText = "No" })) />

where can i put my code to somewhere  if  DialogService.Confirm' OkButton is pressed?

**Comment by akorchev** [comment]
Please use our [forum](https://forum.radzen.com) for questions.
