### ISSUE TITLE
RadzenDataGrid CheckBoxList Filter is not showing all cell values

### ISSUE THREAD

**Issue by Lyra1337** [radzenhq/radzen-blazor#1640]
**Describe the bug**
When `FilterMode="FilterMode.CheckBoxList"` is chosen, there are only shown 14, sometimes 17 (after scrolling a few times) entries shown in the filter dropdown.

**To Reproduce**
1. Go to [CheckBoxList Example](https://blazor.radzen.com/datagrid-checkboxlist-filter)
2. Click on Page 5
3. See Value "10268" in column "Order ID" at the first row displayed
4. Click on filter icon on column header of "Order ID"
5. **There is no way to select Value "10268".**

**Expected behavior**
It is expected to see all values displayed in this column

**Screenshots**
![screenshot](https://github.com/user-attachments/assets/b2cfdcf8-580f-4078-9b8d-e6a84c90f7db)

Happens in any tested Browser (FireFox, Chrome), happens on latest version.

**Comment by Lyra1337** [comment]
I've done some debugging and the `LoadFilterValues` method is called always with the `LoadDataArgs` filled with Top = 14.

Is there an option to modify the `LoadDataArgs` passed to the`RadzenDropDown`?

**Comment by enchev** [comment]
The ListBox used in this filter is virtualized and will load more values when you scroll:
https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenDataGridHeaderCell.razor#L150
