### ISSUE TITLE
AutoComplete OpenOnFocus does not actually open

### ISSUE THREAD

**Issue by bert-algoet** [radzenhq/radzen-blazor#1645]
When using the AutoComplete component with the parameter OpenOnFocus it does not actually open the component on entering.

The issue seems to be that it does seem to open however it is empty, the content is not filled with the data because there is no filter yet.

**Comment by enchev** [comment]
The component will open the popup as expected however since nothing is entered there will be no items.

**Comment by bertalgoet** [comment]
That is indeed my issue, i would expect to see al possible values when focussing on the control with the OpenOnFocus=true, in the current version however nothing is being shown, so there seems no use for the OpenOnFocus parameter since just a bar of 1px is being shown.

**Comment by bert-algoet** [comment]
> The component will open the popup as expected however since nothing is entered there will be no items.

That is indeed my issue, i would expect to see al possible values when focussing on the control with the OpenOnFocus=true, in the current version however nothing is being shown, so there seems no use for the OpenOnFocus parameter since just a bar of 1px is being shown.
