### ISSUE TITLE
Button highlighting on dark mode

### ISSUE THREAD

**Issue by HolyOne** [radzenhq/radzen-blazor#1655]
I use radzen components 5.0. In light mode, buttons are highlighted but in dark mode the buttons are not highlighted when i mouseover them (unless i use outlined or text buttons. It is the same on radzens demo page.

**Comment by yordanov** [comment]
Hi @HolyOne,

Please share the theme in use and a specific button configuration. Is it ButtonStyle light/dark or theme light/dark?

**Comment by HolyOne** [comment]
Just look at your demo page with light theme
https://blazor.radzen.com/button?theme=material3

All the buttons on filled and flat button panels are highlighted on mouseover

Now switch to dark
https://blazor.radzen.com/button?theme=material3-dark

now none of them are highlighted on mouseover
