### ISSUE TITLE
Create cards of equal height 

### ISSUE THREAD

**Issue by paritoshromy** [radzenhq/radzen-blazor#1658]
It will be good to have a feasibility to create columns that are equal height across multiple rows.

**Comment by yordanov** [comment]
Could you please clarify is the issue related to RadzenCard or RadzenColumn height? Perhaps share a screenshot of the desired outcome?

To get Cards with equal height accross columns in a row you can set `<RadzenCard Style="height: 100%;">`

**Comment by paritoshromy** [comment]
That’s what I am doing currently but I am looking at a non inline css solution like Card Group or Card Deck from Bootstrap….even with bootstrap I could do h-100 utility class but I now need to set style to get this.
