### ISSUE TITLE
RadzenPanelMenuItem does not respect/override Match NavLinkMatch.All

### ISSUE THREAD

**Issue by xXBuilderBXx** [radzenhq/radzen-blazor#1661]
**Describe the bug**
RadzenPanelMenuItem does not respect Match NavLinkMatch.All unless you set the main RadzenPanelMenu to NavLinkMatch.All which seems like it should override it?
Using latest version 5.1.1

**To Reproduce**
1. Create a menu item with.
```html
<RadzenPanelMenu>
    <RadzenPanelMenuItem Path="/test" Match="NavLinkMatch.All" Text="Test Page" />
</RadzenPanelMenu>
```
2. Load a page with the path /test/website /test/name ( Not /test )
3. Menu item seems to be showing as active when it should not be.

**Expected behavior**
The nav link should only match All of the path which is /test

**Weird Fix**
In theory PanelMenuItem should be overriding the main PanelMenu for matching but looks like setting Match="NavLinkMatch.All" on PanelMenu sort of fixes this issue but not sure if NavLinkMatch.Prefix will work on PanelMenuItem.
```html
<RadzenPanelMenu Match="NavLinkMatch.All">
    <RadzenPanelMenuItem Path="/test" Match="NavLinkMatch.All" Text="Test Page" />
</RadzenPanelMenu>
```

**Comment by enchev** [comment]
I've just submitted pull request with a change related to this issue. Let me know if this is what you are looking for.
