### ISSUE TITLE
Bug: Data in RadzenDropDownDataGrid are not refreshed after filtering when virtualization is enabled and filtering on type is disabled

### ISSUE THREAD

**Issue by ranger-turtle** [radzenhq/radzen-blazor#1665]
Welcome

When FilterAsYouType in [RadzenDropDownDataGrid](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenDropDownDataGrid.razor) is set to false and virtualization is enabled, clicking on filter button does not refresh the list.

**Steps to reproduce the behavior:**
1. Go to this [demo](https://blazor.radzen.com/dropdown-datagrid#virtualization-with-loaddata);
2. In Edit Source tab, set FilterAsYouType to false in RadzenDropDownDataGrid and run demo;
3. Put some text in filtering field, the one that occurs in one of the example items is the best;
4. Click on the filtering button;
5. To see filtered data, click outside dropdown and expand it again.

**Expected behavior**
List needs to be refreshed right after clicking filter button, not after re-expanding list.

OS: Windows 10
Browser: Chrome, Firefox

**Comment by enchev** [comment]
I'm unable to reproduce this
![dd-filter](https://github.com/user-attachments/assets/62ebd0df-1601-462e-96e8-4905d4fa9004)

**Comment by ranger-turtle** [comment]
I have forgotten to mention that it happen sometimes. Please try several times.
