### ISSUE TITLE
Filter option input for dropdown is not clickable on bootstrap modal

### ISSUE THREAD

**Issue by notiqq** [radzenhq/radzen-blazor#167]
**Describe the bug**
Hi,
I have faced with the issue of embedding Radzen Blazor DropDown with virtualization using IQueryable on bootstrap modal window. In general the dropdown works fine inside modal, it reacts on click and allows to scroll and to select something. However, the search filter option is not clickable. When I click on it does not react in any way and therefore does not allow to type anything inside filter input.

**To Reproduce**
1. Embed dropdown with AllowFiltering="true" in any bootstrap modal window
2. Click on dropdown
3. Click on filter text input
4. See bug

Code example:
https://appp.me/xlnUrg

**Expected behavior**
Expected text input for filter will be clickable and will allow to enter text for filtering purposes.

**Screenshots**
https://i.imgur.com/hAsSkTT.png

**Desktop (please complete the following information):**
 - OS: Ubuntu Latest
 - Browser: Chrome
 - Version: Latest

**Comment by akorchev** [comment]
It is probably the "feature" of the Blazor modal which prevents focus of other elements. More info here: https://forum.radzen.com/t/bootstrap-5-offcanvas-with-filterable-dropdown/8359/8

**Comment by notiqq** [comment]
Thank you for reply. However, I have significant doubts regarding z index. It's already there, and it applies on entire container. In container we have 2 divs, one for filter and another one for options. It's possible to select options, but impossible to select filter even that all of them are inside div with the same z-index. 
https://i.imgur.com/OpVsObj.jpg

Also, I have tried to add z-index !important to filter div and input, but it still does not work.

**Comment by akorchev** [comment]
The issue is not the z-index. Check my reply in the forum thread.

**Comment by notiqq** [comment]
ah, ok, thanks.
FYI I have been previously using KendoUI with bootstrap modal, as far as I may remember, there was no such issue. So it was handled somehow.

**Comment by akorchev** [comment]
I am pretty sure[ Kendo UI attaches to the body](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.popup.js#L90) by default so it will suffer from the same problem unless you set the appendTo option. We may introduce such a setting in Radzen.Blazor in a future release.

**Comment by Cristhianmassa** [comment]
> ah, ok, thanks. FYI I have been previously using KendoUI with bootstrap modal, as far as I may remember, there was no such issue. So it was handled somehow.

Pls can you share the code i have the the same bug
