### ISSUE TITLE
Microsoft.JSInterop.JSException: Could not find 'Radzen.createEditor' ('Radzen' was undefined).

### ISSUE THREAD

**Issue by vpetit-reimagine** [radzenhq/radzen-blazor#1671]
**Describe the bug**
There is a *consistent* issue with the RadzenHtmlEditor that could be related to the fact the editor is created dynamically(?). 

The script it added like the following in the `App.razor` before the Blazor library.

`<script src="@($"_content/Radzen.Blazor/Radzen.Blazor.js?v={(typeof(Radzen.Colors).Assembly.GetName().Version)}")"></script>`

If we refresh the cache of the browser, it somewhat works a bit but it is not reliable as it *always* break again after some point (whenever we do a change on the page that is *unrelated* to anything Radzen touches upon).

Even tho the exception is thrown, the editor still is created.

I don't mind the issue on a local machine during development, but it is extremely problematic when it happens on a staging or production environment.

**Expected behavior**
The editor is created and no exception is thrown for w/e weird reason

**Screenshots**
![image](https://github.com/user-attachments/assets/e76ebf31-c8ec-4c82-9bae-8c81a8fd429c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox/Edge
 - Radzen version 5.4.1

**Comment by akorchev** [comment]
We need a reproduction of this issue in order to troubleshoot. You can also try moving the Radzen.Blazor.js script before blazor.web.js to see if it makes a difference.

**Comment by vpetit-reimagine** [comment]
> We need a reproduction of this issue in order to troubleshoot. You can also try moving the Radzen.Blazor.js script before blazor.web.js to see if it makes a difference.

It is already before blazor.web.js, as mentioned previously and as shown here:
![image](https://github.com/user-attachments/assets/ec2b942b-396f-4fd3-8466-24bff4d44aee)


It will be difficult to provide you with a reproduction of it, I will see what can be done on that

**Comment by akorchev** [comment]
I am afraid that without a reproduction we can't do much. It seems that Blazor tries to initialise before the Radzen.Blazor.js file has been loaded (or it failed to load/parse it). In any case you can check your browser developer tools for any errors that may have occurred before that - for example a 404 error for Radzen.Blazor.js , a parse error etc.

**Comment by akorchev** [comment]
Indeed JavaScript errors usually prevent other scripts from running correctly which isn't specific to Radzen (this is why we haven't documented it).
