### ISSUE TITLE
Incorrect Composite Column Width

### ISSUE THREAD

**Issue by CoderJohnZhou** [radzenhq/radzen-blazor#1674]
When I update Radzen.Blazor version from 4.32.0 to 5.1.5, I found the composite column width is incorrect. 
We can see the demo: https://blazor.radzen.com/datagrid-composite-columns
The [Job Title] column width is set to 200px in code, but the runtime width is 820px which is the width of [Title] column.
I check the history commits, maybe it is caused by aea31474545daf1434faff05a58bbf6e3d6e6f40
Is there any way to set the width of composite column?
![image](https://github.com/user-attachments/assets/20dfb6b3-43e8-491e-b67d-b1fa94936951)
![image](https://github.com/user-attachments/assets/4c3365d2-0ea5-4a54-80d6-f48a838f0931)

**Comment by enchev** [comment]
Thanks @CoderJohnZhou. The fix is valid however the problem comes from the fact that colgroup elements cannot contain other colgroup elements - i.e. cannot describe a complex nested headers like our DataGrid composite columns. We will try to find a way to better apply the column width in such cases however I'm skeptical.

**Comment by lnaie** [comment]
I'm building a dynamic crosstab table with composite columns. And it creates this column size issue:
https://stackoverflow.com/questions/78934033/html-table-with-header-colpans-doesnt-render-as-expected

It looks like there is bug in the code that renders the colgroup: 

- now it renders the minimum (10 = 8 + 2) ; 8 simple, 2 composite of 3 columns each
- while it should be rendering the max number (14 = 8 + 2 * 3).

**Comment by lnaie** [comment]
damn. any directions or a possible workaround of the top of your head?

**Comment by enchev** [comment]
@lnaie if we have any directions we will simply fix it.

**Comment by lnaie** [comment]
how about a property RenderColgroup=true that could be used to not render colgroups (=false) when needed? html table is just fine without colgroup html element.

**Comment by enchev** [comment]
@lnaie do you exact column widths when you remove the colgroup? You can test this in your browser using the developer tools inspector.

**Comment by lnaie** [comment]
yes. I tested it. 
right now I have a .net to js call that does it on grid's LoadData event callback:
```  
  removeElement: function (selector) {
    if (!selector) return;
    var e = document.querySelector(selector);
    if (e) e.remove();
  }
  
  // call
  removeElement("div.rz-data-grid div.rz-data-grid-data table.rz-grid-table colgroup");
```

**Comment by enchev** [comment]
Maybe in this case we should not render colgroup element if there are child columns - no need to introduce new property.
