### ISSUE TITLE
Accessiblity of Drop Down

### ISSUE THREAD

**Issue by efinder2** [radzenhq/radzen-blazor#1676]
**Is your feature request related to a problem? Please describe.**
When using the `RadzenDropDown`-component the aria-labels are generated with the internal values, not the template values. For example if i want to select a localized `DayOfWeek`, Only the english values are read not the used values in the `Template` or `ValueTemplate` part. [Instead ](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenDropDown.razor#L13) the "InternalValue" is used. 

The screen readers (NVDA) is reading "anklickbar  Monday  Eingabefeld  schreibgeschützt  Liste öffnen  Monday" It should read "anklickbar  Montag Eingabefeld schreibgeschützt  Liste öffnen Montag". Currently I have no possiblity to switch my output to english so here my rough translation: clickable Montag, input field. readonly open list Montag". There is a similar output from Microsoft Narrator. 

```csharp
@using System.Globalization;
@page "/Test"

<RadzenDropDown style="display: block" @bind-Value="day" Data=@days Name="Tag" Placeholder="Tag auswählen" aria-label="@de.DateTimeFormat.GetDayName(day)">
    <Template>
        @de.DateTimeFormat.GetDayName(context)
    </Template>
    <ValueTemplate>
        @de.DateTimeFormat.GetDayName(context)
    </ValueTemplate>
</RadzenDropDown>

@code
{
    private DayOfWeek day = DayOfWeek.Monday;
    private static IList<DayOfWeek> days = new List<DayOfWeek>{ DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday };
    private CultureInfo de = new CultureInfo("de-DE");
}
```

**Describe the solution you'd like**
Ideally not an input is read rather a select, also the selected option is read accordingly. Also the disabled output is confusing.

**Describe alternatives you've considered**
Create my own component, cause there is not much I can do around it.

**Additional context**
-

**Comment by akorchev** [comment]
I suggest providing the localized names for the Data property instead:

```
 private static IList<DayOfWeek> days = (new List<DayOfWeek>{ DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday }).Select(d => de.DateTimeFormat.GetDayName);
 ```
 Then you don't need to set Template and ValueTemplate at all.
