### ISSUE TITLE
Can the DataGrid be set up to allow copying of cell areas or rows and columns using mouse selection, similar to Excel?

### ISSUE THREAD

**Issue by weiyoucheng** [radzenhq/radzen-blazor#1679]
Can an Excel-like feature be added where users can select a range of cells with a mouse, click on column headers to select entire columns, and click on row headers to select entire rows, and when users press Ctrl + C, the selected cell contents are copied to the clipboard?

**Additional context**
![image](https://github.com/user-attachments/assets/0e18966d-d3e0-4b7f-86e8-6cd2e6e4a5ad)

**Comment by enchev** [comment]
This is completely different component in my opinion - Spreadsheet. We don’t have plans to add such in the near future, still we are open for pull requests.
