### ISSUE TITLE
Feature Request - Scheduler Improvements

### ISSUE THREAD

**Issue by recomrad** [radzenhq/radzen-blazor#168]
- [x] First minor - make hours headers customizable instead of strict "h tt" format.
- [ ] Second major - resize and drag & drop appointments ability.

**Comment by Dazfl** [comment]
I would love to see the 'second major' implemented as well.

**Comment by JosephMampaey** [comment]
@recomrad Are you still working on this? Can we help with anything?

**Comment by KevinKrueger** [comment]
Resize for duration is important.

**Comment by KevinKrueger** [comment]
So if the resize(start, end) with visual cursor feedback and the drag-drop functionality works now, then I'm the happiest developer in the whole world. Probably XD

**Comment by akorchev** [comment]
Closing this one in favor of #1833. Drag and drop to move is already supported.
