### ISSUE TITLE
Add visual feedback to Dropzone

### ISSUE THREAD

**Issue by richardaubin** [radzenhq/radzen-blazor#1681]
Problem:  Currently when reordering items in the DropZone component, there is no visual feedback other than the currently selected item and it's current position as it is being dragged.

Solution: As an example, MudBlazor has a AllowReorder property that enables visual feedback by creating a space between items, with a highlighted border that clearly shows the position the dragged item will be dropped into.

You can see a demo at this link:
https://www.mudblazor.com/components/dropzone#transfer-items-between-drop-zones-reorder-items

Alternative to RadzenDropZone could be to use another 3rd party component, such as the MudBlazor one, or coding a custom component that uses the fluid sorting options that the Sortable.JS library offers.

Sortable JS Demos can be seen here:
http://sortablejs.github.io/Sortable/

It would be visually beneficial to the user operating a dropzone component on the front end to have such visual feedback.

Thank you for the consideration.

**Comment by enchev** [comment]
Check my response to your forum post: https://forum.radzen.com/t/feature-request-add-visual-feedback-in-drop-zone/18396/2
