### ISSUE TITLE
RadzenHtmlEditorImage: make Attributes property protected

### ISSUE THREAD

**Issue by Kokusz66** [radzenhq/radzen-blazor#1688]
**Is your feature request related to a problem? Please describe.**
We are currenty using Radzen's RadzenHtmlEditorImage component with RadzenHtmlEditor. Our problem is that the RadzenHtmlEditorImage's dialog has unnessesary parts that we dont want to use / show for the users (Attributes.Src, Attributes.Alt). 
We want to override OnClick() function with the condition that we omit 

```
<div class="rz-html-editor-dialog-item">
      <label>@UrlText</label>
      <RadzenTextBox @bind-Value=@Attributes.Src style="width: 100%" />
</div>
<div class="rz-html-editor-dialog-item">
      <label>@AltText</label>
      <RadzenTextBox @bind-Value=@Attributes.Alt style="width: 100%" />
</div>
```
section rather than copy the whole component. 

**Describe the solution you'd like**
- Make property protected or public. 
- Make optional parameters for which RadzenTextBox components to be shown inside the dialog.

**Describe alternatives you've considered**
We tried to achive our goal with javascript and css selectors but we ran into an obstacle.

**Comment by Kokusz66** [comment]
Hi @akorchev
Thank your for your reply and your help!

**Comment by akorchev** [comment]
Should be possible now.
