### ISSUE TITLE
AutoComplete component double OnChange event

### ISSUE THREAD

**Issue by mzcartman** [radzenhq/radzen-blazor#169]
When an item from autocomplete list is selected (by mouse on GIF, keyboard behavior is the same), OnChange Event occurs twice, if not fired before selecting from the list.
What is going on in attached gif:
1. Selected box, print "f", pressed Enter, event fired once
2. Selected "Alfreds Futterkiste" from list, event fired once
3. Removed text, pressed Enter, event fired once with no text
4. Typed "d", then selected value from list (no Enter) - event fired "d" first, then selected value
[
![autocomplete](https://user-images.githubusercontent.com/17473936/125294451-f2698580-e32c-11eb-9993-b76e93b0e8fe.gif)
](url)

**Comment by enchev** [comment]
Details: https://forum.radzen.com/t/autocomplete-change-event/8851
