### ISSUE TITLE
DataBoundFormComponent has internal searchText, which prevents inheriting from this component

### ISSUE THREAD

**Issue by vadimb7** [radzenhq/radzen-blazor#1697]
**Describe the bug**
DataBoundFormComponent has "internal searchText" which prevents inheritance. Please mark this member as protected.

**To Reproduce**
Clone one of the controls inheriting from DataBoundFormComponent (eg RadzenDropdown). Observe compiler errors due to searchText not being accessible.  

**Expected behavior**
Ability to inherit from DataBoundFormComponent

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Edge

**Comment by enchev** [comment]
Can you provide more info? I've just tried this and it worked normally:
![image](https://github.com/user-attachments/assets/80a3a48e-304b-4362-bffb-9f2f191f9079)
![image](https://github.com/user-attachments/assets/1878360b-66b0-48ff-bc09-978602788850)
![image](https://github.com/user-attachments/assets/1a85721a-8295-4813-bfae-ab864a6bb2e9)
