### ISSUE TITLE
Feature Request: Draggable Dashboard Items Component

### ISSUE THREAD

**Issue by gurjeetsdtpl** [radzenhq/radzen-blazor#1703]
Hello Radzen Team,

I would love to see a component or feature that allows for handling dashboard items in a drag-and-drop view. This feature would enhance the flexibility and customization of dashboards, allowing users to rearrange items easily to suit their preferences.

**Use case:**

- Users could organize their dashboard widgets by dragging and dropping them into different positions.
- The layout would persist between sessions, remembering the user's configuration.

This would be an excellent addition to Radzen's component library and improve the user experience for applications with dynamic dashboard requirements.

Thank you for considering this feature request!

Best regards,
Gurjeet

**Comment by enchev** [comment]
There is already such component that can be used for dashboards as well:
https://blazor.radzen.com/dropzone

**Comment by franklupo** [comment]
I created an example

https://blazor.radzen.com/playground/28e871f2-4959-4d8c-8eef-2eada4bcbe56?theme=fluent
