### ISSUE TITLE
RadzenImage Alternate Image how to show alternate image if source image is not found? 

### ISSUE THREAD

**Issue by AliAjami2020** [radzenhq/radzen-blazor#1704]
how to show alternate image if source image is not found? 
   <  onerror = "";  > 
AlternateText shows text if referenced image URL does not exist, but it would be great if we can have **alternative image** as well.

**Comment by enchev** [comment]
RadzenImage accepts arbitrary attributes including onerror. Use our forum in the future for such questions.

**Comment by AliAjami2020** [comment]
Thank you for comment, I'll join the forum. 
I used  onerror="this.src='general.jpg';"
