### ISSUE TITLE
RadzenTree Change Is not work correctly

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#1709]
![image](https://github.com/user-attachments/assets/63532482-f92a-4cf9-b3e5-a691dae3a5e3)

When I click in (clean) check box FIRST time, the method  OnChange is called and check box marked - it is correct.
When I click in market (the same!) check box SECOND time, check box becomes unchecked.
BUT When I click in (the same!) (now clean) check box  THIRED time check box marked BUT OnChange method don't called!!! - it is ERROR!
And in all other check operation with the same! check box, method  OnChange DON'T called - it's ERROR!
Method OnChange must be called everytime when I check/market the same check box.

v. Radzen.Blazor 5.2.2.

**Comment by enchev** [comment]
Works normally on our demos:
https://github.com/user-attachments/assets/2c8ab902-ef52-4785-9ee8-0cd26fa7bed9
any additional details?

**Comment by Andrey-2021** [comment]
No't worked
When I click the SAME check box

https://github.com/user-attachments/assets/b142465a-c4e1-435f-b2b4-729d797d7077

**Comment by Andrey-2021** [comment]
GitHub project 
https://github.com/Andrey-2021/RadzenTreeError

**Comment by Andrey-2021** [comment]
I must create new issues?
