### ISSUE TITLE
Radzen Blazor Google Maps not working

### ISSUE THREAD

**Issue by gurjeetsdtpl** [radzenhq/radzen-blazor#1713]
The Radzen Blazor Google Maps component is not functioning as expected. The map does not display correctly or doesn't load the required data. 

Issue can be found in the given screenshot: 
![image](https://github.com/user-attachments/assets/eeb66f8f-4c23-4464-a997-530495ae618b)

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/24dbee5d3d348ddad0758bf692814895a58dcbec
