### ISSUE TITLE
Request for an iframe component in Radzen Blazor

### ISSUE THREAD

**Issue by yourgurjeet** [radzenhq/radzen-blazor#1723]
It would be highly beneficial to add an iframe component to Radzen Blazor. This component would enable the embedding of external web content or media within Blazor applications, allowing for seamless integration of content from third-party websites, videos, or interactive tools.

The iframe component would be useful for scenarios where developers need to display external content such as:

Embedded videos from platforms like YouTube or Vimeo.
External web tools or applications.
Web pages or documents hosted on other domains.

Features:

Support for basic iframe attributes such as src, width, height, allowfullscreen, sandbox, etc.
Customizable styling options to fit the component into various layouts.
Built-in safety measures for sandboxing or preventing unwanted interactions with the embedded content.

Benefits:

Simplifies embedding external content into Radzen Blazor applications without having to rely on custom HTML or JavaScript.
Improves flexibility for developers who need to integrate third-party tools or services.

**Comment by akorchev** [comment]
There isn't much we can add on top of the built-in `<iframe>`.
