### ISSUE TITLE
DataGrid column picker alternative menu

### ISSUE THREAD

**Issue by Techoneshot** [radzenhq/radzen-blazor#1725]
**Describe the solution you'd like**
Optional button to trigger column picker on DataGrid instead of dropdown which takes too much space, something like [CheckBoxList (Excel like) in filter](https://blazor.radzen.com/datagrid-checkboxlist-filter?theme=material3)

**Describe alternatives you've considered**
Method grid.ShowColumnPicker(element) so user can decide which elelement will trigger showing ColumnPicker menu 

**Additional context**
![image](https://github.com/user-attachments/assets/2929b0f3-8602-4168-8e76-e0816f8d5d09)

**Comment by enchev** [comment]
Thanks for your suggestion @Techoneshot however I’m afraid we will unable to implement such feature.

**Comment by Techoneshot** [comment]
@enchev created pull request hope you will be satisfied ;)

**Comment by Techoneshot** [comment]
@enchev  On demo ContextMenu picker is not showing 
![image](https://github.com/user-attachments/assets/c9c01465-f06c-49ce-8253-ba05244498b4)
