### ISSUE TITLE
Scheduler additional content tooltip for appointment doesn't fit on the screen

### ISSUE THREAD

**Issue by Techoneshot** [radzenhq/radzen-blazor#1726]
**Describe the bug**
If user hover on appointment which is for the end of the week (saturday, sunday) and uses additonal content on hover, then tooltip doesn't fit and goes out of the screen causing showing horizontal scrollbar.

**To Reproduce**
1. Go to Scheduler demo
2. Hover on whole week appointment
3. See appointment doesn't fit screen

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Fit element on screen by showing apppointment info as left tooltip

**Screenshots**
![image](https://github.com/user-attachments/assets/8b6b4246-cbd2-4acd-bca4-3638c0af9873)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Comment by akorchev** [comment]
Indeed this is how the tooltip behaves. Setting the position to bottom would solve the problem (or not setting position altoghether)

```
new TooltipOptions { Position = TooltipPosition.Bottom, Duration = null })
```
