### ISSUE TITLE
Please add template for VisualStudio and .Net

### ISSUE THREAD

**Issue by zandiarash** [radzenhq/radzen-blazor#1728]
Hi dear Radzen developers, Thanks for the perfect ecosystem and components.
Please add some templates for VisualStudio and .Net like this
`dotnet new install Radzen.Templates`

Your template is missing here.
![image](https://github.com/user-attachments/assets/8720bcac-9f8f-48ac-9b76-77224f45ee5b)

**Comment by akorchev** [comment]
Hi @zandiarash,

We don't plan adding such templates. We believe our product Radzen Blazor Studio and the upcoming Visual Studio extension cover that a lot better.
