### ISSUE TITLE
DataGrid ColumnResizing width jumping

### ISSUE THREAD

**Issue by TrisKrijgs** [radzenhq/radzen-blazor#1731]
**Describe the bug**
Having a DataGrid that allows resizing, and contains columns with both MinWidth and Width set, resizing a column to it's minimum will bug the width of that column and cause it to jump visually.
The width of the column also jumps when starting to drag and resize sometimes, this usually more dramatically.

**To Reproduce**
I used an adjusted version of this demo https://blazor.radzen.com/datagrid-column-resizing for my demonstration.
Here is the code I used:

```
@using RadzenBlazorDemos.Data
@using RadzenBlazorDemos.Models.Northwind
@using Microsoft.EntityFrameworkCore

@inherits DbContextPage

<RadzenDataGrid GridLines="Radzen.DataGridGridLines.Vertical" Data="@employees" TItem="Employee" AllowColumnResize="true" ColumnResized=@OnColumnResized>
    <Columns>
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.FirstName)" Title="First Name" />
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.LastName)" Title="Last Name" Width="150px"/>
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.Title)" Title="Title" />
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.TitleOfCourtesy)" Title="Title Of Courtesy" />
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.BirthDate)" Title="Birth Date" FormatString="{0:d}" />
    </Columns>
</RadzenDataGrid>

<EventConsole @ref=@console />

@code {
    IEnumerable<Employee> employees;
    EventConsole console;

    void OnColumnResized(DataGridColumnResizedEventArgs<Employee> args)
    {
        console.Log($"Resized {args.Column.Title} to {args.Width} pixels");
    }

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();

        employees = dbContext.Employees;
    }
}
```

1. Click and drag to resize for example the start of column 2 "Last name".
2. Drag to make it as small as possible and release.
3. The column will jump to another width.

Alternatively:
1. Press and hold to resize a column.
2. Start to move your mouse to resize the column.
3. The column now jumps to a different width.

**Screenshots**
Here is a recording of my experienced issue using the code above in the demo environment [linked](https://blazor.radzen.com/datagrid-column-resizing)

https://github.com/user-attachments/assets/3a383518-30cf-436d-af18-53c32176a90b

It stands out to me that the console is giving the new width back as a float and not an integer.

**Desktop (please complete the following information):**
 - OS: MacOs 14.6.1
 - Browser Safari
 - Version V5

**Comment by jipjan** [comment]
Got the same issue here on Windows, on Edge and Chrome.

**Comment by enchev** [comment]
You need at least one column with no MinWidth/Width specified - for example the last one:
```
@using RadzenBlazorDemos.Data
@using RadzenBlazorDemos.Models.Northwind
@using Microsoft.EntityFrameworkCore

@inherits DbContextPage

<RadzenDataGrid GridLines="Radzen.DataGridGridLines.Vertical" Data="@employees" TItem="Employee" AllowColumnResize="true" ColumnResized=@OnColumnResized>
    <Columns>
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.FirstName)" Title="First Name" />
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.LastName)" Title="Last Name" Width="150px"/>
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.Title)" Title="Title" />
        <RadzenDataGridColumn Width="200px" MinWidth="100px" Property="@nameof(Employee.TitleOfCourtesy)" Title="Title Of Courtesy" />
        <RadzenDataGridColumn Property="@nameof(Employee.BirthDate)" Title="Birth Date" FormatString="{0:d}" />
    </Columns>
</RadzenDataGrid>

<EventConsole @ref=@console />

@code {
    IEnumerable<Employee> employees;
    EventConsole console;

    void OnColumnResized(DataGridColumnResizedEventArgs<Employee> args)
    {
        console.Log($"Resized {args.Column.Title} to {args.Width} pixels");
    }

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();

        employees = dbContext.Employees;
    }
}
```

https://github.com/user-attachments/assets/b525349c-a83d-4a0b-a967-23a3018f673d

**Comment by jipjan** [comment]
@enchev That fixes the jumping issue, but when resizing the last column, it can become 0 pixels and disappear. Giving it a MinWidth is not possible anymore with this fix, so this creates this new problem.

**Comment by enchev** [comment]
Feel free to propose fix - we accept pull requests!
