### ISSUE TITLE
Week view of radzen sheduler does not display certain events in week view

### ISSUE THREAD

**Issue by char8t** [radzenhq/radzen-blazor#1734]
**Describe the bug**
The RadzenSheduler does not display some events in the week view when the event date is in 2025. Only a very few events are displayed. The events are displayed correctly in day and month view.

**To Reproduce**

Simply add ```new Appointment { Start = DateTime.Parse("31.03.2025"), End = DateTime.Parse("31.03.2025").AddHours(1), Text = "Vacation2" },``` to the sheduler example and go to the date 03/31/2025 and switch to week view.

Example: https://blazor.radzen.com/scheduler?theme=material3

**Expected behavior**
The event "Vacation2" should be displayed in week view.

**Screenshots**
![image](https://github.com/user-attachments/assets/4646bc17-29be-4f77-b34d-6673510ab0e3)
![image](https://github.com/user-attachments/assets/10b325b1-58bb-4f1c-b32b-c4b3a41089b5)
![image](https://github.com/user-attachments/assets/cbec7476-e077-46de-a12e-c56271abae8d)

**Desktop (please complete the following information):**
 - Windows 11
 - MAUI Blazor Hybrid
 - .Net 8.0.10

**Additional context**
 -

**Comment by akorchev** [comment]
I see two issues with this code:

1. You are displaying 24.02.2025 - 02.03.2025 and the appointment is for 31.03.2025 - not within this week's range.
2. The default StartTime is 8 am - your event starts at 00:00 and ends at 1:00.

Setting StartTime (`<RadzenWeekView StartTime="@TimeSpan.FromHours(0)"`)and navigating to the right week displays the event as expected:

<img width="1359" alt="image" src="https://github.com/user-attachments/assets/a537069c-7362-4e64-848c-1e425b2852bb">

**Comment by char8t** [comment]
@akorchev Good Catch! I totally missed that. I thought i could alter the example code to give a simple case for reproduction of this issue but i failed miserably. But i found the real issue in our application anyways:

It was a wrong call to
```
calender.GetWeekOfYear(args.Start, CalendarWeekRule.FirstFullWeek, DayOfWeek.Monday)
```
which does not return the correct ISO 8601 value for the week of the year. Changing it to
```
calender.GetWeekOfYear(args.Start, CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday)
```
fixed the issue!
