### ISSUE TITLE
Virtualization with odata : loaddatda gets called twice

### ISSUE THREAD

**Issue by tvanneuville** [radzenhq/radzen-blazor#1738]
Bug : Datagrid with virtualization calls loaddata twice on initialisation

To Reproduce: 

Go to demo : Virtualization > Load data support (https://blazor.radzen.com/datagrid-virtualization-loaddata)

See the logs for the intialisation calls:

![image](https://github.com/user-attachments/assets/9a222159-4fd4-42da-ba96-bbb29d3bf36f)

**Comment by enchev** [comment]
Virtualize component will request LoadData as many times as needed - we cannot control it.
