### ISSUE TITLE
RadzenTree is not selecting parent if parent was not expanded.

### ISSUE THREAD

**Issue by VytasLL** [radzenhq/radzen-blazor#1739]
I have two level Tree (as it is shown in demos). Problem is that when I check parent node component is not checking child items. It works after I expand and collapse parent node. Also by default beverages shows partly selected ("-"). When clicking on it nothing changes. Only after expand/collapse it starts working. Also at start parent node is not checked event all child nodes are selected.

**To Reproduce**
1. Go to https://blazor.radzen.com/tree-checkboxes?theme=material3
2. Click on 'Seafoods'. Console log shows: "CheckedValues Changed Seafood"
3. Expand 'Seafood", then collapse "Seafood"
4. Click on 'Seafoods'. Console logs shows: "CheckedValues Changed Seafood Ikura Konbu Carnarvon Tigers Nord-Ost Matjeshering Inlagd Sill Gravad lax Boston Crab Meat Jack's New England Clam Chowder Rogede sild Spegesild Escargots de Bourgogne Röd Kaviar"
5. 

**Expected behavior**
checkedValues must include all items when selecting parent node.

Also

**Comment by enchev** [comment]
Child items does not exist until expanded and that's why cannot be included in checked values. You can control the parent item checked state manually depending on your case using ItemRender event as shown in our demo.
