### ISSUE TITLE
Radzen Carousel - Manual navigation should reset the auto-rotate timer

### ISSUE THREAD

**Issue by Anspitzen** [radzenhq/radzen-blazor#1741]
**Is your feature request related to a problem? Please describe.**
When you navigate to the next slide by hand it can happen to you that you get moved again one further by the timer immediately. The timer continues to run with the time from the previous slide. When pressing the next button it should reset the timer for navigating again automatically.

**Describe the solution you'd like**
It would be great if that reset would happen internally already by that carousel component, like:

RadzenCarousel.razor.cs

/// <summary>
        /// Navigates to specific index.
        /// </summary>
        public async Task Navigate(int index)
        {
            if (selectedIndex != index)
            {
                selectedIndex = index == items.Count ? 0 : index;
=====> if (Auto)
=====>  {
=====>      await Reset();
=====>  }
                await SelectedIndexChanged.InvokeAsync(selectedIndex);
                await Change.InvokeAsync(selectedIndex);
                await JSRuntime.InvokeVoidAsync("Radzen.scrollCarouselItem", items[selectedIndex].element);
            }
        }

**Describe alternatives you've considered**
currently I have to work around by binding the ref (@ref=@carousel) and then calling on the Change EventCallback the function Change="c => {carousel.Reset();}" manually

**Comment by enchev** [comment]
They way you want to update our code (and the way you use it in the Change event) will reset the timer no matter if navigation is invoked from the timer or manually.

**Comment by Anspitzen** [comment]
For not breaking existing projects I propose to:
Revert the commit ba06a72 an then
- Move the Navigation functionality into the private function ChangeSlide (or however you want to call it)
- Link the Timer delegate to the ChangeSlide
- Put the stuff currently in the GoTo into the Navigate function, so Navigate will reset timer and then call ChangeSlide

So everything will call the Navigate, which will reset the timer bevore navigating. Only the timer is directly navigating as to not reset itself?
