### ISSUE TITLE
Is it possible to set custom text in the date field when the maximum date is reached?

### ISSUE THREAD

**Issue by yourgurjeet** [radzenhq/radzen-blazor#1743]
It would be very helpful to have a parameter that allows setting custom text when the maximum date is reached in the date field.
screenshot added for your reference: 
![image](https://github.com/user-attachments/assets/ffe30bf7-3f6c-4215-8f50-b473fa5bfd43)

**Comment by enchev** [comment]
No, this is not possible. Use our forum in the future to post your questions.
