### ISSUE TITLE
Datagrid Duplicated Records in Radzen

### ISSUE THREAD

**Issue by AliAjami2020** [radzenhq/radzen-blazor#1746]
In the latest version of Radzen, the Datagrid component is displaying duplicate records. This issue was not present in previous versions and affects bound data sources records.
![image](https://github.com/user-attachments/assets/0e419090-69c0-446f-8f71-565a854471b9)

**Comment by emmanuelpare** [comment]
Same here.. reverted

**Comment by enchev** [comment]
Fixed in the last update 
https://forum.radzen.com/t/rows-suddenly-duplicating-in-only-some-adtagrids/18813/6
