### ISSUE TITLE
Incorrect display of Radzen Blazor Components at low internet bandwidth

### ISSUE THREAD

**Issue by VitaliyNec** [radzenhq/radzen-blazor#1752]
The display of Radzen Blazor Components at low internet speeds (3G or slower) shows artifacts during data loading, which is a highly unpleasant experience for users.

- TargetFramework: net8.0
 - OS: Windows 10
 - Browser: Google Chrome
 - Radzen.Blazor: 5.3.5
![Screenshot 2024-10-25 105646](https://github.com/user-attachments/assets/2b18cc1b-bb91-493d-8520-249fe9276448)

Note: The example in the screenshot was taken from your website, but this issue also occurs on our sites that use your controls.

**Comment by yordanov** [comment]
Hi @VitaliyNec,

I believe the best we can do is to hide the icons until the icon font is fully loaded. The most notable drawback of this solution is that you will not know an icon is present until it appears. Here is how it will look with a slow internet connection:

https://github.com/user-attachments/assets/58f9d8a6-5d70-4dd0-88db-0e6eedf0e99a

Would this resolve the artifacts issue?

**Comment by VitaliyNec** [comment]
I believe this issue won't be resolved because artifacts are appearing in multiple places. Additionally, I see that some extraneous elements are being injected into the markup, which are unrelated to the data. It would be better if the control remained empty until the data becomes available.

I'm attaching another example from your website.

![Screenshot 2024-10-25 105646](https://github.com/user-attachments/assets/c9159143-d714-41f8-a5ad-11d6e81f59b4)

**Comment by yordanov** [comment]
Here is a preview of the example page with the proposed solution. No artifacts are appearing anymore:


https://github.com/user-attachments/assets/c6e8873b-df56-4fe6-9de7-7209a2ec4270

That's the best we can do, given the usage of icon fonts.

**Comment by VitaliyNec** [comment]
Your latest example looks like a solution to my problem . When can I receive an updated package with the changes?

**Comment by yordanov** [comment]
We will release this early next week, most probably on Monday.
