### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'classList')     at Radzen.Blazor.js:20:17

### ISSUE THREAD

**Issue by Indoraptor1** [radzenhq/radzen-blazor#1760]
**Describe the bug**
When I open my application it throws this error, it worked since now and i changed nothing on the code, just got a new PC.

**To Reproduce**
1. Just opened the site

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Works without error

**Screenshots**
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/b57c098a-a16f-4140-aadc-81f4851e7be6">

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser chrome
 - Version 130.0.6723.70 (Hivatalos verzió) (64 bites) (cohort: Stable) 

**Additional context**
I tryed clearing nuget cache, but it is not worked.

**Comment by akorchev** [comment]
Check this thread: https://forum.radzen.com/t/version-5-4-0-js-error/18877/10

You are not including Radzen.Blazor.js where you are supposed to.

**Comment by Indoraptor1** [comment]
Hello!
This is how my index.html looks like:
```html
<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Termék kezelő</title>
    <base href="/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="css/app.css" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link href="WebClient.styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="_content/Radzen.Blazor/css/material-base.css">
    <script src="_content/Radzen.Blazor/Radzen.Blazor.js"></script>
    <script src="js/download.js"></script>
    <script src="js/jquery-3.7.1.min.js"></script>
</head>

<body>
    <div id="app">
        <svg class="loading-progress">
            <circle r="40%" cx="50%" cy="50%" />
            <circle r="40%" cx="50%" cy="50%" />
        </svg>
        <div class="loading-progress-text"></div>
    </div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
</body>

</html>
```
Im using WebAssebly, but asp.net hosted (.NET 8)

**Comment by akorchev** [comment]
You should include Radzen.Blazor.js according to the [getting started instructions](https://blazor.radzen.com/get-started/wasm#js). As I said you are not doing that currently.
