### ISSUE TITLE
Carousel - Auto=true does not repeat cycle

### ISSUE THREAD

**Issue by Anspitzen** [radzenhq/radzen-blazor#1774]
**Describe the bug**
On Auto rotation the carousel will stop on last item

**To Reproduce**
1. Go to official demo
2. Go to last item or wait until it is there
3. See error

**Expected behavior**
Rotation should start again

**Desktop (please complete the following information):**
 - Browser Chrome
 - Radzen Version 5.5.4

**Additional context**
Broke with bb675ee because Timer has GoTo(selectedIndex + 1) which will just be out of range and not navigating

**Comment by Anspitzen** [comment]
Should I open the next bug report? Because now the tiemr will reset itself every time (Next() is calling to Navigate which is reseting timer) which was deemed not nice on commit 0466912

**Comment by enchev** [comment]
The timer will reset itself on every navigate no matter if it's from the timer or not. What's the problem with that?

**Comment by Anspitzen** [comment]
On the Navigate there is an explicit call to Timer.Change(); function.
Thats the only thing that was different on the GoTo call on timer itself, was made that way on #1741

**Comment by enchev** [comment]
Yes, that's how should work in my opinion - the navigation should take the same route no matter if initiated by the timer or manually.

**Comment by Anspitzen** [comment]
Ok, then everything is good. Thanks for clearing that up for me and thank you for your work
