### ISSUE TITLE
Dropdown with multiselect and selectAll row does not work consistently. 

### ISSUE THREAD

**Issue by nielsNocore** [radzenhq/radzen-blazor#1776]
**Describe the bug**
The radzen drop down, with multi select mode, and select all row has some inconsistencies. 
The items row can be selected by clicking on the empty part of the row, the select all row does not
The select all row, the cursor changes to a pointer, the item rows do not. 

**To Reproduce**
See screen recording in zip. 
[SelectAll radzen.zip](https://github.com/user-attachments/files/17659998/SelectAll.radzen.zip)

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Select all and item rows to have the same behavior 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Screen recording done in on the demo pages of radzen. https://blazor.radzen.com/dropdown-multiple

**Comment by enchev** [comment]
The cursor is pointer on both select all and select individual item:
![dd-sa-cursor](https://github.com/user-attachments/assets/b7d2f048-ac6f-4645-b4ec-5708b95aa984)

If you want select all to behave in the same way as selecting individual item you should set SelectAllText:
![image](https://github.com/
![dd-sa-cursor-text](https://github.com/user-attachments/assets/1abd78e8-ae37-4578-a844-b7266978be73)
user-attachments/assets/7f7dea93-3bec-4f67-b8e7-1d6f8d1858c4)

**Comment by nielsNocore** [comment]
Hi @enchev 
thank you for your fast answer, 
i think i did not explain it correctly. 

The over, when hovering over the text in the select all row or any other row is different
https://github.com/user-attachments/assets/f2c738e8-c9fc-4c8e-ad1e-8905c4fac4e3

And when clicking in the void/empty part after the text,
when doing so on the select all row. nothing hapens, 
when doing so on an item row. that row is selected. 
https://github.com/user-attachments/assets/3d76c062-6dcf-4171-91e8-6ac63737a9bd

Niels
