### ISSUE TITLE
Dropdowns with attached tooltips do not close other active dropdowns when opened

### ISSUE THREAD

**Issue by mrfixij** [radzenhq/radzen-blazor#1777]
**To Reproduce**

1. Create a page with two dropdowns.  On the first dropdown, attach a tooltip to MouseEnter (as shown here https://blazor.radzen.com/tooltip?theme=material3)
2. Open the second dropdown.
3. Mouse over the first dropdown to make the tooltip appear.  Click on the first dropdown
4. Observe that both dropdowns are open.

**Expected behavior**
The first dropdown should be opened, and the second dropdown should be closed.

**Additional context**

![image](https://github.com/user-attachments/assets/0988cfc3-550e-4080-afbc-532d7e9fab2d)

**Comment by enchev** [comment]
I am afraid that tooltips for popups is not support and will never be.
