### ISSUE TITLE
Make FirstVisibleTab as public in RadzenTabs

### ISSUE THREAD

**Issue by shwetha-rk** [radzenhq/radzen-blazor#1780]
Please make "FirstVisibleTab" method from RadzenTabs as public as it will be very helpful. we have many RadzenTabsItem and each item viisbility is based on many conditions.

**Comment by akorchev** [comment]
Why do you need the FirstVisibleTab to be public? We consider it an implementation detail and don't see much value to make it public.

**Comment by shwetha-rk** [comment]
we have many RadzenTabsItem and each item viisbility is based on many conditions. so by default selectedtab is not visible as it might be hidden based on conditions, if we know FirstVisibleTab, we can set that index for SelectedIndex, so making it public will be useful

**Comment by akorchev** [comment]
I am sorry but I still don't get it. FirstVisibleTab is used internally to determine what tab to display when SelectedIndex is not set. You want to use it to set SelectedIndex which seems backwards to me. Even if we made it public accessing it and then setting SelectedIndex would cause unnecessary rendering cycle.
