### ISSUE TITLE
Feature Request: Kanban board view

### ISSUE THREAD

**Issue by AshD** [radzenhq/radzen-blazor#1783]
**Is your feature request related to a problem? Please describe.**
I want to display my tasks list in a Kanban board View

**Describe the solution you'd like**
Support a Kanban view board like https://www.atlassian.com/agile/kanban/boards

**Describe alternatives you've considered**
Using SyncFusion Blazor and wanting to migrate to Razden to open source parts of the project

![image](https://github.com/user-attachments/assets/b789938b-5007-4b74-93c9-beb9188aad5e)

**Comment by MPapst** [comment]
Isn't that similar to the RadzenDropZone?
https://blazor.radzen.com/dropzone

**Comment by enchev** [comment]
Yep, the DropZone can be used to create Kanban board .
