### ISSUE TITLE
RadzenDataGrid Visual Inconsistency with Filter Icon

### ISSUE THREAD

**Issue by kerajel** [radzenhq/radzen-blazor#1784]
**Preconditions:**
- `RadzenDataGrid` configured with advanced filtering and wrapped in the parent div that controls visibility:
```html
<div style="display:@(Visible ? "block" : "none");">
</div>
```
- `LoadData`, `DataGridSettings`, `Data` are bound to the grid.

**Steps to Replicate:**
1. Filter column A by a specific value.
2. Set the grid's parent div visibility to false (`Visible = false`).
3. Reset `DataGridSettings` to a new instance.
4. Force the grid to reload.
5. Set the grid's visibility back to true.
6. Observe the data loaded correctly (i.e., no filtering, no sorting).

**Expected Result:**
- The filter icon on column A should appear empty, indicating no active filters.

**Actual Result:**
- The filter icon on column A is shown as filled, suggesting a filter is applied even though the `DataGridSettings` instance and `gridRef.ColumnsCollection.ColumnA` confirm no active filter on column A.
![image](https://github.com/user-attachments/assets/f4bbe384-4dcc-4897-bc6a-5c50e5408890)

**Additional Observations:**
- The filtered appearance persists despite no actual filtering affecting the returned data.
- This visual glitch resolves after reloading the grid again and allowing the `LoadData` to update the 'entries' (the grid's 'Data' property).
- The issue may be related to the grid being invisible when the settings are reset.

I go through all this trouble only because there is no way to easily hide grid until it's data is fully loaded when using `LoadData`

Radzen.Blazor" Version="5.5.5"

**Comment by enchev** [comment]
When changing the DataGrid visibility you might need to call Reload() depending on your case.
