### ISSUE TITLE
RadzenDataGrid Numeric Advanced Filter Input Issues

### ISSUE THREAD

**Issue by kerajel** [radzenhq/radzen-blazor#1787]
To reproduce
Open https://blazor.radzen.com/datagrid?theme=material3
Open IQueryable or LoadDataEvent DataGrid demo (I think it would be reproduceable on any demo)
Make ID column filterable
Open the advanced filter on ID column
Press and hold any number (say, 1) as if you tried to submit a long input '1111111111'

Actual result
The input loses responsiveness (entire page freezes) and becomes stuck with '1111' or '111' input, unfreezes after a second
Same glitchy behavior if you input '1111111111' and then keep backspace pressed to delete it

Expected result
The input does not freeze and behaves as smoothly as a text input (in the same demo press and hold 'd' when filtering by First Name - observe that filter input smoothy gets filled up with 'd' characters)

I actually noticed that something is wrong with the numeric input looking at our MVP stand, but in our case the issue is different, below is the gif when I try to input '123' and then delete it. Notice how numbers disappear and sometimes I end up with '13' or '12'. Once again, the input in the advanced for text fields works without any issues. 

![Recording 2024-11-13 221621 (1)](https://github.com/user-attachments/assets/43e684ed-596f-4e17-a045-cbf3f5653c5d)

Radzen.Blazor" Version=5.5.5
Windows 11
Google Chrome Version 130.0.6723.117 (Official Build) (64-bit)

**Comment by kerajel** [comment]
Update: the issue **is not** reproduced if I switch grid to FilterMode.SimpleWithMenu, so it looks like only advanced filter is affected

I also noticed that advanced filter clears your input if it exceeds int32.MaxValue which is not observed with FilterMode.SimpleWithMenu

**Comment by enchev** [comment]
Indeed the Numeric component in advanced filter will validate the number as you type while in simple mode the validation will happen on blur - this is how the DataGrid filtering is implemented and we don't plan to change that.

**Comment by kerajel** [comment]
@enchev 
I don't understand it; I've submitted two different pieces of evidence showing the negative impact of the current implementation on the input, yet you say this is expected. Did you view the .gif in my first post? Do the numbers disappearing and jumping erratically align with the project's objectives and the overall direction of the Radzen?

**Comment by kerajel** [comment]
I currently develop an MVP module using Radzen so that I can showcase it to the management at the end of the year and claim that we can switch from Angular to Radzen completely and stick with pure .NET stack. How am I supposed to justify such cases if the inputs are glitchy? "Yes, I know the numbers disappear and the entire page freezes, but I was ensured this is intended. Also this happens only on numeric filters, so it won't affect customers who do not filter o numeric fields, so it's around 23%, we are still good to proceed with the Blazor migration"

**Comment by enchev** [comment]
If you do not like the default behavior you can always define your own FilterValueTemplate for this column where you can use Numeric with desired settings.

**Comment by delyaKh** [comment]
@enchev,
I had never noticed before, but our grids with advanced numeric filters have the same input issue—the digits are lost or disappear and reappear if you type a number quickly. The only solution is to type slowly.

Why is this considered expected behavior?
