### ISSUE TITLE
Feature request: Add Stroke to enable change color in RadzenSeriesAnnotation text

### ISSUE THREAD

**Issue by georgepaoli** [radzenhq/radzen-blazor#1789]
Please, add Stroke property in RadzenSeriesAnnotation to enable set text color.

![image](https://github.com/user-attachments/assets/4dc10d3b-77c8-4145-b102-87261d21c692)

Suggested code:
<RadzenSeriesAnnotation **Stroke="white"** />

**Comment by akorchev** [comment]
Named it Fill after all (instead of Stroke). Stroke sets the outer text "border" and it looks double the size. Fill looks as expected.

**Comment by georgepaoli** [comment]
Thank you so much!
![image](https://github.com/user-attachments/assets/36ec20af-543a-4fc0-a17c-ac7ed1407c65)
