### ISSUE TITLE
Datagrid Single ExpandMode does nothing when RowExpand is not set

### ISSUE THREAD

**Issue by joriverm** [radzenhq/radzen-blazor#179]
**Describe the bug**
When i create a DataGrid that has ExpandMode set to single , it acts the same as when it is set to Multiple.

**To Reproduce**
1. Create Datagrid with ExpandMode="DataGridExpandMode.Single"
2. Add a template with any content
3. Compile and open the page. 
4. Expand a row
5. Expand another row

**Expected behavior**
When a row is expanded, that all other rows are not/no longer expanded.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 19042.1110
 - Browser: Firefox
 - Version: 89.0

**Additional context**
I have only started using Radzen Blazor like a month ago for an inhouse project, so i have no idea if this is how it is suppose to work or not, but it is not how i would expect it to work going by the naming of the properties.
the issue can also be seen in the examples : https://blazor.radzen.com/master-detail-hierarchy

my test table : 
```
<RadzenDataGrid @ref="PackagesGrid" AllowColumnResize="true" AllowFiltering="true" AllowPaging="true" PageSize="10" AllowSorting="true" 
                EditMode="DataGridEditMode.Single" ExpandMode="DataGridExpandMode.Single"
                Data="@Packages">
    <Template Context="package">
        <span>Content!</span>
    </Template>
    <Columns>
        <RadzenDataGridColumn Width="8%" TItem="PackageModel" Property="ID" Title="ID" Filterable="false" Sortable="false" />
    </Columns>
</RadzenDataGrid>
```

there is no code linked to this table, and my OnInitializedAsync only retrieves the list of models from my API. 
i also have no OnAfterRender.

**Comment by enchev** [comment]
I’ve just tested single ExpandMode on our demo and it worked as expected: https://blazor.radzen.com/master-detail-hierarchy-demand

**Comment by joriverm** [comment]
on the on demand page it indeed seems to work, so this excludes browser issue at first glance i guess. 
however in the general hierarchy page it doesn't seem to work correctly
https://blazor.radzen.com/master-detail-hierarchy

the only difference i can tell from the 2 demo pages is that the on demand page seems to have RowExpand assigned a function (that doesn't seem to do much with the grid).

![image](https://user-images.githubusercontent.com/87806863/126773281-f605e410-b182-4aec-b929-a772fd218d92.png)

I have tried a quick test using the inhouse app and indeed, RowExpand needs to be assigned an (at least empty) function for it to work.
on top of that, because RowExpand needs to be set, TItem also needs to be set.

to me it sounds illogical to have to add an empty function for the single mode to work.

**Comment by joriverm** [comment]
thanks for fixing it ! :)
