### ISSUE TITLE
FileUpload Component Not Working in MAUI Hybrid App Due to Blob Request to Local 0.0.0.1 Address

### ISSUE THREAD

**Issue by Abbossbek** [radzenhq/radzen-blazor#1795]
The `Radzen FileUpload` component doesn't work correctly in a .NET MAUI Hybrid app. It attempts to upload files as a blob to a local `0.0.0.1` address, which is inaccessible from the backend API. This behavior causes file uploads to fail in the MAUI environment, while the same setup works correctly in a standard web browser.

I have attached two screenshots for clarity:  
1. **Working Setup (Web Browser):** Shows the correct network request and successful file upload.  
2. **Non-Working Setup (MAUI Hybrid):** Shows the network tab indicating the failed attempt to upload files to `0.0.0.1`.  

**Steps to Reproduce:**  
1. Create a .NET MAUI Hybrid app and use the Radzen `FileUpload` component.  
2. Configure the `FileUpload` component to upload files to a backend API.  
3. Run the app and attempt to upload a file.  

**Expected Behavior:**  
The `FileUpload` component should upload the file directly to the configured backend API, similar to how it works in a regular web browser.  

**Actual Behavior:**  
The `FileUpload` component tries to upload the file as a blob to `0.0.0.1`, causing the upload to fail.  

**Screenshots:**  
![image](https://github.com/user-attachments/assets/828260e2-b55e-440b-8521-8c315bc5cd76)
![image](https://github.com/user-attachments/assets/8b503de2-4e73-40dd-b33d-d2a8396d6d33)

**Environment:**  
- Radzen.Blazor version: 5.6.0
- .NET version: 9 
- Platform: .NET MAUI Hybrid  

**Proposed Solution:**  
Allow the `Radzen FileUpload` component to bypass the default blob handling in MAUI Hybrid environments and directly upload files to the backend API.

**Comment by enchev** [comment]
FileUpload uploads the file to what is specified in Url property.

**Comment by Abbossbek** [comment]
The url is written correctly, but in MAUI Hybrid it is loading the blob at 0.0.0.1. You can see in this screenshot that the same code is working in the web application.
![image](https://github.com/user-attachments/assets/8d551866-3a5a-4d0e-92f2-c92c183166e8)

 But there is another issue, in MAUI the file contents are showing as null, while in the web they are there. What could be the reason for this?
 
![image](https://github.com/user-attachments/assets/8ba1f7d4-aeb2-45f5-a54b-51628b88a5b8)

**Comment by Abbossbek** [comment]
I resolved the issue—it turned out to be a server-side error. Radzen components are definitely not to blame—they’re simply the best!
