### ISSUE TITLE
RadzenDataGrid, Filter with Settings on Column with a Enum appears broken in 5.6.8,  works in 5.6.7

### ISSUE THREAD

**Issue by Clive321A** [radzenhq/radzen-blazor#1816]
**Describe the bug**
I use a RadzenDataGrid and have filtering on for a column, the column is a Enum column, I also have @bind-settings which saves settings into localstorage.

in 5.6.7 "Settings" contains the filter values when set from the Grid, in 5.6.8 the filter values for this enum column are missing
Below CurrentRuleRow.RuleType is a Enum

Functionality appears to work ok if the column is a string.

```
    public enum RuleType
    {
        Family,
        Section,
        SubSection,
        Class,
        FamilySubSection,
        ClassSubSection
    }
```

```
<RadzenDataGridColumn Property="@nameof(CurrentRuleRow.RuleType)" Sortable="true" Filterable="true" MinWidth="100px" Width="100px" Title="Rule Type">
```

```
 <RadzenDataGrid AllowColumnReorder="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" @bind-Settings="@Settings" AllowPickAllColumns=true Density="Density.Compact" ShowColumnTitleAsTooltip="true" AllowFiltering="true" AllowColumnPicking="true" AllowColumnResize="true" AllowAlternatingRows="true" FilterMode="FilterMode.CheckBoxList"
 AllowSorting="true" PageSize="20" PageSizeOptions="@pageSizeOptions" AllowPaging="true" PagerHorizontalAlign="HorizontalAlign.Center" PagerPosition="PagerPosition.Bottom"
 Data=@Result.Rules LogicalFilterOperator="LogicalFilterOperator.Or" SelectionMode="DataGridSelectionMode.Single">
 ```
 
 Settings are saved like this.
 ```
     DataGridSettings _settings;
    public DataGridSettings Settings
    {
        get
        {
            return _settings;
        }
        set
        {
            if (_settings != value)
            {
                _settings = value;
                InvokeAsync(SaveStateAsync);
            }
        }
    }
    private async Task SaveStateAsync()
    {

        await localStorage.SetItemAsync<string>(Constants.CurrentRuleColumns, JsonSerializer.Serialize<DataGridSettings>(Settings));
    }
 ```
 
Downgrading to v5.6.7, and doing a "Clean" before rebuilding in VS2022, resolves the issue.  Upgrading to 5.6.8 and doing a Clean in VS2022 reproduces the issue

**Expected behavior**
Settings are preserved as in 5.6.7

**Desktop (please complete the following information):**
 Windows/Linux (happens in both)
 VS2022

**Comment by Clive321A** [comment]
Thanks for looking at this, it still hasnt resolved the issue though, when I change the filter, Filtervalue is still null in DataGridColumnSettings for Enum in 5.6.9, and works in 5.6.7

In 5.6.9 when changing filter on enum column
![image](https://github.com/user-attachments/assets/c0ffead2-7f6a-4332-a56f-b96b2e0326c9)

And in 5.6.7 when changing filter

![image](https://github.com/user-attachments/assets/9e749bfd-2a59-4c08-8317-6603720990f5)

**Comment by enchev** [comment]
We will need runnable code demonstrating the problem. You can use our demos ad reference - they are editable.
