### ISSUE TITLE
RadzenDataFilter Numeric Input Issue

### ISSUE THREAD

**Issue by kerajel** [radzenhq/radzen-blazor#1818]
RadzenDataFilter numeric input suffers the same issues as RadzenDataGrid's AdvancedFilter on numeric columns as described in https://github.com/radzenhq/radzen-blazor/issues/1809 (that is, the issue is reproduced only on the hosted environments, influenced by Blazor server lag)

**To reproduce**

Negative case
Define a RadzenDataFilter with numeric column
Input a value and filter right away

**Expected result**
Input value is registered in the RadzenDataFilter<>.ToFilterString();

**Actual result**
Input value is NOT registered in the RadzenDataFilter<>.ToFilterString();

Positive case
Define a RadzenDataFilter with numeric column
Input a value and DO NOT filter right away
Focus something on the page
Do filter

**Expected result** = **Actual Result**
Input value is registered in the RadzenDataFilter<>.ToFilterString();

**Comment by kerajel** [comment]
The following script helped to resolve the issue:

```js
function forceUpdateNumericInputs() {
    document.querySelectorAll('.rz-numeric-input input').forEach(input => {
        input.blur();
        input.focus();
    });
}
```

```c#
async Task Submit() // whatever action that leads to reading RadzenDataFilter<>.ToFilterString();
{
    await JSRuntime.InvokeVoidAsync("forceUpdateNumericInputs");
    string filterString = @dataFilter.RadzenDataFilter<>.ToFilterString(); // returns current input
}
```

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/a0cfc5d26736c5d7f7397356818ceef6059ba152
