### ISSUE TITLE
Components have no support for .net 6

### ISSUE THREAD

**Issue by sofiageo** [radzenhq/radzen-blazor#182]
**Describe the bug**
There are currently 18 cases where component code only executes for NET5 only. NET6 is ignored though. For example Virtualization is only supported for NET 5 in a RadzenDataGrid.  It should probably be changed to [NET5_0_OR_GREATER](https://github.com/dotnet/designs/blob/main/accepted/2020/or-greater-defines/or-greater-defines.md)

**To Reproduce**
1. Create a .net 6 preview 6 Blazor project
2. Create a RadzenDataGrid with Virtualization enabled
3. Virtualization is ignored, application freezes as a result.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Nightly

**Comment by enchev** [comment]
We will provide .NET 6 support after the official release of .NET 6.
