### ISSUE TITLE
RadzenDatagridColumn filter cannot be cleared after setting FilterValue

### ISSUE THREAD

**Issue by tmyllymaki** [radzenhq/radzen-blazor#1821]
**Describe the bug**
I'm setting an initial value on a `RadzenDatagridColumn<T>.FilterValue` as so:
```csharp
foreach (var (key, filterValue) in GridFilters)
{
    if (filterValue is null) continue;
    var column = _dataGrid.ColumnsCollection.FirstOrDefault(c => c.Title == key);
    if (column is null) continue;
    column.FilterValue = filterValue;
}
await _dataGrid.Reload();
```

After setting the `FilterValue` you can't clear the filter as the `GetFilterValue()` always fallbacks to the initial `FilterValue` which is not modified:

```csharp
public object GetFilterValue()
{
    return filterValue ?? FilterValue;
}
```

You can circumvent the issue by using the `SetFilterValueAsync`.

**Expected behavior**
The `FilterValue` should update when the component is updated or the property should be modified or removed.

**Desktop (please complete the following information):**
 - Version 5.6.9

**Comment by enchev** [comment]
This demo is using exactly the same approach and the value can be cleared:
https://blazor.radzen.com/datagrid-filter-api?theme=material3

**Comment by tmyllymaki** [comment]
I'm sorry but it's not. It's using the the method `SetFilterValue`. If you change it to the property `FilterValue` it can't be cleared.

**Comment by enchev** [comment]
FilterValue should not be used since this is what will be restored when you execute StateHasChanged().

**Comment by enchev** [comment]
The warning is added directly by Blazor framework and Visual Studio when you build the project - it's not something specific to Radzen.Blazor compoents. Public parameters should not be set using code.
