### ISSUE TITLE
RadzenDataGrid SimpleWithMenu filter does not wait for an operator to be picked

### ISSUE THREAD

**Issue by kerajel** [radzenhq/radzen-blazor#1825]
To reproduce

1. Go to https://blazor.radzen.com/datagrid-simple-filter-menu?theme=material3

1. Type in '10249' to the 'Order ID' column
2. Click on the filter button to select 'less than or equals'
3. Select 'less than or equals'

Expected result
Query to filter for 'less than or equals 10249' was issued

Actual result
2 queries were issued 'equals to 10249' and 'less than or equals 10249'

**Comment by enchev** [comment]
This is how simple filter (and simple with menu) filtering works - immediately when you update the value.
