### ISSUE TITLE
Scheduler | Month view not showing multi-day events corrently when starts last on day

### ISSUE THREAD

**Issue by w3ori** [radzenhq/radzen-blazor#1828]
**Describe the bug**
If there are more than displayable events on a day, and the last event is a multi-day event, the id doesn't show on the next day, but takes the first slot on the next day in the month view.

**To Reproduce**
1. Add more than 3 events on one day
2. Have the last event take time on the next day
3. Notice that it is not displayed the next day, but occupies the space
![image](https://github.com/user-attachments/assets/3b0e933e-fdf4-422a-96f3-4f19cb909e42)

**Expected behavior**
Display multi-day events correctly also on the next day.

**Screenshots**
![image](https://github.com/user-attachments/assets/3b0e933e-fdf4-422a-96f3-4f19cb909e42)
![image](https://github.com/user-attachments/assets/3bb2dc1b-67eb-4ea9-95e4-fd0ea0a8f021)
![image](https://github.com/user-attachments/assets/3ae8566a-8702-4366-8b69-d15624f7ee5e)

**Desktop:**
 - OS: WIN 11
 - Browser: Chrome
 - Version: 5.6.7

**Comment by akorchev** [comment]
Hi @w3ori,

Please let us know how to reproduce this problem [here](https://blazor.radzen.com/scheduler) (you can edit the demo source).

**Comment by w3ori** [comment]
> Hi @w3ori,
> 
> Please let us know how to reproduce this problem [here](https://blazor.radzen.com/scheduler) (you can edit the demo source).

Hi,

this is the test list for appointments:
```csharp
IList<Appointment> appointments = new List<Appointment>
    {
        new Appointment { Start = DateTime.Today.AddDays(-2), End = DateTime.Today.AddDays(-2), Text = "Birthday" },
        new Appointment { Start = DateTime.Today.AddDays(-11), End = DateTime.Today.AddDays(-10), Text = "Day off" },
        new Appointment { Start = DateTime.Today.AddDays(-10), End = DateTime.Today.AddDays(-8), Text = "Work from home" },
        new Appointment { Start = DateTime.Today.AddHours(10), End = DateTime.Today.AddHours(12), Text = "Online meeting" },
        new Appointment { Start = DateTime.Today.AddHours(10), End = DateTime.Today.AddHours(13), Text = "Skype call" },
        new Appointment { Start = DateTime.Today.AddHours(14), End = DateTime.Today.AddHours(14).AddMinutes(30), Text = "Dentist appointment" },
        new Appointment { Start = DateTime.Today.AddHours(22), End = DateTime.Today.AddDays(1).AddHours(2), Text = "Multi-day event" }, // this is my test event
        new Appointment { Start = DateTime.Today.AddDays(1), End = DateTime.Today.AddDays(2), Text = "Vacation" },
    };
```

![image](https://github.com/user-attachments/assets/32176627-469a-493e-9392-3c03e4d7fe0a)

**Comment by akorchev** [comment]
Got it! Thanks.
