### ISSUE TITLE
Allow to pass a Template to RadzenDataGrid when there is no data

### ISSUE THREAD

**Issue by MPapst** [radzenhq/radzen-blazor#183]
**Is your feature request related to a problem? Please describe.**
When dealing with Drag & Drop in the RadzenDataGrid on scope of rows, it is impossible to drop items on an empty data grid.
This works only if there can be drop callback attached to the empty row. As this is not yet supported natively, this can only be achieved using some workarounds.

**Describe the solution you'd like**
Allow to pass a Renderfragment as an empty Template for the Data Grid.

**Describe alternatives you've considered**
Wrapping the Data Grid completely in a drop zone makes it impossible to catch the rows itself later.
Attaching the RowRender Callback to the Empty Row could work (that is the way I am injecting callbacks to the drop for regular rows) but seems ugly, as there is no data item attached to the empty row.

**Comment by enchev** [comment]
You can set EmptyText to get single row when the DataGrid is bound to empty collection:
https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenDataGrid.razor#L272

**Comment by enchev** [comment]
Hey @MPapst ,

I just saw your implementation and I've merged the pull request!
