### ISSUE TITLE
Display Bug: Doubled Value in Progress Bar

### ISSUE THREAD

**Issue by NEmbgen** [radzenhq/radzen-blazor#1830]
**Describe the bug**
Double value display in Progress Bar.

Using the code in the first screenshot produces the output in the second screenshot. I expect that it is because of line 18 here:
https://github.com/radzenhq/radzen-blazor/blob/c1b7ce0bcc61b0ff29819998f7a41534b30ff4c7/Radzen.Blazor/RadzenProgressBar.razor#L18

**Expected behavior**
For the value to only be shown once.

**Screenshots**
![image](https://github.com/user-attachments/assets/35631617-1cab-49b5-a8ef-17c0a75f9a09)
![image](https://github.com/user-attachments/assets/e6c6955c-21cd-4f80-b430-a76b5e6a7d51)

**Comment by akorchev** [comment]
This would happen if your browser is loading old CSS files. Try clearing your browser cache. If using a premium theme - reapply it.
