### ISSUE TITLE
RadzenDatePicker does not work properly in Server Rendering mode

### ISSUE THREAD

**Issue by MaxwellDAssistek** [radzenhq/radzen-blazor#1831]
**Describe the bug**
RadzenDatePicker seems to always use server time to determine the current date in many places. This doesn't work when the server is in UTC and the end user is in a different timezone.

**To Reproduce**
1. Run a Blazor server page on a server running in UTC.
2. Visit the page from a computer for example in Eastern Time after 7pm.
3. Click on the date picker.
4. Observe that the following day is circled as the "current" day.

**Expected behavior**
Any calculations involving "current" date or time should be based on the browser's date time, not the server's.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 4.24.2

**Comment by enchev** [comment]
Blazor server runs on the server - it's obvious it will take the server time. You might need to check Blazor WebAssembly.

**Comment by Maxwell175** [comment]
It is obvious that if I was able to use webassembly I would. But this page CANNOT be anything except Server rendered. It is obvious that there is a trivial solution, which is to use JS interops to query the necessary information from client side.

**Comment by Maxwell175** [comment]
Anyone doing real web applications obviously need to be using client side time for proper behavior and audit trails.
