### ISSUE TITLE
BL0005 when Setting DropDownBaseItemRenderEventArgs<T>.Disabled

### ISSUE THREAD

**Issue by madjar4-cssmb** [radzenhq/radzen-blazor#1839]
**Describe the bug**
Warning `BL0005` when following the Radzen dropdown grouping demo.

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy the code from [this demo](https://[blazor.radzen.com/dropdown-grouping?theme=material3#multiple-selection](https://blazor.radzen.com/dropdown-grouping?theme=material3#multiple-selection)) into Visual Studio 2022.
2. Notice the error on the `args.Disabled = true`. The error is `BL0005`.

**Expected behavior**
No warning, as the setter is public inside an `EventArgs`

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 131.0.2903.70

**Additional context**
I'm not sure why `DropDownBaseItemRenderEventArgs<T>` has the `ParameterAttribute` on the `Visible` and `Disabled` properties. If it is wanted, please explain their purpose.

**Comment by enchev** [comment]
Blazor framework cannot recognise if you are setting public parameter (which is indeed not recommended) or property of an event argument. We cannot control this 
.

**Comment by madjar4-cssmb** [comment]
@enchev I get that, but why are properties of a non-component class decorated with a `ParameterAttribute` in the first place? Isn't it reserved for component classes?

**Comment by madjar4-cssmb** [comment]
@enchev thanks for the fix!
[Reference](https://github.com/radzenhq/radzen-blazor/commit/93d1e8604ac1be886fea63b0ab355dfafce6cf5b).
