### ISSUE TITLE
Series in a chart sometimes not visible

### ISSUE THREAD

**Issue by karolina-lindvall-motatos** [radzenhq/radzen-blazor#1840]
**Describe the bug**
I have two RadzenColumnSeries in the same chart. If the two column series have the same CategoryProperty and the ValueProperty differs with only a few points, one of the series isn't visible. The only series that is visible in the chart is the series with the higher ValueProperty. The amount of point that causes this error depends on value on the ValueProperty. I know that the series is in the chart (but not visible) since it appears if clicking on the legend to remove the visible series.

**To Reproduce**
1. Go to '[https://blazor.radzen.com/column-chart?theme=material3](https://blazor.radzen.com/column-chart?theme=material3)'
2. Click on 'Edit source'
3. Paste the following code:
```
 @using System.Globalization

<RadzenStack class="rz-p-0 rz-p-md-6 rz-p-lg-12">
    <RadzenCard Variant="Variant.Outlined">
        <RadzenStack Orientation="Orientation.Horizontal" AlignItems="AlignItems.Center" Gap="0.5rem" Wrap="FlexWrap.Wrap">
            <RadzenCheckBox @bind-Value="@showDataLabels" Name="dataLabels"></RadzenCheckBox>
            <RadzenLabel Text="Show Data Labels" Component="dataLabels" />
        </RadzenStack>
    </RadzenCard>
    <RadzenRow>
        <RadzenColumn >
            <h4>Custom size column series</h4>
            <RadzenChart>
                <RadzenColumnSeries Data="@productEu" CategoryProperty="Price" Title="Product EU" ValueProperty="Rate">
                    <RadzenSeriesDataLabels Visible="@showDataLabels" />
                </RadzenColumnSeries>
                <RadzenColumnSeries Data="@productWorld" CategoryProperty="Price" Title="Product World" LineType="LineType.Dashed" ValueProperty="Rate">
                    <RadzenSeriesDataLabels Visible="@showDataLabels" />
                </RadzenColumnSeries>
                <RadzenColumnOptions />
                <RadzenCategoryAxis />
                <RadzenValueAxis>
                    <RadzenGridLines Visible="true" />
                </RadzenValueAxis>
            </RadzenChart>
        </RadzenColumn>
    </RadzenRow>
</RadzenStack>

@code {
    bool showDataLabels = false;

    class DataItem
    {
        public double Price { get; set; }
        public double Rate { get; set; }
    }

    DataItem[] productEu = new DataItem[] {
        new DataItem
        {
            Price = 269,
            Rate = 5
        }
    };

    DataItem[] productWorld = new DataItem[] {
        new DataItem
        {
            Price = 269,
            Rate = 6
        }

    };
}
```
4. Run the code

**Expected behavior**
Each series should always be visible.

**Screenshots**
<img width="622" alt="image" src="https://github.com/user-attachments/assets/272c5150-9c94-46bc-9029-83b29ec45cc1">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome version 131, Edge version 131

**Comment by matthewcuan** [comment]
The chart truncates the value axis to display only the differences between the columns. This can be overridden by setting a minimum value for the RadzenValueAxis. See the example below:

`<RadzenValueAxis Min="0">`

**Comment by akorchev** [comment]
Yes, setting the Min attribute of RadzenValueAxis is the recommended solution.
