### ISSUE TITLE
Is standalone WASM not supported in Radzen Blazor Studio now?

### ISSUE THREAD

**Issue by nicholasyin** [radzenhq/radzen-blazor#1845]
I created a new standalone WASM project in vscode and run it from Radzen Studio, the resulting page displays all controls in plain html, as if all css and js files have not worked at all. I noticed the project creation wizard of Radzen Studio doesn't have the option for standalone WASM. So does this mean the standalone WASM is not supported by Radzen Blazor Studio?

**Comment by enchev** [comment]
There is no standalone WASM template in RBS since you need a service (WASM hosted) to expose a database. Instruction on how to register CSS for standalone WASM are available in our demos.
