### ISSUE TITLE
Tooltip not showing on touch devices

### ISSUE THREAD

**Issue by jap-camasit** [radzenhq/radzen-blazor#1848]
**Describe the bug**
The tooltip is not opening/showing on touch devices

**To Reproduce**
1. Go to https://blazor.radzen.com/tooltip
2. Inspect the page
3. Enable touch simulation
4. Click on one of the buttons

**Expected behavior**
Tooltip should be visible

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
I'm pretty sure it's showing/hiding on mouseenter/mouseleave, but these don't work on touch devices, obviously.

**Comment by enchev** [comment]
Indeed there is no mouseenter/mouseleave on touch devices - you can use different event like click in such cases

**Comment by jap-camasit** [comment]
We are trying to show tooltips for readonly dropdowns. Any chance you can support OnClick on dropdowns?

Our alternative is to add JavaScript onclick event listener, but doesn't seem to be the best solution.
