### ISSUE TITLE
RadzenDatePicker doesn't work in server mode

### ISSUE THREAD

**Issue by huxinshuo** [radzenhq/radzen-blazor#1849]
blazor.server.js:1 [2024-12-11T14:07:43.781Z] Error: Microsoft.JSInterop.JSException: Could not find 'Radzen.createDatePicker' ('Radzen' was undefined).
Error: Could not find 'Radzen.createDatePicker' ('Radzen' was undefined).

My web aready install Radzen and has code as  below:
@using Radzen
@using Radzen.Blazor

And I'm in China  where it is difficut to open https://blazor.radzen.com/getting-started?theme=material3
![微信截图_20241211221744](https://github.com/user-attachments/assets/2e805bf2-8900-4f28-acb2-65a48573506e)

**Comment by akorchev** [comment]
You need to also include the JavaScript file. It is in the instructions.
