### ISSUE TITLE
Password component custom unmask eye

### ISSUE THREAD

**Issue by PJotaRobles** [radzenhq/radzen-blazor#186]
Good Morning.

Based on [issue number 181](https://github.com/radzenhq/radzen-blazor/issues/181) closed as something foreign to Radzen I think it would be a good idea to control it internally and develop a Radzen unmask, like other providers do with the prefixes or suffixes in textinput.
I attach an example.
![adjunto](https://user-images.githubusercontent.com/62036823/127471489-bc9a5dfd-9b7d-4ee2-ad04-e026d49bf59a.png)

Thank you very much in advance.

All the best.

**Comment by yordanov** [comment]
You can now use RadzenPassword together with our new [FormField](https://blazor.radzen.com/form-field) component to hide or reveal a password.

![password](https://user-images.githubusercontent.com/1118895/231745711-285bb058-1c7f-48ba-a35d-e43e143d6147.gif)

Floating label, helper text, prefixes and suffixes are also supported.

![RadzenBlazorFormFieldVariants](https://user-images.githubusercontent.com/1118895/231747091-6d389c3d-f363-462d-82db-9849ef1f72e1.gif)

**Comment by MaksimOsipov** [comment]
there's a ploblem with valid borders in this approach....
![pass_issue](https://github.com/radzenhq/radzen-blazor/assets/157966661/5dfff23f-7617-4b00-9ca9-01b77b94bcfa)
