### ISSUE TITLE
Feature Request: Sort selected items in DropDown multiple selection

### ISSUE THREAD

**Issue by jap-camasit** [radzenhq/radzen-blazor#1862]
**Is your feature request related to a problem? Please describe.**
Our users find it confusing when selected items are still on the bottom of the list when opening the DropDown.

**Describe the solution you'd like**
A property where we can apply sorting on ID or something else.

**Describe alternatives you've considered**
Sorting the list ourselves when DropDown is opened with the `List<T>.Sort` method.

**Additional context**
None.

**Comment by enchev** [comment]
Most probably we will not add such feature, I haven't seen any DropDown component in any platform where selected items are sorted on the top of all items. You might need to create a custom DropDown component similar to [these demos](https://blazor.radzen.com/popup) or to try to sort the collection bound to the DropDown Data property on every selection change.
