### ISSUE TITLE
Scheduler - Month View - Appointments not sorted correctly

### ISSUE THREAD

**Issue by jeanpascal5** [radzenhq/radzen-blazor#1864]
Upgraded to latest version of Radzen, 5.7  (was using 5.6.10)
Started to noticed that appointments in the Scheduler Month view was not sorting the records by Start Time anymore. 

I suspect the following recent commit may be the cause. An OrderByDescending by the "size" (End - Start) of the appointment was added, which seems wrong. 
https://github.com/radzenhq/radzen-blazor/commit/2c24843e4d406b13d75745db2a0d842dea0fff33

**Comment by akorchev** [comment]
This fixed a problem with rendering of appointments that span over a few days. I am afraid we can't revert that change easily.

**Comment by jeanpascal5** [comment]
Unless I am mistaken, the Scheduler component does not expose a way/hook to control to sorting of Appointments. Maybe a simple fix, would be to check for existence of multi-day appointments in the list, if none are found, default back to the original standard sort logic (StartTime, then EndTime).  Just a thought.

**Comment by akorchev** [comment]
I thought about that but it would lead to inconsistent results. Maybe it shouldn't sort by length in general but have an entirely custom comparer - events longer than 1 day go first and then by start time.

**Comment by jeanpascal5** [comment]
If a custom comparer can be specified that would be great. Having the
control over the sorting of the items displayed would be useful.
In my case, the main scenario in the app we are building is basically
several appointments on the same day, with different start time and length.
The need to display them in the order they will occur is important.
The length of the appointment is not really relevant in our case.
Anyway, having a way/hook to control the sorting would be beneficial. I'm
not really aware of the multi-day appointment problem that was fixed by
this, so can't really comment on that.
Happy to help if needed.

J-P

**Comment by akorchev** [comment]
The issue is this one: https://github.com/radzenhq/radzen-blazor/issues/1828. I will test with a comparer that sorts items by start but first moves "longer" events on top. It should still address that issue and also not make a change for appointments that fit in one slot.
