### ISSUE TITLE
Prefixes / suffixes in components

### ISSUE THREAD

**Issue by PJotaRobles** [radzenhq/radzen-blazor#187]
Good Morning.

Many thanks for your work. 
It could be very interesting, as seen in other creators of Blazor or html components such as bootstrap, to have the possibility of creating prefixes and suffixes in some components such as text, password or number forms or buttons.
I attach an example.
![adjunto](https://user-images.githubusercontent.com/62036823/127474957-94af8755-b23b-45d2-80f0-cf4e4e36db0f.png).

Thank you very much in advance.
All the best.

**Comment by yordanov** [comment]
You can use [RadzenFormField](https://blazor.radzen.com/form-field) to add prefixes / suffixes to any input type Radzen component.

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1118895/231748045-f53fc6c0-9490-4762-9821-03ad63e7a739.png">
