### ISSUE TITLE
DataGridColumnPicking example problems

### ISSUE THREAD

**Issue by jakubiszon** [radzenhq/radzen-blazor#1874]
There are numerous problems with this example:
1. It shows two different methods to manage column visibility at the same time and thus is hard to understand.
2. It needs to copy visibility settings in two places - inside the grid and in the example component. This part doesn't work - description below.
3. There is a warning generated by the compiler.

**Steps to reproduce**
1. Go to [`/datagrid-column-picker`](https://blazor.radzen.com/datagrid-column-picker) - it shows the `DataGridColumnPicking.razor` component.
4. Deselect `FirstName` column using the default column picker
5. Switch to context menu column picker and select the `FirstName` column using it
6. The column will remain hidden

**Desktop (please complete the following information):**
 - OS: windows
 - Browser - chrome and firefox

**I'd like to send a PR to fix it**
I would propose to separate the default column picker and the one using context menus to two different examples, possibly placed on the same page. It will be much easier to understand this way. Would you accept a pull request if I submitted such solution?

**Comment by enchev** [comment]
Sure @jakubiszon! We accept pull requests!
