### ISSUE TITLE
"DataGrid CheckBoxList filtering with LoadData for enums": Still not working in 5.7.1

### ISSUE THREAD

**Issue by osre77** [radzenhq/radzen-blazor#1876]
**Describe the bug**
I have a DataGrid with multiple columns, Filter set to Advanced.
LoadData and Virtualization is used.
One column with an enum type is set to FilterMode CheckBoxList.
When setting a filter in that column the filter stays unchanged.
The Advanced Filter in other columns works

**To Reproduce**
1. Open the Filter drop down
2. Select Options
3. Click Apply
4. Filter drop down closes, no filter is applied
5. Open Filter drop down again, no options selected

**Expected behavior**
Filter is applied
When opening the drop down the options are still selected.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - MAUI Blazor Hybrid .net9

```
<RadzenDataGrid @ref="_dataGrid" Class="flex-fill w-100"
                TItem="LogItemModel" Data="@Model.PagedItems" Count="@Model.FullItemCount" LoadData="@LoadData" AllowVirtualization="true"
                AllowColumnReorder="true" AllowColumnResize="true"
                AllowFiltering="true" FilterPopupRenderMode="PopupRenderMode.OnDemand" FilterMode="FilterMode.Advanced"
                FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" LogicalFilterOperator="LogicalFilterOperator.And"
                AllowSorting="true" AllowMultiColumnSorting="true"
                AllowColumnPicking="true" Density="Density.Compact"
                SelectionMode="DataGridSelectionMode.Single" @bind-Value="SelectedItems">

    <Columns>
        <RadzenDataGridColumn Title="Level" Property="@($"{nameof(LogItemModel.LogEvent)}.{nameof(LogEvent.Level)}")"
                              Width="60px" Frozen="true" FrozenPosition="FrozenColumnPosition.Left"
                              Sortable="true" Filterable="true"
                              FilterMode="FilterMode.CheckBoxList">
```

**Comment by enchev** [comment]
We are unable to run the code provided in this issue. Try to replicate your case using our demos and post here runnable code.

**Comment by osre77** [comment]
My application is not yet in a postable form. As soon as it is I will post a link to the GitHub repo with instructions.

**Comment by jreistDev** [comment]
I am experiencing the same issue.

To test it, I used the Radzen Blazor website on this page:
https://blazor.radzen.com/datagrid-enum-filter.

I added FilterMode="FilterMode.CheckBoxList" to the first column (ID), making it look like this:

`<RadzenDataGrid Data=@employees AllowFiltering="true" AllowPaging="true" AllowSorting="true" ColumnWidth="200px">  
    <Columns>  
        <RadzenDataGridColumn Property="@nameof(Employee.ID)" Title="ID" FilterMode="FilterMode.CheckBoxList" />  
        <RadzenDataGridColumn Property="@nameof(Employee.Gender)" Title="Gender" />  
        <RadzenDataGridColumn Property="@nameof(Employee.Status)" Title="Nullable Status" />  
        <RadzenDataGridColumn Property="@nameof(Employee.Color)" Title="Favorite Color (Display Attribute in Filter)" />  
    </Columns>  
</RadzenDataGrid>`

However, when trying to apply the filter, nothing happens. On the other hand, the advanced filter mode works as expected.

**Comment by Drunken88** [comment]
I also have a similar issue in my app where I have a mix of Advance & CheckBoxList filters.
What I noticed is that when I set FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" together with FilterMode="FilterMode.CheckBoxList", it doesnt filter an I get the error "Argument types do not match".

However if I remove FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" it works just fine (but it's annoying...)

**Comment by enchev** [comment]
Hey @Drunken88 it's the same fix that closed this issue. It will be released tomorrow.

**Comment by Drunken88** [comment]
Hey @enchev , sorry I missed that info ! Thanks for letting me know ! 👍
