### ISSUE TITLE
Data validation does not work in datagrid

### ISSUE THREAD

**Issue by pedrobulano** [radzenhq/radzen-blazor#195]
**Describe the bug**
When creating or updating a row in datagrid, the data is not validated.

**To Reproduce**
On the documentation page https://blazor.radzen.com/datagrid-inline-edit create a new row and save it without entering data, or edit the existing row by deleting the "Ship Name". The string will be saved with an empty "Ship Name" field.

 - OS: Win10
 - Browser: any
 - Version: 3.8.2

**Comment by akorchev** [comment]
Just fixed! Will release a new version by the end of the week.
