### ISSUE TITLE
In the DataGrid, the selected row is not highlighted with color when AllowVirtualization= "true"

### ISSUE THREAD

**Issue by pedrobulano** [radzenhq/radzen-blazor#197]
**Describe the bug**
In the DataGrid, the selected row is not highlighted with color when AllowVirtualization= "true".
**To Reproduce**
Set AllowVirtualization="true" in the DataGrid. When you select a row, it is not highlighted.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: any
 - Version: 3.8.2

**Comment by enchev** [comment]
You should either bind the selected items or subscribe to RowSelect event.

![image](https://user-images.githubusercontent.com/5804953/129574287-0aa4ff81-d07f-4234-96bb-5bd2dce0d53a.png)

![image](https://user-images.githubusercontent.com/5804953/129574246-b3125147-2a6a-4bd6-a9d5-3901f15817b4.png)

**Comment by pedrobulano** [comment]
Vladimir, thank you for your quick response. But the problem was different. I used a query without tracking entities **items= db. Items.AsNoTracking().Where (...)**. When I removed AsNoTracking (), the problem was resolved.
