### ISSUE TITLE
RadzenDataGrid performs significantly worse when using AdvancedFilterMode

### ISSUE THREAD

**Issue by dmarsh12** [radzenhq/radzen-blazor#198]
**Describe the bug**
RadzenDataGrid renders significantly slower when using AdvancedFilterMode. My enterprise is using Radzen and so far it has been great but the farther along the project we get, the slower the rendering has gotten on each page. One page with 4 cards, 6 data grids (about 5-10 rows in each with columns ranging from 4 to 10) was taking about 4-5 seconds to load but when I switched the RadzenDataGrids filtering to use SimpleFilterMode it now only takes about 1-2 seconds to load.

**To Reproduce**
Sample Project: https://github.com/dmarsh12/RadzenDataGridPerformanceIssue

Please note, I have the page creating 30 data grids simply to show the difference in performance between the two filter modes; real business cases have complex models and rendering logic.

**Expected behavior**
RadzenDataGrid AdvancedFilterMode to have similar rendering performance to "Simple" Filter Mode.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 92.0.902.73 (Official build) (64-bit)

**Additional context**

**Comment by enchev** [comment]
Hey @dmarsh12,

Simple filtering is single TextBox per column while advanced filtering will render complex filter menu for each column with DropDown, DatePickers, etc. components. You cannot expect to have the same render speed and size.
