### ISSUE TITLE
Expected arc flag

### ISSUE THREAD

**Issue by TheRealDroll** [radzenhq/radzen-blazor#200]
I just implement the demo of RadzenDonutSeries in my page.
The graphical representation works perfectly, however, the blazor.server.js throws the following error:

Error: <path> attribute d: Expected arc flag ('0' or '1'), "…82 A 14,125 14,125 0 0 0 36.25 1…".

how can i fix this?

**Comment by akorchev** [comment]
We will need a reproduction in order to act further. Also please follow the issue template.
