### ISSUE TITLE
[RadzenProfileMenu] Open or Close callbacks

### ISSUE THREAD

**Issue by php-wizard** [radzenhq/radzen-blazor#203]
**Is your feature request related to a problem? Please describe.**
RadzenProfileMenu like other components, has a Click handler, but i would need to be notified when the menu dropdown gets opened or gets closed, not just clicked on. Because when it is open the user can close it by just clicking anywhere else on the page, and in this case RadzenProfileMenu won't fire a Click.

**Describe the solution you'd like**
Provide the possibility to set a callback for Open and Close, like for Click

**Describe alternatives you've considered**

Or alternatively a Radzen method i can poll at any time to ask if a RadzenProfileMenu is open or close.  ( I may e.g. handle click events on the whole page, and ask Radzen if the RadzenProfileMenu is open or close at that moment ). 
But this latter solution is dirty, and at this point i can already solve it via a Jquery click handler , which queries the CSS selector matching with the RadzenProfileMenu and check if its `display ` or its ChildContent is `none` ( assuming the markup for RadzenProfileMenu  will never change, although it may change with future updates of Radzen ).

**Comment by enchev** [comment]
We are not planning to add such feature to ProfileMenu component. You can use Popup component instead where such events are available.
