### ISSUE TITLE
DropDownDataGrid popup gets closes when clicking on the sorting icon

### ISSUE THREAD

**Issue by argonNet** [radzenhq/radzen-blazor#208]
**Describe the bug**
In the DropDownDataGrid, when clicking on the sorting icon in a column header, the data grid popup gets closed. This only occurs when clicking on the sorting icon. When clicking on the header blank part or on the text, all works fine. 

**To Reproduce**
1. Go to a DropDownDataGrid control, a simple configure like this is enough to reproduce the bug.
```
<RadzenDropDownDataGrid TValue="string" 
                        FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" 
                        AllowFiltering="true" 
                        AllowClear="true" 
                        Style="width:100%" />

```
2. Click on fields to make the popup appear
3. Click on the header sorting icon to sort a column (the bug appear even if there is no data)
4. See the popup closing. 

**Expected behavior**
Simply sorting the columns like the same way it works when clicking on the header. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Edge Chromium (Version 92.0.902.84), Google Chrome (Version 92.0.4515.159),
 
**Additional context**
- Using Blazor WASM version 5.0.9
- Using Blazor.Radzen version 3.9.7 (also occurred in previous version)

**Comment by enchev** [comment]
The code you've posted is of unbound DropDownDataGrid. I'm unable to reproduce this on our demos:
https://blazor.radzen.com/dropdown-datagrid

**Comment by argonNet** [comment]
Yes but take this code, paste-in a blazor demo project from Visual Studio, and the issue is reproduce.
