### ISSUE TITLE
RadzenGrid - FilterOperator Enum.Parse issue

### ISSUE THREAD

**Issue by dpozimski** [radzenhq/radzen-blazor#209]
**Describe the bug**

**To Reproduce**
1. Create RadzenGrid with filterable column
2. Subscribe to Load callback
3. Try to read FIlters collection from LoadDataArgs object by doing simple .ToList()
4.  If user specified any filter in RadzenGrid the error will occur. `System.ArgumentException: Requested value '!=' was not found.`

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Filters collection from LoadDataArgs can be created.

Problem is here: 
https://github.com/radzenhq/radzen-blazor/blob/b9e992f118a75165fe70a55dfd4b2c2b4b56a124/Radzen.Blazor/RadzenGrid.razor#L841
and here:
https://github.com/radzenhq/radzen-blazor/blob/b9e992f118a75165fe70a55dfd4b2c2b4b56a124/Radzen.Blazor/RadzenGrid.razor#L843

Solution: please make a dictionary of FilterOperators in string representation to the FIlterOperator enum value

**Comment by enchev** [comment]
Hi @dpozimski ,

I'm unable to reproduce such problem on our demo with LoadData: https://blazor.radzen.com/datagrid-loaddata
![image](https://user-images.githubusercontent.com/5804953/131964343-145d44ce-2a66-4094-b8a7-b0db9c7cc5f5.png)
![image](https://user-images.githubusercontent.com/5804953/131964388-ee263885-b5c9-4084-be93-3fbdccff0ad5.png)

Any additional info?

**Comment by dpozimski** [comment]
Yes, the error does not occurs using **RadzenDataGrid**. You need to use **RadzenGrid** to reproduce that in the same way.

**Comment by enchev** [comment]
RadzenGrid is our legacy DataGrid component. Please use RadzenDataGrid instead.
