### ISSUE TITLE
Google material design icons outdated

### ISSUE THREAD

**Issue by benniedejong** [radzenhq/radzen-blazor#212]
The included google material design icon font is a little bit oudated and missing some of the newer icons. Could you please include the latest/newer google material design icon font?

**Comment by yordanov** [comment]
Latest font added with https://github.com/radzenhq/radzen-blazor/commit/07ff46b98e784f84b83612038f9549632d7b246b

**Comment by iNenadnano** [comment]
Could you please update the font again as I am unable to use some of the new icons (for example oil_barrel, propane)?

**Comment by iNenadnano** [comment]
> Latest font added with [07ff46b](https://github.com/radzenhq/radzen-blazor/commit/07ff46b98e784f84b83612038f9549632d7b246b)

Could you please update the font again as I am unable to use some of the new icons (for example oil_barrel, propane)?
