### ISSUE TITLE
FireFox : DropDownDataGrid virtualization doesn't show the full content

### ISSUE THREAD

**Issue by argonNet** [radzenhq/radzen-blazor#218]
**Describe the bug**
On FireFox, the DropDownDataGrid doesn't show all the list.

**To Reproduce**
1. Go to https://blazor.radzen.com/dropdown-datagrid
2. Click on "Virtualization using IQueryable" to open the drop down
3. Scroll down a bit
4. See that the line are empty. Doing the same on Edge (chromium) is OK.

**Expected behavior**
We should see the full content of the DropDown on FireFox

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : FireFox 
 - Version 90.0.2 64bits / 92.0 64bits

**Comment by argonNet** [comment]
Updating my Blazor app to .NET 6.0.100 and using the last version of your nuget package, produce the same issue than describe above in Edge (chromium).

Checking on your app demo, this issue is not there (but is still there from Firefox)
My project is a webassembly project.

**Comment by enchev** [comment]
Will be fixed in our next release early next week, already fixed in the master branch.
