### ISSUE TITLE
HTML Editor bind-value

### ISSUE THREAD

**Issue by DaNeubi** [radzenhq/radzen-blazor#220]
**Describe the bug**
If you want to bind a value to the RadzenHtmlEditor you must use _**@bind-Value**_ not @bind-value with any other component.

**Expected behavior**
Expected yould be bind-value not bind-Value

**Comment by akorchev** [comment]
You are probably mistaking html elements with custom components. Even some of Microsoft's [built-in](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#built-in-form-components) ones use @bind-Value.
