### ISSUE TITLE
Feature Request - Index property on RadzenDataGridColumn

### ISSUE THREAD

**Issue by elylv** [radzenhq/radzen-blazor#221]
We are able to set a RadzenDataGrid to have user-reorderable columns, however there is no facility to apply column ordering programmatically.  A ColumnReordered event is fired whenever a column is moved, but it seems that currently, that produces no useable information other than where the user moved the column.  We can't use this information to rebuild the grid with that column ordering.

I propose an Index property on RadzenDataGridColumn which takes an optional int value which specifies the order in which the column should be displayed.  This could be bound to allow a user's column order preference to be preserved.  The RadzenDataGrid would order the RadzenDataGridColumns by Index before rendering them.  The ColumnReordered event would also update the Index of the column to allow two-way binding.

**Comment by enchev** [comment]
Hey @elylv,

We accept pull requests!

**Comment by brcaswell** [comment]
I have done partial work on this request and I can tell you there are some edge cases.. that will dictate a managed index approach and two-way binding may not be supported. 

Consider the scenario of declaring a static value for an optional `IndexProperty` parameter on the component (that is added from this work).  
  - Reorder/Swap two columns where one is the column that is passed a static value into it's `IndexProperty` -- Should the Index change and/or column actually render differently?
  - If the index value is different from the inferred visible index (suppose 0..n left to right) should the column that has a declared/assigned Index value render before or after a column with the inferred index value?
