### ISSUE TITLE
Inconsistent `Reload` Method Signatures between `DataDropDownGrid` and `PagedDataBoundComponent`

### ISSUE THREAD

**Issue by Mike-E-angelo** [radzenhq/radzen-blazor#226]
**Describe the bug**
The `Reload` method signature for the `RazdenDropDownDataGrid` differs from the one defined in `PagedDataBoundComponent`.

https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenDropDownDataGrid.razor#L224:

```
public void Reload()
```

https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/PagedDataBoundComponent.cs#L79:

```
public async virtual Task Reload()
```

Additionally, the `RazdenDropDownDataGrid` [now calls](https://github.com/radzenhq/radzen-blazor/commit/9184b038b364f4de143fe70b27cc5b812c8c97e8) `GetAwaiter().GetResult()` which can lead to [thread starvation and synchronous deadlocks](https://stackoverflow.com/a/34549714).

**To Reproduce**
NA

**Expected behavior**
Methods signatures are consistent across all controls.  Additionally, Radzen does not lead to deadlocking and/or thread starvation whenever control methods are invoked.

**Screenshots**
NA

**Additional context**
Thank you for any consideration towards addressing this issue. 🙏

**Comment by enchev** [comment]
Hey @Mike-E-angelo,

Changing void to task will be a breaking change, still we can do that however I'm afraid that I don't have other solution for deadlocks. Let me know if you have a better idea.

**Comment by Mike-E-angelo** [comment]
Dare I suggest introducing `RadzenDropDownDataGrid.ReloadAsync`, @enchev? 😇  If breaking changes are a concern, that would be the best course of action IMO.  Then, all major data components would have the same signature for reloading data, but only one would have a different name.  However, none of them would no longer introduce the possibility of deadlocks.  This is, of course, a far better/desired scenario where even one introduces deadlocks.

Additionally, I would `Obsolete` `RadzenDropDownDataGrid.Reload` and point consumers to the new method.

**Comment by enchev** [comment]
As I said are ready to change directly Reload() method to async Task even it is a breaking change however there are other places that still will need GetAwaiter().GetResult(). For example invoke of an async method from property setter.

**Comment by Mike-E-angelo** [comment]
Ah!  I misread your previous statement.  Yes, I would prefer `Task Reload` (without `Async`) so I accept your breaking change and we have shared understanding now. :)

Now, as for your other problem/question.  What I do (and I admit it's a bit kludgy but works) is when the property is assigned, I set a flag/property of some sort that an asynchronous operation must occur.  Then in `OnParametersSetAsync` I subsequently check on that flag/property and perform the asynchronous operation there (or return the task as the result of `OnParametersSetAsync`).

[Here is an example of that](https://github.com/DragonSpark/Framework/blob/projects/Starbeam/DragonSpark.Presentation/Components/Content/ResultingContentView.razor).

You can see [in the `Content` property](https://github.com/DragonSpark/Framework/blob/projects/Starbeam/DragonSpark.Presentation/Components/Content/ResultingContentView.razor#L35-L37) that I set the flag/properties that demark asynchronous activity. I then [create the `Task`](https://github.com/DragonSpark/Framework/blob/projects/Starbeam/DragonSpark.Presentation/Components/Content/ResultingContentView.razor#L67) in `OnParametersSet`, then [return the task](https://github.com/DragonSpark/Framework/blob/projects/Starbeam/DragonSpark.Presentation/Components/Content/ResultingContentView.razor#L71) in `OnParametersSetAsync`.

Upon looking at this now, I could further improve this by setting the `Task` in the `Content` assignment.  The reason why I am doing this is in `OnParametersSet` is that previous versions of `DetermineSubject` also used another property that has since been removed.  The value of that property may or may not have been set by the time the property assignment occurred, and would lead to exceptions.  Moving that to `OnParametersSet/Async` ensured the property was set/available so it is more dependable to do that there.

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/84ec51da54fa6ccaaec09e3940f7515b13f85801

**Comment by Mike-E-angelo** [comment]
Thank you so very much @enchev!  Your efforts here are greatly appreciated. 🙏
