### ISSUE TITLE
Sorting in data grid resets column width

### ISSUE THREAD

**Issue by dantronik-markus** [radzenhq/radzen-blazor#230]
**Describe the bug**
When you change the column width using the separators between the columns and then sort the column by clicking a column header, the column width gets reset to default. IMO It should not do that.

**To Reproduce**
1. Add a data grid with sorting and column resize functionality.
2. Drag one of the column separators and increase the width of the column.
3. Click one of the headers to sort the column.

**Expected behavior**
The column width should not get reset after sorting columns.

**Desktop (please complete the following information):**
 - OS: Windows 10, x64.
 - Browser: Chrome / Edge
 - Version: 94.0.992.31

**Comment by enchev** [comment]
Works normally on our demo: https://blazor.radzen.com/datagrid
![sorting-resize](https://user-images.githubusercontent.com/5804953/134900688-6224c4a1-3441-4258-aa1c-3aaac2ae93e5.gif)
