### ISSUE TITLE
DataGrid custom Column FilterTemplate filter ordering

### ISSUE THREAD

**Issue by DvD12** [radzenhq/radzen-blazor#235]
**Describe the bug**
Using a `RadzenDropDown` to filter enums in a `DataGrid` resets other filters. This is present even in the Blazor sample provided in the documentation examples.

**To Reproduce**
1. Navigate to the sample https://blazor.radzen.com/datagrid-filter-template
2. Filter by ID (for example, 2)
3. Filter by Title of Courtesy (for example, 'Mr.')
The filter is applied, but the ID filter is reset.

**Additional context**
It would be nice to have a way to filter an enum with a dropdown that works out of the box, instead of resorting to having to write a `FilterTemplate` that filters the data collection.

**Comment by enchev** [comment]
Fixed in our latest update
