### ISSUE TITLE
Table support in HtmlEditor

### ISSUE THREAD

**Issue by tesar-tech** [radzenhq/radzen-blazor#24]
**Is your feature request related to a problem? Please describe.**
Table support in htmlEditor is currently missing.

**Describe the solution you'd like**
Adding tables, adding/deleting rows and columns. (e.g. like [ckeditor ](https://ckeditor.com/ckeditor-5/demo/))

![image](https://user-images.githubusercontent.com/33880579/105078489-628a0380-5a8e-11eb-8ea1-7d49016da7cd.png)

**Comment by varoll55** [comment]
super
@

**Comment by varoll55** [comment]
> **Is your feature request related to a problem? Please describe.**
> Table support in htmlEditor is currently missing.
> 
> **Describe the solution you'd like**
> Adding tables, adding/deleting rows and columns. (e.g. like [ckeditor ](https://ckeditor.com/ckeditor-5/demo/))
> 
> ![image](https://user-images.githubusercontent.com/33880579/105078489-628a0380-5a8e-11eb-8ea1-7d49016da7cd.png)

**Comment by NoeInformatica** [comment]
¿Tienen previsto añadir esta opción? A mi me vendría muy bien.
Gracias

**Comment by akorchev** [comment]
We are unlikely to implement table support any time soon as it would require a lot of JavaScript. If you need table support you can try integrating some JS editor.
