### ISSUE TITLE
Moving a slider handle to the left/right does not result in the minimum/maximum value

### ISSUE THREAD

**Issue by PhilippJR** [radzenhq/radzen-blazor#252]
**Describe the bug**
When moving a slider handle to the left, it does mostly not stop at the minimum value.
When moving a slider handle to the right, it does mostly not stop at the maximum value.

**To Reproduce**
1. Go to [slider example page](https://blazor.radzen.com/slider)
2. Move a slider handle to the maximum and see in the log, that it is mostly not 100 but 99 or lower. It is worse when you move the mouse quickly over the right boundary
3. Observe a similar behavior with the minimum

**Expected behavior**
Even when moving the mouse quickly far over the boundary the handle value should be the minimum/maximum.

**Desktop**
OS: Windows 10
Browser: Chrome 94.0.4606.81, Edge 94.0.992.47, Firefox 92.0.1

**Comment by enchev** [comment]
![image](https://user-images.githubusercontent.com/5804953/137128780-8f64694f-18ad-47e4-ae82-e03a0a8820b9.png)
