### ISSUE TITLE
RadzenTreeItem margins

### ISSUE THREAD

**Issue by PatrickKelley2112** [radzenhq/radzen-blazor#260]
**Describe the bug**
The margins on the RadzenTreeItem appear to be wrong. If I change the left margin from 25px to 21px (the width of the caret), then everything seems to line up better.

This is the code changes I made to correct it.
With check boxes:
 `<RadzenCheckBox TValue="bool?" Value="@IsChecked()" Change="@CheckedChange" Style="@(ParentItem != null && !HasChildren ? "margin-left:21px;margin-right:5px;" : "margin-right:5px;")" />`

Without check boxes:
`<span class="rz-treenode-label" Style="@(Tree != null && !Tree.AllowCheckBoxes && ParentItem != null && !HasChildren ? "margin-left:21px;" : "")" >@Text</span>`

**To Reproduce**
1. Create a Tree that has elements with and without children
2. Expand the nodes and take a look at the spacing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tested on Edge, Chrome, and FireFox

**Comment by akorchev** [comment]
Hi @PatrickKelley2112,

Should be better in the latest releases.
