### ISSUE TITLE
RadzenListBox with Cascading Parameter Breaks MultiSelect Items/Checkboxes and Cannot Update Changes

### ISSUE THREAD

**Issue by noAPEX-Group** [radzenhq/radzen-blazor#266]
**Describe the bug**

When using a RadzenListBox with multiselect and cascading parameter for Data, the items/checkboxes are broken and do not capture or highlight changes.
Specifically the CSS classes:

rz-multiselect-item -- does not receive rz-state-highlight
rz-chkbox-box -- does not receive    rz-state-active
rz-chkbox-icon -- does not receive  rzi  rzi-check

The values are then not captured and the RadzenListBox control does not capture changes/values on form submission.

The cascade does work though, as the list items do toggle based on the cascading parameter - you just cannot select or change them, and the form submission does not recognize any updates.

**To Reproduce**
1. Create a RadzenListBox component and use cascading parameter of type IEnumerable<int> with an ICollection<T> for Data
2. Click on any multiselect item - the checkbox/highlighting for rz-multiselect-item does not change or update.
3. When submitting the form changes are not captured.
4. Code below:

`<RadzenListBox class="col-sm-8" AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" Multiple="true" TValue="IEnumerable<int>" @bind-Value=@employeeWarehousesAccesible
Data=@(Warehouses.Where(w => employeeLocationsAccesible.Contains(w.LocationId)))
TextProperty="Name" ValueProperty="Id" Style="height: 200px;" Name="WarehousesAccessible" />`

Alternatively link your repo with a sample project that can be run.

**Expected behavior**

The rz-multiselect-item and checkbox should update and capture value changes to be submitted properly with the form.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version: 95.0.4638.54 (Official Build) (64-bit)
 - Radzen Blazor Version: 3.6.6

**Additional context**

The cascade does work though, as the list items do toggle based on the cascading parameter - you just cannot select or change them, and the form submission does not recognize any updates.

**Comment by enchev** [comment]
Unable to reproduce
