### ISSUE TITLE
Git 2.32.0.windows.2 - Error: Invalid Path

### ISSUE THREAD

**Issue by brcaswell** [radzenhq/radzen-blazor#267]
**Describe the bug**
git error: invalid path

**To Reproduce**
Using git for windows based tooling (git extensions -- in my case), attempt to merge or reset master branch to latest revision.

**Screenshots**
![image](https://user-images.githubusercontent.com/967010/139579560-525b6a94-f4f6-418e-bf02-351662d41e35.png)

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows 10 Professional
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0

**Additional context**
resolved by #264

**Comment by akorchev** [comment]
The problematic file has been deleted.
