### ISSUE TITLE
ContextMenu only opens once in Blazor WASM (PWA)

### ISSUE THREAD

**Issue by janvdpol** [radzenhq/radzen-blazor#27]
**Describe the bug**
In my Blazor WASM PWA project I have implemented the Radzen ContextMenu. When using it, it opens only the very first attempt. Alle later attempts won't open the ContextMenu. It also only works on html elements, not on the RadzenButton for instance.

**To Reproduce**
1. Unzip the attached project
2. Start it (I use CTRL-F5 from Visual Studio)
3. Click in the menu on "Context menu test"
4. Right click on the html button or one of the table rows
5. Right click again on the html button or one of the table rows
6 Refreshing the page makes it work again once
7 Also notice that the ContextMenu will not show when rightclicking on the RadzenButtons

Here is the reproduction project:
[BlazorWASMRadzen.zip](https://github.com/radzenhq/radzen-blazor/files/5847564/BlazorWASMRadzen.zip)

**Expected behavior**
I expected at step 5 that the context menu would open again

**Screenshots**
N.a.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141

**Additional context**
The sourcecode from this github is working on my machine, but that does not meet my requirements for a Blazor WASM PWA

**Comment by Preacher78** [comment]
I'm using contextmenu on my project and I still have this issue.. Any feedback to solve it?

**Comment by janvdpol** [comment]
I stepped away from using contextmenu's since my target is touch devices anyway.
