### ISSUE TITLE
[Feature Proposal] DateRangePicker

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#278]
I think it would be nice to have a date-range picker control.

It could work a standard way: two side by side calendars. The left calendar would be used to pick the 'from' date and the right calendar would be used to pick the 'to' date.

**Comment by Mike-E-angelo** [comment]
Related issue: #304

**Comment by enchev** [comment]
Duplicate to https://github.com/radzenhq/radzen-blazor/issues/157
