### ISSUE TITLE
[Feature Proposal] Query Builder

### ISSUE THREAD

**Issue by gordon-matt** [radzenhq/radzen-blazor#280]
Any plans on adding a query builder?

I've been using this one in non-Blazor apps: https://querybuilder.js.org/

Any just noticed this one from SyncFusion: https://blazor.syncfusion.com/documentation/query-builder/getting-started

Much prefer your components though.. would be great to see a Radzen query builder component.. and if it can optionally be able to be connected / in sync with a DataGrid, that would be even better.. but at least be able to load and save queries.

**Comment by yordanov** [comment]
RadzenDataFilter component is now available -> https://blazor.radzen.com/datafilter
