### ISSUE TITLE
RadzenDatePicker closes popup when change Month or Year

### ISSUE THREAD

**Issue by gagabu** [radzenhq/radzen-blazor#285]
**Describe the bug**
RadzenDatePicker closes dialog when change Month or Year and doesn't not fires ValueChanged event

**To Reproduce**
1. Go to Radzen Blazor Controls demo page https://blazor.radzen.com/datepicker
2. Click on any DatePicker input
3. Click on Month or Year dropdown control
4. DatePicker dialog closes. ValueChanged event not fired.

**Expected behavior**
RadzenDatePicker changes month or year. Dialog is not closed.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome or Firefox
 - Version: latest

**Comment by enchev** [comment]
Fixed with https://github.com/radzenhq/radzen-blazor/commit/8bd9f6cb4a1ab90e7ec4a19183670eb43aa254d8
