### ISSUE TITLE
[BUG] Radzen Pager/Paging is not showing

### ISSUE THREAD

**Issue by yongshun950824** [radzenhq/radzen-blazor#297]
**Forum reference**
https://forum.radzen.com/t/radzen-pager-paging-not-showing/9533

**Bug / Issue**
- Radzen Pager is unable to show.
- Radzen DataList unable to show pager with `AllowPaging="true"`

**To Reproduce**

> Radzen Pager

```
<RadzenPager Count="2" PageSize="10" PageNumbersCount="3" PageChanged="@PageChanged" />
```

> Radzen DataList

```
<RadzenDataList WrapItems="true" AllowPaging="true" Data="@games" TItem="Models.Game.GameDto">
    <Template Context="game">
        <RadzenCard Style="width:300px;">
            <div class="d-flex flex-row align-items-center text-black-50">
                @game.Name
            </div>
            <hr style="border: none; background-color: rgba(0,0,0,.08); height: 1px; margin: 1rem 0;" />
            <div class="row">
            </div>
        </RadzenCard>
    </Template>
</RadzenDataList>
```

**Expected behavior**
Pager component and Pager under Data List is able to be shown.

**Screenshots**
![088293d7e11f369d0ee79998ad1d6a33cdfdcea2_2_1035x262](https://user-images.githubusercontent.com/29250581/143995930-2112cba3-4c47-48a7-9eb5-9aaab34e6a89.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 3.13.2 (Latest)
 - Application: Blazor Server App (.Net 5)

**Additional context**
Noticed that `rz-paginator` was not rendered in HTML.

![25ecee7c707054070e025e76541a939fc6e6ae2b](https://user-images.githubusercontent.com/29250581/143995971-2d5782fb-f1c3-437d-8c7a-3aeca877d11f.png)

**Question**

1. Is it a bug or due to missing any configuration?
2. Is it supported in the free version?
3. Do the Pager component works independently?
[This means I can use my own table/list and plugin with the Pager component, with the `PageChange` event to fire the filtering & paging logic to update my table/list. Without the needs of Radzen DataList.]

**Comment by akorchev** [comment]
Please do not post questions as github issues.
