### ISSUE TITLE
Error in demo Dashboard

### ISSUE THREAD

**Issue by dingetje** [radzenhq/radzen-blazor#30]
**Describe the bug**
Opening the demo Dashboard resulted in the following error:

An error has occurred: Year, Month, and Day parameters describe an un-representable DateTime.. Try reloading your browser.

**To Reproduce**
1. Download the demo project, build and debug
2. Click on 'Dashboard' in the resulting web page in January!
3. See error

**Expected behavior**
Dashboard should collect github issues data from last month.

**Screenshots**
![image](https://user-images.githubusercontent.com/609871/105488076-66e23680-5cb1-11eb-8e63-13729c1fcef4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 64-bit
 - Chrome
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Additional context**
Issue is caused by this line of code in the GitHubService.cs:

    var lastMonth = new DateTime(date.Year, date.Month - 1, 1);

After changing it into:

    var lastMonth = new DateTime(date.Year, date.Month, 1);
    lastMonth = lastMonth.AddMonths(-1);

it worked as expected.

**Comment by akorchev** [comment]
We have changed that some time ago. Are you using the latest version?
https://github.com/radzenhq/radzen-blazor/blob/master/RadzenBlazorDemos/Services/GitHubService.cs#L99

**Comment by dingetje** [comment]
My bad, I downloaded this from a forked repository. Ticket can be closed (although I liked my fix better 😁 )
