### ISSUE TITLE
Improve `RadzenGrid` Filter Controls with `FilterType.Excel`

### ISSUE THREAD

**Issue by Mike-E-angelo** [radzenhq/radzen-blazor#304]
**Is your feature request related to a problem? Please describe.**
The `RadzenGrid` is really well-done, complete with adaptive UI support.  The one area it struggles with is its column filtering controls.  It would be incredibly valuable to have better control and more features around this.

**Describe the solution you'd like**
I have been using both Radzen and Syncfusion grids within my solution.  Syncfusion has great filtering, with an `FilterType.Excel` type that really hits all the sweet spots.  Having something like this in Radzen would save the day.

Here's an example for dates:

![](https://i.imgur.com/9GE0jX9.png)

(FWIW this would also attend to #278)

And enum types:

![](https://i.imgur.com/CWxa4D6.png)

**Describe alternatives you've considered**
Syncfusion, but they do not have the look and feel of Radzen's grid.  Additionally, their adaptive mode is really lacking and a v1 feature.  It was recently only implemented and poorly at that.  Radzen has this in spades (does not even need configuration and "just works") but does not have the filtering.

**Additional context**
Thank you for any consideration you can provide.  FWIW while I do not yet have $599+ annually to purchase a license, I would greatly recommend putting a Sponsor tab on this repository so I and others can throw some support/appreciation your way for features such as this. 🙏

**Comment by akorchev** [comment]
We are no longer adding new features to RadzenGrid. It has been deprecated in favor of RadzenDataGrid.

**Comment by Mike-E-angelo** [comment]
Thank you for the update @akorchev.  If anyone is looking for more detail around this, that can be found here:
https://forum.radzen.com/t/introducing-the-brand-new-radzendatagrid/7842
https://www.radzen.com/blog/new-powerful-blazor-datagrid-component-from-radzen/

FWIW I did check here:
https://blazor.radzen.com/datagrid-advanced-filter

But it appears this operates and contains the same functionality as the previous control.  Please do let me know if I am mistaken here.

As best as I can tell, this feature request still holds for the new control (that is, `RadzenDataGrid`).  I have updated the title/post to reflect this.  Should I open a new ticket or are we able to re-open this one?

Thank you for any consideration.
