### ISSUE TITLE
`RadzenDataGrid` Does Not Have Adaptive UI Like `RadzenGrid`

### ISSUE THREAD

**Issue by Mike-E-angelo** [radzenhq/radzen-blazor#305]
**Describe the bug**
One of the coolest and most valuable features of `RadzenGrid` was that it had a "no nonsense" adaptive UI mode when the document width shrunk to a certain point, showing a mobile-friendly version of the content when hitting the 768px breakpoint.  This no longer appears to be the case with `RadzenDataGrid`.

**To Reproduce**
1. Use a `RadzenGrid` and shrink the document to less than 768px width.  Observe mobile-friendly content.
2. Replace `RadzenGrid` with `RadzenDataGrid` in the control tag.
3. Reload application and shrink the document to less than 768px.  Observe that the grid no longer changes rendering modes.

**Expected behavior**
As the `RadzenGrid` [may be deprecated in the future](https://forum.radzen.com/t/introducing-the-brand-new-radzendatagrid/7842), its replacement should ideally continue the primary and most-valuable features.  In this case, `RadzenDataGrid` should also provide mobile-friendly rendering when the appropriate breakpoint is reached.

**Screenshots**
`RadzenGrid`:
![](https://bit.ly/31wDSqG)

`RadzenDataGrid`:
![](https://i.imgur.com/WnSALMx.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: `Version 96.0.4664.45 (Official Build) (64-bit)`

**Additional context**
I spent some time searching for any obvious properties that would enable expected behavior but had no luck.

**Comment by Matthewsre** [comment]
I started switching over to the new grids and just noticed this unexpected behavior as well. I'll follow this issue to know when we can upgrade our grids since we rely on this capability. Ideally there would be an option to enable/disable this behavior on the new grid.

**Comment by enchev** [comment]
I've just added this to RadzenDataGrid:
https://github.com/radzenhq/radzen-blazor/commit/f2b1e7beccf347194738e6d18633797f870a4b09

**Comment by Mike-E-angelo** [comment]
AWESOME!  Thank you so much for your quick assistance in this matter @enchev!
