### ISSUE TITLE
[RadzenPanelMenuItem] Selected state based on pattern

### ISSUE THREAD

**Issue by MPapst** [radzenhq/radzen-blazor#306]
**Is your feature request related to a problem? Please describe.**
Building a Menu on a Application that offers "types" on the menu and details navigation not on the menu (e.g. having Customers as menu point, but navigating to a Customer with Id `n` in the url) skips the selected state of the menu item when in a sub state.

**Describe the solution you'd like**
Introduce a `PathMatch` Property that takes an enum:
* Full `default`
* Beginning
* Contains (not sure about the use of this)
* End (not sure about the use of this)
* Pattern uses a second new property `PathPattern` with a regex pattern
Based on the `PathMatch` Property the `Selected` of the item is calculated using the Path and the current Uri.

**Describe alternatives you've considered**
Setting the selected state on base of the path using a pattern or similar works but is a lot of effort.

**Additional context**
Please let me know if this would work for you and I will prepare a Pull Request with implementation.

**Comment by akorchev** [comment]
We should better emulate the existing behavior of [NavLink](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Routing/NavLink.cs#L111-L130).

**Comment by akorchev** [comment]
Implemented the NavLink behavior in https://github.com/radzenhq/radzen-blazor/commit/73a3a881caec5f30f7b84916853ca7c91fc8d097
