### ISSUE TITLE
DataGrid not recognizing changes made to associated data

### ISSUE THREAD

**Issue by jcasement** [radzenhq/radzen-blazor#308]
@akorchev When working with the RadzenDataGrid and the CellRender to change the background-color I came across a small issue.
The DataGrid did not recognize the change to the style after the underlying data had changed.
The way I'm coming at this is to trigger a refresh to the underlying data from a Timer every minute.
When the Timer completes, the code compares the previous data to the newly gotten data and uses the CellRender to change the background-color based upon data status changes.
The timer has the "StateHasChanged" which I thought would have caused the DataGrid to refresh but it doesn't.
I can see the CellRender has done its work since when I start to use the DataGrid sorting functionality the background-color appears.
Maybe there is some other way to force the DataGrid to re-render.

**Comment by akorchev** [comment]
Try calling the Reload method of the DataGrid. Also please follow the issue template.

**Comment by jcasement** [comment]
Many thanks
