### ISSUE TITLE
RadzenUpload UploadProgressArgs limiting size of file to 2,14GB

### ISSUE THREAD

**Issue by MarcinGadomski94** [radzenhq/radzen-blazor#310]
**Describe the bug**
The RadzenUpload component allows to only upload files no larger than 2,14GB, since UploadProgressArgs.Loaded and UploadProgressArgs.Total parameters are integers (max 2147483647 bytes). I believe that if somebody wants to use larger files upload, those parameters should have type of long (max 9223372036854775807 bytes / 9223370000 gb).

**To Reproduce**
1. Make sure that you can see expanded exception messages
2. Place RadzenUpload component on your website
3. Create handler for Progress for RadzenUpload that takes in UploadProgressArgs argument
4. Start the website
5. Open console in your browser
6. Try to upload file larger than 2.15GB
7. See error (JSON cannot be parsed....)

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
File would be uploaded without any issues

**Screenshots**
![image](https://user-images.githubusercontent.com/23195048/145399761-319603ca-d0e3-47a2-b6d6-0732fe4e262f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.0.1
 - Browser Safari
 - Version 15.1

**Additional context**
---

**Comment by venetasoft** [comment]
It seems [they have not time to fix this bug](https://forum.radzen.com/t/radzenupload-file-size/10691)...
As Redzen IDE should generate the source code for everything, have you tried to fix it by yourself..? maybe it's only an "int" to "long" edit ;)

**Comment by venetasoft** [comment]
Download the Radzen source code and fix, it's a pair of 'int' to change into 'long'

**Comment by akorchev** [comment]
Should be fixed by https://github.com/radzenhq/radzen-blazor/commit/9493cbc6ff9db389cd139019338afafe7599afec
