### ISSUE TITLE
RadzenPager does not display when only one page of data

### ISSUE THREAD

**Issue by bengavin** [radzenhq/radzen-blazor#319]
**Describe the bug**
RadzenPager does not display if:
- ShowPagingSummary' is true
- AND
- (PageSizeOptions is not specified (or an empty set)
- OR
- Page Count <= 1)

**To Reproduce**
1. Add a RadzenDataGrid component with appropriate data source
2. Set ShowPagingSummary="true"
3. Set PagingSummaryFormat="Matching Records: {2}"
4. Set PageSize to some number >= number of available records
5. Note that paging summary is not displayed

**Expected behavior**
RadzenPager will display paging summary when a format is specified, regardless of whether or not multiple pages of data exist.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 12.x
 - Browser: Brave
 - Version: 1.33.106

**Additional context**
We want to show the total number of records regardless of whether or not there are multiple pages of data, we also do not want the pager control area to 'pop in and out' under filtering/etc that may cause the number of records in the grid to change.  We are unable to use the built-in 'record count selection' capabilities as they do not meet our requirements (10, 20, 50, 100, All) and as such, we can't use the workaround of supplying a 'PageSizeOptions' property value, which also causes the pager to appear.

**Comment by enchev** [comment]
Hey @bengavin,

I'm afraid that this is how the component is designed - to not display the pager if there are not enough items for paging. For sure this behavior can be changed however it should be optional and the default option should be the current state, otherwise it will be breaking change. We accept pull requests.
