### ISSUE TITLE
Drag and drop sortable components

### ISSUE THREAD

**Issue by krispenner** [radzenhq/radzen-blazor#32]
Browsing through your site I don't see any kind of sortable component via drag and drop. We currently use [Sortable.js](https://github.com/SortableJS/Sortable) in another project and would like the same functionality in Blazor. I have yet to find any obvious components that support this out of the box. Just curious if you provide anything like this or would consider adding it?

**Comment by enchev** [comment]
Hey @krispenner,

There is no such component part of Radzen Blazor components - please use the template for feature requests in the future.
