### ISSUE TITLE
Radzen DropDown: User is Able to Select Options without being Presented the DropDown List

### ISSUE THREAD

**Issue by monseiurmystere** [radzenhq/radzen-blazor#325]
## Bug

When a user focuses on a RadzenDropDown control, they are able to select options without being presented the options when Multiple="true" on the control itself. 

### Environment: 
- Operating System: **Windows 10 \(Version 1809+\) **
- Browser: **Microsoft Edge**
  - Version: **97.0.1072.55 \(Stable Channel\)**
- .NET Runtime Information: **v6.0.101** 

### How to Reproduce:

> Pre-requisite: The RadzenDropDown control needs to have the argument ```Multiple="true"``` & The Action is reproduced on Keyboard Solely. 

- Focus on the RadzenDropDown by navigating to it using the ```Tab``` key. 
- Press the ```ArrowUp``` or ```ArrowDown``` key while the DropDown is focused, and then to press ```Space``` which would then implicitly select a value \(since the list has not been expanded to the user\). 
  - If the user repeatedly performs this action, they should be able to see the amount of selected items increase by means of the placeholder text stating how many items have been selected. 

## Expected Behaviour:

When the user navigates to the control using the ```Tab``` key, the DropDown should expand _onFocus_.

> Alternative Solution: Add the Method into the DropDownBase for Developers to manually expand the DropDown so that they can control this event, should they need to bind anything to this event.

**Comment by enchev** [comment]
No longer reproducible
