### ISSUE TITLE
RadzenGoogleMap and marker clustering

### ISSUE THREAD

**Issue by rodsmr** [radzenhq/radzen-blazor#327]
**Is your feature request related to a problem? Please describe.**
I use [Blazor GoogleMap](https://www.radzen.com/documentation/blazor/googlemap/). In my use case, I've got a lot of marker in same point (very similar latitude and/or longitude). I read in Google documentation the functionality call [marker clustering](https://developers.google.com/maps/documentation/javascript/marker-clustering) to group nearest markers

**Describe the solution you'd like**
Is the a way to implement the functionality call marker clustering?

**Additional context**
My case
![image](https://user-images.githubusercontent.com/17640209/148801171-d03ff9dd-36f3-45f3-8d5a-87ecf46d2d5b.png)

Desiderata
![image](https://user-images.githubusercontent.com/17640209/148801254-8c83bb6f-8113-4c77-86e9-474f9885da84.png)

**Comment by ThatCoolCoder** [comment]
It would be great in general to get more google maps features available in the Radzen map.

**Comment by enchev** [comment]
Marker clustering can be enabled externally using the Google Map API. Check this thread for reference:
https://forum.radzen.com/t/radzengooglemap-marker-clustering/18812/3
