### ISSUE TITLE
Radzen DropDown: Collection Disappears After HTTP Call and Filter Not Cleared

### ISSUE THREAD

**Issue by pacpoc41** [radzenhq/radzen-blazor#328]
## Description
The Radzen DropDown has an error where the component itself goes into a state where the contained collection disappears from rendering in the filter, after an HTTP Call. 

#### Steps to reproduce the behavior:
- In a Form, Navigate to a ```<RadzenDropDown AllowFilter="true" AllowClear="true" Multiple="true"/>```.
- Type into the Filter. 
![image](https://user-images.githubusercontent.com/97504897/148914464-8e7d966f-4fa0-4576-82e3-5dc294734293.png)
- Use an HTTP Call to perform the necessary function.
- Open the Filter.
![image](https://user-images.githubusercontent.com/97504897/148915388-c351d516-ab4a-4e6e-99cb-50e53e009f07.png)
  - The collection has now disappeared. However, when the Filter predicate has changes the collection is re-rendered.
![image](https://user-images.githubusercontent.com/97504897/148915665-3cacd324-7cd2-4a9d-9f99-2cfb0d679f2f.png)

## Expected Behavior
The collection to be filtered needs to be in view of the user at all times. 

## Environment
 - OS: Windows 10 \(v1809+\)
 - Browser: Microsoft Edge v 97.0.1072.55

**Comment by enchev** [comment]
Hey @pacpoc41,

I'm afraid that I don't understand what is HTTP Call nor how to reproduce such issue from screenshots. Feel free to use our forum to describe your case and to look for help.
