### ISSUE TITLE
Lazy loading of components if webassembly profile

### ISSUE THREAD

**Issue by e-norm-repo** [radzenhq/radzen-blazor#33]
**Is your feature request related to a problem? Please describe.**
The download size of the components is 255KB `Radzen.Blazor.dll`. This is no issue with server side rendering, but adds to bandwidth with stand alone webassembly Blazor clients.

**Describe the solution you'd like**
Relevant Radzen Blazor components lazy loaded when page is displayed.

**Describe alternatives you've considered**
No other alternative yet.

**Additional context**
The following description about [lazy loading](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0) by Microsoft.

**Comment by akorchev** [comment]
I don't think lazy loading applies to component libraries. Not sure how this can be implemented here.

**Comment by e-norm-repo** [comment]
Okay, thank you!
