### ISSUE TITLE
DataGrid GroupFooter displays in wrong column

### ISSUE THREAD

**Issue by Sindol36** [radzenhq/radzen-blazor#330]
**Describe the bug**
Datagrid places the GroupFooter in the wrong column when combining expandable rows with a grouping column. 

**To Reproduce**
1. Create a datagrid, ensure it has AllowGrouping="true"
2. Create a Template for the datagrid (triggering expandable behavior, requires no content)
3. Add a datagrid column and give it a GroupFooterTemplate.
4. Add a second datagrid column, ensure Groupable="true".
5. Run the blazor app, navigate to the datagrid page.
6. Group by dragging the groupable column title to the datagrid header.
7. The GroupFooter is placed in the wrong column.

**Expected behavior**
Expectation is that the GroupFooter is placed in the column (RadzenDataGridColumn) for which the corresponding GroupFooterTemplate it was specified.

**Screenshots**
![groupfooter_displaced](https://user-images.githubusercontent.com/95098764/149015249-4834a8e3-3c84-49cc-a496-ae5b12819469.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: Firefox (96.0)
 - Version 3.14.1

**Additional context**
Seems related, but not exactly duplicate of https://github.com/radzenhq/radzen-blazor/issues/271#issue-1049761293

**Comment by enchev** [comment]
Tried to replicate the problem using grouping for master grid by ShipCountry and FooterTemplate for OrderID column however worked properly: https://blazor.radzen.com/master-detail-hierarchy

![image](https://user-images.githubusercontent.com/5804953/149092339-2158ab53-e0f6-483f-8f62-3990a59b4bd2.png)

![image](https://user-images.githubusercontent.com/5804953/149092288-a5626356-7db7-413f-ac9e-bf95ad1eb181.png)

**Comment by Sindol36** [comment]
Thanks for your attention. Your screenshots show that a FooterTemplate works correctly. I can confirm it does, since I use it elsewhere in my application. That is however not the problem I described and is (as far as I can tell without diving into the code) completely unrelated to the bug I reported. 

If you take the above code, add a Template to the datagrid (or otherwise force the rows to be expandable), and add a **GroupFooterTemplate** instead of, or in addition to a FooterTemplate, then you should see the problem.
