### ISSUE TITLE
Radzen DropDown: Can't view previous selections when using keyboard to select

### ISSUE THREAD

**Issue by pacpoc41** [radzenhq/radzen-blazor#331]
**Describe the bug**
If you use the keyboard to select items in the search dropdown you are unable to then view the selections you have made

**To Reproduce**
With RazdenDropDown <RadzenDropDown AllowFilter="true" AllowClear="true" Multiple="true"/>

Type a search into the search area which returns results:
 
![image](https://user-images.githubusercontent.com/97504897/149057202-fd83de1f-9b57-416c-85b5-eb1ecde14397.png)

then use the keyboard to make a selection in this dropdown (by using the arrows and pressing space to select)
NB: The search area will have a space appended to the end when you make the selection:
 
![image](https://user-images.githubusercontent.com/97504897/149057236-bb578786-b788-424d-bd56-14981737306f.png)

Now click away from the dropdown, then expand the dropdown to try and see what selections are currently selected:
 
![image](https://user-images.githubusercontent.com/97504897/149057255-41dd207b-92f2-4f4a-a078-d11f5c789c8c.png)

You are unable to see what selections have been made.

**Expected behavior**
You should be able to see the previous items that have been selected in the dropdown

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 96.0.4664.110 (Official Build) (64-bit)

**Comment by enchev** [comment]
I'm unable to reproduce this on our demo with multiple selection: https://blazor.radzen.com/dropdown
