### ISSUE TITLE
1. Direct Export functionality to CSV and excel 2. the given code (under northwindexportservice) does not include conditional formatting specially rowspan

### ISSUE THREAD

**Issue by samqadir** [radzenhq/radzen-blazor#336]
Hi Team, we are facing issues in implementing below 3 functionalities.

1. How to export all the pages of the grid?Need to export all pages and also include conditional formatting like increasing row span. There is no in-build functionality so far in Radzen , like in Telerik, etc.

2. Consider conditional formatting like increasing row span for records. I have 45 columns in my grid and row span is applied on the first 24 columns based on the 25th column. For example, the first 3 rows of the first 24 columns is merged for first 3 records in 25th column. So when I should export the - > 2nd and 3rd row for first 24 columns, the cells should be blank and instead 2nd row should not start directly from the 25th column but the rows until 24th column should be merged with the above row and 25th column data should start from 25th column and not from 1st column in the exported CSV and Excel file.

**Comment by enchev** [comment]
Hey @samqadir 

You can use our forum to ask questions.

**Comment by samqadir** [comment]
Hi @enchev  : Raised 2 questions in forum :

https://forum.radzen.com/t/no-direct-export-functionality-to-csv-and-excel-how-to-use-and-customise-northwind-service-to-directly-download-the-contents-of-the-entire-grid-without-using-controller/9909

https://forum.radzen.com/t/conditional-formatting-is-breaking/9908
