### ISSUE TITLE
Cannot read property 'removeChild' of null on ContextMenu usage while navigating away to a page which has other PageLayout

### ISSUE THREAD

**Issue by janvdpol** [radzenhq/radzen-blazor#34]
**Describe the bug**
When using a ContextMenu on a regular button (maybe also on RadzenButton, did not test) I'm getting an error when navigating away to a Page where PageLayout is set to a minimal page layout (for printing)

**To Reproduce**
1. Unzip attached project [BlazorPrintCSSwithRadzen.zip](https://github.com/radzenhq/radzen-blazor/files/5869395/BlazorPrintCSSwithRadzen.zip)
2. Press CTRL-F5 (from Visual Studio)
3. Rightclick on first button to see that contextmenu navigation is working to default Counter page
4. Rightclick on second button to see that contextmenu navigation is **NOT** working to default print page

**Expected behavior**
Contextmenu always working while navigating away to print page

**Screenshots**
n.a.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.104

**Additional context**
Full error saved from Chrome Developer tools
[localhost-1611605562122.log](https://github.com/radzenhq/radzen-blazor/files/5869399/localhost-1611605562122.log)

**Comment by enchev** [comment]
The only option I can suggest you is to use `navMgr.NavigateTo("/print", true);` when navigating to this page.
