### ISSUE TITLE
https://forum.radzen.com/ Can't Signup with Github

### ISSUE THREAD

**Issue by groogiam** [radzenhq/radzen-blazor#345]
**Describe the bug**
I'm not sure if this is the correct place to log this but I cannot create a login to the forums with using Github. Clicking the sign up with github takes me directly to this screen.

![image](https://user-images.githubusercontent.com/1992395/150684709-f2fe3295-057b-4758-be60-a12bf9f824cc.png)

**To Reproduce**
1. Go to https://forum.radzen.com/
2. Click Signup
3. Click With GitHub button

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Should be able to login and create an account with GitHub

**Screenshots**
See above.

**Desktop (please complete the following information):**
<html>
<body>

Google Chrome | 97.0.4692.71 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H1 (Build 19043.1466)

</body>
</html>

**Additional context**
If there is another place to log this then please let me know. Thanks.

**Comment by enchev** [comment]
Hey @groogiam,

Please use our GitHub issues strictly for reporting problems with Radzen.Blazor components.
