### ISSUE TITLE
DataGrid Simple Filter layout issue with Default Theme

### ISSUE THREAD

**Issue by Matthewsre** [radzenhq/radzen-blazor#362]
**Describe the bug**
RadzenDataGrid with Simple Filter and Default Theme has layout issues for string and DateTime fields:

**To Reproduce**
1. Go to 'https://blazor.radzen.com/datagrid-filter-template'
2. Change the theme to "Default These"
3. "Id" column header styling is not aligned correctly

**Expected behavior**
Styling and layout should be consistent for the filters.

**Screenshots**
![image](https://user-images.githubusercontent.com/2955659/152588799-3c17a9d8-5feb-429b-9c55-e8bba8f7b0e6.png)

**Additional context**
This is also displaying incorrectly for DateTime Values and I am trying to narrow down an issue where DateTime filters are no longer closing when clicking "Apply", "Clear", or clicking outside of the filter.

**Comment by enchev** [comment]
Fixed with https://github.com/radzenhq/radzen-blazor/commit/adee1531906cacf062ef4457163bdf1684cf3bed
