### ISSUE TITLE
DataGrid issue with adding new row

### ISSUE THREAD

**Issue by s-dezign** [radzenhq/radzen-blazor#364]
In DataGrid when you filter out all data and nothing found row showing up. In this case if you will try to add new row, it will never show up. This is only happens in nothing found case.

**To Reproduce**
1. Open page with DataGrid
2. Apply a filter on one of the columns so nothing will be found
3. Try to add new record (row)
4. See that new row didn't appear

**Expected behavior**
New row should show up instead of nothing found

**Comment by enchev** [comment]
I'm unable to reproduce this on our demo: https://blazor.radzen.com/datagrid-inline-edit
![image](https://user-images.githubusercontent.com/5804953/152935003-2f5c2cb2-a376-4506-ac28-fbfb54030699.png)

**Comment by s-dezign** [comment]
@enchev 
You are unable to reproduce it because in that demo example it is not using LoadData method callback. 
This bug only exist when you are using LoadData.
Here is example setup: 

```
<RadzenDataGrid
    @ref="@Grid"
    Style="height: calc(100vh - 149px)"
    AllowFiltering="true"
    FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
    AllowColumnResize="true"
    FilterMode="FilterMode.Advanced"
    AllowPaging="true"
    PageSizeOptions="@PageSizeOptions"
    PageSize="@DefaultPageSize"
    AllowSorting="true"
    IsLoading="@IsLoading"
    LoadData="@LoadData"
    Data="@Data"
    Count="@Count"
    RowCreate="@AddRow"
    RowUpdate="@UpdateRow"
    TItem="IdrdPeriodViewModel"
    EditMode="DataGridEditMode.Multiple"
    LogicalFilterOperator="LogicalFilterOperator.And">
```

**Comment by ballad95** [comment]
In the demo: https://blazor.radzen.com/datagrid-inline-edit
When I create a new row and click on any sort tab, that row disappears (In my real case, although it does appear in the database and when I press F5)

**Comment by yoguill** [comment]
i confirm i have the same bug, i cant add a new line when i use the loaddata event when my datagrid have no data
