### ISSUE TITLE
Upload (Blazor)

### ISSUE THREAD

**Issue by 08128888y** [radzenhq/radzen-blazor#37]
**Describe the bug**
Upload often fails(CSV)

**To Reproduce**

**Expected behavior**
It doesn't fail every time, but sometimes it fails
Also, I don't know if it's related, but the [Controller] has made two requests, and the first time [IFromFile] is null.
When the file upload fails, UploadCompleteEventArgs.RawResponse in the [Completed] event is "empty".

**Screenshots**
![image](https://user-images.githubusercontent.com/69555810/106247459-e7290e80-6252-11eb-8cdf-2ab5ca7d2b63.png)

**Desktop (please complete the following information):**
 >> Server Centos7 client:Windows10
 >>chrome,Edge,IE11
 
**Additional context**

**Comment by akorchev** [comment]
I am afraid we can't do anything without an actual reproduction of the problem.
