### ISSUE TITLE
[DataGrid] Frozen Columns or Columns without a Title, should not be in Columnpicker

### ISSUE THREAD

**Issue by vertonghenb** [radzenhq/radzen-blazor#371]
If you deselect a Frozen columns the styling is broken, but actually a Frozen column should never be able to be deselected in the ColumnPicker.
![image](https://user-images.githubusercontent.com/10981553/153579252-1bff0c71-dac1-4f47-b76d-42c456a0fd49.png)

When it's a DataGrid with selection
![image](https://user-images.githubusercontent.com/10981553/153579625-3d1ed9fc-0eab-4db5-b55c-c63208b058de.png)

**Expected behavior**
Frozen Columns or Columns without a Title should never be in the ColumnPicker.

**Comment by enchev** [comment]
I'm unable to reproduce this broken styling:
![image](https://user-images.githubusercontent.com/5804953/153826343-8dd5955e-eddf-4980-ad1c-d32f01a067c7.png)
![image](https://user-images.githubusercontent.com/5804953/153826302-033b08e9-e136-4c92-bafb-1311a4e0bd23.png)

Not sure why frozen columns should not be part of the picker, maybe if there is case where the styling is broken we should simply fix it. Excluding also columns without titles from the picker in my opinion is not correct, maybe we can add property similar to Sortable, Reorderable, etc.:
https://github.com/radzenhq/radzen-blazor/commit/1c3f87165e15340208d4366759947dcefd35112c
