### ISSUE TITLE
Class NotificationMessage documentation is not useful

### ISSUE THREAD

**Issue by dxrdxr** [radzenhq/radzen-blazor#372]
**Describe the bug**
The descriptions of the class `NotificationMessage` properties are not very useful.

See [Class NotificationMessage](https://blazor.radzen.com/docs/api/Radzen.NotificationMessage.html)

**To Reproduce**
Read the documentation:
1. Detail: Nothing describes what the detail is, presumably the primary text message.
2. Duration: There are no units specified, it is a double, but is it milliseconds, seconds, minutes, days? It really ought to be a TimeSpan!
3. Style: What is the form of the style? CSS? Other?
4. Summary: How is this different than the Detail? Is it different location? Is it a title?

**Comment by enchev** [comment]
Hey @dxrdxr,

We accept pull requests!
