### ISSUE TITLE
RadzenDataGrid.Data Virtualization documentation doesn't specify its required initial null value

### ISSUE THREAD

**Issue by dxrdxr** [radzenhq/radzen-blazor#391]
If the initial value of the Data parameter in a DataGrid is not `null`, no data will be displayed.

This requirement is not documented anywhere nor commented in any of the samples. I discovered this while writing an app that was using `#nullable enable` . This [pattern ](https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/) recommends that reference type variables never be set to `null`. Visual Studio will issue warnings if a non-nullable reference type is not initialized.  This took quite a bit of time to determine the problem in my code was incorrect initialization.

**To Reproduce**
Modify RadzenBlazorDemos `DataGridVirtualizationLoadDataPage.razor`  to have:
```
    IEnumerable<OrderDetail> orderDetails = Enumerable.Empty<OrderDetail>();
```
Load the page and notice it is empty.

**Root cause**
In `PagedDataBoundComponent.OnAfterRenderAsync` has the following logic:
```
    if (firstRender && Visible && (LoadData.HasDelegate && Data == null))
    {
        InvokeAsync(Reload);
        StateHasChanged();
    }
```
Internally this causes the `Count` to be zero and when `LoadItems` is called the `totalItemsCount` to be zero and ultimately the `Microsoft.AspNetCore.Components.Web.Virtualization` engine thinks that the page is empty even though `virtualDataItems` is not zero.

**To fix**
In various parts of the documentation such as [here](https://blazor.radzen.com/docs/guides/components/datagrid.html#virtualization) and [here](https://blazor.radzen.com/docs/api/Radzen.PagedDataBoundComponent-1.html#Radzen_PagedDataBoundComponent_1_Data) text should be added that `Data` must be initialized to null before the first rendering of the component.

Alternative fix would be to change the semantics where the many places where it checks `Data == null` to be `Data == null || Data.Count() == 0`.

**Comment by neizvesno** [comment]
I have the same problem

**Comment by RobertoPeters** [comment]
It doesn't have to be empty. But if you use virtualization, you should (or could?) resuse the same colelction.
So,
orderDetails.Clear();
orderDetails.AddRange(new data);
grid.Reload();

that worked for me.

**Comment by AndrewBoklashko** [comment]
@enchev I see same issue. Given the following code, grid is loaded empty even though `items` has non-empty list assigned when `OnLoad` is finished. On the other hand if I initialize `items` with `null` instead of `Enumerable.Empty` then grid rows are displayed just fine.

``` C#
<RadzenDataGrid
    Data="items"
    Count="totalItems"
    AllowVirtualization="true"
    LoadData="OnLoad"
    TItem="MyDto">
...
</RadzenDataGrid>

IEnumerable<MyDto> items = Enumerable.Empty<MyDto>();
int totalItems = 0;

async Task OnLoad(LoadDataArgs args)
{
    var model = await _service.LoadGridData();
    items = model.Items;
    totalItems = model.TotalItems;
}
```
