### ISSUE TITLE
[Missing documentation] : Dialog service is necessary for RadzenHtmlEditor

### ISSUE THREAD

**Issue by tesar-tech** [radzenhq/radzen-blazor#40]
**Describe the bug**
Using `RadzenHtmlEditor` without configured dialog service results in error ` Unhandled exception rendering component: Cannot provide a value for property 'DialogService' on type 'Radzen.Blazor.RadzenHtmlEditorLink'. There is no registered service of type 'Radzen.DialogService'.`

It is **not** mentioned in [documentation ](https://www.radzen.com/documentation/blazor/htmleditor/)or in [sample page](https://blazor.radzen.com/html-editor).

**To Reproduce**
1. Add `RadzenHtmlEditor`
2. Run app

**Expected behavior**
it should be mentioned in docs.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context** 
To make it work use `builder.Services.AddScoped<DialogService>();` in `Program.cs`

**Comment by akorchev** [comment]
Thanks! We will add this to the documentation.
