### ISSUE TITLE
Expose EditContext on RadzenTemplateForm 

### ISSUE THREAD

**Issue by TheManDK** [radzenhq/radzen-blazor#408]
**Is your feature request related to a problem? Please describe.**
I cannot programatically trigger a validation on `RadzenTemplateForm`

**Describe the solution you'd like**
I would like to have the `EditContext` exposed

**Describe alternatives you've considered**
Somehow I would like to trigger a validation

**Additional context**
I would like to have two buttons for one form. One to save a draft and one to send the contents for approval. In both cases the validation should run, but the business logic behind is of course different.

**Comment by akorchev** [comment]
[It is already public](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenTemplateForm.cs#L231).
