### ISSUE TITLE
Gave up

### ISSUE THREAD

**Issue by jackbond** [radzenhq/radzen-blazor#41]
Spent 15 minutes trying to get this to work and gave up? Why?

Started here... https://razor.radzen.com/get-started

Right off the bat, I'll note, where is the minimal downloadable solution that has performed all these steps? Doesn't exist, OK, not an auspicious start. Step 1 - 5 could provide some additional helpful details, but step 6 is a gem...

`Open the Shared/MainLayout.razor file and include <RadzenDialog/>, <RadzenNotification/>, <RadzenContextMenu/> and <RadzenTooltip/>`

Include them where? I eventually found this...

https://github.com/radzenhq/radzen-blazor/blob/master/RadzenBlazorDemos/Shared/MainLayout.razor

Kind of gave me an idea, but there's so much other stuff there, i.e. RadzenHeader, that's it not clear where you should just include them.

But Ok, take a guess, include them at the top. Now I'm ready to drop a control onto a page. Let's take RadzenGrid. Bind it to a List and run...

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'Radzen.adjustDataGridHeader' ('Radzen' was undefined).
      Error: Could not find 'Radzen.adjustDataGridHeader' ('Radzen' was undefined).
```

Please take the default Blazor project, add the ABSOLUTE MINIMUM bootstrap code to get a control running, and upload it somewhere.

**Comment by akorchev** [comment]
The listed steps are the minimum requirement. Nothing else to do about that.

**Comment by jackbond** [comment]
So why did following the listed steps not allow a RadzenGrid to work?

And if it is, prove it. Literally just upload the minimal solution somewhere.

Finally, if this is your level of support, there's no effing way ANYONE should waste their time with your software.

**Comment by akorchev** [comment]
There is some misunderstanding. We do not provide support in github issues and have mentioned that in the issue template which you have chosen not to follow.
