### ISSUE TITLE
Line chart, hide lines by default

### ISSUE THREAD

**Issue by Ikantek** [radzenhq/radzen-blazor#416]
**Is your feature request related to a problem? Please describe.**
Yes, it is. What I want to achive is to hide some lines by default in the line chart and make them "crossed" in the legend. I didn't find any property/method to invoke programatically.

**Describe the solution you'd like**
I'd like to have an option to set some property on the chart to turn off visibility of line on the chart, but still have it on the legend.

**Describe alternatives you've considered**
I did not consider other alternatives.

**Additional context**
There is a topic on your forum with clear example what i'd like to achive: https://forum.radzen.com/t/line-chart-hide-lines-by-default/10548

**Comment by akorchev** [comment]
Implemented by https://github.com/radzenhq/radzen-blazor/commit/3594c81b175201afb129f78af035815ac4db89c4
