### ISSUE TITLE
Wrong border color of tooltip on RadzenAreaSeries and RadzenLineSeries

### ISSUE THREAD

**Issue by eharbitz** [radzenhq/radzen-blazor#417]
**Describe the bug**

When using `RadzenAreaSeries` or `RadzenLineSeries` with custom `Fill` and `Stroke`, the tooltip border color does not match the series color.

**To Reproduce**
1. Create a `RadzenChart`
2. Add a `RadzenAreaChart` where the property `Fill` and `Stroke` is set to some arbitrary color
3. Hover over the chart.
4. Notice how the border color for the tooltip does not match the color of the series in the chart.

**Expected behavior**
When using `Fill` or `Stroke`, the color of the tooltip border should be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/15960296/161998075-50e1bc80-0183-4dda-850b-63d3b86c8516.png)

![image](https://user-images.githubusercontent.com/15960296/161998300-7cf0403a-1e5f-42c2-ad79-333039a55f68.png)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
In the screenshots it might at first glance look like the color is just flipped with the other series. That is not the case. That is two different shades of green for the series and the tooltip border.

**Comment by akorchev** [comment]
This is currently supported only for the Pie series. We will make it use Fill for AreaSeries and Stroke for LineSeries.

**Comment by eharbitz** [comment]
Thanks for the fast fixes :) We really appreciate the Radzen charts.

You probably know it already, but I just noticed this is also and issue for the column charts
![image](https://user-images.githubusercontent.com/15960296/162383929-6f9089bc-dc02-410d-a2b4-ead111b6a1c6.png)
