### ISSUE TITLE
Handle inline javascript for Content Security Policy

### ISSUE THREAD

**Issue by Magnus76** [radzenhq/radzen-blazor#42]
Some components use inline javascript, for example RadzenUpload uses onchange property on input to execute javascript. For the browser not to block this action you would need to set Content Security Policy to "script-src 'unsafe-inline'" which is bad security practice.

There are two ways of doing this:

1. Move inline javascript to separate file whenever is possible (Radzen.Blazor.js) (see [this post](https://stackoverflow.com/questions/60046827/how-to-bind-events-such-as-onchange-in-razor-views-without-violating-csp))
2. If 1. is not possible, set all inline javascript in script-blocks with nonce attribute, using the same Radzen Blazor-nonce across all inline script blocks (see [this post](https://stackoverflow.com/questions/42922784/what-s-the-purpose-of-the-html-nonce-attribute-for-script-and-style-elements))

**Comment by enchev** [comment]
The code is already moved:
https://github.com/radzenhq/radzen-blazor/commit/55b539a3e36774e430ac0cb16108387fc40c6ae9
