### ISSUE TITLE
RadzenDataGrid. Allow saving user settings in Column Picking.

### ISSUE THREAD

**Issue by emiliosanchis** [radzenhq/radzen-blazor#422]
**Is your feature request related to a problem? Please describe.**
The AllowColumnPicking property allows you to show or hide columns in a DataGrid, however it is not possible to know when the user makes the change. 

**Describe the solution you'd like**
A CallBack would be necessary to be able to save the user's preferred configuration.

**Describe alternatives you've considered**

**Additional context**

**Comment by enchev** [comment]
Column picking works with Visible property of the column. Check this thread to for reference how to get current visible columns:
https://forum.radzen.com/t/datagrid-visible-columns-binding/10465

**Comment by emiliosanchis** [comment]
What I want to know is the moment when the value of visible changes so that I can save it as a user option.
If the column picker had an event of the type OnVisibleChanged we could know if the user has modified the visible columns.
