### ISSUE TITLE
Feature request: could RadzenDataGridColumn.GetFilterValue() be public?

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#424]
When using RadzenDataGrid with LoadData I have a need to provide a custom filter into the composed query.
To do so I would like to enumerate via columns and read the filter values.

Would it be possible to make following methods in RadzenDataGridColumn public?
GetFilterValue(), GetSecondFilterValue(), GetFilterOperator and GetSecondFilterOperator()

**Comment by enchev** [comment]
You can use Filters and Sorts properties of LoadDataArgs to get what you want.
