### ISSUE TITLE
Icons are displayed distorted

### ISSUE THREAD

**Issue by karuzzo** [radzenhq/radzen-blazor#428]
Icons are displayed distorted
![image](https://user-images.githubusercontent.com/18124355/163474324-3f61d89d-4d0f-4a26-9c7b-f6384bed4a3f.png)
Probably better to add some other set of icons

**Comment by akorchev** [comment]
The icons definitely don't look like that for me.
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/454726/163519537-fcb5da5c-9e59-400c-8440-f7f0903132dc.png">
Do you have the material icons font installed on your machine? Or maybe some non-default font rendering settings?

> Probably better to add some other set of icons

You can use any icon font in your application. You have to change the definition of the .rzi font-name. We don't plan to ship other icon fonts in the near future.

**Comment by karuzzo** [comment]
My windows is fresh out of the box and doesn't have non-standard fonts I guess. Do I understand correctly that on a site using radzen components, i need to issue a notification that additional fonts need to be installed first?

**Comment by akorchev** [comment]
> My windows is fresh out of the box and doesn't have non-standard fonts I guess.
Here is how it looks on a fresh windows 11 machine in Edge:

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/454726/163522662-2d8ecaf6-abfc-442b-b6ed-dd238524f325.png">

How does the material icons font look like on [their own page](https://fonts.google.com/icons)? 

>  Do I understand correctly that on a site using radzen components, i need to issue a notification that additional fonts need to be installed first?

No. However a locally installed font takes precedence over the one served with the Radzen Blazor theme.

**Comment by karuzzo** [comment]
On the Google page they look correct
![image](https://user-images.githubusercontent.com/18124355/163523323-d1bda2ba-18c3-43ab-bc79-ca1b545c00a5.png)

**Comment by yordanov** [comment]
Hey @karuzzo, the icons on the google page still look pixelated on your screenshot. They are just bigger (40px font size) compared to the 20/24px icons on the radzen demo page (depending on the theme applied). Could you confirm that the icons look correct at 20px or 24px font-size on the google page? You can change the font size via DevTools in Chrome or DOM inspector `F12` in Internet Explorer / Edge. 

<img width="742" alt="image" src="https://user-images.githubusercontent.com/1118895/163541539-bce24787-c5f8-42a3-a18b-ab3f053f0a0b.png">


It's a known vector scaling down problem with vector icons/fonts on devices with low pixel density/resolution screens, which is not trivial to solve. There are similar issues filed in the material icons repo suggesting some workarounds you can have a look at https://github.com/google/material-design-icons/issues/648 and https://github.com/google/material-design-icons/issues/679

**Comment by karuzzo** [comment]
Thanks a lot, it really helped
