### ISSUE TITLE
Dropdown children remount still occurs when Data objects change reference (Related to #419)

### ISSUE THREAD

**Issue by PeteJobi** [radzenhq/radzen-blazor#429]
**Describe the bug**
This is a follow up to #419. When an item in a dropdown is selected, all the items in the children are remounted. What I forgot to mention is that this doesn't happen if the ```Data``` parameter does not change, and I should have included this is the Steps to Reproduce.
In my case, I'm using the ```RadzenListBox``` within a "wrapper" of my own. This wrapper component accepts an ```IEnumerable<T>``` parameter, and within the component in ```OnParameterSet```, I map the ```IEnumerable<T>``` to a different type ```IEnumerable<U>``` which is then passed into ```RadzenListBox```.

Something like this is done (```List``` is a Parameter passed to the wrapper and ```modelList``` is passed to ```RadzenListBox```):
```
protected override async Task OnParametersSetAsync(){
       int i = 0
       modelList = List.Select(m =>
            {
                var item = new ListBoxModel<TValue> { Index = i, Object = m };
                i++;
                return item;
            }).ToList()
}
```
In essence, the objects in ```modelList``` always changes. And when that happens, Items are remounted.

**Additional context**
I proposed a change some days ago which was merged
```
builder.SetKey(PropertyAccess.GetItemOrValueFromProperty(item, ValueProperty));
```

But it was later changed to
```
builder.SetKey(GetKey(item));

internal object GetKey(object item)
        {
            var value = PropertyAccess.GetItemOrValueFromProperty(item, ValueProperty);

            if (!keys.Contains(value))
            {
                keys.Add(value);
                return value;
            }
            else
            {
                return item;
            }
        }
```

This doesn't really change much. ```value``` is only used once, and afterwards, ```item``` is always used.
You were probably trying to address some concerns, but I'm not sure what they are. Maybe you can shed some light on why the first fix won't do.

**To Reproduce**
The steps to reproduce are the same as in #419, but instead of binding ```Data``` directly to customers, perform a mapping like below:
```
<RadzenListBox @bind-Value=@value Data=@GetCustomers()...

protected IEnumerable<Customer> GetCustomers(){
        return customers.Select(o => new Customer
            {
                Address = o.Address,
                City = o.City,
                CompanyName = o.CompanyName,
                ContactName = o.ContactName,
                ContactTitle = o.ContactTitle,
                Country = o.Country,
                CustomerCustomerDemos = o.CustomerCustomerDemos,
                CustomerID = o.CustomerID,
                Fax = o.Fax,
                Orders = o.Orders,
                Phone = o.Phone,
                PostalCode = o.PostalCode,
                Region = o.Region
            }).ToList();
    }
```

Selecting a child item (or clicking anything outside the ListBox that changes state) will cause ```OnInitialized``` to be called for all items.

**Expected behavior**
I expect that once the children of a ```RadzenListBox``` are mounted, they are never remounted again no matter what as long as the ```RadzenListBox``` isn't itself remounted.

**Comment by enchev** [comment]
I'm afraid that we will unable to support this.
