### ISSUE TITLE
RadzenDataGrid Group Row Collapse/Expanse Issue When Initially Collapsed

### ISSUE THREAD

**Issue by Jerry239** [radzenhq/radzen-blazor#430]
**Describe the bug**
Prerequisite: GroupFootersAlwaysVisible="true" for RadzenDataGrid
When all groups in a DataGrid are initially collapsed (through GroupRowRender Event, args.Expanded = false), all groups will be expanded when the user expands one group and collapses it again. Afterwards, the expand/collapse feature works as expected.

**To Reproduce**
The issue can easily be reproduced with the RadzenBlazorDemos project
1. Edit DataGridGroupingApiPage.razor:
- Add GroupFootersAlwaysVisible="true" to RadzenDataGrid
- It is not necessary to add group footer templates for the bug to show
- Edit OnGroupRowRender event handler to collapse all groups on first render:
Line 67ff: if (args.FirstRender)
        {
            args.Expanded = false;  
        } 
- Start demo and navigate to /datagrid-grouping-api
- All groups should be collapsed now
- Expand any group
- Now collapse that group again
-> All groups are expanding now. Only the group selected for collapsing is closed.

**Expected behavior**
Only the selected group should collapse. No other groups should expand

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19044.1645]
 - Browser: Chrome 100.0.4896.88
 - Radzen 3.18.3

**Comment by djuchems** [comment]
Thanks for creating this issue, we have exactly the same problem. Initial collapsing via _OnGroupRowRender_ and _GroupFootersAlwaysVisible=true_ leads to this malfunction when collapsing and expanding groups afterwards.

**Comment by daletman** [comment]
The Bug is fixed but in this exact scenario the first click after a freshly loaded page on the expand arrow of a collapsed group is ignored. The second click works just fine.
