### ISSUE TITLE
Radzen Button Css not working

### ISSUE THREAD

**Issue by serkanaslan34** [radzenhq/radzen-blazor#436]
Hi,
Im using .Net 6 and im applying Turkish Culture like this.
`services.Configure<RequestLocalizationOptions>(options =>
            {
                var supportedCultures = new[]
                {
                    new CultureInfo("tr"),
                    new CultureInfo("tr-TR"),
                };
                options.DefaultRequestCulture = new RequestCulture(culture: "tr-TR", uiCulture: "tr-TR");
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });
`
After that when I use Radzen Info button, button's css class is not working because of  this you are making Enum button type to string with ToLower() after that class name is  "btn-ınfo"

This is html output.
`<button type="button" class="rz-button rz-button-md btn-ınfo m-1">
                    <i class="rz-button-icon-left rzi">info</i>
                    <span class="rz-button-text">1</span>
    </button>`

![button](https://user-images.githubusercontent.com/104346434/165040242-403611dc-acd8-48d5-a834-66493e45ab36.png)

**Comment by akorchev** [comment]
Good catch!

**Comment by akorchev** [comment]
Should be fixed by https://github.com/radzenhq/radzen-blazor/commit/6cb5f738d4d86b49083337bdc6c66b04f305bdc5

**Comment by serkanaslan34** [comment]
Thanks for the quick fix and quick reply!
