### ISSUE TITLE
Add setup instructions, contributing guidelines to the repository

### ISSUE THREAD

**Issue by RyanMarcotte** [radzenhq/radzen-blazor#44]
First off, thanks for making the components open source!  Can setup instructions (for building the solution locally) and contributing guidelines be added to the repo?

**Comment by akorchev** [comment]
Hi @RyanMarcotte ,

Are there any setup instructions needed? The projects should build as they are from Visual Studio or command line (via `dotnet build`). 

We are not so experienced with open source yet and are not sure what to add for contributing guidelines. Any tips?

**Comment by RyanMarcotte** [comment]
I was getting a different error yesterday (related to the `webcompiler` tool I think), but this is the error that currently comes back after a clean and rebuild in Visual Studio:
![image](https://user-images.githubusercontent.com/1458084/107662650-1f1b5300-6c50-11eb-9a1f-18f6d2169fbd.png)

I'll keep playing around with it...  As an example, if a `webcompiler` tool needs to be installed in order for the solution to build, that is something I would expect to see in setup instructions.

As for contributing guidelines, various templates exist.  GitHub [has instructions](https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) on how to set these up (templates are linked at the bottom of those instructions).

**Comment by akorchev** [comment]
The tool should install automatically - we are ensuring that in the csproj itself.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/454726/107667248-10f12500-6c98-11eb-8ff4-967b6ee63afc.png">

The webcompiler tool itself sometimes reports errors about locked files. Those are usually resolved with another rebuild. Other than that there shouldn't be any installation instructions and or build requirements.

We will add some contribution guidelines at some point. Still trying to figure out what information to list there. Maybe just copy the content from the issue template ...
