### ISSUE TITLE
Behaviour of RadzenStepsItem vs RadzenTabsItem

### ISSUE THREAD

**Issue by sofiageo** [radzenhq/radzen-blazor#441]
**Describe the bug**

I believe there is a difference in how these two components behave and and I'm trying to see if it's possible to have a Tab that works similar to how a Step is working in Radzen with Blazor WASM.

I've deployed a demo with the different behaviour I'm seeing at https://vermillion-torte-82404c.netlify.app

I will explain the issues I see in the following paragraphs. I'm using browser console to log when methods are called for each step / tab, so you will need to have browser tools open to see the behaviour of the components.

1) Parameters that are passed from a parent -> child -> grandchild will render differently for each component used. When I'm changing a **complex** parameter inside Parent -> Step, it will update instantly, as seen in Step3 of the example. When I'm changing a **complex** parameter inside a Parent -> Step -> Tab I will need to also call InvokeAsync callback of the parameter, as seen in Step2 of the example. In Step1 where I don't call InvokeAsync the values will only update after I select tab2 then select tab1 again. 

2) The when methods OnInitialized and OnParametersSet are going to be called is different for each component. When I click on a Step component, it will always call OnInitialized so I can calculate stuff I need just once before the render happens. But when tabs are selected, it will always call OnParametersSet for tabs that have a **complex** parameter, even if they are not selected. OnInitialized will never be called when selecting a Tab. The difference is visible in Step4 of the example, where only the selected Steps methods are called.

Code is available here: https://github.com/sofiageo/BlazorWasm - in directory Pages/Example1

**Expected behavior**
I'm not sure if it's the expected behaviour, but for my use case it would be ideal if I could run stuff on the OnInitialized method for the tabs that are selected, and OnParametersSet would not run if the tab is not selected.

**Comment by enchev** [comment]
Hi @sofiageo,

I'm afraid that this is how Blazor component will work - that's the lifecycle. 
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0
