### ISSUE TITLE
Easier multiple selection of rows in data grid component with LSHIFT

### ISSUE THREAD

**Issue by diskman** [radzenhq/radzen-blazor#442]
**Is your feature request related to a problem? Please describe.**
There is a problem on selection multiple rows. For example to select the first seven rows I need to click 7 times the checkbox. I cannot just hold LSHIFT and click first and last row to select in two clicks multiple rows.

**Describe the solution you'd like**
Using a combination of LSHIFT and and left mouse button it should be possible to choose range of rows with less clicks.

**Describe alternatives you've considered**
Not sure if any other ways are possible - sometimes it is not possible to just filter data that could be selected by select all checkbox in header.

**Additional context**

**Comment by enchev** [comment]
An example implementation can be found here:
https://forum.radzen.com/t/using-shift-click-to-select-multiple-datagrid-rows/10650/6?u=enchev
