### ISSUE TITLE
RadzenPanelMenu - Child Menu Padding or Margin Feature

### ISSUE THREAD

**Issue by serkanaslan34** [radzenhq/radzen-blazor#444]
Hello,
I am using RadzenPanelMenu and I have child menus. But the main menus and child menus remain in the same vertical line. Can you add margin or padding for childmenus?
![childmenu](https://user-images.githubusercontent.com/104346434/165828500-d83b216d-219f-4ab4-b975-3d2a70619c2c.png)

**Comment by MPapst** [comment]
You can do that on your own by adding some CSS, that is overriding the margin of Child Items.

**Comment by serkanaslan34** [comment]
Yes, I did, unfortunately I mixed up the components.

**Comment by serkanaslan34** [comment]
Thanks @MPapst
