### ISSUE TITLE
Get the selected columns from AllowColumnPicking property

### ISSUE THREAD

**Issue by lgund** [radzenhq/radzen-blazor#446]
**Is your feature request related to a problem? Please describe.**
It´s importent for my project that I can get the selected columns from the dropdown menu via `AllowColumnPicking` property.

**Describe the solution you'd like**
It would be nice to get the property of the visible elements of type T

**Comment by enchev** [comment]
These are all visible columns https://forum.radzen.com/t/datagrid-visible-columns-binding/10465/2
