### ISSUE TITLE
DataGrid InLine Editing - no delete after insert

### ISSUE THREAD

**Issue by ajhopen** [radzenhq/radzen-blazor#447]
Thought it was my code but the **DeleteRow** method in the [official example here](https://blazor.radzen.com/datagrid-inline-edit) does nothing if you try to delete immediately after adding a row.  I put some comments in my code to confirm nothing was happening.  Is there any tips on getting this to work?  

    async Task DeleteRow(Order order)
    {
        if (order == orderToInsert)
        {
            orderToInsert = null;
        }

        if (orders.Contains(order))
        {
            dbContext.Remove<Order>(order);

            // For demo purposes only
            orders.Remove(order);

            // For production
            //dbContext.SaveChanges();

            await ordersGrid.Reload();
        }
        else
        {
            ordersGrid.CancelEditRow(order);
        }
    }

**Comment by akorchev** [comment]
I replied to the your forum thread. We can continue the discussion there.
