### ISSUE TITLE
Context Menu on demo site does not function

### ISSUE THREAD

**Issue by oppknox** [radzenhq/radzen-blazor#45]
**Describe the bug**
On click with either of the three buttons no context menu displays regardless of browser.
https://blazor.radzen.com/contextmenu

**To Reproduce**
1. Go to 'https://blazor.radzen.com/contextmenu'
2. Click on 'show context menu.'
3. Nothing occurs

**Screenshots**
![image](https://user-images.githubusercontent.com/34199047/107602549-cd86b000-6bde-11eb-8daf-a992a6e681aa.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser [e.g. chrome, safari] Chrome, Brave, Edge

**Comment by akorchev** [comment]
Works as expected with all tested browsers (the context menu shows on right click):

<img width="950" alt="image" src="https://user-images.githubusercontent.com/454726/107608820-b9c26480-6c45-11eb-9a35-263960498a83.png">

**Comment by tesar-tech** [comment]
Oh. @oppknox did you try to click with right mouse button? Because that was exactly what I was doing wrong (clicking left) when I tried for the first time...

**Comment by oppknox** [comment]
I did and of course it works. Feels kinda dumb, but is a good learning opportunity. Thank you
