### ISSUE TITLE
Please make RadzenDataGridColumn.GetValue method as virtual 

### ISSUE THREAD

**Issue by oschakravarthi** [radzenhq/radzen-blazor#451]
Hi,

Please make RadzenDataGridColumn.GetValue method as virtual. 
I have a very special case. My entities have properties with names having spaces and dots. They are auto generated types with Reflection.Emit. With such properties, the grid is not working.

If the above method is made virtual, I can inherit a class from  RadzenDataGridColumn and implement my own GetValue functionality.

We are completely blocked on this. Please do the needful

**Comment by akorchev** [comment]
We would accept a pull request.
