### ISSUE TITLE
Allow the Enter key to apply advanced filter changes

### ISSUE THREAD

**Issue by sbIsaacHorvath** [radzenhq/radzen-blazor#453]
**Is your feature request related to a problem? Please describe.**
Several coworkers and I like to navigate our web pages by keyboard, and the DataGrid Advanced Filter does not have a quick way to apply the inputted changes by keystroke.

**Describe the solution you'd like**
When an Advanced Filter dialog is open on a DataGrid component, and the focus is on any input field, pressing Enter should apply the changes you've inputted (same as clicking the `Apply` button). It may be a good idea also to implement a dialog close on Escape (same as clicking outside the dialog).

**Describe alternatives you've considered**
I may be able to use a Simple Filter in my case, at least for now, but ideally I would like to not use the ability to logically combine multiple filters or do more complicated comparisons.

**Comment by akorchev** [comment]
Should be implemented in recent versions. Check it online [here](https://blazor.radzen.com/datagrid-advanced-filter).
