### ISSUE TITLE
RadzenDropDown examples incorrect for object binding in 3.18.8

### ISSUE THREAD

**Issue by burtonr** [radzenhq/radzen-blazor#454]
**Describe the bug**

Copying the DropDown examples for binding to an object do not trigger the `Change` callback, or update the selected value using Radzen 3.18.8

**To Reproduce**

1. Import or update the `Radzen.Blazor` library with version `3.18.8`
2. Copy an example dropdown block from [Radzen DropDown Examples](https://blazor.radzen.com/dropdown)
3. Create a `Customer` class (based on the usage in the examples)
```
public class Customer 
{
    public int CustomerId { get; set; };
    public string CompanyName { get; set; };
}
```
4. Run the app
5. Click the dropdown and make a change. 
6. Observe that the collapsed dropdown does notshow the value selected
7. Observe the console output that the output was not written
8. Click the dropdown again, and see the selected value gets updated (but still no Change event console output)

Alternatively link your repo with a sample project that can be run.

I can put together a small repo to show the issue if needed.

**Expected behavior**
Update the examples to use the proper binding values

Here is a simplified working example of binding a dropdown to an object collection:

```
<RadzenDropDown TValue="Customer" Data=@customers
                        TextProperty="Customer.CompanyName" ValueProperty="Customer"
                        Change=@CustomerChanged />
```

Specifically, the values used for `TValue`, `TextProperty`, and `ValueProperty`

**Screenshots**
I can produce screenshots if needed

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Firefox, Chrome
 - Version [e.g. 22] 22.04

**Additional context**
 
Please know that **I am aware that the examples are functioning on the Radzen website**
However, they do not function with the latest version of the library

**Comment by enchev** [comment]
Our website is using the latest version of the library.

**Comment by akorchev** [comment]
```<RadzenDropDown TValue="Customer" Data=@customers
                        TextProperty="Customer.CompanyName" ValueProperty="Customer"
                        Change=@CustomerChanged />```

I think you don't need to set ValueProperty in this case when TValue is set to Customer.
