### ISSUE TITLE
DataGrid not show all columns

### ISSUE THREAD

**Issue by Xeddon** [radzenhq/radzen-blazor#46]
See https://blazor.radzen.com/datagrid

![grafik](https://user-images.githubusercontent.com/34571845/107673085-ed2cdf80-6c95-11eb-9f28-f39dadf77f3d.png)

In the sample code there are more columns starts from HireDate, Address, City...Notes.
Can reproduce it on own code.

**Comment by akorchev** [comment]
There is a scrollbar which allows you to see all columns.
![grid-scrolling](https://user-images.githubusercontent.com/454726/107674164-59601100-6c9f-11eb-8c7b-eadb75fc4623.gif)
