### ISSUE TITLE
Exception throw when open Confirm Dialog

### ISSUE THREAD

**Issue by atolucky6** [radzenhq/radzen-blazor#461]
**Describe the bug**
The exception throw while opening Confirm Dialog via DialogService.
The exception is System.NotSupportedException: 'Serialization and deserialization of 'System.Type' instances are not supported. Path: $.ChildContent.Method.ReturnParameter.Member.DeclaringType.'

You should add JsonIgnore attribute to ChildContent property of DialogOption class.

**Comment by enchev** [comment]
The provided information is not enough to reproduce the exception
