### ISSUE TITLE
blazor.radzen.com doesn't force HTTPS.

### ISSUE THREAD

**Issue by ThatFlashCat** [radzenhq/radzen-blazor#47]
**Describe the bug**
The demo website at https://blazor.radzen.com/ allows https to be disabled.

**To Reproduce**
Edit the address bar, remove https:// and press enter. The site will load over http.

Additionally, the websockets connection will also be unecrypted:
![image](https://user-images.githubusercontent.com/26885142/107721425-3a16b300-6ca2-11eb-98b7-fe94e1711c7e.png)

Clicking on the Source button of a demo window will result in an error due to the insecure connection:
![image](https://user-images.githubusercontent.com/26885142/107721513-70ecc900-6ca2-11eb-93b8-462758dd9dfc.png)

**Expected behavior**
The server should be served over https.

**Comment by enchev** [comment]
Should be ok now.
