### ISSUE TITLE
Find Component on your site is broken

### ISSUE THREAD

**Issue by dougclutter** [radzenhq/radzen-blazor#470]
**Describe the bug**
Using the **Find component...** filter on the [https://blazor.radzen.com/get-started](https://blazor.radzen.com/get-started) page breaks the menu after clearing the filter options.

**To Reproduce**
1. Go to [https://blazor.radzen.com/get-started](https://blazor.radzen.com/get-started)
2. Click on **Find component...** control
3. Enter some text such as "Progress".  The menu is filtered as expected.
4. Click on the 'X' in the **Find component...** control
5. The menu is *not* returned to its original state.  For example, the *Overview* item now shows a drop-down icon.

**Expected behavior**
The menu should be returned to its original state.

**Screenshots**
Original menu:
![image](https://user-images.githubusercontent.com/12717532/169699909-17c85f1c-57bf-4028-9cf0-3a31c7a24c96.png)

Menu after entering "Progress" in the **Find component...** control:
![image](https://user-images.githubusercontent.com/12717532/169700182-012505d7-c6d7-4ea0-b94a-94616bc6111f.png)

Menu *after* the 'X' in the **Find component...** control has been clicked:
![image](https://user-images.githubusercontent.com/12717532/169700067-a71ba459-5259-468c-8455-cbea51ff32fb.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge 
 - Version 101.0.1210.47 (Official build) (64-bit)

**Additional context**
N/A

**Comment by dougclutter** [comment]
Hi @enchev - why did you close this?  The issue I described still exists.

**Comment by knoxyz** [comment]
Hello,
this bug occurs also with Chrome 101 again.
