### ISSUE TITLE
Feature Request: Optimized rendering for initially collapsed groups in data grid.

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#473]
Currently, in case of grouping the data grid rendering runs in two iterations:

1. All lines are rendered and displayed without grouping.
2. Data grid re-renders and displays lines with expanded or collapsed groups.

(As also visible in the demo: [https://blazor.radzen.com/datagrid-grouping-api](https://blazor.radzen.com/datagrid-grouping-api))

Now, if I understand correctly, the grouping does not work together with the virtualization. And using the grouping together with the paging is restricted only to the active page (which is not very practical if data goes across multiple pages).

So in case the data contains several thousands of items the rendering of all lines causes a significant performance degradation.

However, in many scenarios the performance could be improved if there is a possibility to specify a group shall be initially collapsed and the data grid would render it collapsed in one iteration.

Would it be possible to consider such improvement? Or do you have some other plans for this issue?

**Comment by akorchev** [comment]
There is now a property which displays all groups collapsed by default. Demonstrated in the [grouping API demo](https://blazor.radzen.com/datagrid-grouping-api).
