### ISSUE TITLE
SplitButton in menu element

### ISSUE THREAD

**Issue by denhaandrei** [radzenhq/radzen-blazor#479]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the following component:
https://blazor.radzen.com/menu
but I want to use in the menu something like SplitButton(if the user clicks on the tile him goes to the path if clicks on the arrow open the menu with items)

https://blazor.radzen.com/menu
**Describe the solution you'd like**
Create control RadzenMenuSplitItem based on RadzenMenuItem where clicking on the arrow does not redirect to the path

**Describe alternatives you've considered**
I'm trying to add the following component:
https://blazor.radzen.com/splitbutton
but it has a different design and when I go to the mobile view this Splitbutton goes out from the menu

**Additional context**
Example of code:
```
@inject NavigationManager NavigationManager

<RadzenMenu>
    <RadzenMenuItem Text="Home" Icon="home" Path="home"></RadzenMenuItem>
    <RadzenMenuItem Text="Menu Item" Icon="home" Path="path1">
        <RadzenMenuItem Text="Create data" Path="path2"></RadzenMenuItem>
    </RadzenMenuItem>
    <RadzenSplitButton Click=@(args => OnClick(args, "path1")) Text="SplitButton" Icon="home">
        <ChildContent>
            <RadzenSplitButtonItem Text="Create data" Value="path2" />
        </ChildContent>
    </RadzenSplitButton>
</RadzenMenu>

@code {
    void OnClick(RadzenSplitButtonItem button, string path)
    {
        NavigationManager.NavigateTo(button?.Value ?? path);
    }
}
```
View:
<img src="https://user-images.githubusercontent.com/13841559/172047982-b5acd4a8-f93f-4be2-a7cf-750cadb1e8b3.jpg" width="600">
Mobile view:
<img src="https://user-images.githubusercontent.com/13841559/172047984-084dde0d-5287-4d8d-9a22-10ccebbb838a.jpg" width="600">

**Comment by enchev** [comment]
Hey @denhaandrei,

We don't have plans to support such feature - both components are too different.

**Comment by denhaandrei** [comment]
Describe the solution you'd like
Create control RadzenMenuSplitItem based on **RadzenMenuItem** where clicking on the arrow does not redirect to the path

may not have seen
