### ISSUE TITLE
[Feature request] Add support for Blazor Hybrid apps with MAUI

### ISSUE THREAD

**Issue by vgb1993** [radzenhq/radzen-blazor#480]
**Is your feature request related to a poblem? Please describe.**

As a user of Radzen Studio I would like to create Blazor Hybrid apps with .NET MAUI.
Also, I would like to target multiple project types at the same time. Ex: Server & Hybrid.

**Describe the solution you'd like**

Appart from WebAssebly and Server a third option should be added for Blazor Hybrid apps.

**Describe alternatives you've considered**

I have not considered any alternatives

**Additional context**

In my opinion, the components generated by the designer should be located in a .NET library, not in the main project itself. This would make it possible to import the library from multiple aplication types at the same time. 

This change would have an interesting side effect: I would be able to import this library in existing projects.

Blazor Hybrid really is a game changer for .NET, this would be a very usefull feature!

**Comment by enchev** [comment]
Hey @vgb1993,

Thanks for your suggestion however this repo is for our free Blazor components. For Radzen Blazor Studio you can use this repository: https://github.com/radzenhq/radzen-next/

**Comment by vgb1993** [comment]
My bad, thanks
