### ISSUE TITLE
Blazor 6.0 Radzen DataGrid not able to access System.Collections

### ISSUE THREAD

**Issue by rowana16** [radzenhq/radzen-blazor#489]
Posted it here first: 
https://stackoverflow.com/questions/72607979/blazor-6-0-radzen-datagrid-not-able-to-access-system-collections

I'm simply retrieving some data from the database on initialization and trying to display it in a grid.
Just refuses to allow a List / IEnumerable to be used.
**Error: The type name 'Collections' does not exist in the type 'System'**
![image](https://user-images.githubusercontent.com/19420223/173429702-44cca7d9-38ca-407a-a151-dd3d50e6f409.png)

**Comment by akorchev** [comment]
This looks as a usage question more suited for our forum rather than an issue with the component.
