### ISSUE TITLE
Wrong Tooltip displayed on mouse hover for Line Chart

### ISSUE THREAD

**Issue by SenuinLentar** [radzenhq/radzen-blazor#497]
Hello,
I have a problem with the tooltips of a line chart. The displayed tooltip does not correspond to the point hovered.
It is most visible between distant point in chart with irregular point intervals.

I have recreated the bug in this repository : https://github.com/SenuinLentar/RadzenTooltipProblem.git

Here are a few screens (the yellow points represents the mouse position) :
![image](https://user-images.githubusercontent.com/23256428/174321947-94710ba0-fcfb-48e0-815d-e55e3664ace9.png)
![image](https://user-images.githubusercontent.com/23256428/174322024-990ee3f6-a441-446c-89c2-d58580b4ed3c.png)
![image](https://user-images.githubusercontent.com/23256428/174322172-30c2049c-cd33-4b85-a7e0-034166178445.png)

To have the correct tooltip displayed, it is needed to search around which is not pleasant.
Is there a way to recalibrate the tooltips ?

Thanks in advance, have great day !

[Windows, chrome]

**Comment by akorchev** [comment]
Can you update the demo not to use Random data? I see that there is an issue in some cases but can't debug it because the data changes every time.

**Comment by SenuinLentar** [comment]
Hi, thanks for your reply, I updated the repo using static data. You can check it out

**Comment by akorchev** [comment]
Thanks! Should be fixed by f5fa061

**Comment by SenuinLentar** [comment]
Thank you very much :)
