### ISSUE TITLE
ColorPicker, Cursor from color Slider not working correctly (WASM)

### ISSUE THREAD

**Issue by rblanca** [radzenhq/radzen-blazor#50]
**Describe the bug**
The cursor on the color slider doesn't move...the color change but the cursor is always on the initial position (on the left side of the slider)

**To Reproduce**
1. Create a ColorPicker component
2. Try to pick a color using the Color Slider
3. See that the cursor doesn't move but the color change

**Expected behavior**
The cursor position should move as you pick the color

**Screenshots**
![image](https://user-images.githubusercontent.com/37780410/108082173-8cfcbb80-7050-11eb-89eb-e0ad497eff54.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 88.0.705.68
 - Version: 3.0.10

**Additional context**
On version 2.18.XX it was working good.

**Comment by akorchev** [comment]
Seems to work ok here: https://blazor.radzen.com/colorpicker. Does that demo work for you?

**Comment by rblanca** [comment]
Yes demo works great with every browser...but on 2 of my projects it doesn't...it's strange on Firefox both projects works great too but in Edge and Chrome it doesn't...don't know why (I'm already cleared cache too)...Well i'll continue investigating this...
