### ISSUE TITLE
Chart Feature : option to use DateTime as axis without hours

### ISSUE THREAD

**Issue by SenuinLentar** [radzenhq/radzen-blazor#502]
Hello,
I found out that the chart points are strangelly aligned with the grid when using DateTime as axis.
After further research, it appears that, when no hours components are given, the point is positionned at 00:00.
This behaviour is a bit confusing when I use only dates (without hours).

I understand that this behaviour is correct when using hours, but would it be possible to create an option to use Date only and fix the point on the grid ?

![image](https://user-images.githubusercontent.com/23256428/174828623-622a627a-1b04-4b71-8b83-39f8574335cc.png)

Here is a repo to a test project (don't mind the name, I reused it) :
https://github.com/SenuinLentar/RadzenTooltipProblem.git

In this repo, I used some Date with 23:59 and 12:00 to show the offset to Dates without hours.

I hope I was clear with my explanations, feel free to ask further questions if I'm not.

[Windows, Chrome]

**Comment by akorchev** [comment]
I would recommend to use strings instead of dates in this case. Check our online demo for an example.

**Comment by akorchev** [comment]
Also check #490

**Comment by SenuinLentar** [comment]
Thank you, I'll check these.
