### ISSUE TITLE
Faster graph loading in Blazor Server

### ISSUE THREAD

**Issue by eharbitz** [radzenhq/radzen-blazor#503]
**Is your feature request related to a problem? Please describe.**
When using RadzenAreaSeries with a lot of data, the loading can be very slow when the data changes.

**Describe the solution you'd like**
We have figured out a way to make the graph update significantly faster when the data bound to the parameters in the graphs components change. By unmounting (removing it from the DOM) and then initializing the graph component with the new data, it refreshes much faster than just updating the data directly.

No idea why it is like this, but I assume that it is possible to significantly improve the re-render time when data is updated for Blazor Server.

**Additional context**
Previously submitted a similar feature request (https://github.com/radzenhq/radzen-blazor/issues/418), but we wanted to let you know that we might have a possible solution for this.

Thanks for making a great library :)

**Comment by akorchev** [comment]
Unmounting and remounting seems too drastic. It shouldn't be needed.
