### ISSUE TITLE
DataGrid filter behaviour changed in 3.19.0 : in FilterMode.Simple grid only shows rows that are equal to the entered text

### ISSUE THREAD

**Issue by AndreZinner** [radzenhq/radzen-blazor#504]
in version 3.18.x the normal behaviour for a DataGrid in FilterMode.Simple was:
rows are displayed, if the text entered by the user **is contained** within the value of the property of the corresponding column.

in version 3.19.0 (and later) the text entered by the user must be **equal** to make the row appear in the resulting list.

Is there any new property introduced to the datagrid hat I can set, to get back the old behaviour?
(which is of course the normal way a user expects a column filtering  feature)

**Comment by enchev** [comment]
Everything works normally on our demo:
![image](https://user-images.githubusercontent.com/5804953/176221842-e38e5de5-4155-42b6-beca-5afa9e0e4386.png)

**Comment by AndreZinner** [comment]
Yes, on your demo it does.

But in my app the behaviour changes as soon as I go from 3.18.x to 3.19.0. (without any further changes!).

When I use FilterMode.SimpleWithMenu I can observe, that in 3.18.x the default filter condition is "CONTAINS".
When I use 3.19.0 the grid and it is displayed on page loading for a fraction of a second I can see  "*A*" (=filter condion "contains")  on the filter button. Then the condition changes to  "="  (= filter condition "is equal").

So you definitly changed some defaults, probably by introducing the enum filter.

**Comment by AndreZinner** [comment]
Further information: the column the working as expected when I set FilterOperator="FilterOperator.Contains".
So I suppose that this was the default in 3.18.x. 
(But it is of course very anoying when I must add that to all my columns in all my grid ....)

And in 3.19.x (at least for some value types) the default changed to FilterOperator.Equals.
