### ISSUE TITLE
Version 3.19.2 isn't published

### ISSUE THREAD

**Issue by chrgraefe** [radzenhq/radzen-blazor#507]
**Describe the bug**
Version 3.19.2 was commited and pushed, but not published on nuget.
Maybe there ist a tag missing.

**To Reproduce**

**Comment by akorchev** [comment]
There isn't such version or tag (yet).

**Comment by chrgraefe** [comment]
I meant this.
![image](https://user-images.githubusercontent.com/4922897/176859421-cddef47c-24e9-486e-8731-858fd0193b64.png)

**Comment by akorchev** [comment]
This version is released and there is a tag for it. 3.19.2 does not exist yet.
