### ISSUE TITLE
Scheduler Day/Week Appointments Viewed as Overlapping when Not

### ISSUE THREAD

**Issue by maarkkushere** [radzenhq/radzen-blazor#508]
When one appointment starts at the same time another ends, they act as if they are overlapping if the time is not a slot boundary. If it is a slot boundary, everything works fine.
![Capture](https://user-images.githubusercontent.com/98479389/176923391-38eb635d-0106-4123-93f7-2b3337a7820d.PNG)

As you can see, with "Skype call" ending at 1pm and "Dentist appointment" starting at 1pm, there is no issue. With "Test overlap 1" ending at 3:15 and "Test overlap 2" starting at 3:15, they display differently like when an overlap happens. This happens with the default slot minutes of 30. If I change the slot minutes to 15, then this example works also (although there are other issues as noted in other posts that you are working on with changing slot minutes). Seems to happen when the appointments touch at non-slot boundaries if that makes sense.

**Comment by akorchev** [comment]
Should work now.

**Comment by maarkkushere** [comment]
Awesome!  Thank you!
