### ISSUE TITLE
RadzenDataGrid IsNull to check for empty strings as well.

### ISSUE THREAD

**Issue by 130nk3r5** [radzenhq/radzen-blazor#513]
Currently the RadzenDataGrid's _Is Null_ filter does not support string.Empty values.

Would it be possible to update the `QueryableExtension` on line 407 - 414 to be as follow:
`
else if (columnFilterOperator == FilterOperator.IsNull)
                {
                    return $@"np({property}) == null || np({property}) == ''";
                }
                else if (columnFilterOperator == FilterOperator.IsNotNull)
                {
                    return $@"np({property}) != null || {property} != ''";
                }
`

**Comment by enchev** [comment]
Hey @130nk3r5,

Empty strings are not null, maybe we can add IsEmpty/IsNotEmpty for string columns.

**Comment by 130nk3r5** [comment]
I like the idea. Will respond on the forum.

**Comment by enchev** [comment]
Implemented in https://github.com/radzenhq/radzen-blazor/pull/514
