### ISSUE TITLE
RadzenFileInput 700MB file, args = ""

### ISSUE THREAD

**Issue by MG1376** [radzenhq/radzen-blazor#517]
I configured file input like this:
```
<RadzenFileInput @bind-Value="@file" TValue="string" Class="w-100" Accept="video/*,audio/*"
                                     Change="@(args => OnChange(args, item.AlbumID, item.Id))" @ref="@fileInput"
                                     Error="@(args => OnError(args, "FileInput"))" Placeholder="File Name"
                                     MaxFileSize="int.MaxValue">

</RadzenFileInput>      
```

With a method that reads audio/video as Base64 and save to file. But this only works for small video/audios. I want to store a 700MB movie. but when I debug, args is empty. 
I set MaxFileSize="int.MaxValue" and this should store up to 2GB but I have problem with a 700MB file. How to use RadzenFileInput  for larger files?

**Comment by akorchev** [comment]
You can't use RadzenFileInput for larger files as will have to send all data to the server and keep it in memory. Use RadzenUpload for this purpose or try the built in InputFile.
