### ISSUE TITLE
The property Expanded in GroupRowRenderEventArgs is always null.

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#519]
When the event GroupRowRenderEventArgs the property Expanded is always null, even if the row has already been expanded.
The problem is the property Expanded is not initialized when the event is being instantiated:

`var args = new Radzen.GroupRowRenderEventArgs() { Group = item.Group, FirstRender = firstRender };`

Would it be possible to update the code to set Expanded to true if it is expanded?

So the code in the responsible method would be:

```
internal Tuple<GroupRowRenderEventArgs, IReadOnlyDictionary<string, object>> GroupRowAttributes(RadzenDataGridGroupRow<TItem> item)
{
	var args = new Radzen.GroupRowRenderEventArgs()
	{
		Group = item.Group,
		FirstRender = firstRender,
		
		// Initialization of expanded
		Expanded = IsGroupItemExpanded(item)
	};

	if (GroupRowRender != null)
	{
		GroupRowRender(args);
	}

	return new Tuple<GroupRowRenderEventArgs, IReadOnlyDictionary<string, object>>(args, new System.Collections.ObjectModel.ReadOnlyDictionary<string, object>(args.Attributes));
}
```

**Comment by enchev** [comment]
We cannot do that since you will unable to toggle expand state later at runtime.
