### ISSUE TITLE
Notification - couple of issues

### ISSUE THREAD

**Issue by glutio** [radzenhq/radzen-blazor#520]
See it close 2 last notifications at the same time, but then if you navigate away you can see the one that still hasn't expired. Plus positioning issue imho.

https://user-images.githubusercontent.com/22550674/178155282-2c65ffad-36db-4a94-afb6-8be068797b00.mp4

**Comment by enchev** [comment]
Unable to reproduce this with latest https://blazor.radzen.com/notification
