### ISSUE TITLE
DataGrid DateTime Only Date Filter

### ISSUE THREAD

**Issue by serkanaslan34** [radzenhq/radzen-blazor#521]
Hi there,
Im using RadzenDataGrid and im using LoadData event for getting data and filtering.
I have one DateTime filter column and i want to get every data for this date without time filter.
But i can only use Greater than or less than filter mode but there is one problem.
When i want to get only one day with filtering there are so many records after this data.
There is no way to get data only one date.
Can you add to dynamic-linq query generator with only date equals filter like this.
```
  query = query.Where(x => x.TransactionDate.Value.Date == DateTime.Today.Date) or 
  query = query.Where(x => x.ApprovalDate.Value.Date == new DateTime(2020,1,1,).Date));
```

**Comment by Kuyaromeo** [comment]
Closed and completed with no resolution.  I just made an account to see NOTHING.
