### ISSUE TITLE
Please support Content Security Policy (CSP) without unsafe-inline for script-src

### ISSUE THREAD

**Issue by 304NotModified** [radzenhq/radzen-blazor#526]
**Is your feature request related to a problem? Please describe.**
Our content security policy blocks inline scripts. For example, the dropdown is generating inline scripts.
Funny though, when it's blocked the dropdown  component still works the same? 

![image](https://user-images.githubusercontent.com/5808377/178547487-01f216ee-8e15-42e4-bf10-32dd237f9498.png)

**Describe the solution you'd like**
- Fix the Dropdown
- No inline scripts in other components
- Make new stuff without inline scripts
- Please document that Content Security Policy (CSP) without unsafe-inline for script-src is supported

**Describe alternatives you've considered**
- Let me remove the inline scripts with a trick or 
- Limit the functionality
- Document which components supports unsafe-inline for script-src

**Additional context**
related: https://github.com/radzenhq/radzen-blazor/issues/42

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
![image](https://user-images.githubusercontent.com/5808377/178547938-6b45efdc-a0c2-4f7f-8d23-4accf82894db.png)

**Comment by akorchev** [comment]
We don't plan to implement this as it will make the implementation complex - for every inline JavaScript attribute we would need a JSInterop call (performance will suffer as well).

**Comment by 304NotModified** [comment]
OK loud and clear. Thanks for the fast response!
