### ISSUE TITLE
RadzenDropDown multiselection is broken after last changes

### ISSUE THREAD

**Issue by gagabu** [radzenhq/radzen-blazor#540]
Hi,
After last changes in [RadzenDropDownItem](https://github.com/radzenhq/radzen-blazor/commit/a0d49f8c29896e47465695fccc55d34af2b2b66d#r79163281) multiselection is broken. 

Conditions in lines 11 and 12 are not same:
`if(DropDown.LoadData.HasDelegate && !string.IsNullOrEmpty(DropDown.searchText))`
`if(**!**(DropDown.LoadData.HasDelegate && !string.IsNullOrEmpty(DropDown.searchText)))`
and thus can't be replaced by singe fuction `SelectItem`.
It breaks multiselection in my app :-(
Also multiselection is broken on [demo page ](https://blazor.radzen.com/dropdown)

v3.19.8 - multiselection is broken,
v3.19.7 - multiselection works as expected.

**Comment by arx-l** [comment]
Broke for me too
