### ISSUE TITLE
Please add a tree with checkbox support.

### ISSUE THREAD

**Issue by mwaqasaziz** [radzenhq/radzen-blazor#55]
what you have offered is way more than one can ask for, but i need this feature, please add it.

as in below picture

![image](https://user-images.githubusercontent.com/18336355/108366435-2deaa280-721a-11eb-812e-f59d4d2441a2.png)

**Comment by mwaqasaziz** [comment]
Any Update

**Comment by akorchev** [comment]
Checkbox support is now available! Check this demo: https://blazor.radzen.com/tree
