### ISSUE TITLE
UseRowNumberForPaging

### ISSUE THREAD

**Issue by blackbirddevelopment** [radzenhq/radzen-blazor#56]
Error being generated because "UseRowNumberForPaging" is no longer supported.

Row-number paging is no longer supported. See https://ak.ms/AA6h122 for more information.

When using Radzen development tool 2.57.9 and using a MSSQL database the error is generated and build is stopped.

An error should not be created when trying to run the application generated by the Radzen tool. Since the "UseRowNumberForPaging" is no longer viable, it should be an option for older versions of the app or a way to turn off the Row Number For Paging should be available.

![image](https://user-images.githubusercontent.com/6655056/108531979-8bbbd080-7294-11eb-9ab4-b3790147f242.png)

**Comment by enchev** [comment]
This is not related to Radzen.Blazor components.

**Comment by blackbirddevelopment** [comment]
Radzen generated the code.
