### ISSUE TITLE
The default-base theme should only style Radzen components, and leave browser defaults alone

### ISSUE THREAD

**Issue by jnsn** [radzenhq/radzen-blazor#565]
**Is your feature request related to a problem? Please describe.**

When using the `default-base` theme, I expected it to leave everything alone and just theme the Radzen components, but it's coloring the browser scrollbar too.

https://github.com/radzenhq/radzen-blazor/blob/8a8be30657266a33670df29fb3b1b3066cc82a2c/Radzen.Blazor/themes/components/blazor/_scrollbar.scss#L5-L36

It took me a good while to figure out where this was coming from, since it's counter intuitive and not documented at all, as far as I found.

**Describe the solution you'd like**

Don't color the scrollbars using the `default-base` theme, as this should only style the Radzen components and not interfere with the already present style or default styles.

**Describe alternatives you've considered**

Improve the documentation that adding the `.rz-default-scrollbars` class to the body element will not add the styling.

**Comment by enchev** [comment]
Fixed in our latest update 4.1.1
