### ISSUE TITLE
Dropdown aria-label broken

### ISSUE THREAD

**Issue by enumiton** [radzenhq/radzen-blazor#566]
**Describe the bug**
The `aria-label` attribute is straight up broken.

**To Reproduce**
Use the `<RadzenDropDown />` component. [Even the demo has the issue](https://blazor.radzen.com/dropdown).

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
I'm assuming the value of `aria-label` was intended to be the `TextProperty` value of the option.

**Screenshots**
<img width="268" alt="A screenshot showing the bug on Radzen's demo page." src="https://user-images.githubusercontent.com/41439661/183373280-e8c5aa11-4278-4ad6-987e-97a170b31da9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari & Chromium
 - Version Safari 14.5 & Edge 104.0.1293.47

**Comment by digitaldarragh** [comment]
I don't believe this is fixed. I am still encountering the problem.
