### ISSUE TITLE
Tooltip issue with custom layout throws exception System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'removeChild'))

### ISSUE THREAD

**Issue by developertest02** [radzenhq/radzen-blazor#570]
**Describe the bug**
When using an element with a show tooltip event, after tooltip is shown, and then you navigate to another page (that uses a created layout, not the main layout generated by project creation), application crashes. 

Following error can be observed in developer tools console.

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'removeChild')
    at H (blazor.server.js:1:17214)
    at H (blazor.server.js:1:17184)
    at H (blazor.server.js:1:17184)
    at ie.applyEdits (blazor.server.js:1:21387)
    at ie.updateComponent (blazor.server.js:1:20617)
    at blazor.server.js:1:114721
    at xn.processBatch (blazor.server.js:1:115093)
    at kt.<anonymous> (blazor.server.js:1:129275)
    at blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
H @ blazor.server.js:1
H @ blazor.server.js:1
H @ blazor.server.js:1
applyEdits @ blazor.server.js:1
updateComponent @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
processBatch @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
_invokeClientMethod @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
o.onmessage @ blazor.server.js:1
blazor.server.js:1 [2022-08-09T13:11:41.432Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'removeChild'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'removeChild')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---

**To Reproduce**
1. See github linked project below.
2. Run project
3. Navigate to child and hover over icon to trigger the tooltip
4. navigate back to home using the main menu

Alternatively link your repo with a sample project that can be run.
https://github.com/developertest02/ScratchBlazor

**Expected behavior**
Tooltips should not trigger application crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.134

**Additional context**

**Comment by enchev** [comment]
I'm afraid that I'm unable to access your project. 
![image](https://user-images.githubusercontent.com/5804953/183837490-e28576d6-d156-4fee-911d-f70590d74573.png)

Try to debug the code of  the tooltip and if you think there is a bug and you have a fix you can submit pull request.
