### ISSUE TITLE
Tooltip causes crash when navigating away from page

### ISSUE THREAD

**Issue by yelanjri** [radzenhq/radzen-blazor#572]
**Describe the bug**
Tooltip services causes a Javascript crash when navigating to another page

**To Reproduce**
Open a tooltip by hovering over it with your mouse,
Navigate to another page. The blazor yellow issue bar will show up at the bottom. In the event viewer it says:
`Exception: 
System.AggregateException: One or more errors occurred. (Error: No element is currently associated with component 1752)
 ---> System.InvalidOperationException: Error: No element is currently associated with component 1752
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
`

**Expected behavior**
Navigating to another page should work with a tooltip open.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 104.0.5112.81

**Screenshots*
Open tooltip
![image](https://user-images.githubusercontent.com/66680137/183870652-6c30f0e7-a300-47f2-abca-b61d04319a9c.png)
Navigate to other page shows me the yellow bar:
![image](https://user-images.githubusercontent.com/66680137/183870813-db31f0b8-9a46-4dc1-b94c-5a9bc2b89a50.png)
Event viewer:
![image](https://user-images.githubusercontent.com/66680137/183870941-10216aeb-572d-47ec-9793-16e8b557eb46.png)
JS console output: 
![image](https://user-images.githubusercontent.com/66680137/183871218-16785c70-3644-4dd6-b4e6-e517514b8537.png)

**Additional context**
The issue happens at the JS level on the destroyPopup function it tries to destroy the popup while it didn't exist anymore. I didn't have this issue before it could be that it was introduced during one of the last updates to Radzen. I was able to make a quick fix my implementing my own CustomTooltip component in Blazor and commenting this line out in the Dispose() Method:
![image](https://user-images.githubusercontent.com/66680137/183869976-95e4a1d6-b81c-4df2-82f9-6bfac3ef40d0.png)
If you are using  this fix make sure to replace the Radzen Tooltip in your MainLayout with your custom one.

**Comment by enchev** [comment]
Duplicate to https://github.com/radzenhq/radzen-blazor/issues/571
