### ISSUE TITLE
Page numbering breaks in RadzenDataGrid using Maui

### ISSUE THREAD

**Issue by julianadormon** [radzenhq/radzen-blazor#576]
**Describe the bug**
Page numbering buttons is incorrect on load and after switching pages.

**To Reproduce**
Create a DataGrid with paging. 
Ensure you have multiple pages.
Load the component and see.

Alternatively link your repo with a sample project that can be run.

**Expected behavior**

**Screenshots**
I will attach a video

**Desktop (please complete the following information):**
Mac Catalyst and Windows 
Same details I provided in the other bug report I created right before this one.

**Additional context**

**Comment by julianadormon** [comment]
https://www.loom.com/share/0ca6adc1c26142c0a89b7392a84285c5

**Comment by enchev** [comment]
no code reproducing the problem and demonstrating how the DataGrid is bound.

**Comment by julianadormon** [comment]
Sorry, I didn't think it was necessary since we have nothing really to implement except for the settings which are as follows:

`@using SortedDesktopForShootproof.Data
@using Radzen
@using System.Text.Json
@inject AppStateService AppStateService
@inject NotificationService _notificationService

<div class="scrollDiv" style="width:1000px">

    <div class="flexCenter" style="align-items: center; margin-right:10px; min-width:500px; max-width: 70vw;">

        <RadzenDataGrid Style="height: calc(100% - 247px)"
                        AllowFiltering="false"
                        FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                        AllowPaging="true"
                        PageSizeOptions="pageSizeOptions"
                        ShowPagingSummary="true"
                        PagingSummaryFormat="pagingSummaryFormat"
                        AllowSorting="true"
                        Data="@availableCustomers"
                        TItem="CustomerVm"
                        SelectionMode="DataGridSelectionMode.Single"
                        RowSelect=@((x) => SelectCustomer(x))>
            <Columns>
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.FirstName" Title="FirstName" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.LastName" Title="LastName" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.FullName" Title="FullName" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.Email" Title="Email" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.Mobile" Title="Mobile" />
            </Columns>
        </RadzenDataGrid>

    </div>

</div>

    @code {

        [CascadingParameter] BlazoredModalInstance ModalInstance { get; set; }

        [Parameter] public List<CustomerVm> availableCustomers { get; set; }

        IEnumerable<int> pageSizeOptions = new int[] { 10, 20, 30, 40, 50 };
        string pagingSummaryFormat = "On page {0} of {1} (total {2} records)";

        protected override void OnInitialized()
        {
            AppStateService.OnChange += StateHasChanged;
        }

        public void Dispose()
        {
            AppStateService.OnChange -= StateHasChanged;
        }


        void SelectCustomer(CustomerVm customer)
        {
            if (customer != null)
            {
                AppStateService.selectedCustomerIdToConnect = customer.CustomerId;
            }

            ModalInstance.CloseAsync(ModalResult.Ok($"Form was submitted successfully."));
        }


        public void ShowNotification(NotificationMessage message)
        {
            _notificationService.Notify(message);
        }

    }
`

**Comment by julianadormon** [comment]
https://www.loom.com/share/2b806e91e97b41ccb8b5616ceefa2830
