### ISSUE TITLE
Cannot use RadzenNumeric with validation and double type

### ISSUE THREAD

**Issue by AdamJachocki** [radzenhq/radzen-blazor#578]
Hi, I try to use RadzenNumeric with double type and validation, like this:
```
<RadzenDataGridColumn TItem="ProductViewModel" Property="Quantity" Title="Quantity">
    <EditTemplate Context="item">
        <RadzenNumeric TValue="double" Step="0.5" @bind-Value="@item.Quantity" Name="QuantityNumeric"/>
        <RadzenNumericRangeValidator Min="0.0001" Max="10000.0" Text="Enter quantity" Popup="true" Component="QuantityNumeric" />
    </EditTemplate>
</RadzenDataGridColumn>
```
As you can see this is inside inline form.
Anyway, I get the error: Argument 1: cannot convert from 'double' to 'dynamic'

my @itemQuantity is of type double.
What's more, when I try to use Min and Max properties withing double type on RadzenNumeric I get the error also.

My Radzen version: 3.20.3

**Comment by enchev** [comment]
I'm unable to reproduce such error. Such code compiles and runs as expected:
![image](https://user-images.githubusercontent.com/5804953/184813156-656d3184-5780-44b7-9c3a-c27cc7222126.png)
![image](https://user-images.githubusercontent.com/5804953/184813176-8062bd9f-21e0-4265-994a-f3ac062bdeee.png)
