### ISSUE TITLE
Page numbering not working in Maui

### ISSUE THREAD

**Issue by julianadormon** [radzenhq/radzen-blazor#579]
**Describe the bug**
Page numbering buttons is incorrect on load and after switching pages.

**To Reproduce**
Create a DataGrid with paging.
Ensure you have multiple pages.
Load the component and see.

**Expected behavior**
To see multiple pages and the correct page showing

**Desktop (please complete the following information):**
Mac Catalyst and Windows
Same details I provided in the other bug report I created right before this one.

I have also tried with and without PageSizeOptions

`@using SortedDesktopForShootproof.Data
@using Radzen
@using System.Text.Json
@inject AppStateService AppStateService
@inject NotificationService _notificationService

<div class="scrollDiv" style="width:1000px">

    <div class="flexCenter" style="align-items: center; margin-right:10px; min-width:500px; max-width: 70vw;">

        <RadzenDataGrid Style="height: calc(100% - 247px)"
                        AllowFiltering="false"
                        FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                        AllowPaging="true"
                        PageSizeOptions="pageSizeOptions"
                        ShowPagingSummary="true"
                        PagingSummaryFormat="pagingSummaryFormat"
                        AllowSorting="true"
                        Data="@availableCustomers"
                        TItem="CustomerVm"
                        SelectionMode="DataGridSelectionMode.Single"
                        RowSelect=@((x) => SelectCustomer(x))>
            <Columns>
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.FirstName" Title="FirstName" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.LastName" Title="LastName" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.FullName" Title="FullName" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.Email" Title="Email" />
                <RadzenDataGridColumn TItem="CustomerVm" Property="UserProfile.Mobile" Title="Mobile" />
            </Columns>
        </RadzenDataGrid>

    </div>

</div>

    @code {

        [CascadingParameter] BlazoredModalInstance ModalInstance { get; set; }

        [Parameter] public List<CustomerVm> availableCustomers { get; set; }

        IEnumerable<int> pageSizeOptions = new int[] { 2, 10, 20, 30, 40, 50 };
        string pagingSummaryFormat = "On page {0} of {1} (total {2} records)";

        protected override void OnInitialized()
        {
            AppStateService.OnChange += StateHasChanged;
        }

        public void Dispose()
        {
            AppStateService.OnChange -= StateHasChanged;
        }

        void SelectCustomer(CustomerVm customer)
        {
            if (customer != null)
            {
                AppStateService.selectedCustomerIdToConnect = customer.CustomerId;
            }

            ModalInstance.CloseAsync(ModalResult.Ok($"Form was submitted successfully."));
        }

        public void ShowNotification(NotificationMessage message)
        {
            _notificationService.Notify(message);
        }

    }
`

**Comment by julianadormon** [comment]
https://www.loom.com/share/0ca6adc1c26142c0a89b7392a84285c5

**Comment by enchev** [comment]
Hey @julianadormon,
We will need runnable code that reproduces the problem. Please try to reproduce it in a self contained example and post it here. You can use also our demos to try to replicate your scenario.

**Comment by julianadormon** [comment]
Ok, I may need some time to put a repo together. Thanks.

**Comment by julianadormon** [comment]
Here is a minimal repo.
https://github.com/julianadormon/RadzenPageNumberBug.git

**Comment by julianadormon** [comment]
https://www.loom.com/share/830fef21793c4f36be727f5742205f6a
