### ISSUE TITLE
Add a way to know the current 'open' state of tooltips

### ISSUE THREAD

**Issue by mwarvik** [radzenhq/radzen-blazor#582]
It would be nice to know the open state of tooltips. I can also try to create a PR, if this is something more people think is missing.

**Is your feature request related to a problem? Please describe.**
We are using tooltips on our page, with a click to open them. We would like to close them with a click on the same button, but that is not possible (as I see it) at the moment, as there is no way to know the state of the tooltip.

**Describe the solution you'd like**
Either add a flag to `TooltipService` to indicate if any tooltip is currently open, or invoke the `OnClose` event when the tooltip is closed (also when closed by clicking some other element).

**Describe alternatives you've considered**
I tried to make it work with the current implementation, but it's not possible as I see it.
Example: 
1. Add event handler to `OnClose` that sets a `TooltipIsOpen` flag to `false`.
1. Click button to open tooltip (sets flag to `true`).
3. Click outside the button (tooltip closes), event handler not called, `TooltipIsOpen` is still `true`.
3. Click on button again, as the flag indicates it's still open, it will not open before a second click.

**Additional context**
Nothing to add.

**Comment by enchev** [comment]
I believe that you can use a simple variable in your button click for such state.

**Comment by mwarvik** [comment]
@enchev That would not work, if you read the example. The wrong state will be set if the tooltip is closed by clicking something else than the button.

**Comment by enchev** [comment]
Maybe similar option can work for tooltip as well:
https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/DialogService.cs#L373

**Comment by mwarvik** [comment]
Thank you! It works great :)
