### ISSUE TITLE
Dialog resize and drag combination

### ISSUE THREAD

**Issue by MPapst** [radzenhq/radzen-blazor#587]
**Describe the bug**
When creating a Dialog with `DialogOptions.Resizable = true` and `DialogOptions.Draggable = true`, the resize of the dialog first behaves as if `DialogOptions.Draggable` is false. After moving the dialog once, it is resized differently.

**To Reproduce**
Check the dialog page demo: https://blazor.radzen.com/dialog
Click the Button "Order 10248 details" and resize the dialog, it will resize as it is fixed on the center of the screen.
Move the dialog a bit, try resizing again.

**Expected behavior**
When `DialogOptions.Draggable` is true, the resize behavior should not be around the center of the screen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by enchev** [comment]
This will be the behavior if there is no Left and Top specified. If you specify them the initial resize will be exactly the same as after drag: 
![image](https://user-images.githubusercontent.com/5804953/186839269-3d0ed109-1de0-48de-8dcd-a1bd300007b8.png)
![image](https://user-images.githubusercontent.com/5804953/186839178-11086ec5-afcb-483d-a622-1bacbf7a441f.png)
