### ISSUE TITLE
Feature request DialogService: Close handler to intercept and prevent closing // Make Close() virtual

### ISSUE THREAD

**Issue by Pmyl** [radzenhq/radzen-blazor#588]
**Problem**
When the user is filling a form in a modal dialog and accidentally presses the X (or overlay/cancel button), applications with good user experience should prompt a confirmation dialog to ask for confirmation.
Radzen DialogService doesn't have any "close handler" feature and cannot be used to achieve the above functionality.

**Solution**
Blazor has just recently added this feature to the NavigationManager by [allowing to add/remove handlers that can intercept and cancel the navigation](https://github.com/dotnet/aspnetcore/pull/42638), a similar solution for the DialogService would allow creating "mistake safe" forms in dialogs.

**Alternatives**
There are 3 alternatives I've considered:
- Tell everyone to not use modals to show forms
  - This would ruin the flow of some applications
- Tell everyone to remove X and overlay dismiss, allowing full control on the dialog closing events
  - It's not good UX if an application has some dialogs with X/overlay dismiss and some other don't. it would confuse the users (it would confuse me for sure). Removing it for every dialog is not pretty
- Make the Close method in DialogService virtual so that anyone can create a `class MyDialogService : DialogService`, override Close and implement their own intercept functionality

**Comment by Pmyl** [comment]
@enchev hey I noticed you closed this issue without giving any reason, I'm sure it was a mistake, could you reopen it or give me a reason why it has been closed?

**Comment by akorchev** [comment]
[enchev](https://github.com/enchev) closed this as [completed](https://github.com/radzenhq/radzen-blazor/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/radzenhq/radzen-blazor/commit/77e3952849474238ce7d5ea42b333edbc9f823d9 [4 hours ago](https://github.com/radzenhq/radzen-blazor/issues/588#event-7267096210)

The issue was addressed in the linked commit.

**Comment by Pmyl** [comment]
I just noticed that, thank you @akorchev and @enchev !

**Comment by MrMaavin** [comment]
@Pmyl can you provide a working example of a class that inherits the DialogService?
If I inherit the DialogService, my dialog won't open...
