### ISSUE TITLE
Make TooltipService.OnClose be called in all cases when tooltip is closed

### ISSUE THREAD

**Issue by mwarvik** [radzenhq/radzen-blazor#590]
**Is your feature request related to a problem? Please describe.**
First, thank you for very quickly closing and fixing my previous (582). 😄 It helped me on my way, but was unfortunately not enough to solve my problems. We need to be able to close our tooltips by clicking the same button as we use to open it. As it is now, clicking the same button the second time does nothing. 

**Describe the solution you'd like**
I think the best solution would be to have OnClose be called when tooltip is closed by clicking outside the tooltip or opening another tooltip (now it's only called by actually calling the Close method). This would let us listen to the `OnClose`, and call `TooltipService.Open` / `Close` based on the current state of the tooltip.

**Describe alternatives you've considered**
I can't see any other way to make it work as we want, other than adding some custom JS of our own.

**Additional context**

-

**Comment by enchev** [comment]
https://github.com/radzenhq/radzen-blazor/commit/6c729deb77e0d620da585e4b491c7d3a1dab50b3
