### ISSUE TITLE
Changing the Url of the Upload in code generates silent error

### ISSUE THREAD

**Issue by rudolfdeschipper** [radzenhq/radzen-blazor#594]
**Describe the bug**
I am using the Upload component with Auto=false. The Upload() method is called when after I have submitted contents of a form (and have received an ID back), where I use this ID in the Url to the controller that handles the upload. So I change the Url of the Upload component in code.

The controller action is called as expected by the upload component and finishes correctly. However, at no point the callbacks Progress, Error or Complete are called, which means there is no way to get any result back (such as the ID of the record where I saved the uploaded file to).

**To Reproduce**
Put an Upload component inside a form template. Set Auto=false, ref=upload
Create "Complete" callback
In the Submit action of the form, change the Url of the upload component (using the Value=@($"{url}")) construct, and call the upload.Upload()
Observe that the Complete method is not called.

**Expected behaviour**
The callbacks are called.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge, FireFox
 - Version RadZen 3.20.9

**Comment by rudolfdeschipper** [comment]
Further investigation: changing the Url during the submit action fails. If the Url remains unchanged, all works fine.

**Comment by enchev** [comment]
Hey @rudolfdeschipper,

I'm afraid that changing the upload url in form submit action is not possible.
