### ISSUE TITLE
RadzenDataGrid / RadzenPager not working when EventCallback<PagerEventArgs> Page is used

### ISSUE THREAD

**Issue by MGerdel** [radzenhq/radzen-blazor#598]
**Describe the bug**
After #591 has been solved the pager of the DataGrid does not work at all anymore, when the EventCallback Page is used.
The current behaviour is the following:
- At any time only next- and last page are clickable
- The DataGrid does not updated anymore when next- or last page are clicked

**To Reproduce**
Use a RadzenDataGrid with Paging and assigned PageCallback (even an empty method does the trick).

**Expected behavior**
The DataGrid / Paginator should update and work as expected (update content, en- and disable according to the current page).

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox (64 Bit)
 - Version: 104.0

**Additional context**
None

**Comment by enchev** [comment]
Hey @MGerdel,

We will need minimal repro code.

**Comment by enchev** [comment]
@MGerdel we need runnable code example

**Comment by MGerdel** [comment]
I have created a repo to reproduce this issue for you:
[https://github.com/MGerdel/RadzenExample](url)

**Comment by MGerdel** [comment]
@enchev Thank you again for your time and fix, but won't this fix bring back #591?
If I understand the code correctly, the assigned callback for page would now prevent the recalculation of the paginator properties.

**Comment by vperumal88** [comment]
RadzenGrid<> FirstPage () getting null exception error
