### ISSUE TITLE
Stack Component Request

### ISSUE THREAD

**Issue by 1002527441** [radzenhq/radzen-blazor#599]
this component is very useful to manage layout of its childitems along the vertical or horizontal axis, like the StackPanel in WPF.

Could you help to build this one?

https://mudblazor.com/components/stack#basic-usage

**Comment by enchev** [comment]
Hey @1002527441,

Maybe you can simply use display: flex and set desired flex-direction:
https://www.w3schools.com/cssref/playdemo.asp?filename=playcss_flex-direction

**Comment by 1002527441** [comment]
good idea, thanks a lot for your suggestion.
