### ISSUE TITLE
Option to disable RadzenMenuItem

### ISSUE THREAD

**Issue by Matthewsre** [radzenhq/radzen-blazor#60]
I have a RadzenMenu that based on the selected items below I need to enable/disable certain actions that are represented by RadzenMenuItems.

For an example, you can see the "CommandBar with split and disabled buttons" example for the [FluentUI CommandBar control](https://developer.microsoft.com/en-us/fluentui#/controls/web/commandbar).

![image](https://user-images.githubusercontent.com/2955659/108933216-9d3c0a00-75ff-11eb-98b8-c2876c3968eb.png)

For the solution I would like to have a "Disabled" bool property like the button has so I can enable or disable the menu item.

Alternatively, I could also build up my own menu using buttons and have an option for styling the button similar to the menu. An example for the button would be the "Action Button" or "Command Button" section on the [FluentUI Button page](https://developer.microsoft.com/en-us/fluentui#/controls/web/button).

**Comment by enchev** [comment]
Hey @Matthewsre,

We have [SplitButton](https://blazor.radzen.com/splitbutton) that can be used to execute actions. Menus are for navigation.
