### ISSUE TITLE
Tailwind Support

### ISSUE THREAD

**Issue by Drammy** [radzenhq/radzen-blazor#615]
**Is your feature request related to a problem? Please describe.**
No, its not related to a problem.  I would like to know if a feature is planned for the future.

**Describe the solution you'd like**
Tailwind is growing in popularity so I wondered if you have any plans to support theming via tailwind in the future?

**Comment by akorchev** [comment]
Hi @Drammy,

I have summarised our thoughts on the matter here: https://forum.radzen.com/t/how-to-use-custom-css-class-for-radzen-components/6953/8?u=korchev

**Comment by Drammy** [comment]
Thanks for the quick response @akorchev and I completely understand your stance on the matter.

I guess our best approach is to fork and alter the styling to use tailwind classes.  We can then bring across and change what we need as and when required.  Does that sound feasible and within the license terms?

**Comment by akorchev** [comment]
> I guess our best approach is to fork and alter the styling to use tailwind classes

This would be quite an effort and I am not sure possible at all considering the Radzen UI that does not have Tailwind equivalent. 

Wouldn't it be easier to set the Radzen CSS variables (introduced in Radzen.Blazor 4.0) to the Tailwind values? Full disclosure I am not sure if this is how Tailwind works.

**Comment by enchev** [comment]
I'm closing this since we already have CSS variables and there is no way we can render Tailwind CSS classes.
