### ISSUE TITLE
Radzen Autocomplete doesn't render in Radzen Datagrid FilterTemplate

### ISSUE THREAD

**Issue by ThatFlashCat** [radzenhq/radzen-blazor#62]
**Describe the bug**
Nesting a `<RadzenAutoComplete>` component inside the `<FilterTemplate>` of a data grid component results in incorrect rendering.

**To Reproduce**
1. Create a Radzen Datagrid
2. Add at least one column and add a filter template.
3. Add a RadzenAutoComplete component and run the site.

```
<RadzenGridColumn TItem="ContactGoalViewModel" Property="CompanyName" Title="CLient Agency">
                <FilterTemplate>
                    <RadzenAutoComplete Placeholder="Type to search" Data="agencies" LoadData="SearchAgencies" @bind-Value="CurrentAgency"></RadzenAutoComplete>
                </FilterTemplate>
            </RadzenGridColumn>
```

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
The autocomplete component should render and run.

**Screenshots**
The client agency and primary liaison are using autocomplete components.
![image](https://user-images.githubusercontent.com/26885142/109062290-5b699d00-76ad-11eb-8d3d-3e757138b5b1.png)

**Desktop (please complete the following information):**
 - Browser: Chrome, Chromium Edge, Firefox
 - Version: Radzen 3.1.1
.NET 5 Blazor Server

**Comment by akorchev** [comment]
Thank you for reporting this issue! Should be fixed with the next release.
