### ISSUE TITLE
RadzenDataGrid with list as FilterValue & FilterOperator.Contains

### ISSUE THREAD

**Issue by Bluejanis** [radzenhq/radzen-blazor#621]
**Is your feature request related to a problem? Please describe.**
I have an Object in a RadzenDataGrid, one field is a list of another object. Its basically 3 options with multiple choice. To show them in the grid, I aggregated them as a comma-seperated string.

Now I would also like to filter the Grid based on those 3 states. So I added a FilterTemplate with a RadzenDropDown to select the option(s) to search for. The FilterOperator is set to Contains.
But it only finds exact matches: entries which have just that the value that was selected. If I selected 2 options from the RadzenDropDown, then it will find all options with either value.

**Describe the solution you'd like**
So what I would like is
A) The FilterOperator Contains to be able to search a string for multiple values.
It would also be nice to be able to handle scenarios where it has to intersect 2 lists (filter & value property).
B) A way to set/override a custom filter operation, which determines whether an entry is filtered. This would give developer a great deal of flexibility in other scenarios as well.

**Describe alternatives you've considered**
I also considered just changing the data the grid gets, based on the selected filter. But this will interferes with some logic in my FooterTemplate that uses purchasesGrid.View.Count() to show the total entry count.

**Comment by enchev** [comment]
There are at least three examples showing how to filter single column by multiple values:
https://blazor.radzen.com/datagrid-loaddata
https://blazor.radzen.com/datagrid-odata
https://blazor.radzen.com/datagrid-filter-template

**Comment by Bluejanis** [comment]
The examples that have multiple selection filter, all only have exact matches. None of the examples has entries that would be find by contains anyways.

When debugging it seems like the FilterOperator.Contains is not available if the FilterValue is an IEnumerable<string>.

**Comment by Bluejanis** [comment]
I implemented my use case not with my possible alternative, somewhat similar to your loaddata example.

Its not perfectly clean, since I'm working next to Radzen.Blazor and forces me to use another copy to store the full list vs the filtered list.
But its fine for my use case now. Thank you for your time.
