### ISSUE TITLE
Add Carousel or  Slideshow

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#629]
Hi!

please!
add Carousel [https://mudblazor.com/components/carousel#api](https://mudblazor.com/components/carousel#api)
or  Slideshow  [https://asuikit.com/v3/slideshow](https://asuikit.com/v3/slideshow)

thanks!

**Comment by HolyOne** [comment]
I agree, It would be a great new component

**Comment by yordanov** [comment]
RadzenCarousel Component is available with [v5.3.0](https://github.com/radzenhq/radzen-blazor/releases/tag/v5.3.0). See demos at https://blazor.radzen.com/carousel
