### ISSUE TITLE
Radzen Tree Property 'Expand' callback is not invoked

### ISSUE THREAD

**Issue by nadde11** [radzenhq/radzen-blazor#635]
**Describe the bug**
If you have set an "Expand"-Callback to the RadzenTree Component, the expand callback is not invoked, when user expands a TreeItem.

**To Reproduce**
Use Radzen demonstration and configuration of the Radzen Blazor Tree component and expand a TreeItem.

**Expected behavior**
I expect a log in the console log for the "Expand"-Callback, as it happens with the "Change"-Callback.

**Screenshots**
![image](https://user-images.githubusercontent.com/115006168/193825990-fcd92059-73ec-4dc5-88b7-eca70aed3434.png)

![image](https://user-images.githubusercontent.com/115006168/193826418-2ebd456f-65c6-4e79-88cf-184a22f28185.png)

**Desktop (please complete the following information):**

**Comment by enchev** [comment]
I'm afraid that we cannot reproduce such problem on our demos:

![image](https://user-images.githubusercontent.com/5804953/193829448-2097a9fe-5c09-4c56-a717-a0043231128e.png)
![image](https://user-images.githubusercontent.com/5804953/193829500-6ba5f174-471a-4e13-9e90-9dcdef99a041.png)
