### ISSUE TITLE
Datagrid select row: could navigate to page

### ISSUE THREAD

**Issue by Foitn** [radzenhq/radzen-blazor#636]
**Is your feature request related to a problem? Please describe.**
When I use the DataGrid.SelectRow() method, the proper item is selected.
It would be a great addition if the DataGrid would also navigate (page wise) to the proper page on which this item is located.
Currently when I add a new item, that is on page 2, page 1 is still selected and I only see the selection when I manually navigate to page 2.
E.g.
![datagrid_select_row](https://user-images.githubusercontent.com/14889176/194067092-4af5e157-d283-44c2-ad26-82744cea7c89.gif)

**Describe the solution you'd like**
Once I use the SelectRow() method on a DataGrid, it will perform the following:
* Select the Item (as it currently does)
* Navigate to the page on which this item is located.

This could also be a boolean parameter for the SelectRow method, to choose the behavior.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by akorchev** [comment]
There isn't a performant way for the datagrid to determine which page a particular row is at. You should implement that yourself - find the page and use the GoToPage method to go there.
