### ISSUE TITLE
Slide out panels

### ISSUE THREAD

**Issue by oppknox** [radzenhq/radzen-blazor#64]
**Is your feature request related to a problem?
We have a complex creation scenario that will span multiple pages and need to solve the problem in all platforms ideally with one implementation

**Describe the solution you'd like**
Ideally this would be solved with side panels

**Describe alternatives you've considered**
Fluentui web panels

**Additional context**
https://developer.microsoft.com/en-us/fluentui#/controls/web/panel

**Comment by vertonghenb** [comment]
If interested, https://github.com/Append-IT/Blazor.Sidepanel does this and can be used as a reference.

**Comment by akorchev** [comment]
The [side dialog](https://blazor.radzen.com/dialog) implement something similar.
