### ISSUE TITLE
DataGrid resets page when data is changed

### ISSUE THREAD

**Issue by gagabu** [radzenhq/radzen-blazor#648]
**Describe the bug**
DataGrid resets to the first page when I changed data in cell:
![](https://raw.githubusercontent.com/gagabu/RadzenGridReset/main/bug.gif)

I've seen #591 and #632, but in my case count of items are same and it seems odd jump to first page on data edit.

This works fine before [v3.20.9](https://github.com/radzenhq/radzen-blazor/releases/tag/v3.20.9).
[Sample Project](https://github.com/gagabu/RadzenGridReset)

**Comment by enchev** [comment]
Expression assigned to Data property will force reload on every StateHasChanged(). You can change it to:
![image](https://user-images.githubusercontent.com/5804953/196210541-39a2d613-f330-4a54-a076-0a5d4ea8b1b0.png)
