### ISSUE TITLE
WASM Radzen Datagrid RowSelect event fires before the selected row binding has been 'bound'

### ISSUE THREAD

**Issue by RFIsoft** [radzenhq/radzen-blazor#650]
Radzen Datagrid in WASM:
The RowSelect event fires before the selected row binding has been 'bound'

Expected:
On RowSelect event, bounded selected property to represent selected row
Actual:
On RowSelect, bounded selected property represents previous selected row.

Workaround: use property setter (which is sync only...)

To check/reproduce: implement a property setter (on rowselect bind) and event method (on rowselect event), and print the 'trigger'

```
//In RadzenDataGrid, use 
@bind-Value="@SelectedTenants"
RowSelect="@TenantSelected"

//in @code:
private IList<TenantDto> _selectedTenants = new List<TenantDto>();
    IList<TenantDto> SelectedTenants 
    {
        get
        {
            return _selectedTenants;    
        }
        set
        {
            _selectedTenants = value;
            var id = SelectedTenants[0].Id;
           //This will print after the Event Callback
            Console.WriteLine($"Selected tenant PROP: {id} {SelectedTenants[0].Name}");
        }
    }
   private async Task<EventCallback> TenantSelected()
    {
        var id = SelectedTenants[0].Id;
        //this will print before the property binding)
        Console.WriteLine($"Selected tenant CallBack: {id} {SelectedTenants[0].Name}");
}
```

**Comment by enchev** [comment]
Hey @RFIsoft,

You can use the argument of the event to get the selected row.

**Comment by RFIsoft** [comment]
Thanks @enchev Did not realize the event included that..... That's indeed the preferred solution!
Pete
