### ISSUE TITLE
datagrid-virtualization-loaddata bug with many rows

### ISSUE THREAD

**Issue by georgheimltwat** [radzenhq/radzen-blazor#653]
**Describe the bug**
- set a total row count of 700.000 or more
- adjust scrollbar to display rows starting from row 0
- move scrollbar directly to the end (f.e. via keyboard: Ctrl+End)
--> it takes several seconds until screen is updated, too many LoadData-events are fired, at least LoadDataArgs contains problematic values:
![image](https://user-images.githubusercontent.com/85229336/196861363-d0ed40fb-fa30-4fbf-83f1-4519742c6ae1.png)

--> finally scrollbar is not at the end, displayed rows does not match scrollbar-position
![image](https://user-images.githubusercontent.com/85229336/196860658-41a378bc-9813-4b22-b65b-adf823bc699e.png)
--> when I now move the scrollbar upwards by mouse  the scrollbar jumps to the beginning

**To Reproduce**
https://github.com/georgheimltwat/radzen-blazor/tree/georgheim/datagrid-virtualization-loaddata-bug

**Expected behavior**
- just load and display last page of data
- no performance issue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Radzen 4.1.8

**Additional context**
I'm afraid its a problem in the aspnetcore-virtualization - here I stopped investigations

**Comment by enchev** [comment]
Hi @georgheimltwat,

I'm not sure if we can do much since we are just raising LoadData event when ASP.NET Virtualize component needs items:
https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenDataGrid.razor.cs#L65

**Comment by georgheimltwat** [comment]
If you are sure its a aspnetcore - bug you probably may report it to microsoft ?
