### ISSUE TITLE
4.1.10 dropdown font too big

### ISSUE THREAD

**Issue by PeterViau** [radzenhq/radzen-blazor#658]
A
![Screenshot 2022-10-22 104959](https://user-images.githubusercontent.com/80265322/197342683-3eea6f79-dfbe-4291-9e72-01ce053f4fa4.png)
fter installing version 4.1.10 the font in the dropdown is much bigger than previous versions.

**Comment by akorchev** [comment]
You can check what CSS rules apply. The font-size is 16px in the material themes and 14px in all other. Can be verified in our online demo. https://blazor.radzen.com/dropdown
