### ISSUE TITLE
Saving Grid settings with Groups

### ISSUE THREAD

**Issue by PeterViau** [radzenhq/radzen-blazor#659]
When loading DataGridSetting from json  with Groups and then loading a saved DataGridSetting without groups the columns display properly but when  using DataGridSettings  to export data the values are the default grid values for orderindex , orderindex can also have duplicates. 
Note: if I resize a column manually and try the export again the DataGridSettings are correct.

**Comment by akorchev** [comment]
Please follow the issue template.

**Comment by PeterViau** [comment]
Maybe I should break it further :-)
When I save DataGridSettings to JSON OrderIndex  can have duplicate entries.

**Comment by PeterViau** [comment]
overwritting old gridsettings seemed to fix the issue
