### ISSUE TITLE
Upgrading from 4.1.8 to 4.1.9 breaks visualization of RadzenDropDown

### ISSUE THREAD

**Issue by lg2de** [radzenhq/radzen-blazor#662]
![image](https://user-images.githubusercontent.com/44983012/197414543-e7bc0caf-a90b-458a-bd61-2a0f2ed67329.png)

After upgrading to 4.1.12 I identified above changes.
Testing different versions I verified that the problem starts with version 4.1.9.

This is the Xaml for the control (nothing special, I guess):
```xaml
<RadzenDropDown TValue="int" Data="@this.chunkSizes" Value="this.chunkSizes.First()" Change="SetChunkSize"/>
```
All DropDown controls are affected in my app.

Problems:
* The width has changed.
* The text is vertical cut. (Seams to be related to the `overflow` attribute of the `rz-dropdown-label`.)

**Comment by yordanov** [comment]
@lg2de, I couldn't reproduce the second problem "The text is vertical cut". Can you share more about your scenario? Is the dropdown placed inside another component/template? Looks like the `rz-dropdown-label` has `height` applied, and it shouldn't. What are the styles applied to `rz-dropdown-label` in your browser?

**Comment by eziante** [comment]
We are seing the same issue @lg2de 

We are running a .net6.0 blazor wasm app using Radzen.Blazor 4.1.12 with the material design theme.

We see a cut text both when a dropdown is used in a RadzenDataGrid as well as in a RadzenCard.

The stylesof `rz-dropdown-label` for us is:
```css
.rz-multiselect-label-container, .rz-dropdown-label {
    display: block;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    padding: var(--rz-dropdown-label-padding);
}
```

### This is for the RadzenCard
![image](https://user-images.githubusercontent.com/4362151/197480663-02fd0f6a-cb60-4188-9f84-a2f3cfbd5981.png)
```html
<h3>@Localize["Settings"]:</h3>
<RadzenCard>

	<div class="row">
		<div class="col-md-12">
			<h3>@Localize["Language"]</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<RadzenDropDown TValue="CultureInfo" Data="@SupportedLanguagesByName" @bind-Value="@SelectedCultureInfo" TextProperty="Key" ValueProperty="Value" />
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<h3>@Localize["Visible rows in data grids"]</h3>
			<RadzenDropDown AllowClear="false" TValue="int" Data=@PageSizeOptions @bind-Value="@SelectedPageSize" />
		</div>
	</div>

	<div class="row">
		<div class="col-md-12" style="margin-top:20px; margin-bottom:20px;">
			<RadzenButton class="float-right" Click="Save" Text="@Localize["Save"]" Disabled="NoChangesToSettings" />
		</div>
	</div>

</RadzenCard>
```



### This is for the RadzenDataGrid
![image](https://user-images.githubusercontent.com/4362151/197480544-07c29d26-dab6-444a-b328-79d77273cd79.png)
```html
    <RadzenDataGrid ContextMenu="@(args => ShowContextMenuWithContent(args))" AllowPaging="true" PageSize="@UserSettings.PageSize" AllowFiltering="true" AllowSorting="true" Data="@Clients" FilterMode="FilterMode.Advanced" TItem="Client" AllowColumnResize="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
            ApplyFilterText="@Localize["Apply"]" ClearFilterText="@Localize["Clear"]" ContainsText="@Localize["Contains"]" EqualsText="@Localize["EqualsText"]" NotEqualsText="@Localize["Not equals"]" StartsWithText="@Localize["Starts with"]" EndsWithText="@Localize["Ends with"]" EmptyText="@Localize["No records to display"]" LessThanText="@Localize["Less than"]" LessThanOrEqualsText="@Localize["Less than or equals"]" GreaterThanText="@Localize["Greater than"]" GreaterThanOrEqualsText="@Localize["Greater than or equals"]">
        <Columns>
            <RadzenDataGridColumn TItem="Client" Property="ClientId" Title="@Localize["Id"]" />
            <RadzenDataGridColumn TItem="Client" Property="Remarks" Title="@Localize["Remarks"]">
                <Template Context="data">
                    <RadzenTextBox @bind-Value=data.Remarks MaxLength="300" Change="@(args => OnClientChange(args, data, nameof(data.Remarks)))"/>
                </Template>
            </RadzenDataGridColumn>

            <RadzenDataGridColumn TItem="Client" Property="IsApproved" Title="@Localize["Approved"]" TextAlign="TextAlign.Center">
                <Template Context="data">
                    <AuthorizeView Policy="@Policies.IsAdmin">
                        <Authorized>
                            <RadzenCheckBox TriState="false" TValue="bool" Value="@data.IsApproved" Change="@(args => OnClientChange(args, data, nameof(data.IsApproved)))" />
                        </Authorized>

                        <NotAuthorized>
                            <RadzenIcon Icon="@( data.IsApproved ? "done" : "clear" )" />
                        </NotAuthorized>
                    </AuthorizeView>
                </Template>
            </RadzenDataGridColumn>

            <RadzenDataGridColumn TItem="Client" Property="IsMultiTenant" Title="@Localize["Multi"]" TextAlign="TextAlign.Center">
                <Template Context="data">
                    <AuthorizeView Policy="@Policies.IsAdmin">
                        <Authorized>
                            <RadzenCheckBox TriState="false" TValue="bool" Value="@data.IsMultiTenant" Change="@(args => OnClientChange(args, data, nameof(data.IsMultiTenant)))" />
                        </Authorized>

                        <NotAuthorized>
                            <RadzenIcon Icon="@( data.IsMultiTenant ? "done" : "clear" )" />
                        </NotAuthorized>
                    </AuthorizeView>
                </Template>
            </RadzenDataGridColumn>

            <RadzenDataGridColumn TItem="Client" Property="ApplicationVersion" Title="@Localize["Current Version"]" />

            <RadzenDataGridColumn TItem="Client" Property="TargetApplicationVersion" Title="@Localize["Target Version"]">
                <Template Context="data">
                    <AuthorizeView Policy="@Policies.IsAdmin">
                        <Authorized>
                            <RadzenDropDown TValue="string" Data="@AvailableVersions" @bind-Value="@data.TargetApplicationVersion" Change="@(args => OnClientChange(args, data, nameof(data.TargetApplicationVersion)))" />
                        </Authorized>

                        <NotAuthorized>
                            @data.TargetApplicationVersion
                        </NotAuthorized>
                    </AuthorizeView>
                </Template>
            </RadzenDataGridColumn>

            <AuthorizeView Policy="@Policies.IsAdmin">

                <RadzenDataGridColumn TItem="Client" Context="data" Filterable="false" Sortable="false" Width="50px" TextAlign="TextAlign.Center">
                    <Template Context="data">
                        <RadzenButton ButtonStyle="ButtonStyle.Info" Icon="description" Size="ButtonSize.Small" Click="@(args => CollectLogs(data))" />
                    </Template>
                </RadzenDataGridColumn>

            </AuthorizeView>

        </Columns>
    </RadzenDataGrid>
```

**Comment by yordanov** [comment]
@eziante Which browser + version are you using? Also, sending an isolated sample project would be really helpful.

**Comment by eziante** [comment]
@yordanov  I've just tested it in the following browsers:

- Chrome: Version 106.0.5249.119 (Officiel version) (64-bit)
- Edge: Version 106.0.1370.52 (Official build) (64-bit)
- Opera: Version:92.0.4561.21
- Firefox: 106.0.1 (64-bit)

All having the issue with the cut text.

For the style in `rz-dropdown-label` I tried to disable `overflow: hidden;` which seemed to have solved the issue but I don't know if that solution would cause other issues down the line. 

I'll try to come up with a sample project :)

**Comment by yordanov** [comment]
Instead of removing the `overflow: hidden;` could you try adding `min-height: 1.5rem;` and see if this fixes the trimmed text? `overflow: hidden` makes sure longer texts are properly handled when the dropdown is having a fixed width or there is not enough screen space.

**Comment by yordanov** [comment]
@eziante a screenshot of devtools might also help. These are the styles applied to the label in our demos environment:
### Styles
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1118895/197496072-5802c3cc-e96d-4fee-9bef-47c47ad0efd5.png">

### Computed
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/1118895/197496638-8a6cd670-52f6-48f3-a01f-c3f3d08ad503.png">

**Comment by eziante** [comment]
@yordanov  setting `min-height: 1.5rem;` solves the problem.

When making a project to reproduce the error I wasn't able to reproduce the problem initially. 
However, I found out that we are using bootstrap 4.6.2 in our app but the newest blazor wasm template uses bootstrap 5.1.0. Changing the bootstrap version in out app from 4.6.2 to 5.1.0 solved the problem with cut text.
I don't know if it's bootstrap that causes the issue then

**Comment by yordanov** [comment]
Thank you, @eziante! Managed to isolate the problem. It is bootstrap v4.6.2 reset styles adding `margin-bottom: 0.5rem;` to the `label` element. Fixing it (`margin: 0;`) with next Radzen.Blazor release.

**Comment by eziante** [comment]
@yordanov  perfect! Thank you for the help and thanks for an amazing framework! :)

**Comment by lg2de** [comment]
@yordanov thanks for your fast and great support.
What I'm wondering how you are able to keep all the relations in mind.
I fear you have not because it is not (fully) possible, isn't it?

What do you think? How about adding some additional comments on the CSS tweaking you did? This could also help other developers to identify such issues?
Do you have (automated) tests checking the visual result?
