### ISSUE TITLE
Datagrid sort problem when used LoadData event

### ISSUE THREAD

**Issue by Dmitry0108** [radzenhq/radzen-blazor#663]
**Describe the bug**
RadzenDatagrid can not sort data when used LoadData event. When sorting we have exception: Sysytem.InvalidOperationException: The current thread is not assotiated with Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state. 

I think in your Demos you have the same problem.

**To Reproduce**
1. Go to https://blazor.radzen.com/datagrid-virtualization-loaddata
2. Click on column header for sorting
3. Items disappear

**Expected behavior**
Sorted items

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/55c0fe05cce488485532914bd7659ac6c5bfb14b
