### ISSUE TITLE
OrderIndex duplicate values

### ISSUE THREAD

**Issue by PeterViau** [radzenhq/radzen-blazor#666]
When saving Radzen.DataGridSettings Orderindex can have duplicate value causing columns to be in the wrong order when reloading Radzen.DataGridSettings

example from  json

 "Property": "RandomName",
      "Visible": true,
      "Width": "263px",
      **"OrderIndex": 2,**
      "SortOrder": null,
      "FilterValue": null,
      "FilterOperator": 6,
      "SecondFilterValue": null,
      "SecondFilterOperator": 0
    },
    {
      "Property": "AnotherName",
      "Visible": true,
      "Width": "217px",
      **"OrderIndex": 2,**
      "SortOrder": null,
      "FilterValue": null,
      "FilterOperator": 6,
      "SecondFilterValue": null,
      "SecondFilterOperator": 0

**Comment by enchev** [comment]
Any idea how to reproduce this?

**Comment by PeterViau** [comment]
I loaded a test app without restoring Radzen.DataGridSettings, resized a couple of columns and then moved one ahead of the second one and this is what I get:

Columns": [
    {
      "Property": null,
      "Visible": true,
      "Width": "35px",
      "OrderIndex": 0,
      "SortOrder": null,
      "FilterValue": null,
      "FilterOperator": 0,
      "SecondFilterValue": null,
      "SecondFilterOperator": 0
    },
    {
      "Property": "One",
      "Visible": true,
      "Width": "184px",
      "OrderIndex": 1,
      "SortOrder": null,
      "FilterValue": null,
      "FilterOperator": 6,
      "SecondFilterValue": null,
      "SecondFilterOperator": 0
    },
    {
      "Property": "Two",
      "Visible": true,
      "Width": "237px",
      "OrderIndex": 2,
      "SortOrder": null,
      "FilterValue": null,
      "FilterOperator": 6,
      "SecondFilterValue": null,
      "SecondFilterOperator": 0
    },
    {
      "Property": "Three",
      "Visible": true,
      "Width": "287px",
      "OrderIndex": 2,
      "SortOrder": null,
      "FilterValue": null,
      "FilterOperator": 6,
      "SecondFilterValue": null,
      "SecondFilterOperator": 0
    },

**Comment by enchev** [comment]
Hi @PeterViau,

Can you try the same on our demo and let me know exact order of actions. Unfortunately I was no able to reproduce this so far.
https://blazor.radzen.com/datagrid-save-settings

**Comment by enchev** [comment]
You might need to clear your application cache:
![image](https://user-images.githubusercontent.com/5804953/199246003-baf8ffaf-d635-4295-8b9e-4f0305adb36f.png)

**Comment by enchev** [comment]
I give up. I'm unable to reproduce such problem using your instructions:
![image](https://user-images.githubusercontent.com/5804953/199663586-a7771ddc-3d8a-4c70-87e3-90fdf729db82.png)
![image](https://user-images.githubusercontent.com/5804953/199663540-579e59a7-0052-459f-b378-cf8530918daa.png)

If you think there is a problem, you can reproduce it at your end and you have a fix feel free to submit pull request.
