### ISSUE TITLE
have you sidebar??

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#671]
have you sidebar??
I can't find it.

As
https://blazor.syncfusion.com/demos/sidebar/default-functionalities
Or
https://mudblazor.com/components/drawer#variants-responsive

**Comment by akorchev** [comment]
[Yes](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenSidebar.razor). It is used in the [MainLayout](https://github.com/radzenhq/radzen-blazor/blob/master/RadzenBlazorDemos/Shared/MainLayout.razor#L101) of our online demo.
