### ISSUE TITLE
Scrollbar disappears when zoomed in on chromium browsers

### ISSUE THREAD

**Issue by DanRogers99** [radzenhq/radzen-blazor#675]
**Describe the bug**
The scrollbar on components disappears when zoomed in on chromium browsers.

**To Reproduce**
1. Go to 'https://blazor.radzen.com/datagrid-virtualization'
2. Set browser zoom to 150% or 200%

**Expected behavior**
Scrollbar width should scale with browser zoom. Ie if it is 8px at 100% it should be 12px at 150% and 16px at 200%

**Screenshots**
**100% Browser Zoom:**
![image](https://user-images.githubusercontent.com/33861884/199228603-1921ce21-939e-47ba-99a9-4f17248e36a2.png)

**150% Browser Zoom:**
![image](https://user-images.githubusercontent.com/33861884/199228704-05ea25b6-0183-49a8-9386-0a17230d8393.png)

**200% Browser Zoom:**
![image](https://user-images.githubusercontent.com/33861884/199228773-dc22a51d-9814-4cd2-93fe-f143a6a3881c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 106.0.5249.120

**Comment by akorchev** [comment]
What Radzen theme CSS file did you include? We need to know if you are using the base theme (which does not style the scrollbar) or the full theme (which styles it). In any case you can try including <theme>-base.css and see if it resolves the problem.

**Comment by DanRogers99** [comment]
@akorchev this is using any of the themes on the website (we use material for our project).  RadzenBlazorDemos/Theme.razor always uses the -base.css version of any files

**Comment by akorchev** [comment]
It happens because of the custom scroll styling implementation. We will probably change it with the next release.
