### ISSUE TITLE
Add optional global search capabillity

### ISSUE THREAD

**Issue by chrgraefe** [radzenhq/radzen-blazor#68]
**Describe the solution you'd like**
Add an optional global search box on top of data grid. 
It is handy to type some characters in a global search box and the "contains" criteria is applied to all columns.

Example:
![image](https://user-images.githubusercontent.com/4922897/110490489-a85b6380-80f0-11eb-8d46-1b1ed9e23dbd.png)

**Comment by enchev** [comment]
Such functionally can be easily generated by Radzen:
![image](https://user-images.githubusercontent.com/5804953/111130607-146e1980-8580-11eb-8fb7-a5d9067bb546.png)
