### ISSUE TITLE
RadzenDatePicker poor rendering performance using Max & Min

### ISSUE THREAD

**Issue by Avenged** [radzenhq/radzen-blazor#683]
**Describe the bug**
RadzenDatePicker has poor rendering performance when using Max & Min properties to limit the range of the dates. We had to change to common html input dates because RadzenDatePicker takes a long time to render.

**To Reproduce**

```
<RadzenDatePicker DateFormat="d"
                                 Max="@(tramitesModel.CreateDateUntil ?? DateTime.Today)"
                                 ShowUpDown="false"
                                 DateRender=@DateRenderSpecial
                                 @bind-Value="tramitesModel.CreateDateFrom" />

<RadzenDatePicker DateFormat="d"
                                 Max="DateTime.Today"
                                 Min="@(tramitesModel.CreateDateFrom ?? DateTime.MinValue)"
                                 ShowUpDown="false"
                                 DateRender=@DateRenderSpecial
                                 @bind-Value="tramitesModel.CreateDateUntil" />

@code {
    public class TramitesModel
    {
         public DateTime? CreateDateFrom { get; set; }
         public DateTime? CreateDateUntil { get; set; }
    }

    public TramitesModel tramitesModel { get; set; } = new();
}
```

Radzen.Blazor 4.1.8
Google Chrome 107.0.5304.88 (Build oficial) (64 bits)
.NET 6.0
Windows 10 (64 bits)
Visual Studio 2022 17.3.6 (64 bits)

**Comment by enchev** [comment]
Hey @Avenged,

This code cannot be complied and there are properties like ShowUpDown that are not available for RadzenDatePicker. Not sure also why you use DateTime.MinValue (which is 1), this will lead to 2000+ items in the year dropdown of the picker. You might need to revise your date range.
