### ISSUE TITLE
DatePicker icon not visible / shifted

### ISSUE THREAD

**Issue by nanocortex** [radzenhq/radzen-blazor#684]
**Describe the bug**
DatePicker icon is not visible/shifted.

**To Reproduce**
1. Go to 'https://blazor.radzen.com/datepicker'
2. No icons are visible at datepicker components

**Expected behavior**
DatePicker icon visible.

**Screenshots**
![SCR-20221107-t3r](https://user-images.githubusercontent.com/40443396/200403192-1de75579-2216-4f7d-9abb-a993646294c7.png)
![SCR-20221107-t4n](https://user-images.githubusercontent.com/40443396/200403198-c84554ae-ca30-440a-9b10-d5339ba1acc6.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Chrome/Firefox 
 - Version 4.2.3

**Comment by enchev** [comment]
Works normally on our end. Try to clear your browser cache. 
![image](https://user-images.githubusercontent.com/5804953/200499497-35ed8294-15c0-429a-a2ed-b8efd56abb86.png)
