### ISSUE TITLE
Negitive Values in column chart

### ISSUE THREAD

**Issue by KenDarlingPAF** [radzenhq/radzen-blazor#685]
**Describe the bug**
For a column chart when all the columns contain negative values, it is not rendering correctly and the tool tip does not show. It also looks like the x axis is not displaying when all values are negative as well.

**Expected behavior**
The chart should display correctly showing the x axis as well as and the tool tips should show,

**Screenshots**
![image](https://user-images.githubusercontent.com/47124065/200420587-10b277e6-5080-450f-bdc7-6c1c4247dce0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19044.2130
 - Browser chrome : Version 107.0.5304.88 (Official Build) (64-bit)

**Comment by akorchev** [comment]
Hi @KenDarlingPAF,

You can set the Max attribute of RadzenValueAxis to 0 as immediate workaround:
```
<RadzenValueAxis Max="0" ...>
```
