### ISSUE TITLE
Layout must have "Mini varian"

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#697]
Hi!

Layout must have "Mini varian" - when I can see ICONS
Please, see here
[https://mudblazor.com/components/drawer#variants-mini](https://mudblazor.com/components/drawer#variants-mini)
the part "Mini" and "Mini Drawer Customization"

Thanks!

**Comment by enchev** [comment]
Duplicate to https://github.com/radzenhq/radzen-blazor/issues/238
