### ISSUE TITLE
Accordion - Error when I set background color

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#698]
Hi!
I use 'Accordion with multiple expand'
[https://blazor.radzen.com/accordion](https://blazor.radzen.com/accordion)

When I insert 'class="rz-background-color-warning-lighter"'
the "check mark" runs away to the left

`<RadzenAccordionItem Text="Employees" Icon="account_box"
                                 class="rz-background-color-warning-lighter">
                Details for Employees
</RadzenAccordionItem>`

Thanks!

**Comment by akorchev** [comment]
Looks fine to me.
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/454726/201486626-fe682f73-94d1-4d79-ab68-d1ad4dfa513c.png">

**Comment by Andrey-2021** [comment]
Excuse me, but I don't see error too.

You can see project,
file Index.razor,
line 21
class="rz-background-color-warning-lighter"

Link on C# project
[https://drive.google.com/file/d/1M8gQgawGPppbSkbeUXBdt5ODRxxqFjeF/view?usp=sharing](https://drive.google.com/file/d/1M8gQgawGPppbSkbeUXBdt5ODRxxqFjeF/view?usp=sharing)

**Comment by enchev** [comment]
Hey @Andrey-2021,

The issue cannot be reproduced on your project too - not sure why you post a project that cannot reproduce anything.

**Comment by Andrey-2021** [comment]
excuse me.
1) I reDownload the project from Google Disk from my link.
2) Run the project
What I see 

![Безымянный](https://user-images.githubusercontent.com/92442252/201639987-d952dc61-2a84-4285-a108-57945462a17e.jpg)

I don't know why it work correctly at you,
but it not work at me

**Comment by Andrey-2021** [comment]
Thanks
