### ISSUE TITLE
Support for Speech to Text on TextArea

### ISSUE THREAD

**Issue by groogiam** [radzenhq/radzen-blazor#699]
**Is your feature request related to a problem? Please describe.**
This request is not related to a problem just a nice to have. Mobile users often use this feature on larger text areas that require some sort of narrative.

**Describe the solution you'd like**
Add the ability to initiate browser [speech recognition API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition)  on a text area.  This would ideally be a new parameter that would enable a microphone icon to initiate the recognition.

**Describe alternatives you've considered**
I have not considered any other alternatives.

**Additional context**
Something like this.

![image](https://user-images.githubusercontent.com/1992395/201493651-744667be-295c-4a6d-807b-f4bb200baf81.png)

I'd be happy to implement and submit a PR for the functionality, I just want to make sure that this functionality is desirable before taking the time. Looking forward to your feedback. Thanks.

**Comment by kelvinkipruto741-netizen** [comment]
give the link
