### ISSUE TITLE
Menu must have "Automatic opening mode" when "Mouse over" on RadzenMenuItem

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#701]
Hi!

1)
When we have 'Mouse over' event on main RadzenMenuItem,
subMenu must automatically open. I don't want click on main menu item. Click - this is an unnecessary action (in some cases)

Please, see 
Part 'Mouse Events' , 'Mouse over' example 
[https://mudblazor.com/components/menu#custom-activator-mouse-events](https://mudblazor.com/components/menu#custom-activator-mouse-events)

2) It is necessary to highlight the background or/and change  the TEXT color,  when 'mouse over'  on main/horizontal menu item.
3)And when a menu/subMenu item is selected, it is necessary that the selection of this  main menu item remains.

Thanks.

**Comment by enchev** [comment]
You can achieve the same very easily:
![image](https://user-images.githubusercontent.com/5804953/201595488-348cc373-bda1-4600-964a-222213b1940f.png)
![menuover](https://user-images.githubusercontent.com/5804953/201595614-7a518df1-f226-42a0-a79b-91055b6db59e.gif)

**Comment by enchev** [comment]
Built-in feature implemented in https://github.com/radzenhq/radzen-blazor/pull/706

**Comment by ochiro1** [comment]
Hello,
Facing the following issue: if I have a menu with ClickToOpen set to "false" and I have menu item with child items followed by other menu items, then I mouse out of the menu item with children, the whole menu closes rather than just closing the item with children.
Example:
            <RadzenMenuItem Text="More">
                <RadzenMenuItem Text="Item1"></RadzenMenuItem>
                <RadzenMenuItem Text="Item2"></RadzenMenuItem>
                <RadzenMenuItem Text="More items">
                    <RadzenMenuItem Text="More sub items">
                        <RadzenMenuItem Text="Item1"></RadzenMenuItem>
                        <RadzenMenuItem Text="Item2"></RadzenMenuItem>
                    </RadzenMenuItem>
                </RadzenMenuItem>
                <RadzenMenuItem Text="Last"></RadzenMenuItem>
            </RadzenMenuItem>
