### ISSUE TITLE
CheckBoxList must have flags 'isShowHighlight' and 'isChangeTextColor'

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#702]
Hi!

CheckBoxList must have flags 
1) 'isShowHighlight' and 
2) 'isChangeTextColor',

when 'Mouse over' event on RadzenCheckBoxListItem,
this RadzenCheckBoxListItem must 
1) set/change  highlight  background (as in RadzenPanelMenuItem)
2) change the TEXT color

Thanks!

**Comment by enchev** [comment]
Hey @Andrey-2021,

RadzenCheckBoxListItem accept arbitrary attributes and what you are looking for is as simple as:
```
<RadzenCheckBoxListItem Text="Orders" Value="1" 
                            onmouseenter="this.style.backgroundColor = 'red'" onmouseleave="this.style.backgroundColor = ''" />
```
