### ISSUE TITLE
RadzenAccordion huge intervals - How to manage intervals correctly????

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#707]
Hi!
RadzenAccordion.
how to manage  with intervals? or height?
By default they're huge.

**How to manage intervals correctly????**
Maybe you need to create additional settings?

![image](https://user-images.githubusercontent.com/92442252/201971991-de75c808-de04-4f50-b1ac-49aa7cda2e6f.png)

Zeroing  (margin, padding AND set height)  doesn't help completely

![image](https://user-images.githubusercontent.com/92442252/201968004-ba32d42d-67f4-4081-9b05-2815b005d9a2.png)

Thanks!

**Comment by akorchev** [comment]
Please use our forum for questions like this.
