### ISSUE TITLE
Menu - ClickToOpen="false" not work correctly

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#710]
Hi!

We consider the situation when ClickToOpen="false"

1)Go [https://blazor.radzen.com/menu](https://blazor.radzen.com/menu)
2)Set 'Click to open' to 'OFF'
3)And click ''General-Menu'

Menu 'General' don't closed
and Menu will not work correctly. 
Move the mouse over the menu items, they do not work correctly.
We have bugs.

After clicking the submenu, the menu list should always close.

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/b5b8aaf731bd25eb93cd9663cd34305f600bffd2
