### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by drullo** [radzenhq/radzen-blazor#715]
The documentation is very incomplete.  Many components not documented at all and most components lack documentation about members (properties, etc).  Developers are left with relying on incomplete examples and experimentation to learn how the components work.

Also, there are broken/inaccurate links in some of the documentation.  For example, the **Source** link in the [Layout example](https://blazor.radzen.com/layout) points back to the example page instead of to Github.  And the **Source** link for components such as [Dialog](https://blazor.radzen.com/dialog) point to an [incorrect](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenDialog.razor.cs) (broken) Github destination.

I understand time constraints and the challenges related to documentation.  But as a new user of your package, I'm finding the experience to be a bit frustrating.

**Comment by akorchev** [comment]
I've fixed the broken source links. Other than that I would respectfully disagree that the documentation is **very** incomplete.

> most components lack documentation about members

Which ones? Most component should have 90% of their members documented in the API reference.

**Comment by HubKing** [comment]
I came here, because I find it annoying that the demos in the Getting Started are not self-contained. I mean, at the bottom of https://blazor.radzen.com/get-started , if I click "Explorer Demos", it shows a DataGrid with some employee data. Whilst the picture icons may look pretty, if I click "<> SOURCE", it is using `Employees` data table in EntityFrameworkCore, and an unknown class `Employee`, so I can't quickly test it. 

Either it should have a link to a page that provide those things (class definitions, an SQLite DB file, profile pictures, etc), or it should just use self-contained data like MudBlazor's[ similar examples](https://mudblazor.com/components/datagrid#default-data-grid).

**Comment by akorchev** [comment]
> I came here, because I find it annoying that the demos in the Getting Started are not self-contained. 
There is always a trade off between having self-contained demos and demos that are more "real-world". We have opted for the second as most of our user seem to already use EF and want to know if / how they can use it with RadzenDataGrid.

Other components use self-contained data - Scheduler, Charts etc.

> Either it should have a link to a page that provide those things (class definitions, an SQLite DB file, profile pictures, etc),

Indeed we can do that. We also plan to add the ability to edit the example in the browser so you can experiment with stuff live.

> Also, the documentation code is using very long lines and it does not have a horizontal scrollbar.

This doesn't seem to be the case. I see a scrollbar in the linked demo.

![scroll](https://user-images.githubusercontent.com/454726/204124319-3ca66e3f-2f0f-4f0a-a593-32840aedbd46.gif)

**Comment by HubKing** [comment]
> This doesn't seem to be the case. I see a scrollbar in the linked demo.

You scrolled the page down to the bottom of the source code. When I wrote my comment, I did not know I have to scroll it down. And even if now I know, it still is inconvenient to scroll the page down just to horizontally scroll the code, and then scroll it back up to see where I was. I think that the horizontal source code scroll bar should be shown at the bottom of the screen as an overlay over the source code, not at the bottom of the source code.

**Comment by akorchev** [comment]
@HubKing this is how scrolling of HTML elements works :) The horizontal scrollbar renders at the bottom of the scrollable HTML element. And the vertical scrollbar shows that there is more content in the page.

**Comment by akorchev** [comment]
@HubKing we discussed it a bit more and would probably make the source code viewer have fixed height so both scrollbars are initially visible.

**Comment by Alex55040** [comment]
> Also, the documentation code is using very long lines and it does not have a horizontal scrollbar ( https://blazor.radzen.com/datagrid-composite-columns ), which make it very annoying to read the code (I had to use left/right arrow keys or mouse middle-click drag to see the clipped out parts).

Try also to hold shift key while scrolling with mouse wheel - it scrolls horizontally.
