### ISSUE TITLE
RadzenPanelMenuItem - Path with C# code

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#720]
Hi!
Please 
add the ability to insert code into the Path,
for example

`<RadzenPanelMenuItem Text="@item.menu"

                         Path="Products/AllProducts?ProductType=@item.menu" 
                         Icon="save"
                         class="rz-background-color-danger-lighter">`

                                                  
  Thanks!

**Comment by akorchev** [comment]
This is a limitation of Blazor. It does not allow you to set properties like that. Using C# interpolation is a viable workaround:

```
Path=@($"Products/AllProducts?ProductType={item.menu}" )
```

**Comment by Andrey-2021** [comment]
Thank you very much!
Please insert this example into the documentation
RadzenPanelMenuItem
