### ISSUE TITLE
DataGridRow closes with async RowExpand callback

### ISSUE THREAD

**Issue by buehler** [radzenhq/radzen-blazor#721]
**Describe the bug**
After expending a radzen grid row with an async RowExpand callback, the row immediately closes again.

**To Reproduce**
1. Create a RadzenGrid analog to the example in https://blazor.radzen.com/master-detail-hierarchy-demand
2. Make the RowExpand callback async and make two awaited calls in it
3. Expand the row in the UI
4. The row will open and immediately close again

**Expected behavior**
It would be nice to have the row to stay open.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: newest Chrome

**Additional context**
I also tried with "StateHasChanged" at the end of the async method. Sadly, it just closes.

**Comment by buehler** [comment]
I have an addition: When the object reference does not change, the row does not close. So using `myObject.Prop ??= ...` results in a closing row.

**Comment by buehler** [comment]
When using the same object, it works:
```csharp
private async Task RowExpand(User user)
{
    user.Details.Roles = (await RoleService.GetUserRoles(user.Id)).ToList();
    user.Details.Redemptions = await Tokens.GetRedeemedUserTokens(user.Id);
}
```

Should this stay open, i.e. is it still a bug?

**Comment by enchev** [comment]
Hi @buehler,

Unfortunately no row state can be preserved if the data item is different every time.

**Comment by buehler** [comment]
Got it, thank you :-)
