### ISSUE TITLE
Dialog  el.computedStyleMap is not a function

### ISSUE THREAD

**Issue by Transzendental** [radzenhq/radzen-blazor#732]
When opening a dialog with focusable elements Radzen.Blazor.js throws a exception: Uncaught TypeError: el.computedStyleMap is not a function.

This can also be seen in the [offical showcase](https://blazor.radzen.com/dialog) in with open page as dialog example.

**Comment by enchev** [comment]
Can you post more info which dialog exactly in this demo is causing the error at your end? What's your browser?
