### ISSUE TITLE
DropdownBase.SelectItem Invalid Cast Exception when using Value Property

### ISSUE THREAD

**Issue by groogiam** [radzenhq/radzen-blazor#734]
**Describe the bug**
The recent updates to optimize value selection appear to have broken the SelectItem method.

**To Reproduce**
See unit test code snippet using Radzen.Blazor 4.4.0

```csharp
        [Fact]
        public async Task Dropdown_SelectItem_Method_Should_Not_Throw()
        {
            using var ctx = new TestContext();

            ctx.JSInterop.Mode = JSRuntimeMode.Loose;

            var component = DropDown<int>(ctx);

            var items = component.FindAll(".rz-dropdown-item");

            Assert.Equal(2, items.Count);

            //this throws
            await component.InvokeAsync(async () => await component.Instance.SelectItem(1));
        }
```

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Before the update SelectItem would take the value that you wanted set not an instance of the bound object type.

**Comment by enchev** [comment]
Hi @groogiam,

This test failed with 4.4.0 as well:
![image](https://user-images.githubusercontent.com/5804953/206113802-a365d290-5f68-4eb3-aa27-9f9b691442c9.png)
![image](https://user-images.githubusercontent.com/5804953/206113848-f7538603-43e2-44fc-92a5-2b1d4353ac84.png)

**Comment by groogiam** [comment]
Sorry I think my original post was not clear. This appears to be a regression from somewhere between 3.x and 4.x. It worked in 3.x but does not work in 4.4 and above. Looks like this might have been this commit https://github.com/radzenhq/radzen-blazor/commit/b0baad56e7845c917106390076e573c7a37ace4f.
