### ISSUE TITLE
Dropdown component doesn't line up with other form elements.

### ISSUE THREAD

**Issue by SethJustus** [radzenhq/radzen-blazor#737]
There is a styling discrepancy between the RadzenDropdown component and the other form components (ie. RadzenTextBox, RadzenNumeric ect. ).  

1. Create a new, basic blazor project
2. Add the necessary radzen dependencies and packages
3. Place a RadzenDropdown next to a RadzenTextBox using the bootstrap grid system
4. The vertical placement of the components is inconsistent

<img width="1468" alt="RadzenScreenshot" src="https://user-images.githubusercontent.com/105650714/206277464-8f4bb295-8144-4229-abbb-6829bc9016c0.png">

And on your website

<img width="1252" alt="AnotherRadzenScreenshot" src="https://user-images.githubusercontent.com/105650714/206277716-91f46f07-d2dc-4bd6-8314-d3894eddb365.png">

 - OS: Windows 11
 - Browser: Edge

This problem is also occurring on your official website, so I doubt it is a problem on my end of things.

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/c99e82bd8e843c116c4b586ee3e2bdad04b94cbb
