### ISSUE TITLE
Right-click context menu does not work on iPhones

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#743]
It seems it is not possible to open the context menu on iPhones.

To reproduce the issue please open the context menu demo example and try to use "long-tap" to open the context menu.
Context menu will not open.
[https://blazor.radzen.com/contextmenu](https://blazor.radzen.com/contextmenu)

Or is there any trick I need to do in my application to activate the correct behavior?

**Comment by enchev** [comment]
https://bugs.webkit.org/show_bug.cgi?id=213953

**Comment by OndrejUzovic** [comment]
The problem is present not only on Safari but on Chrome too.
But maybe it is the same bug as you mentioned.

**Comment by enchev** [comment]
Chrome and Safari on iOS are using both WebKit

**Comment by OndrejUzovic** [comment]
Thanks for the clarification.
