### ISSUE TITLE
Add Dropdown Component Footer

### ISSUE THREAD

**Issue by lenardchristopher** [radzenhq/radzen-blazor#744]
**Is your feature request related to a problem? Please describe.**
Add a footer template to the dropdown list.

**Describe the solution you'd like**
A render fragment template for a footer

**Describe alternatives you've considered**
I tried to extend Radzen's DropDown component myself, but many of the methods and properties used are internal to the package.

**Additional context**
Examples
[Syncfusion](https://blazor.syncfusion.com/documentation/dropdown-list/templates#footer-template)
[Telerik](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist/configuration/footertemplate)

**Comment by enchev** [comment]
You can use DropDownDataGrid with single column where you can define, Template, HeaderTemplate and FooterTemplate:
![image](https://user-images.githubusercontent.com/5804953/214520925-a1039f71-7ef1-430a-928e-5277a395101b.png)
![image](https://user-images.githubusercontent.com/5804953/214521047-26347155-50b4-4960-920b-5e11d0c8ed02.png)
