### ISSUE TITLE
Radzen Controls not working on .Net Maui Blazor App Ios Device in Release Mode

### ISSUE THREAD

**Issue by NEHAMAZIK** [radzenhq/radzen-blazor#751]
Radzen controls are working fine on Web and Android both in Debug and Release Configurations but they are not working on ios device in release mode in .net 7 , app crashes in release mode with Radzen UI controls , i am using visual studio 2022 preview 17.5 version  targets framework  .net 7 .
it would be of great help if someone would come up with the solution to this issue ASAP.
thankyou

**Comment by dstillwell** [comment]
I have been able to get Radzen controls working by enabling the interpreter for Release builds.

```
<PropertyGroup>
  <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

**References**
https://github.com/dotnet/maui/issues/13019

**Comment by akorchev** [comment]
Closing as there doesn't seem to be anything we can do to address that.
