### ISSUE TITLE
Feature/behavior request: make min with of enum simple-mode filter in data grid much smaller.

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#757]
**Is your feature request related to a problem? Please describe.**
If datagrid in the simple filter mode has an enum filter, the minimum width of this filter is too big causing the column consumes too much space - otherwise the filter is not properly visible.

E.g. in case of an one letter enum the minimum width of the column is:
![image](https://user-images.githubusercontent.com/55758368/209798589-9e6cc4c8-0789-47dc-a7f9-379fa77f075b.png)

In case the column width is smaller the filter buttons gets hidden:
![image](https://user-images.githubusercontent.com/55758368/209797436-10707e80-a54d-4ffd-a470-487c3c487f42.png)

**Describe the solution you'd like**
Please adjust the minimum width of the enum simple-mode filter in datagrid so that it can be much smaller.
Or provide a variable to change the default value.

The simple code to test the behavior:
```
@page "/"

@using Radzen;
@using Radzen.Blazor;

<div style="width:700px; height:500px; background-color:beige;">
    <RadzenDataGrid TItem="Person" Data="@myPersons" FilterMode="FilterMode.Simple"
                    AllowFiltering=true AllowColumnResize=true>
        <Columns>
            <RadzenDataGridColumn TItem="Person" Property="Name" />
            <RadzenDataGridColumn TItem="Person" Property="Gender" />
        </Columns>
    </RadzenDataGrid>
</div>


@code {
    private enum Gender
    {
        M,
        F,
        U
    }
    private class Person
    {
        public string Name { get; set; }
        public Gender? Gender { get; set; }
    }

    private List<Person> myPersons;

    protected override void OnInitialized()
    {
        myPersons = new List<Person>()
        {
            new Person() { Name = "Chuck", Gender = Gender.M },
            new Person() { Name = "Lisa", Gender = Gender.F },
            new Person() { Name = "Bla", Gender = Gender.U },
        };
    }
}

```

**Comment by akorchev** [comment]
The filter width is determined by the column width.
