### ISSUE TITLE
Using Blazor native `InputFile` with `OnChange` event inside the `RadzenTemplateForm` resets the selected file immediately

### ISSUE THREAD

**Issue by kalai-logicsoft** [radzenhq/radzen-blazor#760]
**Describe the bug**

Using Blazor native `InputFile` with `OnChange` event inside the `RadzenTemplateForm` resets the selected file immediately on after selecting the file. 

I have a `RadzenTemplateForm` with Blazor native `InputFile` component and submit button inside the `RadzenTemplateForm`. On selecting a file in from the `InputFile` component, i have to remember the file and allow the user to submit the form / select another file. In this case when the user selects the file it got unselected immediately.

While debugging the `OnChage` event triggers and `InputFileChangeEventArgs` has the selected file. on after that `InputFile` resets to the unselected state. 

Further debugging results, It's causing problem on after `Radzen.Blazor 4.4.4` update. I have tested the same situation with `Radzen.Blazor 4.4.3` it is working fine. No changes on any place except `Radzen.Blazor 4.4.4` update.

**To Reproduce**
1. Use `Radzen.Blazor 4.4.4` or later
2. Place a blazor native `FileInput` with `OnChange` event inside a `RadzenTemplateForm`
 ```
<RadzenTemplateForm TItem="long" Submit="@OnSubmit">
    <RadzenFieldset Text="With Radzen Form">
            <div class="col-12">
                <div class="form-group">
                    <RadzenLabel Text="File Input with OnChangeEvent" />
                    <InputFile class="form-control" OnChange="OnInputFileChange" accept=".xlsx" required />
                </div>
            </div>
        </div>
        <div class="row">
            <RadzenButton ButtonType="ButtonType.Submit" Text="Submit" />
        </div>
    </RadzenFieldset>
</RadzenTemplateForm>
``` 
3. Run the Program
4. Click on Input file, Select any file you want
6. Now the file got disappeared
7. Move back to `Radzen.Blazor 4.3.3`
8. Now try again, file will be selected

Alternatively, I have attached the working [Sample Repository](https://github.com/kalai-logicsoft/RadzenBlazorFileInputSample) for the understanding of the problem 

**Expected behavior**
On Selecting any file it should not disappeared / cleared

**Screenshots**
![msedge_OoGKWNZh2x](https://user-images.githubusercontent.com/70625103/210547838-2f36cfc4-eb62-4442-965b-5c5e7f046785.gif)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Home Single Language
 - Browser `Microsoft Edge`
 - Version `108.0.1462.54 (Official build) (64-bit)`

**Comment by shrayasr** [comment]
Team, a little more context: 

I checked a little more at the DOM level and found that on `4.4.4` whenever I select an item via a `InputFile` component which has a `OnChange` associated, the entire form gets rewritten? 

I found this out by checking the ID(?) that is given to the radzen form and it changed from `_bl_a25e8208-f38b-4711-ab21-f763efd6a237` to `_bl_3cc56395-7292-47cb-9522-0b09ebc74bd9` once I selected the file.

I checked this using the project that @kalai-logicsoft has linked above.

**Comment by akorchev** [comment]
We've made a change so RadzenTemplateForm behaves as the built-in EditForm. For example this fails in the same way without using any Radzen component:

```
<EditForm TItem="long" Model="model" Submit="@OnSubmit">
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <InputFile class="form-control" accept=".xlsx" required />
            </div>
        </div>

        <div class="col-12">
            <div class="form-group">
                <InputFile class="form-control" OnChange="OnInputFileChange" accept=".xlsx" required />
            </div>
        </div>
    </div>
    <div class="row">
    </div>
</EditForm>

@code {
    long model = 10;
    private void OnInputFileChange(InputFileChangeEventArgs e)
    {
        Console.WriteLine($"Input file selected.[FileName= {e.File?.Name}]");
    }

    private void OnSubmit()
    {
        Console.WriteLine($"Form submitted");
    }
}
```

The fix is not to use `long` as model for example (also fixes EditForm):

```
<RadzenTemplateForm TItem="MyModel" Submit="@OnSubmit">
    <RadzenFieldset Text="With Radzen Form">
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <RadzenLabel Text="File Input without OnChangeEvent" />
                    <InputFile class="form-control" accept=".xlsx" required />
                </div>
            </div>

            <div class="col-12">
                <div class="form-group">
                    <RadzenLabel Text="File Input with OnChangeEvent" />
                    <InputFile class="form-control" OnChange="OnInputFileChange" accept=".xlsx" required />
                </div>
            </div>
        </div>
        <div class="row">
            <RadzenButton ButtonType="ButtonType.Submit" Text="Submit" />
        </div>
    </RadzenFieldset>
</RadzenTemplateForm>

@code {
    class MyModel
    {

    }

    private void OnInputFileChange(InputFileChangeEventArgs e)
    {
        Console.WriteLine($"Input file selected.[FileName= {e.File?.Name}]");
    }

    private void OnSubmit()
    {
        Console.WriteLine($"Form submitted");
    }
}
```
