### ISSUE TITLE
Datepicker - open popup on click input

### ISSUE THREAD

**Issue by johanpolak** [radzenhq/radzen-blazor#767]
**Is your feature request related to a problem? Please describe.**
We would like the popup for the datepicker to be opened on click of the input.

**Describe the solution you'd like**
The easiest way for us would be that the function 'getOpenPopupForInput' in RadzenDatePicker.razor.cs will be made virtual, so we can overwrite it in our application.

**Comment by enchev** [comment]
You can simply add the following
![image](https://user-images.githubusercontent.com/5804953/211799001-49da1b5e-7bbe-4d06-baec-b023b04967f7.png)

**Comment by johanpolak** [comment]
Hi Vladimir,

That looks like a great solution! The only problem with this approach is
that the click on the button in the datepicker makes the panel appear and
directly disappear again.

Kind regard,

Johan Polak


Op wo 11 jan. 2023 om 12:50 schreef Vladimir Enchev <
***@***.***>:

**Comment by johanpolak** [comment]
@enchev This isn't a good solution. Any other ideas?
