### ISSUE TITLE
Issue with the dropdown window of DropDownDataGrid as of version 4.5.0

### ISSUE THREAD

**Issue by Linkaaaaa** [radzenhq/radzen-blazor#770]
Hello, have noticed this behaviour after updating from version 4.4.9 to 4.5.0 and is still present in 4.5.2

How clicking on the dropdown looks like in 4.4.9:

![1](https://user-images.githubusercontent.com/23245218/212331055-72885bc7-178d-4e8e-b1f0-a07f07207631.png)

How it looks like in versions >= 4.5.0

![2](https://user-images.githubusercontent.com/23245218/212331132-066b7da8-4e73-4e55-ace2-2eb3a636ea08.png)

As you can see, the placement of the window is dislocated from the actual element, behaviour that wasn't present in previous versions.

The code of the dropdown is the following:

![3](https://user-images.githubusercontent.com/23245218/212332611-7c39e9e5-37c6-4bfe-b746-1daab36da3db.png)

Currently utilizing Radzen.Blazor in a .NET Maui Blazor project, platform is Windows 10.0.19045.2486 on the latest Visual Studio Community version.

**Comment by enchev** [comment]
I'm afraid that I'm unable to reproduce such behavior
![image](https://user-images.githubusercontent.com/5804953/212620797-789a74d8-ac4b-4657-9eda-03c0aba53677.png)
![dd-maui](https://user-images.githubusercontent.com/5804953/212620729-5432f748-30f9-4b77-98d6-39ca194a633a.gif)
You can attach the source code of Radzen.Blazor to your project to debug your scenario.

**Comment by iNenadnano** [comment]
Hello @enchev, I have the same problem as @Linkaaaaa but in 
Blazor Server project. The issue occurs in Edge only, not in Chrome, and depends on page scroll position. Please observe the behavior I am experiencing below. On the left is Chrome with a dropdown selected in the last (20th) table row, while on the right is Edge with the same dropdown selected.
![image](https://user-images.githubusercontent.com/652920/213417544-e0bfbf97-a66d-4c7d-a9f9-ca21af2fc29a.png)
The code I am using is as follows:
```
@page "/"
@using System.ComponentModel;
@using System.Reflection;

<table class="rz-grid-table rz-grid-table-striped">
    <thead>
        <tr>
            <td><RadzenText TextStyle="TextStyle.H6">Heading</RadzenText></td>
        </tr>
    </thead>
    <tbody>
        @for (int i = 1; i < 21; i++)
{
    <tr>
                <td>
                    <div class="row mt-2">
                        <div class="col-sm-4 col-lg-2 col-12">
                            @i
                            <RadzenText TextStyle="TextStyle.Subtitle2">Nivo</RadzenText>
                            <RadzenNumeric Name="TankLevel" @bind-Value=@level TValue="decimal" Style="width:50%" Step="0.1" Format="0.0" />
                            <RadzenDropDown @bind-Value="@unit" TextProperty="Text" ValueProperty="Value" Style="width:50%;"
                                        Data="@(Enum.GetValues(typeof(LevelUnits)).Cast<LevelUnits>().Select(t => new { Text = GetEnumDescription(t), Value = t }))" />
                        </div>
                    </div>
        </td>
    </tr>
}
    </tbody>
</table>

@code {
    private LevelUnits unit = LevelUnits.cm;
    private decimal level;
    public enum LevelUnits
    {
        [Description("%")]
        percent,
        [Description("cm")]
        cm
    }

    public static string GetEnumDescription(Enum value)
    {
        FieldInfo? fi = value.GetType().GetField(value.ToString());
        if (fi != null)
        {
            if (fi.GetCustomAttributes(typeof(DescriptionAttribute), false) is DescriptionAttribute[] attributes && attributes.Any())
            {
                return attributes.First().Description;
            }
        }

        return value.ToString();
    }
}
```

**Comment by Linkaaaaa** [comment]
Hello @iNenadnano 

I've just tested the latest release 4.6.2 and the issue seems to have been resolved. If you haven't yet, i suggest giving that release a try!

Thanks to the team for the fix!
