### ISSUE TITLE
Save column width when using column resize (Datagrid)

### ISSUE THREAD

**Issue by onemoreuserinthisworld** [radzenhq/radzen-blazor#771]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by onemoreuserinthisworld** [comment]
I apologize, for whatever reason it did not post my issue.
I am trying to request a feature where the column width can be saved on resizing it.

**Comment by enchev** [comment]
This demo shows how to save various settings including column width after resize:
https://blazor.radzen.com/datagrid-save-settings
![image](https://user-images.githubusercontent.com/5804953/212354787-c8718b7d-0f80-4b78-80c9-a941a9710801.png)

**Comment by onemoreuserinthisworld** [comment]
Great!
Thanks for the info!
