### ISSUE TITLE
[RadzenDataFilter] Wrong input type when configuring the property dynamically

### ISSUE THREAD

**Issue by benghaner** [radzenhq/radzen-blazor#778]
**Describe the bug**
We are using a DropDown to configure a RadzenDataFilter. The RadzenDataFilter works as expected at first. However, when the DropDown value is changed, the input type of the new filters are incorrect. See [sample project](https://github.com/benghaner/bug-reports/tree/main/DataFilterWrongInputType).

**To Reproduce**
1. See linked [sample project](https://github.com/benghaner/bug-reports/tree/main/DataFilterWrongInputType).
2. Select "Collection 1" from the DropDown.
3. Select + to add a filter.
4. Observe the first field "DateTime Field" and the input type is DateTime. Working as expected.
5. Select "Collection 2" from the DropDown.
6. Select + to add a filter.
8. Observe the new filters available. E.g. "Boolean Field" but the input type is still DateTime.

**Expected behavior**
When the filters are cleared, the new filters will have the correct input type.

`Change="@(() => _dataFilter.ClearFilters())"`

**Screenshots**
![image](https://user-images.githubusercontent.com/78243998/213301791-0a48a4c0-3654-4583-9188-4098122a9af6.png)

**Desktop (please complete the following information):**
 - Windows
 - Chrome Version 108.0.5359.125

**Comment by groogiam** [comment]
I'm also seeing strange behavior in the ordering of the properties in the dropown when dynamically rendering the RadzenDataFilter properties. This looks like it is due to the caching of the property definitions internally on RadzenDataFilter component.

**Comment by enchev** [comment]
Unable to reproduce it using the latest version.
