### ISSUE TITLE
Closing Blazor Dropdown without selection "steals" focus

### ISSUE THREAD

**Issue by matjankow** [radzenhq/radzen-blazor#782]
**Description**
Using the Radzen Dropdown and clicking in another text field withou selecting an item sets the cursor out of the textfield.

**To Reproduce**
Steps to reproduce the behavior (see attached sample)

- Open the drodown on the left (do not select an item)
- Click into the textarea on the right

-> Cursor is gone from the textarea (I assume back to the DropDown)

**Expected behavior**
Cursor stays in the control last clicked

OS: Windows
Browser: Chrome
Version 4.6.2

[FocusBugRepro.zip](https://github.com/radzenhq/radzen-blazor/files/10499549/FocusBugRepro.zip)

**Comment by enchev** [comment]
Fixed in https://github.com/radzenhq/radzen-blazor/commit/7455d1bfb255afe543f1eb1c090ab6bb7a6d079a
