### ISSUE TITLE
Radzen datagrid cant filter on negative numbers

### ISSUE THREAD

**Issue by pierresetteskog** [radzenhq/radzen-blazor#788]
Radzen datagrid cant filter on negative numbers. Try fill in -5 

1. Go to https://blazor.radzen.com/datagrid-performance
2. Click filter on Unit Price
3. try fill in -5 and Apply
4. the number will lose the minus sign which is not expected.
5. The down pile on the number box can go down to -5 ,  double and int can be negative

**Comment by pierresetteskog** [comment]
please note!
The example https://blazor.radzen.com/datagrid-odata dont seems to have any number fields in the example.
Then it would have showed that negative numbers must be filtered like
UnitPrice = (-1) 

otherwise dynamic linq will fail which is strange
https://dynamic-linq.net/expression-language

**Comment by enchev** [comment]
I'm afraid that I cannot reproduce such problem:
![image](https://user-images.githubusercontent.com/5804953/216053762-b3d7cbd9-129d-401b-803f-72fd17ee2978.png)

**Comment by pierresetteskog** [comment]
Its something with the locale when its sv-SE (Sweden) the minus sign disappears on the blur event , can be tested like the picture bellow.
![image](https://user-images.githubusercontent.com/4455363/216612574-3a531fac-ddfc-4631-b59b-1c1468e62867.png)
