### ISSUE TITLE
RadzenDataGrid: ContexMenu dont work correctly on right click

### ISSUE THREAD

**Issue by BaggerFast** [radzenhq/radzen-blazor#789]
**I use the RadzenDataGrid component**
1) When I **left-click** on a line, it is highlighted. This is the correct behavior
![image](https://user-images.githubusercontent.com/54527361/216247818-6726aacd-59fe-4572-8227-a2741453dc63.png)
2) But when I right-click to get the context menu, the highlighted line does not change. [Although on the official example, everything works as I need it.](https://blazor.radzen.com/datagrid-cell-contextmenu)
![image](https://user-images.githubusercontent.com/54527361/216247893-a6d97423-80ce-4801-8503-294c18f52152.png)
3) Source code
![image](https://user-images.githubusercontent.com/54527361/216248783-d3771492-1648-4358-ace0-b939e38fe0d7.png)

**Comment by enchev** [comment]
Our example explicitly selects the row on right click - check the code for reference.

**Comment by BaggerFast** [comment]
https://user-images.githubusercontent.com/54527361/216561973-04386b6e-c22c-4098-87a9-fa7690e259c3.mp4

**Comment by BaggerFast** [comment]
Its not the same behaviour as in your example. **I try to fix this over 1 week. Ist not working**
