### ISSUE TITLE
Cannot use RadzenComponent.Element in inheritance

### ISSUE THREAD

**Issue by bazarniy** [radzenhq/radzen-blazor#79]
Hi guys! 
I'm trying to make my oun component inherited from RadzenComponent. Element property has "internal set". So using @ref="@Element" generates compile errors.

UPDATE

**Is your feature request related to a problem? Please describe.**
Cannot use "Element" property in RadzenComponent after inheritance

**Describe the solution you'd like**
Make protected or public setter there

**Describe alternatives you've considered**

**Additional context**
https://github.com/radzenhq/radzen-blazor/blob/a5293d714b7cfdb934cd01982ff7d5b46962deef/Radzen.Blazor/RadzenComponent.cs#L14

**Comment by akorchev** [comment]
This issue does not follow any of the accepted templates as well as your other issues. Please address that.
