### ISSUE TITLE
[RadzenDataFilter] Improve the style for boolean filters

### ISSUE THREAD

**Issue by benghaner** [radzenhq/radzen-blazor#790]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
In the RadzenDataFilter, would like to see the user interface for boolean filters be more obvious. Currently, it shows a small tri-state checkbox. Relative to the rest of the component, it's less noticeable, especially as the screen gets wider. For example, it could be dropdown of "true" or "false" instead.

**Describe alternatives you've considered**
N/A

**Additional context**
Example currently:
![RadzenDataFilter Boolean](https://user-images.githubusercontent.com/78243998/216380067-aab97eb6-2d33-4599-b152-ebbcebde3c48.jpg)

Example alternative:
![ServiceNow Boolean](https://user-images.githubusercontent.com/78243998/216377317-4895c346-a41e-4af0-b2a3-08d488463eae.jpg)

Thanks for your consideration!

**Comment by enchev** [comment]
We will unable to do that since it will be breaking change, will require additional localization, etc. You can define FilterTemplate with desired UI for your case.
