### ISSUE TITLE
Feature request - add posibility to set 'AllowInput' on DatePicker in DataGrid filtering

### ISSUE THREAD

**Issue by johanpolak** [radzenhq/radzen-blazor#797]
The property 'AllowInput' in the datepicker for filtering in the DataGrid is always set to false:
https://github.com/radzenhq/radzen-blazor/blob/f4c776f10ec6bce372452b8d302c377c3785d712/Radzen.Blazor/RadzenDataGrid.razor#L254

I would like to be able to type in the inputfield. It would be great if the value of this property can be changed using a parameter.

**Comment by enchev** [comment]
You can define your own column FilterTemplate:
![image](https://user-images.githubusercontent.com/5804953/217474070-2283300f-21e6-416f-8e98-cd0e9575e853.png)
![image](https://user-images.githubusercontent.com/5804953/217474415-d9fe1910-e68d-4ae1-b065-303cd73abd6c.png)

**Comment by johanpolak** [comment]
Hi Vladimir,

Thanks for your quick reply. Defining the FilterTemplate will work fine for the data grid when filter mode is 'Simple', but we use filter mode 'Simple with menu', so if we define our own filter template, the menu disappears. Therefore it would be great if you could add a parameter.
