### ISSUE TITLE
RadzenTree: Children of a checked parent only show up in CheckValues if the children level is expanded.

### ISSUE THREAD

**Issue by CReizner** [radzenhq/radzen-blazor#814]
**Expected behavior**
When I check a parent node, all children are also checked (with parameter AllowCheckChildren="true"). The childrens should show up in CheckedValues (if @bind-CheckedValues is used) even if they are not visible.

**Comment by enchev** [comment]
This is how the component works - child nodes are unknown when the parent is checked since they are now yet loaded. If we need to check all child nodes on parent node check we might end with serious performance problems since to check the child nodes we must load them and they might be millions.
