### ISSUE TITLE
Error duing Form validation

### ISSUE THREAD

**Issue by prrandrade** [radzenhq/radzen-blazor#816]
Hello everyone, this is a continuation of https://github.com/radzenhq/radzen-blazor/issues/815

I found the problem! :-D

'@bind-value' (with a lowercase 'v') does not trigger the validation, but the binding continues to work.
'@bind-Value' (witha Uppercase 'v') resolves the problem.

I think this is a bug, isn't it?

**Comment by akorchev** [comment]
This isn't a but - the property is called Value and casing is important. Unfortunately we haven't found a way to detect this case as Radzen Blazor components support custom attributes as well. In this case `@bind-value` is treated as a custom attribute.
