### ISSUE TITLE
RadzenSidebar always expands even when Epanded = false.

### ISSUE THREAD

**Issue by PaulSinnema** [radzenhq/radzen-blazor#818]
**Describe the bug**
The new RadzenSidebar component keeps expanding even when I set the 'SidebarExpanded' to false. Some anonymouse method is called and sets the 'SidebarExpanded' to true resulting the Sidebar to expand.

**To Reproduce**
1. Take the code from the example of the 'Right sidebar'
2. Change the code 'bool sidebar4Expanded = false;'
3. Run the page

If I set a breakpoint on the setter of the boolean I can see it is called from an anonymous function which sets it to 'true'.

**Expected behavior**
If the boolean is 'false' on startup the sidebar should not show as expanded.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser FireFox
 - Version v4.7.1

**Comment by akorchev** [comment]
Sounds duplicate to https://github.com/radzenhq/radzen-blazor/issues/716.

**Comment by PaulSinnema** [comment]
Yup, is the same.
