### ISSUE TITLE
The RadzenTooltip is not showing when I put the <RadzenTooltip/> in the _Layout.cshtml

### ISSUE THREAD

**Issue by PaulSinnema** [radzenhq/radzen-blazor#819]
**Describe the bug**
The RadzenTooltip is not showing when I put the < RadzenTooltip /> in the _Layout.cshtml and hover over the component that call the ShowTooltip although the routine is called.

**To Reproduce**
1. Do all the steps described in the Get Started documentation (In there it states you should add the < RadzenTooltip /> to the _MainLayout.razor. I'm writing a server hosted Blazor application which does not have that, it has a _Layout.cshtml so I put it in there.
2. Create a Blazor page and add the following code:

```
        <RadzenIcon Icon="assignment" MouseEnter="@(args => @ShowTooltip(args))" />

        void ShowTooltip(ElementReference elementReference) => tooltipService.Open(elementReference, "Some content", new TooltipOptions() { Position = TooltipPosition.Top });
```
3. Run the program and hover over the icon with your mouse.
4. No Tooltip is shown.

If however I place the < RadzenTooltip /> tag inside the page that is rendered the tooltip does show.

Expected behavior
Tooltip should show on hover over the component.

 - OS: Windows 11
 - Browser FireFox
 - Version v4.7.1

**Comment by enchev** [comment]
You can check our demos and Getting Started for reference.

**Comment by PaulSinnema** [comment]
@enchev : I found the solution in the meantime. I should have reported back here, sorry. It should be in the Mainlayout.razor and it works perfectly.
