### ISSUE TITLE
Restoring grid settings not working since latest changes

### ISSUE THREAD

**Issue by mcristelo** [radzenhq/radzen-blazor#824]
When loading the DataGrid with previous settings containing a filtered column, it will not filter the data as it was doing previously. This happen after upgrading from 4.2.3 to the latest version (4.7.1).

**Comment by enchev** [comment]
Works normally on our demo and we’ve not changed anything. You can attach the source code of Radzen.Blazor to your project to debug your case - if you think you have a fix for something feel free to submit pull request.

**Comment by mcristelo** [comment]
I did some more testing and this can be replicated on the [`LoadData Binding example`](https://blazor.radzen.com/datagrid-save-settings-loaddata)
If you filter by title, for example, and then reload the page, the filter value will be kept but the grid won't be filtered. What happens is the filter passed to the LoadData function is empty.
This is not an issue on the IQueryable example.
