### ISSUE TITLE
RadzenDropDown Not Automatically Focus on SearchBox When Opening DropDown 

### ISSUE THREAD

**Issue by fericode** [radzenhq/radzen-blazor#83]
**Describe the bug**
RadzenDropDown component works nicely, except for not focusing on the search box when opening the dropdown. It works in the demo page, but not works on my device with multi tests.

**To Reproduce**
1. Add Radzen to a new VS hosted web assembly template project
2. Check it out

**Expected behavior**
Focus on Searchbox automatically when opening dropdown.

**Desktop (please complete the following information):**
 - OS: Windows 10 64Bit
 - Browser Chrome 89.0.4389.90
 - Visual Studio 16.9.2 community
 - .Net 5
 - Web Assembly Hosted model of VS template project
 - Radzen.Blazor 3.1.7

**Comment by enchev** [comment]
Hey @fericode,

Indeed it works normally on our demo. You can attach the source code to debug why it's not working for you.

**Comment by fericode** [comment]
Hi again Vladimir
Thanks for the reply. I get the source code and from the first look, I suspected the issue cause is Blazor Server. I created the same VS Blazor template project as I described above, with the exact same config, but this time I chose Blazor Server instead of Blazor Web Assembly and it worked in my machine like the source code which is in Blazor Server too.
I think the issue would happen only in Web Assembly mode. Can you check it out, please?

**Comment by stcpottdav** [comment]
This issues still seems to happen in the latest release when running under Blazor Web Assembly.  It does not happen when running under Blazor Server.  Is there a reason this issue was closed?

**Comment by fericode** [comment]
Unfortunately, this issue still exists, and because I do not have the time and maybe the knowledge to fix the issue and the owner relied on me to fix it (I believe it was the reason to close the issue!), I use another package for my dropdowns in Blazor WebAssembly. 
Thanks
