### ISSUE TITLE
DataGrid @bind-Settings with Filter parameter are not working properly

### ISSUE THREAD

**Issue by kmrzyglod** [radzenhq/radzen-blazor#831]
**Describe the bug**
When both @bind-Settings and Filter input parameters are used then filtering is not working at all - 
 e.g. after typing something inside simple text filter the filter value is removed.

**To Reproduce**
1. Create data grid and use input parameters @bind-Settings and Filter 
2. Run the app
3. Try to add filter on some column 
4. Instead of applying the filter the filter value is removed. 

This can be reproduced by introducing some small modifications  to the official demo "datagrid-save-settings-loaddata": 
1. Add OnFilter method
`
   protected Task OnFilter(DataGridColumnFilterEventArgs<Employee> args)
    {
        return Task.CompletedTask;
    }
`
2. Use this method in "Filter" input parameter
`
 <RadzenDataGrid @bind-Settings="@Settings" AllowFiltering="true" AllowColumnPicking="true" AllowGrouping="true" AllowPaging="true" PageSize="4"
                AllowSorting="true" AllowMultiColumnSorting="true" ShowMultiColumnSortingIndex="true" 
                AllowColumnResize="true" AllowColumnReorder="true" ColumnWidth="200px"
                FilterPopupRenderMode="PopupRenderMode.OnDemand" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive" 
                Data="@employees" IsLoading=@isLoading Count="@count" LoadData=@LoadData TItem="Employee" Filter="@OnFilter">
`

**Expected behavior**
Filter is properly applied

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 109.0.5414.121

**Comment by enchev** [comment]
I've added Filter callback in this demo: https://blazor.radzen.com/datagrid-save-settings-loaddata 
![image](https://user-images.githubusercontent.com/5804953/221114841-dbd3faa4-a591-4513-928d-72a522597e6e.png)
and everything worked as expected:
![dd-settings-filter](https://user-images.githubusercontent.com/5804953/221115138-792c2471-dae8-4791-a62c-f85d06689d7e.gif)

**Comment by kmrzyglod** [comment]
@enchev In the Server version, it's working fine. But the issue is occurring in WebAssembly version, I forget to add information about that to the bug description.

**Comment by kmrzyglod** [comment]
@enchev This issue is still occuring. Could you reopen it?
