### ISSUE TITLE
Feature request: DataGrid built-in search by all columns similar to DataTables 

### ISSUE THREAD

**Issue by marekott** [radzenhq/radzen-blazor#833]
**Is your feature request related to a problem? Please describe.**
In Datatables there is a neat feature of search input not related with any specific column but rather whole table. It allows to provide multiple words as inputs delimited with space. All rows containing all of the provided inputs are shown after confirming. Since we are migrating from Datatables to Radzen components it would be great if this feature was also available in you library without need to implement it by ourselves. 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/46067021/221509564-9664dac9-33d3-4b3d-b799-44d099597d31.png)

![image](https://user-images.githubusercontent.com/46067021/221509453-7afdd0f5-ff94-4f14-9ee4-6e5de1551934.png)

https://datatables.net/

**Describe alternatives you've considered**
This feature was already available in our application so we can't drop its support after migrating to Radzen components. Since it's not implemented in you library the only solution for now would be to write this input search ourselves. I'm sure this is a great feature and lot of people would appreciate and use it.

**Comment by enchev** [comment]
Hey @marekott,

This is part of our CRUD templates in both Radzen IDE and Radzen Blazor Studio:
![image](https://user-images.githubusercontent.com/5804953/221513199-fdd06ea6-84da-44e4-8cd8-ce59a28815be.png)
![image](https://user-images.githubusercontent.com/5804953/221513346-632673a9-7cee-46c4-9f87-da160d85dc81.png)

**Comment by marekott** [comment]
Hi @enchev, thank you for an immediate response. Is there any chance that possibility of generating this search will be available on component level (so it can be configured from Visual Studio etc.)?

**Comment by enchev** [comment]
We don't have plans to add such feature in the near future however we accept pull requests.

**Comment by marekott** [comment]
Ok, thanks
