### ISSUE TITLE
Dropdown with Group checkbox to select and unselect group items 

### ISSUE THREAD

**Issue by khalilsheikh** [radzenhq/radzen-blazor#835]
Dropdown Group By seems to be incomplete or immature.

it should support group template and item template.

data structure for data binding of group should be like nested node e.g:
Country1
....State1
.......County1
.......County2
....State2
.......County1
.......County2
....State2
.......County1
.......County2
Country2
....State1
.......County1
.......County2
....State2
.......County1
.......County2
....State2
.......County1
.......County2

**Comment by akorchev** [comment]
Please follow the issue template. We are not sure what you are trying to say or request at the moment.

**Comment by enchev** [comment]
Hey @khalilsheikh,

DropDown grouping is not a feature of the component - it's an example. You can use the Template to define whatever extra UI you need and additional logic.
