### ISSUE TITLE
RadzenSplitButton - strange scroll behaviour

### ISSUE THREAD

**Issue by marekott** [radzenhq/radzen-blazor#840]
**Describe the bug**
When `RadzenSplitButton` component is used with a lot of subitems, strange scroll behavior can be observed. Instead of the scroll showing inside a control, it is rendered next to page scroll (see below screens) and using it causes scrolling through empty page as there are two separate scrolls now and page one is not scrolling. Is it desired behavior? Shouldn't it behave similar to `RadzenDropDown` scroll?

**To Reproduce**
Create `RadzenSplitButton` with lot of options that do not fit into page vertically. Documentation page can be used: https://blazor.radzen.com/splitbutton. Add a lot of options for any of the split buttons and click on it. Scroll down with cursor inised split button options.

**Expected behavior**
Would't it be a better user experience if the scroll would be rendered similar to `RadzenDropDown`?
![image](https://user-images.githubusercontent.com/46067021/222427316-8111389e-5514-42f7-af17-3bfcafc19277.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/46067021/222426982-d7c57f36-241c-4ed5-8cfa-948aa4b5f5e3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Radzen.Blazor - 4.6.2, Chrome - 110.0.5481.177

**Comment by akorchev** [comment]
We don't think a splitbutton should have so many options to require a scroll to appear. Still you can achieve that with CSS if you need it (or use RadzenDropDown).

```
.rz-splitbutton-menu {
   overflow: auto;
   max-height: 100px;
}
```
