### ISSUE TITLE
Change empty tags to self closing tags in example

### ISSUE THREAD

**Issue by AlexChadwickP** [radzenhq/radzen-blazor#843]
**Describe the bug**
On the product website (https://blazor.radzen.com/), I'm seeing quite a few empty tags in the examples. For instance:
```cs
<RadzenButton Text="Test button"></RadzenButton>
```

Instinctively, I am lead to think that I could put `"Test button"` in between the `RadzenButton` tags instead of in a `Text` parameter. It is only after I experimented that I found out that this is not the case. I think self-closing tags would help in this aspect a little bit.

While it isn't exactly a huge problem, I think it's a good practice for tags that don't have children, to be self-closing, and I think it should be reflected in the examples in the documentation. I have found the documentation to be extremely friendly for beginners otherwise, so I think it would be best to try to show them good practices wherever we can.

What are other peoples thoughts on this?

**Comment by AlexChadwickP** [comment]
Just to be 100% clear, I'm talking about the examples that **are not** under the `/docs` route.

**Comment by akorchev** [comment]
Hi @AlexChadwickP,

RadzenButton [does support child content](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenButton.razor#L12).
