### ISSUE TITLE
Radzen Dropdown does not return selected items

### ISSUE THREAD

**Issue by PouryaMontakhab** [radzenhq/radzen-blazor#845]
Hello guys. I have created an asp.net core application which in, I have used the RadZen dropdown. everything is ok and the component is rendered successfully but when the user clicks on the item and selects them, I am not able to get the selected values. Here is a brief of my code :

this is the razor file which the RadZen dropdown exists there.
![image](https://user-images.githubusercontent.com/45295227/222929435-210e5794-4d51-4f1c-b980-59cdb0cdec27.png)

here is also my .cshtml file which I have wrapped in the razor file in order to use it somewhere else.
![image](https://user-images.githubusercontent.com/45295227/222929494-7ce6e066-c443-4733-880e-99f6f23c85dd.png)

I called it this way: 
![image](https://user-images.githubusercontent.com/45295227/222929518-95b7f22c-6c5d-4827-84a2-b118dc75f644.png)

as you can see in this image, everything is ok 👍 
![image](https://user-images.githubusercontent.com/45295227/222929572-af3b878d-c26b-48c7-8fbc-609f8addef6e.png)

but when I try to get `Model.SelectedValues ` (that I have bonded it in the razor file) when the form is submitted. nothing there on the list.
![image](https://user-images.githubusercontent.com/45295227/222936182-43e8f238-6fc5-4636-b5b5-d41fbd06d3c0.png)

**Comment by PouryaMontakhab** [comment]
I also read that the selected items data type and data list should have the same data type as well so I have changed the selected items data type, unfortunately, it did not work.

**Comment by akorchev** [comment]
I am not sure if Blazor components support your scenario. You can try using the built-in InputSelect and see if it makes a difference. Also I see you have opened a forum thread as well - will close this issue as I don't think there is anything actionable on our side.
