### ISSUE TITLE
Dropdown with autocomplete from API

### ISSUE THREAD

**Issue by Matthewsre** [radzenhq/radzen-blazor#85]
I need to implement something similar to AutoComplete, but with the dropdown. The end result can only contain available values and not allow free text options like the AutoComplete. Additionally the chosen value will have a separate display name from the underlying value (UserName will be searched, but underlying value is the UserId).

Maybe I am missing it, but I could not see a way to use the filter option in a way that would allow me to update the values to results from an API.

I am considering using Blazored Typeahead as an alternative:
https://github.com/Blazored/Typeahead

It has this option to enable the dropdown option:

**EnableDropDown** (Optional - Default: false) - Allows the control to behave as a dropdown

**Comment by enchev** [comment]
Hey @Matthewsre,

This is not feature request nor bug report - more how to.
DropDown demos are here: https://blazor.radzen.com/dropdown 
You can use LoadData event to request your data.

**Comment by Matthewsre** [comment]
@enchev , thank you for pointing me in this direction, but there are issues with using LoadData event example when using a remote subset of data.

In the example the LoadData replaces the entire set of data with the values returned by the filter rather then maintaining a separate set of values for the filter.

Here is an example of results returned:

![image](https://user-images.githubusercontent.com/2955659/112700440-66018880-8e4b-11eb-9820-4b15c3fe60f9.png)

And a result after it is chosen:

![image](https://user-images.githubusercontent.com/2955659/112700488-816c9380-8e4b-11eb-88d5-a58a5d014399.png)

In the scenario where the value is either pre-populated or chosen like above, when you begin typing the existing value will be wiped out, even if no options are chosen:

![image](https://user-images.githubusercontent.com/2955659/112700602-c395d500-8e4b-11eb-862c-cd126c9450ca.png)

After typing
![image](https://user-images.githubusercontent.com/2955659/112700641-d3adb480-8e4b-11eb-9803-0dda1113ede8.png)

Now the value is no longer selected.

I can also reproduce this same behavior on the demo site with the "DropDown with custom filtering":
![image](https://user-images.githubusercontent.com/2955659/112701177-305d9f00-8e4d-11eb-825d-be7494c59656.png)

I can work around this type of behavior, but I wouldn't expect a remote search filter to clear out my existing value and didn't think the LoadData option was a fit when I first came across it since it replaces the entire data set.


Any suggestions for dealing with this scenario, or should this be opened as a feature request or bug?
