### ISSUE TITLE
RadZen Blazor Studio - ApplicationTenant.cs missing!!

### ISSUE THREAD

**Issue by graybis12** [radzenhq/radzen-blazor#855]
OS: Windows 11 x64
DB: MySQL local
Ver : RadZen Blazor Studio 1.5.1 Community Trial

Basically, I want to be able to create a MySQL connection without having to be forced to include a table like RadZen Studio. Nevertheless, I created a dummy table and and it went through. The problem is when I generate the ASP.NET Core Identity generation, it's missing the ApplicationTenant.cs in Models

`error CS0234: The type or namespace name 'ApplicationTenant' does not exist in the namespace 'MyProject.Models' (are you missing an assembly reference?)
`
Any ideas what's happening? 
p.s Authentication works on RadZen Studio!! but not the blazor studio!

**Comment by akorchev** [comment]
Hi @graybis12,

This repository is for issues regarding the Radzen.Blazor component library. Use the forum for Radzen Blazor Studio. Here is a recent thread about this issue: https://forum.radzen.com/t/multi-tenant/13329/14
