### ISSUE TITLE
RadzenPanelMenuItem. I need OnIconClick method

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#864]
Hi!

I want show helpIcon,
and when user click on this icon (or mouse will stand on top),
we show Tooltip with help

Please add OnIconClick method
(and/or mouse on top event)

Thanks

![image](https://user-images.githubusercontent.com/92442252/226563495-0de1bcb4-6fe5-4ded-98a1-c9e281d0f00a.png)

**Comment by akorchev** [comment]
You can use the Template option and handle the click event of whatever element you want. 

```
            <RadzenPanelMenuItem>
                <Template>
                    Buttons <RadzenButton Icon="Help" Click=@(() => HelpClicked("Buttons")) />
                </Template>
            </RadzenPanelMenuItem>
```

**Comment by akorchev** [comment]
Try adding `position: relative; z-index:1`:


```
     Buttons <RadzenButton style="position: relative; z-index: 1" Icon="Help" Click=@(() => HelpClicked("Buttons")) />
```

**Comment by Andrey-2021** [comment]
Thanks,
It work
