### ISSUE TITLE
Radzen Color Picker -> Ability to define Colors for "Show Colors"

### ISSUE THREAD

**Issue by bennimoser** [radzenhq/radzen-blazor#868]
**Is your feature request related to a problem? Please describe.**
I would like to give the User the ability to chose from predefined colors. The given colors are not bad, but i would like to shrink it down to a few.

**Describe the solution you'd like**
Bindable Property for Radzen Color Picker with either a List of string (Hex Strings of Colors) or a List of RadzenColorPickerItems.

**Describe alternatives you've considered**
Writing my own or use another Library for a Color Picker

**Comment by akorchev** [comment]
This is already supported:

```
    <RadzenColorPicker>
       <RadzenColorPickerItem Value="red" />
       <RadzenColorPickerItem Value="blue" />
    </RadzenColorPicker>
```
