### ISSUE TITLE
RadzenDropDown focus issue

### ISSUE THREAD

**Issue by fericode** [radzenhq/radzen-blazor#87]
Hi again @enchev 
Thanks for the reply. I get the source code and from the first look, I suspected the issue cause is Blazor Server. I created the same VS Blazor template project as I described above, with the exact same config, but this time I chose Blazor Server instead of Blazor Web Assembly and it worked in my machine like the source code which is in Blazor Server too.
I believe the issue would happen only in Web Assembly mode. Can you check it out, please?

_Originally posted by @fericode in https://github.com/radzenhq/radzen-blazor/issues/83#issuecomment-806452742_

**Comment by enchev** [comment]
As I suggested in your other issue you can attach the source code and debug the problem and even suggest a fix. We accept pull requests.
