### ISSUE TITLE
Datagrid loses filter and/or Sorting when certain actions occur

### ISSUE THREAD

**Issue by codepend** [radzenhq/radzen-blazor#870]
**Describe the bug**
When using ToolTips or clicking on a button on a row to "EditRow" any current filtering or sorting is removed making the current row move to whatever it's original position was.

**To Reproduce**
1. Create a Datagrid, enable Filtering and or Sorting
2. Include an EditTemplate and create a button to get into Edit Mode (or create a button that does nothing but have a ToolTip on it)
3. Filter or Sort your data, then hover over a ToolTip or click the Edit button
4. Filter and Sorting will clear

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Filtering and Sorting would not be affected by ToolTips or Edit Context

**Screenshots**
![image](https://user-images.githubusercontent.com/76008419/226993021-c680bb08-d1c5-4799-96c1-a2440ce5e8a8.png)
![image](https://user-images.githubusercontent.com/76008419/226993118-7df71aac-cabb-4c8e-b068-e8988ca0feae.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome (Others as well)
 - Version; 110.0.5481.178

*Additional Info
Radzen.Blazor version: 4.7.13

**Comment by enchev** [comment]
I'm unable to reproduce such problem on our in-line edit demo:
https://blazor.radzen.com/datagrid-inline-edit
![sort-edit](https://user-images.githubusercontent.com/5804953/227128341-052a020f-49c0-45c4-8368-4d4291c256b5.gif)
