### ISSUE TITLE
Fixate columns in component data grid

### ISSUE THREAD

**Issue by chrgraefe** [radzenhq/radzen-blazor#88]
**Describe the solution you'd like**
I'm using the data grid component with a lot of columns. I have to scroll to the right, to get to the last columns.
When I try to edit a line via inline editing it is difficult to remember, which line is edited at the moment, if the columns are out of view.

Is it possible to fixate one or more leading columns? Only not fixated columns are scrollable to the rights.

**Comment by enchev** [comment]
At the moment frozen columns are not supported.

**Comment by akorchev** [comment]
Frozen columns will be supported with the upcoming RadzenDataGrid component that will be released soon.
