### ISSUE TITLE
Feature Request - RadzenAutoComplete with custom object/complexe types

### ISSUE THREAD

**Issue by msdevcode** [radzenhq/radzen-blazor#898]
**Is your feature request related to a problem? Please describe.**
Searching for customers, objects etc on-demand with LoadData-method and without RadzenDropDown-component

Current RadzenAutoComplete-component doenst support custom objects/complexe types.

**Describe the solution you'd like**
Extend the current RadzenAutoComplete-component to allow binding/searching custom objects

**Describe alternatives you've considered**
Maybe there is a possibility to add a new radzen-component like this blazor-component:
[Github Blazored/Typeahead](https://github.com/Blazored/Typeahead)

![grafik](https://user-images.githubusercontent.com/115212774/229524650-c836bdba-03c3-4542-abe4-ae0b8aee0cf6.png)

I currently using this one, but the creator unfortunately stopped the main-development.

Would be nice to get a radzen-component like this with radzen-themes and your support.

**Additional context**
I tried to extend the current autocomplete-component at my own fork. I saw RadzenDropDown got custom object support, so i tried to transfer the feature to RadzenAutoComplete, but i failed.

Maybe it fits into your radzen-roadmap

**Comment by enchev** [comment]
Hi @msdevcode,

Not sure I understand the described limitation. All of our examples are using custom objects:
https://blazor.radzen.com/autocomplete

**Comment by msdevcode** [comment]
Hey @enchev 

Oh well, i probably just missed that or failed to use it properly. Nevermind, i will try it again. Thanks for your reply.

**Comment by SchubertDNS** [comment]
Hi,

may I ask again on this topic? I have the same problem and I dont see how this is actually covered,
The Autocomplete expects a value binding to string, the examples are "limited" to this also.

If I compare the code between Autocomplete and Dropdown, I find this difference:
`public partial class RadzenAutoComplete : DataBoundFormComponent<string>`
`public partial class RadzenDropDown<TValue> : DropDownBase<TValue>`

@msdevcode: Did you already achieve the complex object binding without the need to use a string property as separate value binding?

I don't find anything on Autocomplete which is equal to this:
[https://blazor.radzen.com/dropdown-custom-objects](https://blazor.radzen.com/dropdown-custom-objects)

Sorry if my understanding is wrong.

**Comment by msdevcode** [comment]
Hey @SchubertDNS,

i also found out that difference between these classes. I tried to change the DataBoundFormComponent<string> to ...<TValue> at my fork to publish a PR but it failed to get everything working again at RadzenAutoComplete. 

Unfortunately i got no solution and still use the other NuGet i mentioned in my first post.

My english isnt that perfect, maybe i explained my problem with the wrong details or kinda like that. 

I would love to use the RadzenAutoComplete with a complex object binding instead with a "simple" string object.
