### ISSUE TITLE
4.7.13 change hanging PageSize in DataGrid with bound Settings causes an infinite loop.

### ISSUE THREAD

**Issue by SteveWave** [radzenhq/radzen-blazor#899]
This change now causes an infinite loading data loop for me. I am using LoadData on a data set that has 1500 rows. Version 4.7.12 works fine but from this point forward, I am stuck in a loop. I tried setting page size from 5 to 100, but that did not change anything. Please let me know if you need anything from me. This does not appear to be a problem on small datasets that I have (perhaps they are under the page size).

Regards,
Steve

**Comment by enchev** [comment]
I'm afraid that I'm unable to reproduce such problem
![image](https://user-images.githubusercontent.com/5804953/229703993-404e7760-0976-4108-a9c4-b591b67cf36c.png)
![settings-pagesize](https://user-images.githubusercontent.com/5804953/229704709-c86124ad-eff7-4e02-a193-7f22dce5448b.gif)

**Comment by SteveWave** [comment]
Thanks for looking into this. I found the problem. My load data was async.
When I switched to sync it worked. I guess in the earlier version an async
load data worked.
'
Great product, by the way.

Regards,
Steve
