### ISSUE TITLE
Add seprator option in Cell context menu.

### ISSUE THREAD

**Issue by gurjeet2019** [radzenhq/radzen-blazor#900]
Can you please add sepator option in the context menu?

**Comment by enchev** [comment]
https://github.com/radzenhq/radzen-blazor/commit/c92440756989cc5b2be853d125068d64842a47a9

**Comment by gurjeet2019** [comment]
![image](https://user-images.githubusercontent.com/55094664/231663998-fdbd6985-4ed1-485f-9e17-82aeaf0ba12f.png)

Please check given refrence to add seprator line in the context menu.
