### ISSUE TITLE
RadzenTextBox Max length from annotation

### ISSUE THREAD

**Issue by malkeet-gwebs** [radzenhq/radzen-blazor#901]
Please provide the possibility in RadzenTextBox for getting the max length attribute value from the bind filed annotation. Now if Filed max length value is updated in the class then we need to update everywhere in the project. So please add the possibility to do dynamically like we add only the annotation name then max length automatically gets the annotation value

**Comment by malkeet-gwebs** [comment]
Please check

**Comment by enchev** [comment]
Hey @malkeet-gwebs,

Do not use our github issues to demand support.
