### ISSUE TITLE
CTRL-K keystroke instead of button to add hyperlinks in Radzen Blazor HTML Editor component

### ISSUE THREAD

**Issue by ajhopen** [radzenhq/radzen-blazor#903]
Virtually all HTML editors support CTRL-K to mark a string with a URL hyperlink. 

Would love for the Radzen HTML control to support this.  You would high-light the text for the link in the textbox and then hit CTRL-K on the keyboard to bring up the existing INSERT LINK dialog box. That highlighted text would already be populated in the TEXT textbox field and focus would be in the Web address field so you could CTRL-V (paste) the URL you wanted to link.

Currently, you have to click the URL link button instead of a keyboard command. 

Thanks!

**Comment by akorchev** [comment]
Recently implemented.
