### ISSUE TITLE
HtmlEditor Image insert not working

### ISSUE THREAD

**Issue by goldytech** [radzenhq/radzen-blazor#904]
**Describe the bug**
Unable to insert a image in the HTMLEditor

**To Reproduce**
1. Go to https://blazor.radzen.com/html-editor
2. Place the cursor in the editor, where you wish to place the image
3. Click on "Insert Image" icon from the top toolbar
4. Browse for the image from the local computer (jpg image) and provide height, width, and alt text properties. 
5. Click on the OK button
6. Nothing happens. The select image dialog is still open and not getting closed
7. No error is visible on the UI

**Expected behavior**
An image should be inserted into the editor

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Ventura
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] 16.3

**Additional context**
NA

**Comment by akorchev** [comment]
Should be now fixed - the UploadUrl property was not set in the first demo.
