### ISSUE TITLE
Label and associated input element

### ISSUE THREAD

**Issue by Flachdachs** [radzenhq/radzen-blazor#912]
An HTML `label` element has a `for` attribute. To associate the label with an input element the value of the `for` has to be the `id` of the "labelable" element (e.g. input/select/textarea). If this is the case you can click on the label and the associated input element is focused (i.e. input cursor is set into the field).

`RadzenLabel` has a property `Component` which suggests that this is a reference to a `RadzenTextBox` etc. But instead it is a Magic String, that only works when you set the RadzenTextBox's `id` to the same value. You have to keep this in mind when using labels with input elements. I guess there is no better solution (except of using `nameof()`). Referencing in Blazor doesn't work before things are rendered, so a Label can't access the properties of the TextBox that is rendered later.

But at least Radzen Blazor Studio should be aware of this. Currently it creates pages where Label's `Component` and TextBox's `Name` have the same value, but TextBox's `id` is not set and gets a random unique value.

And it would generally be better when string values that are actually references to a property of something are rendered with `nameof(something.Property)`. You can then see what the value really means, especially in cases where the same value is used for a lot of different things. Renaming is also easier done by the IDE without manually searching the value in the whole code base.

**Comment by akorchev** [comment]
I am afraid I couldn't understand what the problem is.

**Comment by akorchev** [comment]
> One problem is that Radzen Blazor Studio creates pages with RadzenLabels

You can log an issue in the RBS repo.

> Component is a misleading name. It doesn't refer to a component, instead you have to enter an id that you also have to give a Component that renders it to an input/select/etc. element. 

It probably is but it is too late to change it. This would break all existing applications created with Radzen and Radzen Blazor Studio.

> And the third: less magic strings, when nameof() can provide these strings for concrete identifiers.

Feel free to submit a PR addressing that.

**Comment by ikappas** [comment]
@akorchev Hi Atanas, we've run into this problem as well, which looks/feels like a bug.

**RadzenLabels** use the "Component" attribute to emit the "for" attribute which corresponds to the related input's "name" attribute.

According to the [HTML5 specification for Labels](https://www.w3.org/TR/2011/WD-html5-20110405/forms.html#the-label-element) If the "for" attribute is specified, the attribute's value must be the [ID](https://www.w3.org/TR/2011/WD-html5-20110405/elements.html#concept-id) of a [labelable form-associated element](https://www.w3.org/TR/2011/WD-html5-20110405/forms.html#category-label) in the same [Document](https://www.w3.org/TR/2011/WD-html5-20110405/infrastructure.html#document) as the [label](https://www.w3.org/TR/2011/WD-html5-20110405/forms.html#the-label-element) element.

As a result the relationship between the labels and the inputs is broken which has implications with [Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG21), more specifically with label click event focusing the related input.

**Comment by akorchev** [comment]
Have you tried setting the id of the component as well? This works as expected:

```
<RadzenLabel Text="Label" Component="textbox" />
<RadzenTextBox id="textbox"  />
```

**Comment by ikappas** [comment]
@akorchev Thank you for looking at this. Yes, this is the way to make it work, but unless I am missing something it feels buggy with respect to Component... for example, the following is a custom component:

``` razor
<RadzenLabel
    class="w-100"
    Component="EconomicActivityDropDown" // <---- this refers to the "id" attribute
    Text="@L["EconomicActivity:Singular"]" />

<RadzenDropDown
    @ref="FilterDropDown"
    @bind-Value="@State.Selection"
    AllowClear="true"
    AllowFiltering="true"
    AllowVirtualization="true"
    class="w-100"
    Count="State.TotalCount"
    Data="State.Items"
    LoadData="LoadDataAsync"
    id="EconomicActivityDropDown"  // <----- These lines feel duplicated, and unless they are equal
    Name="EconomicActivityDropDown" // <---- potentially break the implementation
    TextProperty="Name"
    TValue="int?"
    ValueProperty="Id" />

@if (Required)
{
    <RadzenRequiredValidator
        class="w-100"
        Component="EconomicActivityDropDown" // <---- this refers to the "Name" attribute
        Text="@L["FieldRequired"]" />
}
```

**Comment by akorchev** [comment]
Not sure why you think its buggy. Name serves a different purpose than id. Feel free to explore the source and see how validators work with regards to Name.

**Comment by ikappas** [comment]
It feels buggy because in Radzen docs the **Component** attribute is used for both "id" and "name" matching (which in this case need to be equal - something not necessarily true in vanilla HTML).

### Label
https://www.radzen.com/documentation/blazor/label/
<html>
<body>


Component | string | null | The ID of a labelable form-related element.
-- | -- | -- | --



</body>
</html>

### Validator
https://blazor.radzen.com/docs/api/Radzen.Blazor.ValidatorBase.html?q=Validator
**Component**: Specifies the component which this validator should validate. Must be set to the [Name](https://blazor.radzen.com/docs/api/Radzen.IRadzenFormComponent.html#Radzen_IRadzenFormComponent_Name) of an existing component.

**Comment by akorchev** [comment]
Still not sure what buggy is. IMHO a bug is something which doesn't work. In this case both work as advertised. Anyway we don't plan to change this behavior as it would break a lot of customer applications. Feel free to use `for` in RadzenLabel if Component bothers you too much:

```
<RadzenLabel for="textbox" Text="Textbox" />
<RadzenTextBox id="textbox"/>
```

**Comment by ikappas** [comment]
Perhaps "Buggy" is not the right word for it, because it works., "Unexpected" then?

We had to look for it in the documentation and it was not self-evident that both "Id" and "Name" attributes must be specified and equal in order to make **Labels** and **Validators** work with the same "Component" attribute connotation.

My intent was to help elaborate on the possible confusion, nothing else.
Thank you for suggesting the direct usage of the "for" attribute. It just feels more straightforward.
