### ISSUE TITLE
Wrong code for example in online documentation

### ISSUE THREAD

**Issue by koddek** [radzenhq/radzen-blazor#916]
**To Reproduce**
1. Go to '[https://blazor.radzen.com/form-field](url)'
2. Scroll down to 'Helper text'
3. Click on 'Edit Source'
4. The code does not match the example. It is the same code for the previous example (Start, End, and ChildContent)

**Desktop (please complete the following information):**

**Additional context**
Please also add an example on how to validate control on changed

**Comment by enchev** [comment]
Fixed with https://github.com/radzenhq/radzen-blazor/commit/dd30b30b34aae3556ff5e0d63c92d4bd65ed216b. Check also the last example for more info about validation.
