### ISSUE TITLE
mobile

### ISSUE THREAD

**Issue by sdhzth** [radzenhq/radzen-blazor#917]
Does DatePicker have plans to support mobile devices?  thanks

**Comment by akorchev** [comment]
RadzenDatePicker supports mobile devices already.
![Blazor Datepicker component with calendar mode](https://user-images.githubusercontent.com/454726/231980788-00950bc3-22df-452e-aa60-982103bda205.png)

**Comment by sdhzth** [comment]
Thank you for your reply.
Sorry, I didn't describe it clearly just now. I hope it has such an effect
![temp](https://user-images.githubusercontent.com/22364998/231984846-b27fb2f0-6da9-4fd2-bdad-dd61a7c94cc7.png)
