### ISSUE TITLE
Datagrid - InsertRow position parameter

### ISSUE THREAD

**Issue by Abolten** [radzenhq/radzen-blazor#921]
Hi All,

I wish to include an optional parameter in the RadzenDataGrid.InsertRow method, template below.

![insertrow](https://user-images.githubusercontent.com/122609107/232550590-5f848361-541c-4ff5-b9f4-f452f463cdb3.png)

Can anyone process this implementation?

Kind regards,
Arjen

**Comment by enchev** [comment]
Hey @Abolten,

We accept pull requests! Make sure however to not change the default/current behavior.

**Comment by enchev** [comment]
We've decided not to add such method. Use your collection to insert item at desired position and call Reload() method of the DataGrid component.
