### ISSUE TITLE
Loop when click on RadzenButton

### ISSUE THREAD

**Issue by lqlam** [radzenhq/radzen-blazor#925]
**Describe the bug**
I have a loop with RadzenButton inside. When I click on RadzenButton it go to loop again. You can see my screenshots, **counter variable in loop been called every clicked**. I tried with original button and it fine.

**Screenshots**
[https://imgur.com/a/ABbM0Fs](https://imgur.com/a/ABbM0Fs)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox 111

**Comment by akorchev** [comment]
Please follow the issue template.
