### ISSUE TITLE
Add property ReadOnly to CheckBoxList as well

### ISSUE THREAD

**Issue by johanpolak** [radzenhq/radzen-blazor#926]
In the newest release, the property 'ReadOnly' has been added to the component RadzenCheckBox. Can this property also be added to the RadzenCheckBoxList and the RadzenCheckboxListItem? Would be a nice addition!

**Comment by enchev** [comment]
We accept pull requests! Not sure however about the  RadzenCheckboxListItem ReadOnly since the component works with single input:
https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenCheckBoxList.razor#L30

**Comment by johanpolak** [comment]
I will look into it!

**Comment by johanpolak** [comment]
I created a pull request #928
