### ISSUE TITLE
RadzenHtmlEditorSource - missing from documentation

### ISSUE THREAD

**Issue by MrChriZ** [radzenhq/radzen-blazor#936]
Hi unless I'm missing something (quite likely!) then you're missing RadzenHtmlEditorSource  from your documentation here:
https://blazor.radzen.com/html-editor
and here:
https://blazor.radzen.com/docs/guides/components/htmleditor.html?tabs=page

Thanks for some great components!

**Comment by akorchev** [comment]
Indeed it is missing as it was recently added by a community member. We will add it to the documentation at some point.
