### ISSUE TITLE
Confusing design of the standard theme checkbox

### ISSUE THREAD

**Issue by Cosmatevs** [radzenhq/radzen-blazor#940]
**Is your feature request related to a problem? Please describe.**
The checked state of the [checkbox in the standard theme](https://blazor.radzen.com/checkbox?theme=standard) looks… nonstandard. I'd even say: misleading.
![Radzen themes selected checkboxes](https://user-images.githubusercontent.com/44393502/234971828-943c5b92-64e9-4590-b279-c1fddae596da.png)
A full square is often used to indicate an indeterminate state of a checkbox. A checked state is almost always indicated with a check mark.
![Common checkbox designs](https://user-images.githubusercontent.com/44393502/234970248-22ac93bd-7f1b-4613-b8ad-b8828eb6726b.png)
I think it could be also confused with a radio button, especially that it's rounded.

**Describe the solution you'd like**
Make the checkbox design in the standard theme similar to other themes.
In fact, it's the only theme which uses a different design.

**Describe alternatives you've considered**
Use [switches](https://blazor.radzen.com/switch?theme=standard) instead.
Use another theme.
Override css on my own.

**Additional context**
I'd like to know what others think about the design of checkboxes in the standard theme.

**Comment by yordanov** [comment]
Indeed, the design of the checkbox is non-standard and is in contrast with the theme's name. Here is how the updated checkbox looks like:
![StandardThemeCheckboxes](https://user-images.githubusercontent.com/1118895/235064540-011cd033-5e9f-4e23-ab17-b876fae14547.gif)
