### ISSUE TITLE
Accent Insensitive for Radzen DropDown

### ISSUE THREAD

**Issue by philippedurocher** [radzenhq/radzen-blazor#941]
Would it be possible to add Accent Insitive for Radzen Dropdown. The same way it is Case Insensitive?

**Comment by enchev** [comment]
Hey @philippedurocher,

As far as we know this is directly database related and we are not sure how it can be implemented using LINQ:
https://stackoverflow.com/questions/2461522/how-do-i-perform-an-accent-insensitive-compare-e-with-%C3%A8-%C3%A9-%C3%AA-and-%C3%AB-in-sql-ser

**Comment by philippedurocher** [comment]
Thanks @enchev for your quick answer. I forgot to say that it's in a Blazor WASM context.

The Dropdown receives the data in an `IList<>` with `MyDto(int Id, string Description)` and I want the filter to find accent characters when searching.

Here's an example :
![radzendropdown-accent-sensitive](https://user-images.githubusercontent.com/1459389/235174680-5318e590-4de1-46a9-8a97-7ca92f77ba16.gif)

Do you think it's possible? If not, what are the possible solutions?

Thank you for your support.
