### ISSUE TITLE
DataGrid OData Call LoadData two times !

### ISSUE THREAD

**Issue by MR-MAP** [radzenhq/radzen-blazor#945]
Hi.
In New versions, DataGrid Component when load call LoadData Function two Time . 
in your demo website same : 

https://blazor.radzen.com/datagrid-odata

![image](https://user-images.githubusercontent.com/6194984/235355012-05e982ba-c2d6-4cac-9692-26a57cfa4069.png)

 - Version 4.10.0 and 4.10.1

**Comment by enchev** [comment]
Fixed with https://github.com/radzenhq/radzen-blazor/commit/f5b7ddcf0e99e1a42f3359b11fef637032892a5d
