### ISSUE TITLE
RadzenDataGrid doesn't know it's using OData until after first load

### ISSUE THREAD

**Issue by evandixon** [radzenhq/radzen-blazor#957]
**Describe the bug**
In PagedDataBoundComponent.ReloadOnFirstRender, if Data is null on the first render, Reload will be called. RadzenDataGrid's implementation of Reload handles filtering and ordering. RadzenDataGrid.GetOrderBy gets the columns to order by, and calls IsOData to determine the format of the order. IsOData depends on knowing Data's type, which is null because that's required to trigger the reload on first render. Until https://github.com/radzenhq/radzen-blazor/commit/f5b7ddcf0e99e1a42f3359b11fef637032892a5d, an alternative was to set Data to `IEnumerable.Empty<MyClass>().AsODataEnumerable()` as a hint for IsOData, but now that solution results in the grid not loading on first render.

**To Reproduce**
1. Create a view model with an object such as the following:
```
public class GridItem
{
    public MyClass ViewModel { get; set; }
}

public class MyClass
{
    public string SomeProperty { get; set; }
}
```
2. Create a RadzenDataGrid with `TItem="GridItem"` with null Data and a LoadData delegate that uses OData to get data. Add a column referencing the property `ViewModel.SomeProperty` with `SortOrder="SortDirection.Ascending"`.
3. In the implementation of LoadData, observe how `LoadDataArgs.OrderBy` equals `np(ViewModel.SomeProperty) asc`. The "np" is a result of the grid thinking OrderBy is going to be used in a dynamic linq expression. (See RadzenDataGridColumn.GetSortOrderAsString)

**Expected behavior**
The LoadData implementation receives a LoadDataArgs.OrderBy equal to "ViewModel/SomeProperty asc" and not "np(ViewModel.SomeProperty) asc", perhaps by setting Data to Enumerable.Empty<GridItem>().AsODataEnumerable() or by having a separate parameter on the grid to force IsOData to true.

**Comment by enchev** [comment]
Hi @evandixon,

In my opinion empty ODataEnumerable and explicit call of Reload() to invoke LoadData might work for you.
