### ISSUE TITLE
PageSizeOptions is not calling Reload when increasing size

### ISSUE THREAD

**Issue by jmiller76** [radzenhq/radzen-blazor#965]
**Describe the bug**
After 4.10.2 "PageSize changed should invoke Reload() only when needed."  Page Size changes made via a set PageSizeOptions variable are not causing a Reload.

**To Reproduce**
1. Go to https://blazor.radzen.com/datagrid-pager-api
2. Change "items per page" drop down
3. Change page to see that reload does adjust size.

**Expected behavior**
Page Size change should trigger a reload when needed. (Or update sample with PageSizeChanged event to reload.)

**Desktop (please complete the following information):**
 - OS: Win 11 22H2
 - Browser Chrome,Edge
 - Version Current.

**Additional context**
Work around:
       PageSizeChanged="@(arg=> {dataGrid.Reload(); })"
Adjusting Filters will also cause a refresh in other context then the specific demo page.

**Comment by Cosmatevs** [comment]
#962
