### ISSUE TITLE
RadzenDataList pageSize 10 don't work on loading

### ISSUE THREAD

**Issue by PeterOliverDev** [radzenhq/radzen-blazor#972]
**Describe the bug**
The RadzenDataList component does not want to display the first load if the PageSize attribute is 10. 
You can try putting 8,9,11,12,20, it all works. But number 10 does not work.

**To Reproduce**
```
<RadzenDataList AllowVirtualization="false"
		LoadData="@LoadDataV2"
		WrapItems="true"
		Data="@_testsDto" TItem="TestDto"
		AllowPaging=true
		PageSize=11>
		<Template Context="test">
			<RadzenColumn Size="10" class="rz-p-3">
					<RadzenText TextStyle="TextStyle.H5" TagName="TagName.H5" class="rz-color-secondary">@(test.Name)</RadzenText>
			</RadzenColumn>
		</Template>
</RadzenDataList>

@code{
	public class TestDto
	{
		public string Name { get; set; } = default!;
	}

	private List<TestDto> _testsDto = new();

	public async Task LoadDataV2(LoadDataArgs args)
	{
		_testsDto = new List<TestDto>
		{
			new TestDto
			{
				Name = "test1"
			},
			new TestDto
			{
				Name = "test2"
			},
			new TestDto
			{
				Name = "test3"
			}
		};
	}
}
```
**Expected behavior**

I don't know if this can help you, but I noticed during my tests that the function defined in the LoadData attribute is not being called.

**Screenshots**
With PageSize=10 (It's empty)
![image](https://github.com/radzenhq/radzen-blazor/assets/133120114/febb0675-f8d0-44ed-b1a8-7db2814ffd03)

With PageSize=11
![image](https://github.com/radzenhq/radzen-blazor/assets/133120114/b75ed068-bd24-48c6-9b0c-f2020d4f918f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 113.0.5672.92

**Comment by PeterOliverDev** [comment]
> You've not set Count which is mandatory. Check carefully our demos before opening new issues.

Indeed, but it is because I removed some code to set up a demonstration.

Here is the complete code with the count. I change it when I call the LoadDataV2 function, but as I told you, the problem is that the LoadDataV2 function is not called when you put 10.

Voila le code complet avec le count. Je le change lorsque j'appel la fonction LoadDataV2, mais comme je vous ai dis, le problème c'est que la fonction LoadDataV2 ne se fait pas appelé lorsqu'on met 10.

```
<RadzenDataList AllowVirtualization="false"
				LoadData="@LoadDataV2"
				WrapItems="true"
				Data="@_testsDto" TItem="TestDto"
				AllowPaging=true
				PageSize=10
				Count="@_totalRows2">
	<Template Context="test">
		<RadzenColumn Size="10" class="rz-p-3">
			<RadzenText TextStyle="TextStyle.H5" TagName="TagName.H5" class="rz-color-secondary">@(test.Name)</RadzenText>
			</RadzenColumn>
		</Template>
	</RadzenDataList>

	@code {
	public class TestDto
	{
		public string Name { get; set; } = default!;
	}

	private List<TestDto> _testsDto = new();
	private int _totalRows2;

	public async Task LoadDataV2(LoadDataArgs args)
	{
		_testsDto = new List<TestDto>
		{
			new TestDto
			{
				Name = "test1"
			},
			new TestDto
			{
				Name = "test2"
			},
			new TestDto
			{
				Name = "test3"
			}
		};

		_totalRows = 3;
	}
}
```

**Comment by MPapst** [comment]
I suspect, thats not the whole code. The `LoadDataV2` method does not contain a await statement.
Is the LoadData called? I would suspect no, use a nullable `_testsData` field and initialize it with null.
