### ISSUE TITLE
RadzenDropdown ValueTemplate support when Multiple is true

### ISSUE THREAD

**Issue by MiloCDavis** [radzenhq/radzen-blazor#984]
The ValueTemplate feature of the RadzenDropdown is very nice when working with single selection. The Template or TextProperty will be reflected in the popup options, and the ValueTemplate will show in the input box when a selection is made. When set to multiple selection however, the ValueTemplate has no effect. I have a list of objects with a Name property and a Letter property, and what I'd like to achieve is a multiple, chips dropdown that displays the names as the options, and the letters as the selections.

**Comment by enchev** [comment]
You can use `Template` for that:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/2cba7bef-fc2b-42fa-8c51-936dc4b6a063)

![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/0c168c10-0696-476e-a4aa-60c317f749b2)

Here is the same with chips:
![image](https://github.com/radzenhq/radzen-blazor/assets/5804953/e5b6df49-d10a-4956-b4dc-a83449c3f1a8)
