### ISSUE TITLE
Radzenchart - RadzenDonutSeries shows Tooltip without hover after Update to 4.11.2

### ISSUE THREAD

**Issue by trickshot2012** [radzenhq/radzen-blazor#986]
**Describe the bug**
I updated from 4.11.1 to 4.11.2  after that this issue appears. On my Dashboard page just shows the tooltip of
one section. If you hover over a different section this tooltip stays on the screen even when you move the move away from the chart.
I downgraded to 4.11.1 to solve the issue for now. 

**To Reproduce**
```
 <RadzenChart class="mb-2">
            <RadzenDonutSeries Data="@data" CategoryProperty="Text"  ValueProperty="Value">
                <ChildContent>
                    <RadzenSeriesDataLabels />
                    <RadzenLegend Visible="false" />
                </ChildContent>
                <TitleTemplate>
                    <div class="rz-donut-content">
                        <div>@DateTime.Now.Year</div>
                    </div>
                </TitleTemplate>
                <TooltipTemplate>
                    @{
                        var percent = Math.Round((double)context.Value / data.Sum(x => x.Value) * 100, 2);
                    }
                    <div style="text-align:center;">
                        <div>@context.Text</div>
                        <div>@percent%</div>
                    </div>
                </TooltipTemplate>
            </RadzenDonutSeries>
        </RadzenChart>
@code {
    [Parameter] public string Title { get; set; }
    TextandValue[] data;
    protected override async Task OnInitializedAsync()
    {
        data = await _TicketServiceDapper.NumberofCategories(State.Current_User.Abteilung);
    }
}
```

**Expected behavior**
Tooltip not showing when page is loaded. Tooltip disappears when mouse is moved away.

**Screenshots**
4.11.2
![grafik](https://github.com/radzenhq/radzen-blazor/assets/40659134/a33ff215-d9b1-4312-8a70-bed4c29ec681)

4.11.1 
![grafik](https://github.com/radzenhq/radzen-blazor/assets/40659134/ec978dcc-a34d-4361-a0d7-5164921adf4b)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome Version 113.0.5672.127

**Comment by akorchev** [comment]
Hi @trickshot2012, we have already fixed that issue but haven't released a new version on nuget yet. Use the older version for now.
