### ISSUE TITLE
DataGrid Composite Columns with grouping artifacts

### ISSUE THREAD

**Issue by aplib** [radzenhq/radzen-blazor#988]
![Screenshot_43](https://github.com/radzenhq/radzen-blazor/assets/1092292/1ec31f75-e2f2-4cc7-8ebd-1d3ba448b74c)
![image](https://github.com/radzenhq/radzen-blazor/assets/1092292/ebfd45fd-427a-4e84-8d25-472c240ec32c)

**Comment by enchev** [comment]
Grouping on composite columns is explicitly disabled since such rendering is not implemented.
