### ISSUE TITLE
RadzenPanelMenu not synced when navigating via RadzenLink or RadzenButton

### ISSUE THREAD

**Issue by marekott** [radzenhq/radzen-blazor#993]
**Describe the bug**
When navigating to page that is present on `RadzenPanelMenu` using `RadzenLink`, navigation menu is not synced with target page. The same behavior can be observed using `RadzenButton` with `NavigationManager` (however in that case refreshing the page expands navigation menu to appropriate item).

**To Reproduce**
1. Using https://blazor.radzen.com/link click on "Go to Buttons page"
2. You are being navigated to https://blazor.radzen.com/buttons hovewer this transition is not reflected by navigation menu. It remains collapsed even that this page has its navigation item.

**Expected behavior**
When navigating to https://blazor.radzen.com/buttons related navigation item should be expanded (see screenshot below).

**Screenshots**
![image](https://github.com/radzenhq/radzen-blazor/assets/46067021/b3881a92-06c6-4ffe-9b0b-3d03df269112)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Radzen.Blazor - 4.6.2, Chrome - 113.0.5672.127

**Comment by marekott** [comment]
Hi @akorchev, thanks for the quick answer. Is there a chance for such feature? In my app we are navigating via buttons from cards representing microservices to pages with info specific for such microservice. There are more than one page with this specific info nested in `RadzenPanelMenu` and then in `RadzenPanelMenuItem`. Since nav menu is not synced user is a little bit lost and doesn't now about other pages he can visit.

**Comment by akorchev** [comment]
We don't plan to make such a feature soon. You can however use the available API to expand the items when needed.

**Comment by enchev** [comment]
We don't have plans to add such feature to RadzenPanelMenu component.
