### ISSUE TITLE
OnSeriesClick event not being called in Radzen chart

### ISSUE THREAD

**Issue by kElaadwy** [radzenhq/radzen-blazor#994]
I am having a problem with the OnSeriesClick event in the Radzen chart. I have tried the following:

Made sure that I am using the latest version of Radzen.
Tried using a different browser.
Tried clearing my browser's cache and cookies.
The problem is still not fixed. **I have also tried using the Radzen chart on your website, and the problem is still there**.
**Here is the pages I tried on your website:**
[bar-chart](https://blazor.radzen.com/bar-chart)
[pie-chart](https://blazor.radzen.com/pie-chart)

I haven't only tried on your website, but also in my code, I tried to log in the method that is called when the event is fired,
tried to change a value of string that is being rendered as `<h1>` but nothing seem to happen

**Comment by akorchev** [comment]
Hi @kElaadwy,

We may have fixed that issue with one of the latest commits. You can test once we release a new version of Radzen.Blazor later today.

**Comment by kElaadwy** [comment]
great thanks @akorchev
