### ISSUE TITLE
Radzen chart set the color of the chart series based on the value of the current element

### ISSUE THREAD

**Issue by kElaadwy** [radzenhq/radzen-blazor#996]
I am writing to request a feature for the Radzen chart. I would like to be able to set the color of the chart series based on the value of the current element.

For example, I would like to be able to set the color of the chart series to green if the value of the current element is greater than 200, and red if the value of the current element is less than 200.

I believe that this would be a valuable addition to the Radzen chart.

Thank you for your time and consideration.

**Comment by paulo-rico** [comment]
Hi @kElaadwy 
This has now been implemented. See [https://blazor.radzen.com/column-chart](https://blazor.radzen.com/column-chart) for example chart and source code.
